storage: ../.store/storage
max_body_size: 64mb

auth:
  htpasswd:
    file: ../.store/htpasswd

uplinks:
  npmjs:
    url: https://registry.npmjs.org/
    timeout: 120s
    maxage: 30d
    cache: true
    fail_timeout: 1m
    max_fails: 3

packages:
  '@reference-ui/*':
    access: $all
    publish: $all
    unpublish: $all

  '**':
    access: $all
    publish: $all
    unpublish: $all
    proxy: npmjs

server:
  keepAliveTimeout: 120
  requestTimeout: 120s

log:
  - type: stdout
    format: pretty
    level: http