/**
 * Printers for the three committed primitives artifacts, E1, E2, and E4.
 * buildVocabularyJson renders the machine contract with sorted keys and a stable
 * layout; buildPrimitivesMjs renders the raw system-unbound component module with
 * the configurePrimitives seam; buildPrimitivesDts renders the raw types in today's
 * react-types shape with the exact typegen union instead of the per-world bake.
 * scanTripwires rejects the forbidden surface (Box/Flex/Grid, as-prop, styled
 * factory, slot recipes, rounded, atomic class names, pandacss) before anything
 * touches disk.
 */
import type { ElementRow } from './elements.js'
import { ELEMENT_OVERRIDES, RESERVED_KEYS, type VocabView } from './vocabulary.js'

export interface VocabularyModel {
  elements: ElementRow[]
  vocab: VocabView
}

export interface ArtifactText {
  name: string
  text: string
}

export const VOCABULARY_VERSION = 1

export const CONDITION_RULE =
  'Keys starting with `_`, `&`, or `@` resolve as condition arms (canon is_condition); ' +
  'the named list carries no `@…` breakpoint keys — those join per-system at print time.'

const E4_HEADER = [
  '/**',
  ' * Raw primitive types generated from canon + typegen — do not edit manually.',
  ' * @generated by `pnpm --filter @reference-ui/rust run primitives` (modules/primitives/generate/generate.ts).',
  ' * Element roster: canon ELEMENTS, HTML namespace only (101); prop names: typegen PropDefs over napi.',
  ' */',
]

const E2_HEADER = [
  '/**',
  ' * Raw system-unbound primitive components generated from canon — do not edit manually.',
  ' * @generated by `pnpm --filter @reference-ui/rust run primitives` (modules/primitives/generate/generate.ts).',
  ' * Element roster: canon ELEMENTS, HTML namespace only (101); per-system binds arrive',
  ' * through configurePrimitives({ layerName, stylePropNames, css }), which returns the',
  ' * bound roster. The unbound exports below never render — empty splitter, blank layer,',
  ' * throwing css — unreachable by construction, the eval-safe barrel contract.',
  ' */',
]

const E2_UNBOUND_GUARD = [
  'function unboundCss() {',
  "  throw new Error('[primitives] unbound primitives never render — bind them with configurePrimitives({ layerName, stylePropNames, css })')",
  '}',
  '',
  'const unboundSplit = createPropSplitter([])',
  '',
]

const E2_SEAM_DOC = [
  '/**',
  ' * Bind the roster to one system: the splitter carries the compiled style prop names,',
  ' * renders stamp the layer scope, and style props resolve through the given css().',
  ' * Returns a fresh bound roster; the unbound module exports stay untouched.',
  ' */',
]

const STYLE_PROPS_WIRING = [
  "import type { StyleConditionKey, StyleProps as NarrowStyleProps, SystemStyleObject } from '@reference-ui/styled'",
  '/** React style props: typegen precision where tokens exist, open everywhere else. */',
  "export type StyleProps = Omit<NarrowStyleProps, 'font' | 'weight'> & {",
  "  [K in Exclude<StylePropName, keyof NarrowStyleProps> | 'font' | 'weight']?: unknown",
  '} & {',
  '  [K in StyleConditionKey]?: StyleProps',
  '}',
]

const PRIMITIVE_PROPS = [
  '/** Shared prop shape every primitive accepts: native props for one tag plus style props and primitive extras. */',
  'export type PrimitiveProps<T extends PrimitiveTag> = Omit<',
  '  React.ComponentPropsWithoutRef<T>,',
  "  StylePropName | 'css' | 'colorMode' | 'variant'",
  '> & StyleProps & {',
  '  css?: PrimitiveCssProp',
  '  colorMode?: unknown',
  '  variant?: unknown',
  '}',
]

function fail(source: string, detail: string): never {
  throw new Error(`[primitives] ${source}: ${detail}`)
}

function unionOf(names: readonly string[]): string {
  return names.map(name => JSON.stringify(name)).join(' | ')
}

function verifyOverrides(elements: readonly ElementRow[]): void {
  const tags = new Set(elements.map(row => row.dom))
  for (const tag of Object.keys(ELEMENT_OVERRIDES)) {
    if (!tags.has(tag)) fail('emit', `override target <${tag}> left the roster`)
  }
}

export function buildVocabularyJson(model: VocabularyModel): string {
  verifyOverrides(model.elements)
  const document = {
    version: VOCABULARY_VERSION,
    elements: model.elements.map(row => ({
      dom: row.dom,
      jsx: row.jsx,
      family: row.family,
    })),
    stylePropNames: [...model.vocab.stylePropNames],
    conditions: [...model.vocab.conditions],
    conditionRule: CONDITION_RULE,
    aliases: model.vocab.aliases,
    reserved: [...RESERVED_KEYS],
    elementOverrides: Object.fromEntries(Object.entries(ELEMENT_OVERRIDES).sort()),
  }
  return `${JSON.stringify(document, null, 2)}\n`
}

function sortedByDom(elements: readonly ElementRow[]): ElementRow[] {
  return [...elements].sort((left, right) =>
    left.dom < right.dom ? -1 : left.dom > right.dom ? 1 : 0
  )
}

function unboundDecl(row: ElementRow): string[] {
  const call = `createPrimitive({ tag: ${JSON.stringify(row.dom)}, displayName: ${JSON.stringify(row.jsx)}, layerName: '', split: unboundSplit, css: unboundCss })`
  if (row.jsx === 'Map')
    return [`const MapPrimitive = ${call}`, 'export { MapPrimitive as Map }']
  return [`export const ${row.jsx} = ${call}`]
}

function boundDecl(row: ElementRow): string {
  return `    ${row.jsx}: createPrimitive({ tag: ${JSON.stringify(row.dom)}, displayName: ${JSON.stringify(row.jsx)}, layerName, split, css }),`
}

export function buildPrimitivesMjs(model: VocabularyModel): string {
  const tags = sortedByDom(model.elements)
  const lines = [
    ...E2_HEADER,
    "import { createPrimitive } from '../js/factory.ts'",
    "import { createPropSplitter } from '../js/split.ts'",
    '',
    "export { Fragment, createElement } from 'react'",
    'export {',
    '  ColorModeContext,',
    '  DocumentContext,',
    '  LayerScopeContext,',
    '  useColorMode,',
    "} from '../js/context.ts'",
    '',
    ...E2_UNBOUND_GUARD,
  ]
  for (const row of tags) lines.push(...unboundDecl(row))
  lines.push(
    '',
    ...E2_SEAM_DOC,
    'export function configurePrimitives({ layerName, stylePropNames, css }) {',
    '  const split = createPropSplitter(stylePropNames)',
    '  return {'
  )
  for (const row of tags) lines.push(boundDecl(row))
  lines.push('  }', '}', '')
  return lines.join('\n')
}

function perTagDecls(elements: readonly ElementRow[]): string[] {
  const ordered = [...elements].sort((left, right) =>
    left.dom < right.dom ? -1 : left.dom > right.dom ? 1 : 0
  )
  const lines: string[] = []
  for (const row of ordered) {
    const tag = JSON.stringify(row.dom)
    lines.push(
      `export type ${row.jsx}Props = Omit<React.ComponentPropsWithoutRef<${tag}>, StylePropName | 'css' | 'colorMode' | 'variant'> & StyleProps & { css?: PrimitiveCssProp; colorMode?: unknown; variant?: unknown }`,
      `export declare const ${row.jsx}: (props: ${row.jsx}Props & { ref?: React.Ref<React.ComponentRef<${tag}>> }) => React.ReactNode`,
      ''
    )
  }
  return lines
}

export function buildPrimitivesDts(model: VocabularyModel): string {
  verifyOverrides(model.elements)
  const tags = [...model.elements].sort((left, right) =>
    left.dom < right.dom ? -1 : left.dom > right.dom ? 1 : 0
  )
  const lines = [
    ...E4_HEADER,
    "import type * as React from 'react'",
    '',
    '/** Compiled style prop names: the styling keys every primitive accepts. */',
    `export type StylePropName = ${unionOf(model.vocab.stylePropNames)}`,
    ...STYLE_PROPS_WIRING,
    'export type PrimitiveCssProp = Record<string, unknown> | Array<Record<string, unknown>>',
    '',
    '/** Every platform tag the generated primitives cover. */',
    `export type PrimitiveTag = ${unionOf(tags.map(row => row.dom))}`,
    '',
    '/** React types two tags with the generic HTMLElement instead of the real host. */',
    'interface PrimitiveElementOverrides {',
    '  caption: HTMLTableCaptionElement',
    '  menu: HTMLMenuElement',
    '}',
    '/** Host element for one tag, with the caption/menu overrides applied. */',
    'export type PrimitiveElement<T extends PrimitiveTag> = T extends keyof PrimitiveElementOverrides ? PrimitiveElementOverrides[T] : React.ComponentRef<T>',
    '',
    ...perTagDecls(model.elements),
    'export declare const LayerScopeContext: React.Context<boolean>',
    'export declare const ColorModeContext: React.Context<string | undefined>',
    'export declare const DocumentContext: React.Context<Document | null>',
    'export declare function useColorMode(): string | undefined',
    `export { Fragment } from 'react'`,
    `export { createElement } from 'react'`,
    '',
    ...PRIMITIVE_PROPS,
    '',
  ]
  return lines.join('\n')
}

const TRIPWIRE_CHECKS: Array<{ label: string; pattern: RegExp }> = [
  { label: 'map-rule component (Box/Flex/Grid)', pattern: /\b(Box|Flex|Grid)\b/ },
  { label: 'polymorphic as-prop', pattern: /^\s*as\?:/m },
  { label: 'styled factory member', pattern: /styled\./ },
  { label: 'styled factory call', pattern: /styled\(/ },
  { label: 'jsx factory call', pattern: /jsx\(/ },
  { label: 'slot recipe', pattern: /\bslot\b/i },
  { label: 'rounded utility prop', pattern: /rounded/ },
  { label: 'atomic class name', pattern: /"c_[0-9a-z]{5,}"/ },
  { label: 'pandacss import', pattern: /pandacss/i },
  { label: 'deferred set (namespace law forbids it)', pattern: /"deferred"/ },
]

export function scanTripwires(artifacts: ArtifactText[]): void {
  for (const artifact of artifacts) {
    for (const check of TRIPWIRE_CHECKS) {
      if (check.pattern.test(artifact.text))
        fail('tripwire', `${check.label} in ${artifact.name}`)
    }
  }
}
