import type { BaseSystem } from '@reference-ui/cli/config'
import { existsSync, mkdirSync, readdirSync, rmSync, writeFileSync } from 'node:fs'
import { join, resolve } from 'node:path'
import { emit } from '../../../event-bus'
import { log } from '../../../lib/log'
import { microBundle } from '../../../lib/microbundle'
import { scanDirectories } from '../../eval/scanner'
import { buildPandaEntryContent } from './entryTemplate'

/** Scan core + user dirs for config files; returns paths that exist. */
function collectConfigFiles(coreDir: string, userDirectories: string[] = []): string[] {
  const basePath = resolve(coreDir, 'panda.base.ts')
  const styledDir = resolve(coreDir, 'src/styled')
  const dirsToScan = [styledDir, ...userDirectories]
  const scannedPaths = scanDirectories(dirsToScan)
  return [basePath, ...scannedPaths].filter(p => existsSync(p))
}

/** Bundle entry file with esbuild; returns in-memory bundled code. */
async function bundleConfigFiles(entryPath: string): Promise<string> {
  return microBundle(entryPath)
}

/** Emit event so other systems know config is ready. */
function emitConfigCreated(configPath: string): void {
  emit('system:config:created', { configPath })
}

export interface CreatePandaConfigOptions {
  /** When true, add codegen to include so Panda scans the codegen folder (used by sync only). */
  includeCodegen?: boolean
  /** Additional directories to scan for config files (e.g., user project directories) */
  userDirectories?: string[]
  /** Upstream baseSystems from ui.config.extends — merged into theme so Panda generates var() refs */
  extends?: BaseSystem[]
  /** Consumer project root — virtual dir is written to .reference-ui/virtual here; Panda include uses this path */
  userProjectDir?: string
}

/**
 * Mini-compiler: Bundle files that call extendPandaConfig into panda.config.ts.
 *
 * Uses esbuild to bundle all config files, properly inlining functions and their closures.
 * This handles TypeScript properly and inlines all dependencies.
 *
 * @param coreDir - Package root (reference-core)
 * @param options - includeCodegen: set when called from sync so generated config scans codegen/
 *                  userDirectories: additional directories to scan (from config.include)
 */
export async function createPandaConfig(
  coreDir: string,
  options: CreatePandaConfigOptions = {}
): Promise<void> {
  try {
    const refDir = join(coreDir, '.ref')
    if (!existsSync(refDir)) {
      mkdirSync(refDir, { recursive: true })
    }

    // Step 1: Find all files that need to be bundled
    log.debug('system:config', 'Scanning for config files...')
    const userDirs = options.userDirectories || []
    log.debug('system:config', `Scanning directories: src/styled${userDirs.length ? `, ${userDirs.join(', ')}` : ''}`)
    const configFiles = collectConfigFiles(coreDir, userDirs)
    log.debug('system:config', `Found ${configFiles.length} config files`)

    // Step 2: Create entry file from template
    const entryPath = join(refDir, 'panda-entry.ts')
    const initCollectorPath = resolve(
      coreDir,
      'src/cli/system/config/panda/initCollector.ts'
    )
    const extendPandaPath = resolve(
      coreDir,
      'src/cli/system/config/panda/extendPandaConfig.ts'
    )
    const deepMergePath = resolve(
      coreDir,
      'src/cli/system/config/utils/deepMerge.ts'
    )

    // Step 2: Create entry file from template (imports all fragments, merges via deepMerge)
    const entryContent = buildPandaEntryContent({
      refDir,
      initCollectorPath,
      extendPandaConfigPath: extendPandaPath,
      deepMergePath,
      configFilePaths: configFiles,
      extends: options.extends,
    })
    writeFileSync(entryPath, entryContent)
    log.debug('system:config', 'Created entry file')

    // Step 3: Bundle entry with esbuild (inlines all imports)
    log.debug('system:config', 'Bundling with esbuild...')
    const bundled = await bundleConfigFiles(entryPath)
    log.debug('system:config', 'Bundle complete')

    // Step 4: Write final panda.config.ts; inject codegen include when sync requested; replace .virtual with consumer's .reference-ui/virtual
    let output = bundled
    if (options.includeCodegen) {
      const srcPattern = '"src/**/*.{ts,tsx}"'
      output = output.replace(srcPattern, `${srcPattern}, "codegen/**/*.{ts,tsx,jsx}"`)
    }
    if (options.userProjectDir) {
      const consumerVirtualDir = resolve(options.userProjectDir, '.reference-ui', 'virtual')
      const escapedPath = consumerVirtualDir.replace(/\\/g, '\\\\')
      const virtualPattern = '".virtual/**/*.{ts,tsx,js,jsx}"'
      const consumerPattern = `"${escapedPath}/**/*.{ts,tsx,js,jsx}"`
      output = output.split(virtualPattern).join(consumerPattern)
    }

    const configPath = resolve(coreDir, 'panda.config.ts')
    const finalConfig = `/** Generated by createPandaConfig - do not edit manually */
              ${output}
`
    log.debug('system:config', `Writing config to ${configPath}...`)
    writeFileSync(configPath, finalConfig)
    log.debug('system:config', 'Config written successfully')

    // Step 6: Emit event so other systems know config is ready
    emitConfigCreated(configPath)

    // Step 7: Clean up temp files in .ref
    const refFiles = readdirSync(refDir)
    for (const file of refFiles) {
      rmSync(join(refDir, file), { force: true, recursive: true })
    }
  } catch (error) {
    log.error('[system:config] ERROR:', error)
    throw error
  }
}
