import type { CSSProperties } from 'react'

/** Fixture chrome: accordion/collapsible titles are a hairline divider, not a boxed button. */
export const dividerTrigger = {
  width: '100%' as const,
  display: 'flex' as const,
  textAlign: 'left' as const,
  justifyContent: 'space-between' as const,
  alignItems: 'center' as const,
  height: 'auto' as const,
  minHeight: '0',
  color: 'design.text.base',
  fontWeight: '500',
  whiteSpace: 'normal' as const,
  borderBottomColor: 'gray.700',
  borderBottomWidth: '1px',
  cursor: 'pointer' as const,
  _hover: {
    bg: 'ui.button.mutedBackground',
    color: 'design.text.base',
  },
  css: {
    width: '100%',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    textAlign: 'left',
    height: 'auto',
    minHeight: '0',
    paddingInline: '0.5rem',
    paddingBlock: '0.75rem',
    backgroundColor: 'transparent',
    color: 'design.text.base',
    fontWeight: '500',
    whiteSpace: 'normal',
    borderWidth: '0px',
    borderStyle: 'solid',
    borderRadius: '4px',
    borderBottomWidth: '1px',
    borderBottomColor: 'gray.700',
    boxShadow: 'none',
    cursor: 'pointer',
    _hover: {
      backgroundColor: 'var(--ui-button-muted-background, rgba(255, 255, 255, 0.04))',
      boxShadow: 'none',
      opacity: 1,
    },
    _active: { boxShadow: 'none' },
    '&[data-state="open"]': {
      borderBottomWidth: '0px !important',
      borderBottomColor: 'transparent !important',
    },
    '&[aria-expanded="true"]': {
      borderBottomWidth: '0px !important',
      borderBottomColor: 'transparent !important',
    },
    '&[data-content-present]': {
      borderBottomWidth: '0px !important',
      borderBottomColor: 'transparent !important',
    },
  },

  style: {
    backgroundColor: 'transparent',
    borderTop: 'none',
    borderRight: 'none',
    borderLeft: 'none',
    borderBottomWidth: 1,
    borderBottomStyle: 'solid',
    borderBottomColor: 'var(--colors-gray-700)',
    borderRadius: 0,
    boxShadow: 'none',
    height: 'auto',
    width: '100%',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingInline: 0,
    paddingBlock: '0.75rem',
  } as CSSProperties,
}

export const dividerContent = {
  paddingBlock: '0.75rem' as const,
  paddingInline: '0' as const,
  borderWidth: '0px' as const,
  borderBottomWidth: '1px' as const,
  borderBottomStyle: 'solid' as const,
  borderBottomColor: 'gray.700' as const,
  css: {
    paddingBlock: '0.75rem',
    paddingInline: '0',
    borderWidth: '0px',
    borderStyle: 'solid',
    borderBottomWidth: '1px',
    borderBottomColor: 'gray.700',
  },
  style: {
    borderTop: 'none',
    borderRight: 'none',
    borderLeft: 'none',
    paddingBlock: '0.75rem',
    paddingInline: 0,
    borderBottomWidth: 1,
    borderBottomStyle: 'solid',
    borderBottomColor: 'var(--colors-gray-700)',
  } as CSSProperties,
}

