import assert from 'node:assert/strict'
import { describe, it } from 'node:test'
import { createManagedBundlerFiles, getManagedBundlerDevDependencies } from './index.js'

describe('managed bundlers', () => {
  it('describes bundler-owned dependencies', () => {
    assert.deepEqual(getManagedBundlerDevDependencies(['vite7', 'webpack5']), {
      '@vitejs/plugin-react': '^4.7.0',
      'css-loader': '^7.1.2',
      'html-webpack-plugin': '^5.6.3',
      'style-loader': '^4.0.0',
      'ts-loader': '^9.5.2',
      vite: '^7.3.1',
      webpack: '^5.98.0',
      'webpack-cli': '^6.0.1',
      'webpack-dev-server': '^5.2.0',
    })
  })

  it('creates the managed Vite surface', () => {
    assert.deepEqual(createManagedBundlerFiles({ bundlers: ['vite7'], react: 'react19', title: 'Reference UI matrix' }), {
      'index.html': [
        '<!doctype html>',
        '<html lang="en">',
        '  <head>',
        '    <meta charset="UTF-8" />',
        '    <meta name="viewport" content="width=device-width, initial-scale=1.0" />',
        '    <title>Reference UI matrix</title>',
        '  </head>',
        '  <body>',
        '    <div id="root"></div>',
        '    <script type="module" src="/src/main.tsx"></script>',
        '  </body>',
        '</html>',
        '',
      ].join('\n'),
      'vite.config.ts': [
        "import { referenceVite } from '@reference-ui/core'",
        "import react from '@vitejs/plugin-react'",
        "import { defineConfig } from 'vite'",
        '',
        'export default defineConfig({',
        '  plugins: [react(), referenceVite()],',
        '})',
        '',
      ].join('\n'),
    })
  })

  it('creates the managed webpack surface', () => {
    assert.deepEqual(createManagedBundlerFiles({ bundlers: ['webpack5'], react: 'react19', title: 'Reference UI matrix' }), {
      'index.html': [
        '<!doctype html>',
        '<html lang="en">',
        '  <head>',
        '    <meta charset="UTF-8" />',
        '    <meta name="viewport" content="width=device-width, initial-scale=1.0" />',
        '    <title>Reference UI matrix</title>',
        '  </head>',
        '  <body>',
        '    <div id="root"></div>',
        '  </body>',
        '</html>',
        '',
      ].join('\n'),
      'webpack.config.cjs': [
        "const path = require('node:path')",
        "const HtmlWebpackPlugin = require('html-webpack-plugin')",
        '',
        'module.exports = async () => {',
        "  const { referenceWebpack } = await import('@reference-ui/core')",
        '',
        '  return {',
        "    mode: 'development',",
        "    devtool: 'eval-cheap-module-source-map',",
        "    entry: path.resolve(__dirname, 'src/main.tsx'),",
        '    output: {',
        "      path: path.resolve(__dirname, 'dist'),",
        "      filename: 'bundle.js',",
        '      clean: true,',
        "      publicPath: '/',",
        '    },',
        '    resolve: {',
        "      extensions: ['.tsx', '.ts', '.jsx', '.js'],",
        '      symlinks: true,',
        '    },',
        '    module: {',
        '      rules: [',
        '        {',
        '          test: /\\.tsx?$/',
        '          ,',
        '          exclude: /node_modules/,',
        '          use: {',
        "            loader: 'ts-loader',",
        '            options: {',
        '              transpileOnly: true,',
        '            },',
        '          },',
        '        },',
        '        {',
        '          test: /\\.css$/,',
        "          use: ['style-loader', 'css-loader'],",
        '        },',
        '      ],',
        '    },',
        '    plugins: [',
        '      new HtmlWebpackPlugin({',
        "        template: path.resolve(__dirname, 'index.html'),",
        '      }),',
        '      referenceWebpack(),',
        '    ],',
        '    devServer: {',
        '      port: 4173,',
        '      hot: true,',
        '      liveReload: true,',
        '      historyApiFallback: true,',
        '      static: {',
        '        directory: __dirname,',
        '      },',
        '      client: {',
        '        overlay: true,',
        '      },',
        '    },',
        '  }',
        '}',
        '',
      ].join('\n'),
    })
  })
})