import { existsSync, mkdirSync, rmSync, writeFileSync } from 'node:fs'
import { join, resolve } from 'node:path'
import type { ReferenceUIConfig, BaseSystem } from '../../../config'
import { deepMerge } from '../utils/deepMerge'
import { log } from '../../../lib/log'
import { microBundle } from '../../../lib/microbundle'
import { runCollectScript } from '../../collectors/runCollectScript'
import { scanDirectories } from '../../eval/scanner'
import { buildBaseSystemCollectEntryContent } from './collectEntryTemplate'
import { createLayerCss } from './createLayerCss'

/** Scan core + user dirs for config files; same as createPandaConfig. */
function collectConfigFiles(coreDir: string, userDirectories: string[] = []): string[] {
  const basePath = resolve(coreDir, 'panda.base.ts')
  const styledDir = resolve(coreDir, 'src/styled')
  const dirsToScan = [styledDir, ...userDirectories]
  const scannedPaths = scanDirectories(dirsToScan)
  return [basePath, ...scannedPaths].filter(p => existsSync(p))
}

/**
 * Emit baseSystem.mjs — the bundled config artefact that `extends[]` reads.
 *
 * Uses runCollectScript to run the collect script (same config files as panda entry),
 * merges config.extends, then microbundles the final output.
 */
export async function createBaseSystem(
  coreDir: string,
  userDirectories: string[],
  config: ReferenceUIConfig,
  outputDir: string
): Promise<void> {
  try {
    const { name, extends: upstream = [] } = config

    log.debug('system:baseSystem', `Building baseSystem for ${name} (${upstream.length} upstream)`)

    const configFiles = collectConfigFiles(coreDir, userDirectories)
    if (configFiles.length === 0) {
      log.debug('system:baseSystem', 'No config files found, skipping')
      return
    }

    const refDir = join(coreDir, '.ref')
    mkdirSync(refDir, { recursive: true })
    const jsonPath = join(refDir, 'baseSystem-collected.json')

    const entryContent = buildBaseSystemCollectEntryContent({
      refDir,
      jsonOutputPath: jsonPath,
      initCollectorPath: resolve(coreDir, 'src/cli/system/config/panda/initCollector.ts'),
      extendPandaConfigPath: resolve(coreDir, 'src/cli/system/config/panda/extendPandaConfig.ts'),
      deepMergePath: resolve(coreDir, 'src/cli/system/config/utils/deepMerge.ts'),
      configFilePaths: configFiles,
    })

    const extracted = await runCollectScript<Omit<BaseSystem, 'name'>>({
      coreDir,
      entryContent,
      entryBasename: 'collect-baseSystem',
      jsonFilename: 'baseSystem-collected.json',
      logLabel: 'system:baseSystem',
    })

    // Merge upstream (from config.extends)
    let base: Omit<BaseSystem, 'name'> = {
      tokens: extracted.tokens ?? {},
      font: extracted.font ?? {},
      keyframes: extracted.keyframes ?? {},
      globalCss: extracted.globalCss ?? {},
    }
    for (const sys of upstream) {
      base = {
        tokens: deepMerge({}, base.tokens, sys.tokens) as Record<string, unknown>,
        font: deepMerge({}, base.font, sys.font) as Record<string, unknown>,
        keyframes: deepMerge({}, base.keyframes, sys.keyframes) as Record<string, unknown>,
        globalCss: deepMerge({}, base.globalCss, sys.globalCss) as Record<string, unknown>,
      }
    }

    const layerCss = createLayerCss(
      resolve(coreDir, 'src/system/styles.css'),
      name
    )
    const baseSystem: BaseSystem = {
      name,
      ...base,
      ...(layerCss != null ? { css: layerCss } : {}),
    }

    // Microbundle the output — same pipeline as panda.config
    mkdirSync(outputDir, { recursive: true })
    const entryPath = join(refDir, 'baseSystem-export.ts')
    const entryCode = `export const baseSystem=${JSON.stringify(baseSystem)};`
    writeFileSync(entryPath, entryCode, 'utf-8')

    const bundled = await microBundle(entryPath, { minify: true })

    rmSync(entryPath, { force: true })

    const outPath = resolve(outputDir, 'baseSystem.mjs')
    writeFileSync(
      outPath,
      `/** Generated by createBaseSystem - do not edit manually */\n${bundled}`,
      'utf-8'
    )
    log.debug('system:baseSystem', `Wrote ${outPath}`)
  } catch (error) {
    log.error('[createBaseSystem]', error)
    throw error
  }
}
