import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import type { ReferenceUIConfig } from '../../config'
import type { BaseSystem } from '../../types'
import { getOutDirPath } from '../../lib/paths'
import { log } from '../../lib/log'
import { writeGeneratedSystemFontTypes } from '../types/generate'
import {
  createCollectorBundleFromBase,
  createPortableBaseFragmentBundle,
  prepareBaseFragments,
} from './fragments'
import type { BaseArtifacts } from './types'

function createBaseSystem(config: ReferenceUIConfig, fragment: string): BaseSystem {
  return {
    name: config.name,
    fragment,
  }
}

function writeBaseSystem(cwd: string, baseSystem: BaseSystem): void {
  const systemDir = join(getOutDirPath(cwd), 'system')
  const outputPath = join(systemDir, 'baseSystem.mjs')
  const typesPath = join(systemDir, 'baseSystem.d.mts')

  mkdirSync(systemDir, { recursive: true })
  writeFileSync(
    outputPath,
    `/** Generated by reference-core — do not edit manually */\nexport const baseSystem = ${JSON.stringify(baseSystem, null, 2)}\n`,
    'utf-8'
  )
  writeFileSync(
    typesPath,
    `import type { BaseSystem } from '@reference-ui/core'\nexport declare const baseSystem: BaseSystem\n`,
    'utf-8'
  )

  log.debug('base', 'baseSystem written', outputPath)
}

/**
 * Update the existing baseSystem.mjs artefact with layer-ready CSS.
 * Call after Panda cssgen and layer postprocess so baseSystem.css is portable for layers consumers.
 */
export function updateBaseSystemCss(cwd: string, css: string): void {
  const systemDir = join(getOutDirPath(cwd), 'system')
  const outputPath = join(systemDir, 'baseSystem.mjs')
  if (!existsSync(outputPath)) return

  const content = readFileSync(outputPath, 'utf-8')
  const prefix = 'export const baseSystem = '
  const i = content.indexOf(prefix)
  if (i === -1) return
  const jsonStr = content.slice(i + prefix.length).trim()
  const baseSystem = JSON.parse(jsonStr) as BaseSystem
  baseSystem.css = css
  writeBaseSystem(cwd, baseSystem)
}

/**
 * Build the portable base-system artefact once, then expose the collector bundle
 * that config generation uses to write `panda.config.ts`.
 */
export async function createBaseArtifacts(
  cwd: string,
  config: ReferenceUIConfig
): Promise<BaseArtifacts> {
  const preparedFragments = await prepareBaseFragments(cwd, config)
  const collectorBundle = await createCollectorBundleFromBase(cwd, preparedFragments)
  const baseSystem = createBaseSystem(
    config,
    createPortableBaseFragmentBundle(preparedFragments)
  )

  writeBaseSystem(cwd, baseSystem)
  await writeGeneratedSystemFontTypes(cwd, baseSystem.fragment)

  return {
    collectorBundle,
    baseSystem,
  }
}
