/**
 * Condition code emitter for Reference UI Rust canon modules.
 * Formats curated named conditions and pseudo-class/media query grammar rules.
 * Emits zero-allocation binary-searchable static slices into modules/canon/src/conditions.rs.
 */

import type { DialectData } from '../dialect';
import { formatChunks } from './format';

export function emitConditionsRs(dialect: DialectData): string {
  const condChunks = dialect.conditions.map((c) => `"${c}"`);

  return `//! Reference UI conditions, pseudo-selectors, and named condition catalog.
//!
//! Generated by \`packages/reference-rs/modules/canon/generate/generate.ts\`.
//! Defines discriminator prefixes (_ / & / @) for pseudo-classes and media queries.
//! Provides a curated catalog of named conditions for typegen and autocomplete.
// @generated

/// Sorted catalog of curated named condition identifiers.
pub const NAMED_CONDITIONS: &[&str] = &[
${formatChunks(condChunks, '    ', 4)}
];

/// Alias to NAMED_CONDITIONS for catalog inspection.
pub const CONDITIONS: &[&str] = NAMED_CONDITIONS;

/// Returns true if the given key represents a condition, pseudo selector, or media query.
/// Pure grammar discriminator: condition keys must begin with '_', '&', or '@'.
pub fn is_condition(name: &str) -> bool {
    name.starts_with('_') || name.starts_with('&') || name.starts_with('@')
}
`;
}
