/**
 * CSS code emitters for Reference UI Rust canon modules.
 * Generates formatted Rust source strings for canonical CSS properties,
 * native shorthand longhand slices, color properties, and property lookup facades.
 * Emits zero-allocation binary-searchable static slices across modular Rust files.
 */

import type { DialectData, DialectProperty } from '../dialect';
import { formatChunks } from './format';

function toConstIdent(name: string): string {
  return name
    .replace(/^--/, 'VAR_')
    .replace(/^-/, '')
    .replace(/-([a-z0-9])/g, (_, l) => `_${l}`)
    .replace(/([a-z0-9])([A-Z])/g, '$1_$2')
    .toUpperCase();
}

function buildLonghandDefs(properties: DialectProperty[]): {
  longhandSlices: Map<string, string>;
  longhandSliceDefs: string[];
} {
  const longhandSlices = new Map<string, string>();
  const longhandSliceDefs: string[] = [];
  for (const p of properties) {
    if (p.longhands.length > 0) {
      const sliceConstName = `${toConstIdent(p.name)}_LONGHANDS`;
      longhandSlices.set(p.name, sliceConstName);
      const itemsStr = p.longhands.map((s) => `"${s}"`).join(', ');
      longhandSliceDefs.push(`pub static ${sliceConstName}: &[&str] = &[${itemsStr}];`);
    }
  }
  return { longhandSlices, longhandSliceDefs };
}

export function emitCssModRs(dialect: DialectData): string {
  const unitlessChunks = dialect.unitlessProperties.map(p => `"${p}"`).join(',\n    ');
  return `//! Canonical CSS property switchboard, property struct, and lookup functions.
//!
//! Generated by \`packages/reference-rs/modules/canon/generate/generate.ts\`.
//! Unifies standards-backed W3C CSS properties with Reference UI dialect class prefixes.
//! Provides zero-allocation binary-search lookups for property metadata, colors, and shorthands.
// @generated

pub mod color;
pub mod longhands;
pub mod properties;
pub mod unrealizable;
pub mod values;

pub use color::COLOR_PROPERTIES;
pub use properties::CANONICAL_PROPERTIES;
pub use unrealizable::{is_unrealizable_extension, UNREALIZABLE_EXTENSIONS};
pub use values::{classify_css_value, prop_accepts, ValueKind};

/// Canonical property specification in the compiler canon.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Property {
    pub name: &'static str,
    pub css: &'static str,
    pub class_prefix: &'static str,
    pub longhands: &'static [&'static str],
}

impl Property {
    pub const fn new(
        name: &'static str,
        css: &'static str,
        class_prefix: &'static str,
        longhands: &'static [&'static str],
    ) -> Self {
        Self {
            name,
            css,
            class_prefix,
            longhands,
        }
    }
}

/// Returns the Property record for a canonical property name, if known.
pub fn find_property(name: &str) -> Option<&'static Property> {
    CANONICAL_PROPERTIES
        .binary_search_by_key(&name, |p| p.name)
        .ok()
        .map(|idx| &CANONICAL_PROPERTIES[idx])
}

/// Returns true if the given property semantically accepts color values and design tokens.
pub fn is_color_prop(prop: &str) -> bool {
    let canonical = match crate::dialect::resolve_alias(prop) {
        Some(c) => c,
        None => prop,
    };
    COLOR_PROPERTIES.binary_search(&canonical).is_ok()
}

/// Returns the native shorthand longhands for a property, if it is a shorthand.
pub fn native_longhands_for_prop(name: &str) -> Option<&'static [&'static str]> {
    let canonical = match crate::dialect::resolve_alias(name) {
        Some(c) => c,
        None => name,
    };
    match find_property(canonical) {
        Some(p) if !p.longhands.is_empty() => Some(p.longhands),
        _ => None,
    }
}

/// Cascade rank derived from existing longhand slices: shorthands-of-shorthands,
/// then shorthands, then logical longhands (\`Inline\` / \`Block\` in the name), then
/// physical longhands. Lower sorts first so a longhand utility always wins.
pub fn property_cascade_rank(name: &str) -> u8 {
    match native_longhands_for_prop(name) {
        Some(hands) if has_nested_shorthand(hands) => 0,
        Some(_) => 1,
        None if is_logical_longhand(name) => 2,
        None => 3,
    }
}

fn has_nested_shorthand(hands: &[&str]) -> bool {
    hands
        .iter()
        .any(|hand| native_longhands_for_prop(hand).is_some())
}

fn is_logical_longhand(name: &str) -> bool {
    let canonical = match crate::dialect::resolve_alias(name) {
        Some(c) => c,
        None => name,
    };
    canonical.contains("Inline") || canonical.contains("Block")
}

/// Properties whose unitless numbers remain bare in CSS without gaining \`px\`.
pub const UNITLESS_PROPERTIES: &[&str] = &[
    ${unitlessChunks},
];

/// Returns true if a numeric value on this property should stay unitless without gaining \`px\`.
pub fn is_unitless_prop(prop: &str) -> bool {
    if prop.starts_with("--") {
        return true;
    }
    let canonical = match crate::dialect::resolve_alias(prop) {
        Some(c) => c,
        None => prop,
    };
    UNITLESS_PROPERTIES.binary_search(&canonical).is_ok()
}
`;
}

export function emitCssLonghandsRs(dialect: DialectData): string {
  const { longhandSliceDefs } = buildLonghandDefs(dialect.canonicalProperties);
  return `//! Static longhand slices for native CSS shorthands.
//!
//! Generated by \`packages/reference-rs/modules/canon/generate/generate.ts\`.
//! Contains individual longhand property name slices for all living W3C CSS shorthand properties.
//! Referenced by canonical property declarations to enable zero-allocation shorthand expansion.
// @generated

${longhandSliceDefs.join('\n')}
`;
}

export function emitCssColorRs(dialect: DialectData): string {
  const colorPropChunks = dialect.colorProperties.map((p) => `"${p}"`);
  return `//! Standards-backed color properties and Reference dialect color extensions.
//!
//! Generated by \`packages/reference-rs/modules/canon/generate/generate.ts\`.
//! Ingests color-syntax CSS properties from W3C specs unioned with dialect color properties.
//! Sorted lexicographically to enable zero-allocation binary search in is_color_prop.
// @generated

/// Standards-backed color-bearing properties and dialect color properties.
pub const COLOR_PROPERTIES: &[&str] = &[
${formatChunks(colorPropChunks, '    ', 3)}
];
`;
}

export function emitCssUnrealizableRs(dialect: DialectData): string {
  const nameChunks = dialect.unrealizableExtensions.map((p) => `"${p}"`);
  return `//! Dialect extensions whose \`css\` form no browser honors.
//!
//! Generated by \`packages/reference-rs/modules/canon/generate/generate.ts\`.
//! Computed at build from live @webref/css truth: EXTENSIONS rows with css
//! absent from webref, no longhands, and no platform row shadowing the name.
//! Resolve refuses these at the expansion fall-through (warn-and-skip) unless
//! a lowering arm above claims the prop; sorted for binary search.
// @generated

/// Extension names whose served \`css\` form is fictional per live webref.
pub const UNREALIZABLE_EXTENSIONS: &[&str] = &[
${formatChunks(nameChunks, '    ', 3)}
];

/// Returns true if the prop is a dialect extension with no CSS realization.
pub fn is_unrealizable_extension(name: &str) -> bool {
    UNREALIZABLE_EXTENSIONS.binary_search(&name).is_ok()
}
`;
}

export function emitCssPropertiesRs(dialect: DialectData): string {
  const { longhandSlices } = buildLonghandDefs(dialect.canonicalProperties);
  const propertyChunks = dialect.canonicalProperties.map((p) => {
    const sliceName = longhandSlices.get(p.name) ? `super::longhands::${longhandSlices.get(p.name)}` : '&[]';
    return `Property::new("${p.name}", "${p.css}", "${p.classPrefix}", ${sliceName})`;
  });

  return `//! Canonical CSS properties, declaration mappings, and utility class prefixes.
//!
//! Generated by \`packages/reference-rs/modules/canon/generate/generate.ts\`.
//! Contains the complete table of living W3C CSS properties and Reference dialect extensions.
//! Pre-sorted lexicographically by camelCase property name for zero-allocation binary search.
// @generated

use super::Property;

/// All canonical CSS and system properties sorted by camelCase property name.
pub const CANONICAL_PROPERTIES: &[Property] = &[
${formatChunks(propertyChunks, '    ', 2)}
];
`;
}
