/**
 * Dialect and alias code emitter for Reference UI Rust canon modules.
 * Formats authoring shorthand aliases and Reference-only macro props.
 * Emits zero-allocation binary-searchable static slices into modules/canon/src/dialect.rs.
 */

import type { DialectData } from '../dialect';
import { formatChunks } from './format';

export function emitDialectRs(dialect: DialectData): string {
  const aliasChunks = dialect.aliases.map((a) => `Alias::new("${a.alias}", "${a.canonical}")`);
  const refPropChunks = dialect.referenceProps.map((p) => `"${p}"`);

  return `//! Reference UI StyleProps dialect aliases and custom props.
//!
//! Generated by \`packages/reference-rs/modules/canon/generate/generate.ts\`.
//! Maps concise authoring shorthand aliases to canonical CSS properties and defines Reference-only props.
//! Provides zero-allocation lookup functions for resolving aliases during compiler passes.
// @generated

/// StyleProps alias mapping a shorthand alias to its canonical property name.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Alias {
    pub alias: &'static str,
    pub canonical: &'static str,
}

impl Alias {
    pub const fn new(alias: &'static str, canonical: &'static str) -> Self {
        Self { alias, canonical }
    }
}

/// Sorted table of StyleProps shorthand aliases.
pub const ALIASES: &[Alias] = &[
${formatChunks(aliasChunks, '    ', 3)}
];

/// Reference-only custom macro props (e.g. rhythm multipliers, variant discriminators).
pub const REFERENCE_PROPS: &[&str] = &[
${formatChunks(refPropChunks, '    ', 3)}
];

/// Resolves a dialect alias or shorthand to its canonical property name.
pub fn resolve_alias(alias: &str) -> Option<&'static str> {
    ALIASES
        .binary_search_by_key(&alias, |a| a.alias)
        .ok()
        .map(|idx| ALIASES[idx].canonical)
}

/// Returns true if the given name is a Reference-only macro prop.
pub fn is_reference_prop(name: &str) -> bool {
    REFERENCE_PROPS.binary_search(&name).is_ok()
}
`;
}
