/**
 * HTML and SVG element code emitter for Reference UI Rust canon modules.
 * Formats curated HTML/SVG DOM tag names and PascalCase JSX primitive identifiers.
 * Emits zero-allocation binary-searchable static slices into modules/canon/src/html.rs.
 */

import type { DialectData } from '../dialect';
import { formatChunks } from './format';

export function emitHtmlRs(dialect: DialectData): string {
  const elementChunks = dialect.elements.map(
    (e) => `Element::new("${e.html}", "${e.jsx}")`
  );
  const jsxChunks = dialect.primitiveJsx.map((j) => `"${j}"`);
  return `//! Generated HTML and SVG tags and Reference primitive JSX element names.
//!
//! Generated by \`packages/reference-rs/modules/canon/generate/generate.ts\`.
//! Represents the curated subset of HTML and SVG host elements wrapped as Reference UI JSX primitives.
//! Maps lowercase DOM tag names to PascalCase JSX primitive component names.
// @generated

/// Element mapping from lowercase HTML/SVG element tag to PascalCase JSX primitive.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Element {
    pub html: &'static str,
    pub jsx: &'static str,
}

impl Element {
    pub const fn new(html: &'static str, jsx: &'static str) -> Self {
        Self { html, jsx }
    }
}

/// All canonical elements supported as Reference UI primitives.
pub const ELEMENTS: &[Element] = &[
${formatChunks(elementChunks, '    ', 3)}
];

/// All canonical JSX primitive component names, sorted lexicographically.
pub const PRIMITIVE_JSX: &[&'static str] = &[
${formatChunks(jsxChunks, '    ', 4)}
];

/// Returns true if the given tag name is a valid lowercase HTML/SVG element tag in the canon.
pub fn is_html_tag(tag: &str) -> bool {
    if tag.len() > 64 {
        return false;
    }
    let mut buf = [0u8; 64];
    for (i, &b) in tag.as_bytes().iter().enumerate() {
        buf[i] = b.to_ascii_lowercase();
    }
    let lower = match std::str::from_utf8(&buf[..tag.len()]) {
        Ok(s) => s,
        Err(_) => return false,
    };
    ELEMENTS.binary_search_by_key(&lower, |e| e.html).is_ok()
}

/// Returns true if the given identifier is a valid Reference primitive JSX component name.
pub fn is_primitive_jsx_name(name: &str) -> bool {
    PRIMITIVE_JSX.binary_search(&name).is_ok()
}

/// Returns true if the given element name is either an HTML tag or a Reference primitive.
pub fn is_reference_primitive(name: &str) -> bool {
    is_html_tag(name) || is_primitive_jsx_name(name)
}
`;
}
