export type {
  ReadonlyProps,
  WithMethod,
  Callable,
  StringMap,
  MixedMembers,
  StringArray,
  NumberArray,
  StringNumberPair,
  WithIdAndName,
  Pairs,
  NamedPair,
  WithOptionalElement,
  WithRest,
  Constructible,
  ParenType,
} from './api';
