packages:
  - pipeline
  - packages/*
  - packages/reference-lib/playwright/runtimes/*
  - matrix/tests/*
  - matrix/tests/*/*
  - matrix/fixtures/*
  - panda-playground
  - '!packages/old/**'

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - esbuild
  - nx

linkWorkspacePackages: true

