packages:
  - pipeline
  - packages/*
  - packages/reference-lib/playwright/runtimes/*
  - fixtures/*
  - matrix/*
  - matrix/*/*
  - panda-playground
  - '!packages/old/**'

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - esbuild
  - nx

linkWorkspacePackages: true

