// census-union.ts — the checked-in PARITY-02 absence list for NEO-PARITY-02.
// It takes nothing and emits the 159-entry union (158 group entries plus
// P-DELTA-4) transcribed from the parity SPEC §union table, each with the
// owner group, the approved/out-of-scope kind, and a grounding keyword the
// census verifies inside the owner's SPEC. The census spec asserts this
// list equals the SPEC table exactly, labels verbatim, so transcription
// drift fails the case instead of silently forking the list.

export interface UnionEntry {
  id: string;
  group: string;
  kind: 'approved' | 'oos' | 'parity';
  label: string;
  key: string;
}

export const UNION: UnionEntry[] = [
  { id: 'sync-a1', group: 'sync', kind: 'approved', label: 'types/ pkg D19', key: 'fourth package' },
  { id: 'sync-a2', group: 'sync', kind: 'approved', label: 'font-registry.json', key: 'font-registry.json' },
  { id: 'sync-a3', group: 'sync', kind: 'approved', label: 'packaged core types', key: 'packaged core types' },
  { id: 'sync-a4', group: 'sync', kind: 'approved', label: 'styled/tokens|themes|extensions/', key: 'styled/tokens' },
  { id: 'sync-a5', group: 'sync', kind: 'approved', label: 'D7 bugs', key: 'Panda bugs (D7)' },
  { id: 'sync-o1', group: 'sync', kind: 'oos', label: 'panda.config + styled machinery', key: 'panda.config.ts' },
  { id: 'sync-o2', group: 'sync', kind: 'oos', label: 'virtual/', key: 'virtual/` mirror' },
  { id: 'sync-o3', group: 'sync', kind: 'oos', label: 'Vite/Webpack/CLI/session', key: 'Vite / Webpack' },
  { id: 'sync-o4', group: 'sync', kind: 'oos', label: 'strict/layers/mcp config', key: '`strict`, `layers`, `mcp`' },
  { id: 'sync-o5', group: 'sync', kind: 'oos', label: 'cva/css.raw', key: '`cva` alias, `css.raw`' },
  { id: 'cond-a1', group: 'cond', kind: 'approved', label: 'rtl/_ltr/_rtl', key: '`[dir=rtl]`' },
  { id: 'cond-a2', group: 'cond', kind: 'approved', label: '@slot cartesian', key: '@slot` cartesian' },
  { id: 'cond-a3', group: 'cond', kind: 'approved', label: 'custom conditions table', key: 'Config-defined custom conditions' },
  { id: 'cond-a4', group: 'cond', kind: 'approved', label: '★DELTA-1 forced-colors/@supports/(hover:hover)', key: 'DELTA-1' },
  { id: 'cond-a5', group: 'cond', kind: 'approved', label: '★DELTA-2 zero-count pseudos', key: 'DELTA-2' },
  { id: 'cond-o1', group: 'cond', kind: 'oos', label: 'rtl wraps', key: ':dir(' },
  { id: 'cond-o2', group: 'cond', kind: 'oos', label: '@slot', key: '@slot` multi-block' },
  { id: 'cond-o3', group: 'cond', kind: 'oos', label: 'conditions table', key: 'Custom `conditions` table' },
  { id: 'cond-o4', group: 'cond', kind: 'oos', label: 'four-way dark', key: 'Four-way dark' },
  { id: 'cond-o5', group: 'cond', kind: 'oos', label: '_themePrimary', key: '_themePrimary' },
  { id: 'cond-o6', group: 'cond', kind: 'oos', label: 'hideFrom/hideBelow', key: 'hideFrom' },
  { id: 'token-a1', group: 'token', kind: 'approved', label: 'colorPalette D14', key: 'colorPalette` virtual' },
  { id: 'token-a2', group: 'token', kind: 'approved', label: 'token() D15', key: 'token()` string helper' },
  { id: 'token-a3', group: 'token', kind: 'approved', label: 'composite objects', key: 'Composite token objects' },
  { id: 'token-a4', group: 'token', kind: 'approved', label: 'themes JSON', key: 'Panda `themes` JSON' },
  { id: 'token-a5', group: 'token', kind: 'approved', label: ':where(html)', key: ':where(html)' },
  { id: 'token-a6', group: 'token', kind: 'approved', label: 'hashed vars', key: 'Hashed var names' },
  { id: 'token-a7', group: 'token', kind: 'approved', label: '★F2 0.33% D7', key: 'red/0.33' },
  { id: 'token-a8', group: 'token', kind: 'approved', label: '★F3 /half', key: 'red/half' },
  { id: 'token-a9', group: 'token', kind: 'approved', label: '★OOD bp-conditioned values', key: 'breakpoint-conditioned' },
  { id: 'token-a10', group: 'token', kind: 'approved', label: '★OOD osDark:highCon', key: 'osDark:highCon' },
  { id: 'token-a11', group: 'token', kind: 'approved', label: '★OOD forced-colors islands', key: 'forced-colors token islands' },
  { id: 'token-a12', group: 'token', kind: 'approved', label: '★OOD token() fallbacks', key: 'nested fallbacks' },
  { id: 'token-a13', group: 'token', kind: 'approved', label: '★OOD percent cssVar', key: 'percent cssVar' },
  { id: 'token-a14', group: 'token', kind: 'approved', label: 'leading-zero numerics', key: 'leading-zero numerics' },
  { id: 'token-a15', group: 'token', kind: 'approved', label: 'flat-nested token miss', key: 'flat-nested token miss' },
  { id: 'token-a16', group: 'token', kind: 'approved', label: 'slash diagnostic wording', key: 'slash diagnostic wording' },
  { id: 'token-o1', group: 'token', kind: 'oos', label: 'semanticTokens', key: '`semanticTokens`' },
  { id: 'token-o2', group: 'token', kind: 'oos', label: '@slot OR', key: 'selector-only OR' },
  { id: 'token-o3', group: 'token', kind: 'oos', label: 'DEFAULT', key: '`DEFAULT` keyword' },
  { id: 'token-o4', group: 'token', kind: 'oos', label: 'strict hatches', key: 'WithEscapeHatch' },
  { id: 'token-o5', group: 'token', kind: 'oos', label: 'token.var', key: '`token.var`' },
  { id: 'token-o6', group: 'token', kind: 'oos', label: 'text/layer/animation styles', key: '`textStyles`' },
  { id: 'token-o7', group: 'token', kind: 'oos', label: 'asset tokens', key: 'Asset tokens' },
  { id: 'token-o8', group: 'token', kind: 'oos', label: 'circular refs', key: 'Circular refs' },
  { id: 'css-a1', group: 'css', kind: 'approved', label: 'hideFrom/hideBelow', key: '`hideFrom` / `hideBelow`' },
  { id: 'css-a2', group: 'css', kind: 'approved', label: 'shared-class custom utils', key: 'shared class names' },
  { id: 'css-a3', group: 'css', kind: 'approved', label: '@scope', key: '`@scope`' },
  { id: 'css-a4', group: 'css', kind: 'approved', label: 'token()', key: '`token()` string helper' },
  { id: 'css-a5', group: 'css', kind: 'approved', label: 'capital-W vendor keys', key: 'Capital-W vendor keys' },
  { id: 'css-a6', group: 'css', kind: 'approved', label: 'numerics lower to px', key: 'numerics lower to px' },
  { id: 'css-a7', group: 'css', kind: 'approved', label: 'no autoprefixer', key: 'no autoprefixer' },
  { id: 'css-o1', group: 'css', kind: 'oos', label: 'prefix/hash', key: 'custom `toHash`' },
  { id: 'css-o2', group: 'css', kind: 'oos', label: 'fromJSON wire', key: 'fromJSON' },
  { id: 'css-o3', group: 'css', kind: 'oos', label: 'truncate', key: 'truncate' },
  { id: 'css-o4', group: 'css', kind: 'oos', label: 'textStyle/animationStyle', key: '`textStyle`' },
  { id: 'css-o5', group: 'css', kind: 'oos', label: 'divideX/Y', key: '`divideX`' },
  { id: 'css-o6', group: 'css', kind: 'oos', label: 'template-literal css', key: 'Template-literal' },
  { id: 'resp-a1', group: 'resp', kind: 'approved', label: '@media breakpoints D8', key: '`@media screen` viewport' },
  { id: 'resp-a2', group: 'resp', kind: 'approved', label: 'hideFrom/hideBelow', key: '`hideFrom` / `hideBelow`' },
  { id: 'resp-a3', group: 'resp', kind: 'approved', label: '{sizes.x}', key: '{sizes.x}' },
  { id: 'resp-o1', group: 'resp', kind: 'oos', label: '@breakpoint macro', key: '`@breakpoint` directive' },
  { id: 'resp-o2', group: 'resp', kind: 'oos', label: 'rem epsilon', key: 'rem epsilon' },
  { id: 'resp-o3', group: 'resp', kind: 'oos', label: 'RTL×resp', key: 'RTL × responsive' },
  { id: 'resp-o4', group: 'resp', kind: 'oos', label: 'named container statics', key: 'Named `@container pb' },
  { id: 'resp-o5', group: 'resp', kind: 'oos', label: 'sort-mq', key: '`sort-mq` plugin' },
  { id: 'resp-o6', group: 'resp', kind: 'oos', label: 'recipe resp variants (→RECIPE-08)', key: 'Recipe responsive variants' },
  { id: 'resp-o7', group: 'resp', kind: 'oos', label: 'globalCss resp keys (→GLOBAL)', key: '`globalCss` nested responsive' },
  { id: 'merge-a1', group: 'merge', kind: 'approved', label: 'red-then-blue', key: 'red-then-blue' },
  { id: 'merge-a2', group: 'merge', kind: 'approved', label: 'mergeProps', key: '`mergeProps` deep-merge' },
  { id: 'merge-a3', group: 'merge', kind: 'approved', label: 'walkObject leaves', key: '`walkObject` arrays-as-leaves' },
  { id: 'merge-a4', group: 'merge', kind: 'approved', label: 'GHOST-04', key: 'GHOST-04' },
  { id: 'merge-o1', group: 'merge', kind: 'oos', label: 'sort comparators', key: '`sort-mq` / `sort-css`' },
  { id: 'merge-o2', group: 'merge', kind: 'oos', label: 'hideFrom/hideBelow', key: '`hideFrom` / `hideBelow`' },
  { id: 'merge-o3', group: 'merge', kind: 'oos', label: 'shared className', key: 'sharing one className' },
  { id: 'merge-o4', group: 'merge', kind: 'oos', label: 'token()', key: '`token()` string helper' },
  { id: 'merge-o5', group: 'merge', kind: 'oos', label: 'sva merge', key: 'Slot/`sva` merge' },
  { id: 'recipe-a1', group: 'recipe', kind: 'approved', label: 'sva D9', key: 'Slot recipes / `sva` (D9)' },
  { id: 'recipe-a2', group: 'recipe', kind: 'approved', label: 'cva D3', key: '`cva` name (D3)' },
  { id: 'recipe-a3', group: 'recipe', kind: 'approved', label: '_base inner layer', key: '`recipes._base` inner-layer' },
  { id: 'recipe-a4', group: 'recipe', kind: 'approved', label: 'static expansion', key: 'static recipe expansion' },
  { id: 'recipe-o1', group: 'recipe', kind: 'oos', label: 'sva/slots layer', key: '`sva()` / slot recipes' },
  { id: 'recipe-o2', group: 'recipe', kind: 'oos', label: 'cva', key: '`cva` export name' },
  { id: 'recipe-o3', group: 'recipe', kind: 'oos', label: 'nested layers', key: 'nested recipe layers' },
  { id: 'recipe-o4', group: 'recipe', kind: 'oos', label: 'static combo expansion', key: 'Static expansion of all variant combos' },
  { id: 'recipe-o5', group: 'recipe', kind: 'oos', label: 'staticCss.recipes', key: '`staticCss.recipes`' },
  { id: 'recipe-o6', group: 'recipe', kind: 'oos', label: 'const-bound indirection', key: 'Const-bound `recipe(definition)`' },
  { id: 'global-a1', group: 'global', kind: 'approved', label: 'banner+var-dump D7', key: 'var dump (D7)' },
  { id: 'global-a2', group: 'global', kind: 'approved', label: 'base global.css artifact D2', key: '`global.css` file as a build artifact (D2)' },
  { id: 'global-a3', group: 'global', kind: 'approved', label: 'tokens-layer keyframes', key: 'in the tokens layer' },
  { id: 'global-a4', group: 'global', kind: 'approved', label: 'comma-merge', key: 'comma-merging' },
  { id: 'global-a5', group: 'global', kind: 'approved', label: 'colorPalette/size_md/leftover/dup-dark D7', key: 'leftover class' },
  { id: 'global-a6', group: 'global', kind: 'approved', label: 'data-theme rules in global', key: 'rules inside the global layer' },
  { id: 'global-o1', group: 'global', kind: 'oos', label: 'themes JSON', key: 'Panda `themes` JSON' },
  { id: 'global-o2', group: 'global', kind: 'oos', label: ':where(html)+@property', key: '`@property`' },
  { id: 'global-o3', group: 'global', kind: 'oos', label: '@position-try', key: '`@position-try`' },
  { id: 'global-o4', group: 'global', kind: 'oos', label: 'divideX/Y', key: '`divideX`' },
  { id: 'global-o5', group: 'global', kind: 'oos', label: 'static cardinality', key: 'Static colour/spacing cardinality' },
  { id: 'global-o6', group: 'global', kind: 'oos', label: 'viewport breakpoints', key: 'Viewport `@media` breakpoints in globals' },
  { id: 'global-o7', group: 'global', kind: 'oos', label: 'groupHover/peerFocus', key: '`groupHover` / `peerFocus`' },
  { id: 'global-o8', group: 'global', kind: 'oos', label: 'sva', key: 'Slot recipes / `sva`' },
  { id: 'global-o9', group: 'global', kind: 'oos', label: 'token()', key: '`token()` string helper' },
  { id: 'global-o10', group: 'global', kind: 'oos', label: 'preflight', key: 'Panda preflight' },
  { id: 'site-a1', group: 'site', kind: 'approved', label: 'tagged templates', key: 'Tagged templates' },
  { id: 'site-a2', group: 'site', kind: 'approved', label: 'Vue/Svelte', key: 'Vue/Svelte' },
  { id: 'site-a3', group: 'site', kind: 'approved', label: 'compiled JSX', key: 'Compiled JSX runtimes' },
  { id: 'site-a4', group: 'site', kind: 'approved', label: 'importMap', key: '`importMap`' },
  { id: 'site-a5', group: 'site', kind: 'approved', label: 'matchTag/PascalCase', key: '`matchTag`' },
  { id: 'site-a6', group: 'site', kind: 'approved', label: 'token() inlining', key: '`token()` inlining' },
  { id: 'site-a7', group: 'site', kind: 'approved', label: 'css.raw', key: '**`css.raw`**' },
  { id: 'site-a8', group: 'site', kind: 'approved', label: 'element-access refusal', key: 'element-access refusal' },
  { id: 'site-a9', group: 'site', kind: 'approved', label: 'computed-key refusal', key: 'computed-key refusal' },
  { id: 'site-o1', group: 'site', kind: 'oos', label: 'styled() factory', key: '`styled()` factory' },
  { id: 'site-o2', group: 'site', kind: 'oos', label: 'patterns pack', key: 'Patterns pack' },
  { id: 'site-o3', group: 'site', kind: 'oos', label: 'cva/sva', key: '`cva` / `sva` as author APIs' },
  { id: 'site-o4', group: 'site', kind: 'oos', label: 'template-literal syntax', key: "syntax: 'template-literal'" },
  { id: 'site-o5', group: 'site', kind: 'oos', label: 'jsxFramework modes', key: '`jsxFramework`' },
  { id: 'site-o6', group: 'site', kind: 'oos', label: 'strictTokens type-level', key: '`strictTokens` / `strictPropertyValues`' },
  { id: 'site-o7', group: 'site', kind: 'oos', label: 'staticCss config', key: '`staticCss` config' },
  { id: 'prim-a1', group: 'prim', kind: 'approved', label: 'Box/Flex/Grid', key: '`Box`/`Flex`/`Grid`' },
  { id: 'prim-a2', group: 'prim', kind: 'approved', label: 'as', key: 'Polymorphic `as`' },
  { id: 'prim-a3', group: 'prim', kind: 'approved', label: 'cx/splitCssProps', key: '`cx` / `splitCssProps`' },
  { id: 'prim-o1', group: 'prim', kind: 'oos', label: 'styled()/factory', key: '`styled()` / jsx-factory' },
  { id: 'prim-o2', group: 'prim', kind: 'oos', label: 'pattern fns', key: 'pattern fns' },
  { id: 'prim-o3', group: 'prim', kind: 'oos', label: 'data-panda-theme/data-theme', key: '`data-panda-theme` / `data-theme`' },
  { id: 'prim-o4', group: 'prim', kind: 'oos', label: 'liquid/forwardRef', key: 'forwardRef' },
  { id: 'prim-o5', group: 'prim', kind: 'oos', label: 'sva on primitives', key: 'on primitives' },
  { id: 'static-a1', group: 'static', kind: 'approved', label: 'static recipes', key: 'compound-variant statics' },
  { id: 'static-a2', group: 'static', kind: 'approved', label: 'static slots/patterns', key: 'Static slot recipes / patterns' },
  { id: 'static-a3', group: 'static', kind: 'approved', label: 'colorPalette wildcards', key: 'colorPalette` no-op atoms in wildcard counts' },
  { id: 'static-a4', group: 'static', kind: 'approved', label: 'named container statics', key: 'Named `@container` statics' },
  { id: 'static-o1', group: 'static', kind: 'oos', label: 'cache/memo/bench', key: 'wildcard memo' },
  { id: 'static-o2', group: 'static', kind: 'oos', label: 'freeform condition strings', key: 'freeform condition strings' },
  { id: 'static-o3', group: 'static', kind: 'oos', label: 'sva statics', key: '`sva` / slot anatomy in staticCss' },
  { id: 'static-o4', group: 'static', kind: 'oos', label: 'text/layer statics', key: '`textStyles` / `layerStyles` statics' },
  { id: 'static-o5', group: 'static', kind: 'oos', label: 'prefix/hash', key: 'custom `toHash`' },
  { id: 'layer-a1', group: 'layer', kind: 'approved', label: 'empty base/recipes bodies', key: 'Empty `base` / `recipes` bodies' },
  { id: 'layer-a2', group: 'layer', kind: 'approved', label: 'recipes._base/slots inner', key: '`recipes.slots` inner layers' },
  { id: 'layer-a3', group: 'layer', kind: 'approved', label: 'compositions layer', key: '`compositions` layer' },
  { id: 'layer-a4', group: 'layer', kind: 'approved', label: 'banner+var-dump D7', key: 'transform-var dump' },
  { id: 'layer-a5', group: 'layer', kind: 'approved', label: 'colorPalette atoms', key: '`colorPalette.*` virtual atoms' },
  { id: 'layer-a6', group: 'layer', kind: 'approved', label: '★F7 scoped reset', key: 'scoped reset' },
  { id: 'layer-o1', group: 'layer', kind: 'oos', label: 'custom layer names', key: 'Custom `CascadeLayers`' },
  { id: 'layer-o2', group: 'layer', kind: 'oos', label: 'LightningCSS five-layer', key: 'five-layer list' },
  { id: 'layer-o3', group: 'layer', kind: 'oos', label: 'static recipe expansion', key: 'Static recipe expansion' },
  { id: 'layer-o4', group: 'layer', kind: 'oos', label: 'panda.config/global.css inputs', key: '`panda.config.ts` / `styled/global.css`' },
  { id: 'type-a1', group: 'type', kind: 'approved', label: 'strict hatches D17', key: 'WithEscapeHatch' },
  { id: 'type-a2', group: 'type', kind: 'approved', label: 'pattern+factory types', key: 'Pattern types' },
  { id: 'type-a3', group: 'type', kind: 'approved', label: 'recipes d.ts + tokens.mjs/token()', key: '`tokens.mjs`' },
  { id: 'type-a4', group: 'type', kind: 'approved', label: 'styled global.d.ts', key: 'global.d.ts' },
  { id: 'type-a5', group: 'type', kind: 'approved', label: 'TokenCategory/ColorPalette unions', key: '`TokenCategory`' },
  { id: 'type-a6', group: 'type', kind: 'approved', label: 'text/layer/animation+asset+formatTokenName+hashed', key: '`formatTokenName`' },
  { id: 'type-o1', group: 'type', kind: 'oos', label: 'bare sm keys', key: 'Bare `sm`' },
  { id: 'type-o2', group: 'type', kind: 'oos', label: 'ConditionalValue variants', key: '`ConditionalValue`-wrapped' },
  { id: 'type-o3', group: 'type', kind: 'oos', label: 'csstype dump', key: '`csstype.Properties`' },
  { id: 'type-o4', group: 'type', kind: 'oos', label: 'atomic names in d.ts', key: 'Atomic class names' },
  { id: 'type-o5', group: 'type', kind: 'oos', label: 'cva/css.raw', key: '`cva` alias, `css.raw`' },
  { id: 'type-o6', group: 'type', kind: 'oos', label: 'token.var/globalVars', key: '`token.var` JS map' },
  {
    id: 'parity-p1',
    group: 'parity',
    kind: 'parity',
    label:
      'P-DELTA-4: boolean leaks (`.focus_true`, `.isolation_true`, …) + dotted passthroughs (`background: ui.panel.background`) — D7 extension, captain auto-§3 (w4-synthesis C-DELTA-4)',
    key: 'P-DELTA-4',
  },
];
