/**
 * Reference Lib - design system consumer.
 * Exports baseSystem for extends[] in downstream apps.
 *
 * Run `ref sync` in reference-lib before using.
 */
// @ts-expect-error -- generated by `ref sync`; declaration is emitted alongside the runtime file
export { baseSystem } from '../.reference-ui/system/baseSystem.mjs'
export { REF_LIB_CANARY } from './colors.js'
