//! Frozen `colors.ui.*` semantic tokens copied from `core/theme/primitives/tokens.ts`.
//! Each leaf has distinct light and dark values, often `{colors…}` aliases into the palette.
//! Paths stay under the `colors` category so `colors.ui.field.border` is the lookup key.
//! This file does not resolve those aliases; atomic and later token layers do.

use super::{fill_pairs, TokenDictionary};

const UI: &[(&str, &str, &str)] = &[
    (
        "ui.selection.background",
        "{colors.gray.900}",
        "{colors.gray.100}",
    ),
    (
        "ui.selection.foreground",
        "{colors.gray.50}",
        "{colors.gray.800}",
    ),
    (
        "ui.dialog.background",
        "oklch(100% 0 0)",
        "{colors.gray.950}",
    ),
    (
        "ui.dialog.foreground",
        "{colors.design.text.base}",
        "{colors.design.text.base}",
    ),
    ("ui.dialog.border", "{colors.gray.200}", "{colors.gray.800}"),
    ("ui.hr.border", "{colors.gray.200}", "{colors.gray.800}"),
    (
        "ui.meta.foreground",
        "{colors.design.text.light}",
        "{colors.design.text.light}",
    ),
    (
        "ui.blockquote.foreground",
        "{colors.design.text.light}",
        "{colors.design.text.light}",
    ),
    (
        "ui.blockquote.border",
        "{colors.gray.300}",
        "{colors.gray.700}",
    ),
    (
        "ui.cite.foreground",
        "{colors.design.text.light}",
        "{colors.design.text.light}",
    ),
    (
        "ui.small.foreground",
        "{colors.design.text.light}",
        "{colors.design.text.light}",
    ),
    (
        "ui.code.inline.foreground",
        "{colors.design.accent.foreground}",
        "{colors.design.accent.foreground}",
    ),
    (
        "ui.code.inline.background",
        "{colors.design.accent.background}",
        "{colors.design.accent.background}",
    ),
    (
        "ui.code.inline.border",
        "{colors.design.accent.border}",
        "{colors.design.accent.border}",
    ),
    (
        "ui.kbd.background",
        "{colors.gray.100}",
        "{colors.gray.800}",
    ),
    (
        "ui.kbd.foreground",
        "{colors.design.text.base}",
        "{colors.design.text.base}",
    ),
    ("ui.kbd.border", "{colors.gray.200}", "{colors.gray.800}"),
    ("ui.kbd.shadowMix", "{colors.gray.950}", "{colors.gray.50}"),
    (
        "ui.pre.foreground",
        "{colors.design.text.base}",
        "{colors.design.text.base}",
    ),
    (
        "ui.pre.background",
        "{colors.gray.100}",
        "{colors.gray.900}",
    ),
    (
        "ui.pre.border",
        "{colors.design.accent.border}",
        "{colors.gray.800}",
    ),
    (
        "ui.samp.background",
        "{colors.gray.200}",
        "{colors.gray.800}",
    ),
    (
        "ui.samp.foreground",
        "{colors.design.text.base}",
        "{colors.design.text.light}",
    ),
    ("ui.link.default", "{colors.blue.700}", "{colors.blue.400}"),
    ("ui.link.hover", "{colors.blue.800}", "{colors.blue.300}"),
    (
        "ui.mark.background",
        "{colors.blue.200}",
        "{colors.blue.900}",
    ),
    (
        "ui.mark.foreground",
        "{colors.blue.950}",
        "{colors.blue.100}",
    ),
    (
        "ui.ins.foreground",
        "{colors.design.text.base}",
        "{colors.design.text.base}",
    ),
    (
        "ui.ins.decoration",
        "{colors.blue.700}",
        "{colors.blue.400}",
    ),
    (
        "ui.abbr.textDecoration",
        "{colors.gray.500}",
        "{colors.gray.400}",
    ),
    (
        "ui.del.foreground",
        "{colors.design.text.light}",
        "{colors.design.text.light}",
    ),
    (
        "ui.dfn.foreground",
        "{colors.design.text.light}",
        "{colors.design.text.light}",
    ),
    (
        "ui.q.foreground",
        "{colors.design.text.light}",
        "{colors.design.text.light}",
    ),
    (
        "ui.s.foreground",
        "{colors.design.text.light}",
        "{colors.design.text.light}",
    ),
    (
        "ui.u.textDecoration",
        "{colors.design.text.light}",
        "{colors.design.text.light}",
    ),
    (
        "ui.varTag.foreground",
        "{colors.blue.700}",
        "{colors.blue.400}",
    ),
    (
        "ui.list.marker.foreground",
        "{colors.design.text.light}",
        "{colors.design.text.light}",
    ),
    (
        "ui.list.definition.description.foreground",
        "{colors.design.text.light}",
        "{colors.design.text.light}",
    ),
    (
        "ui.fieldset.border",
        "{colors.gray.200}",
        "{colors.gray.800}",
    ),
    (
        "ui.label.controlAccent",
        "{colors.gray.950}",
        "{colors.gray.50}",
    ),
    ("ui.field.border", "{colors.gray.300}", "{colors.gray.700}"),
    (
        "ui.field.borderHover",
        "{colors.gray.400}",
        "{colors.gray.600}",
    ),
    (
        "ui.field.background",
        "oklch(100% 0 0)",
        "{colors.gray.950}",
    ),
    (
        "ui.field.foreground",
        "{colors.design.text.base}",
        "{colors.design.text.base}",
    ),
    (
        "ui.field.focusRing",
        "{colors.gray.400}",
        "{colors.gray.500}",
    ),
    (
        "ui.field.placeholder",
        "{colors.gray.500}",
        "{colors.gray.400}",
    ),
    (
        "ui.field.controlAccent",
        "{colors.gray.950}",
        "{colors.gray.50}",
    ),
    (
        "ui.checkbox.unchecked.borderMix",
        "{colors.gray.950}",
        "{colors.gray.50}",
    ),
    (
        "ui.checkbox.checked.fill",
        "{colors.gray.950}",
        "{colors.gray.50}",
    ),
    (
        "ui.checkbox.tick.stroke",
        "oklch(100% 0 0)",
        "{colors.gray.950}",
    ),
    (
        "ui.radio.track.background",
        "{colors.gray.300}",
        "{colors.gray.800}",
    ),
    (
        "ui.radio.checked.inner.background",
        "oklch(100% 0 0)",
        "{colors.gray.950}",
    ),
    (
        "ui.radio.checked.ring.border",
        "{colors.gray.950}",
        "{colors.gray.50}",
    ),
    (
        "ui.button.background",
        "{colors.gray.950}",
        "{colors.gray.50}",
    ),
    (
        "ui.button.foreground",
        "{colors.gray.50}",
        "{colors.gray.950}",
    ),
    (
        "ui.button.disabled.background",
        "{colors.gray.200}",
        "{colors.gray.800}",
    ),
    (
        "ui.button.disabled.foreground",
        "{colors.design.text.lighter}",
        "{colors.design.text.lighter}",
    ),
    (
        "ui.progress.bar.foreground",
        "{colors.gray.950}",
        "{colors.gray.50}",
    ),
    (
        "ui.progress.track.mixForeground",
        "{colors.gray.950}",
        "{colors.gray.50}",
    ),
    (
        "ui.progress.track.mixBackground",
        "oklch(100% 0 0)",
        "{colors.gray.950}",
    ),
    (
        "ui.meter.optimum.foreground",
        "{colors.blue.600}",
        "{colors.blue.400}",
    ),
    (
        "ui.meter.suboptimum.foreground",
        "{colors.amber.500}",
        "{colors.amber.400}",
    ),
    (
        "ui.meter.evenLessGood.foreground",
        "{colors.red.600}",
        "{colors.red.400}",
    ),
    ("ui.focus.ring", "{colors.gray.900}", "{colors.gray.50}"),
    ("ui.table.border", "{colors.gray.200}", "{colors.gray.800}"),
    (
        "ui.table.row.mutedBackground",
        "{colors.gray.100}",
        "{colors.gray.800}",
    ),
    (
        "ui.table.footer.mutedBackground",
        "{colors.gray.100}",
        "{colors.gray.800}",
    ),
    (
        "ui.table.cell.foreground",
        "{colors.design.text.base}",
        "{colors.design.text.base}",
    ),
    (
        "ui.table.caption.foreground",
        "{colors.design.text.light}",
        "{colors.design.text.light}",
    ),
    (
        "ui.media.caption.foreground",
        "{colors.design.text.light}",
        "{colors.design.text.light}",
    ),
    (
        "ui.media.embed.border",
        "{colors.gray.200}",
        "{colors.gray.800}",
    ),
    (
        "ui.disclosure.border",
        "{colors.gray.200}",
        "{colors.gray.800}",
    ),
    (
        "ui.tab.track.background",
        "{colors.gray.100}",
        "{colors.gray.900}",
    ),
];

/// Insert `colors.ui.*` semantic tokens.
pub fn fill(dict: &mut TokenDictionary) {
    fill_pairs(dict, "colors", UI);
}
