export { baseTypography } from './baseTypography'
export { codePrimitiveStyles } from './code'
export { headingPrimitiveStyles } from './headings'
export { inlinePrimitiveStyles } from './inline'
export { textPrimitiveStyles } from './text'
