/**
 * Canon generator: produces the static, typed, zero-allocation Rust canon module
 * from Web standards specifications (@webref) and Reference UI design system dialects.
 */
import * as fs from 'node:fs';
import * as path from 'node:path';
import { fileURLToPath } from 'node:url';
import { loadPlatformCss, loadPlatformElements } from './platform';
import { loadDialect, type DialectElement, type DialectProperty, type DialectAlias } from './dialect';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const systemCrateDir = path.resolve(__dirname, '../crates/system/src/canon');

fs.mkdirSync(systemCrateDir, { recursive: true });

function formatChunks(items: string[], indent = '    ', perLine = 2): string {
  const lines: string[] = [];
  for (let i = 0; i < items.length; i += perLine) {
    const chunk = items.slice(i, i + perLine).join(', ');
    lines.push(`${indent}${chunk},`);
  }
  return lines.join('\n');
}

async function main() {
  console.log('[canon] Ingesting web standards and Reference UI dialect...');
  const platformElements = await loadPlatformElements();
  const platformCss = await loadPlatformCss();
  const dialect = loadDialect();

  // --- 1. Validate Join (Fail Closed) ---
  console.log('[canon] Validating platform vs dialect join...');

  // Rule 1: Every dialect HTML tag MUST be in webref elements
  const invalidTags = dialect.elements.filter((el) => !platformElements.has(el.html.toLowerCase()));
  if (invalidTags.length > 0) {
    console.error('[canon] FAIL: Dialect HTML tags not found in web standards (@webref):', invalidTags);
    process.exit(1);
  }

  // Rule 2: Every canonical CSS property MUST be in webref or dialect allowlist
  const unverifiedProps = dialect.canonicalProperties.filter((p) => {
    const inWebref = platformCss.properties.has(p.name) || platformCss.properties.has(p.css);
    const inAllowlist = dialect.dialectCssAllowlist.has(p.css) || dialect.dialectCssAllowlist.has(p.name);
    return !inWebref && !inAllowlist;
  });
  if (unverifiedProps.length > 0) {
    console.error('[canon] FAIL: Canonical properties not in webref or dialect allowlist:', unverifiedProps);
    process.exit(1);
  }

  // Rule 3: Native spec shorthands MUST match webref longhands
  const specShorthands = ['padding', 'margin', 'border', 'inset', 'outline'];
  for (const sh of specShorthands) {
    const prop = dialect.canonicalProperties.find((p) => p.name === sh);
    const webrefLonghands = platformCss.nativeShorthands.get(sh);
    if (!prop || !webrefLonghands) {
      console.error(`[canon] FAIL: Missing native shorthand longhands for '${sh}'`);
      process.exit(1);
    }
    const dL = prop.longhands.slice().sort();
    const wL = webrefLonghands.slice().sort();
    if (JSON.stringify(dL) !== JSON.stringify(wL)) {
      console.error(`[canon] FAIL: Mismatched native shorthand longhands for '${sh}':`, { dialect: dL, webref: wL });
      process.exit(1);
    }
  }

  console.log('[canon] Join validation passed with 100% compliance.');

  // --- 2. Emit crates/system/src/canon/html.rs ---
  const elementChunks = dialect.elements.map(
    (e) => `Element::new("${e.html}", "${e.jsx}")`
  );
  const htmlRs = `//! Generated HTML tags and Reference primitive JSX element names.
//!
//! Generated by \`packages/reference-rs/canon/generate.ts\`.
//! Represents the curated subset of HTML elements wrapped as Reference UI JSX primitives.
// @generated

/// Element mapping from lowercase HTML element tag to PascalCase JSX primitive.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Element {
    pub html: &'static str,
    pub jsx: &'static str,
}

impl Element {
    pub const fn new(html: &'static str, jsx: &'static str) -> Self {
        Self { html, jsx }
    }
}

/// All canonical elements supported as Reference UI primitives.
pub const ELEMENTS: &[Element] = &[
${formatChunks(elementChunks, '    ', 3)}
];

/// Returns true if the given tag name is a valid lowercase HTML element tag in the canon.
pub fn is_html_tag(tag: &str) -> bool {
    ELEMENTS.binary_search_by_key(&tag, |e| e.html).is_ok()
}

/// Returns true if the given identifier is a valid Reference primitive JSX component name.
pub fn is_primitive_jsx_name(name: &str) -> bool {
    ELEMENTS.binary_search_by_key(&name, |e| e.jsx).is_ok()
}

/// Returns true if the given element name is either an HTML tag or a Reference primitive.
pub fn is_reference_primitive(name: &str) -> bool {
    is_html_tag(name) || is_primitive_jsx_name(name)
}
`;
  fs.writeFileSync(path.join(systemCrateDir, 'html.rs'), htmlRs, 'utf-8');

  // --- 3. Emit crates/system/src/canon/css.rs ---
  const longhandSlices = new Map<string, string>();
  const longhandSliceDefs: string[] = [];

  for (const p of dialect.canonicalProperties) {
    if (p.longhands.length > 0) {
      const sliceConstName = `${p.name.toUpperCase()}_LONGHANDS`;
      longhandSlices.set(p.name, sliceConstName);
      const itemsStr = p.longhands.map((s) => `"${s}"`).join(', ');
      longhandSliceDefs.push(`static ${sliceConstName}: &[&str] = &[${itemsStr}];`);
    }
  }

  const propertyChunks = dialect.canonicalProperties.map((p) => {
    const sliceName = longhandSlices.get(p.name) ?? '&[]';
    return `Property::new("${p.name}", "${p.css}", "${p.classPrefix}", ${sliceName})`;
  });

  const cssRs = `//! Canonical CSS properties, native shorthand longhands, and utility class prefixes.
//!
//! Generated by \`packages/reference-rs/canon/generate.ts\`.
//! Bridges W3C/WHATWG CSS property definitions with Reference UI class prefixes.
// @generated

/// Canonical property specification in the compiler canon.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Property {
    pub name: &'static str,
    pub css: &'static str,
    pub class_prefix: &'static str,
    pub longhands: &'static [&'static str],
}

impl Property {
    pub const fn new(
        name: &'static str,
        css: &'static str,
        class_prefix: &'static str,
        longhands: &'static [&'static str],
    ) -> Self {
        Self {
            name,
            css,
            class_prefix,
            longhands,
        }
    }
}

// Native shorthand longhand slices
${longhandSliceDefs.join('\n')}

/// All canonical CSS and system properties sorted by camelCase property name.
pub const CANONICAL_PROPERTIES: &[Property] = &[
${formatChunks(propertyChunks, '    ', 2)}
];

/// Returns the Property record for a canonical property name, if known.
pub fn find_property(name: &str) -> Option<&'static Property> {
    CANONICAL_PROPERTIES
        .binary_search_by_key(&name, |p| p.name)
        .ok()
        .map(|idx| &CANONICAL_PROPERTIES[idx])
}

/// Returns the native shorthand longhands for a property, if it is a shorthand.
pub fn native_longhands_for_prop(name: &str) -> Option<&'static [&'static str]> {
    match find_property(name) {
        Some(p) if !p.longhands.is_empty() => Some(p.longhands),
        _ => None,
    }
}
`;
  fs.writeFileSync(path.join(systemCrateDir, 'css.rs'), cssRs, 'utf-8');

  // --- 4. Emit crates/system/src/canon/dialect.rs ---
  const aliasChunks = dialect.aliases.map((a) => `Alias::new("${a.alias}", "${a.canonical}")`);
  const refPropChunks = dialect.referenceProps.map((p) => `"${p}"`);

  const dialectRs = `//! Reference UI StyleProps dialect aliases and custom props.
//!
//! Generated by \`packages/reference-rs/canon/generate.ts\`.
//! Maps concise authoring shorthand aliases to canonical CSS properties and defines Reference-only props.
// @generated

/// StyleProps alias mapping a shorthand alias to its canonical property name.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Alias {
    pub alias: &'static str,
    pub canonical: &'static str,
}

impl Alias {
    pub const fn new(alias: &'static str, canonical: &'static str) -> Self {
        Self { alias, canonical }
    }
}

/// Sorted table of StyleProps shorthand aliases.
pub const ALIASES: &[Alias] = &[
${formatChunks(aliasChunks, '    ', 3)}
];

/// Reference-only custom props (e.g. rhythm multipliers, container macros, variant discriminators).
pub const REFERENCE_PROPS: &[&str] = &[
${formatChunks(refPropChunks, '    ', 3)}
];

/// Resolves a dialect alias or shorthand to its canonical property name.
pub fn resolve_alias(alias: &str) -> Option<&'static str> {
    ALIASES
        .binary_search_by_key(&alias, |a| a.alias)
        .ok()
        .map(|idx| ALIASES[idx].canonical)
}

/// Returns true if the given name is a Reference-only prop.
pub fn is_reference_prop(name: &str) -> bool {
    REFERENCE_PROPS.binary_search(&name).is_ok()
}
`;
  fs.writeFileSync(path.join(systemCrateDir, 'dialect.rs'), dialectRs, 'utf-8');

  // --- 5. Emit crates/system/src/canon/conditions.rs ---
  const bpChunks = dialect.breakpoints.map((b) => `"${b}"`);
  const condChunks = dialect.conditions.map((c) => `"${c}"`);

  const conditionsRs = `//! Reference UI conditions, pseudo-selectors, and default responsive breakpoints.
//!
//! Generated by \`packages/reference-rs/canon/generate.ts\`.
//! Defines discriminator keys for pseudo-classes, responsive breakpoints, and media queries.
// @generated

/// Canonical ordered list of default responsive breakpoints.
pub const DEFAULT_BREAKPOINTS: &[&str] = &[
${formatChunks(bpChunks, '    ', 6)}
];

/// Sorted list of recognized condition keys.
pub const CONDITIONS: &[&str] = &[
${formatChunks(condChunks, '    ', 4)}
];

/// Returns true if the given key represents a condition, pseudo selector, or breakpoint.
pub fn is_condition(name: &str) -> bool {
    if name.starts_with('_') || name.starts_with('&') || name.starts_with('@') {
        return true;
    }
    CONDITIONS.binary_search(&name).is_ok()
}

/// Returns the default responsive breakpoint name for an array index.
pub fn default_breakpoint_for_index(idx: usize) -> Option<&'static str> {
    DEFAULT_BREAKPOINTS.get(idx).copied()
}
`;
  fs.writeFileSync(path.join(systemCrateDir, 'conditions.rs'), conditionsRs, 'utf-8');

  // --- 6. Emit crates/system/src/canon/mod.rs ---
  const modRs = `//! The official set of platform elements, CSS properties, aliases, and conditions.
//!
//! Serves as the central dictionary consulted by all compiler stages (extract, resolve, stylesheet).
//! Joins living W3C/WHATWG specifications with Reference UI design system dialects.

pub mod conditions;
pub mod css;
pub mod dialect;
pub mod html;
#[cfg(test)]
mod tests;

pub use conditions::{default_breakpoint_for_index, is_condition, CONDITIONS, DEFAULT_BREAKPOINTS};
pub use css::{find_property, native_longhands_for_prop, Property, CANONICAL_PROPERTIES};
pub use dialect::{is_reference_prop, resolve_alias, Alias, ALIASES, REFERENCE_PROPS};
pub use html::{is_html_tag, is_primitive_jsx_name, is_reference_primitive, Element, ELEMENTS};

/// Returns true if the given property name is a recognized Reference UI style prop.
pub fn is_known_style_prop(name: &str) -> bool {
    if name.starts_with("--") {
        return true;
    }
    is_reference_prop(name) || resolve_alias(name).is_some() || find_property(name).is_some()
}

/// Returns true if the given key represents a condition, pseudo selector, or breakpoint.
pub fn is_condition_prop(name: &str) -> bool {
    is_condition(name)
}

/// Resolves a shorthand or alias to its canonical camelCase property name.
pub fn resolve_canonical_prop(prop: &str) -> &str {
    resolve_alias(prop).unwrap_or(prop)
}

/// Returns the atomic class name prefix for a property.
pub fn class_prefix_for_prop(prop: &str) -> &str {
    let canonical = resolve_canonical_prop(prop);
    if let Some(p) = find_property(canonical) {
        p.class_prefix
    } else {
        canonical
    }
}

/// Converts a camelCase property name to a CSS kebab-case property name.
pub fn to_css_declaration_property(prop: &str) -> String {
    let canonical = resolve_canonical_prop(prop);
    if canonical.starts_with("--") {
        return canonical.to_string();
    }
    if let Some(p) = find_property(canonical) {
        return p.css.to_string();
    }
    let mut out = String::with_capacity(canonical.len() + 4);
    for ch in canonical.chars() {
        if ch.is_ascii_uppercase() {
            out.push('-');
            out.push(ch.to_ascii_lowercase());
        } else {
            out.push(ch);
        }
    }
    out
}
`;
  fs.writeFileSync(path.join(systemCrateDir, 'mod.rs'), modRs, 'utf-8');

  // --- 7. Emit crates/system/src/canon/tests.rs ---
  const testsRs = `//! Unit tests verifying the canon dictionary and all lookup contracts.
//!
//! Asserts element membership, dialect alias resolution, condition matching,
//! and ensures hallucinated primitives (Box, Flex, Grid) are rejected.
// @generated

use super::*;

#[test]
fn test_real_primitives_match() {
    assert!(is_reference_primitive("Div"));
    assert!(is_reference_primitive("Span"));
    assert!(is_reference_primitive("Button"));
    assert!(is_reference_primitive("P"));
    assert!(is_reference_primitive("A"));
    assert!(is_reference_primitive("Obj"));
    assert!(is_reference_primitive("Var"));
    assert!(is_reference_primitive("Section"));
    assert!(is_reference_primitive("Nav"));
    assert!(is_reference_primitive("Header"));
    assert!(is_reference_primitive("Footer"));
    assert!(is_reference_primitive("Main"));
}

#[test]
fn test_lowercase_html_tags_match() {
    assert!(is_html_tag("div"));
    assert!(is_html_tag("span"));
    assert!(is_html_tag("object"));
    assert!(is_html_tag("var"));
    assert!(is_html_tag("button"));
    assert!(is_html_tag("p"));
    assert!(is_reference_primitive("div"));
}

#[test]
fn test_hallucinated_primitives_fail() {
    assert!(!is_reference_primitive("Box"));
    assert!(!is_reference_primitive("Flex"));
    assert!(!is_reference_primitive("Stack"));
    assert!(!is_reference_primitive("Center"));
    assert!(!is_reference_primitive("Spacer"));
    assert!(!is_reference_primitive("Badge"));
    assert!(!is_reference_primitive("Card"));
    assert!(!is_reference_primitive("Tabs"));
    assert!(!is_reference_primitive("Tab"));
    assert!(!is_reference_primitive("Image"));
    assert!(!is_reference_primitive("Portal"));
    assert!(!is_reference_primitive("AspectRatio"));
    assert!(!is_reference_primitive("Grid"));
}

#[test]
fn test_style_props_match() {
    assert!(is_known_style_prop("r"));
    assert!(is_known_style_prop("container"));
    assert!(is_known_style_prop("colorMode"));
    assert!(is_known_style_prop("variant"));
    assert!(is_known_style_prop("font"));
    assert!(is_known_style_prop("weight"));
    assert!(is_known_style_prop("m"));
    assert!(is_known_style_prop("mt"));
    assert!(is_known_style_prop("p"));
    assert!(is_known_style_prop("pt"));
    assert!(is_known_style_prop("bg"));
    assert!(is_known_style_prop("rounded"));
    assert!(is_known_style_prop("borderX"));
    assert!(is_known_style_prop("color"));
    assert!(is_known_style_prop("display"));
    assert!(is_known_style_prop("--custom-token"));
}

#[test]
fn test_non_style_attributes_fail() {
    assert!(!is_known_style_prop("onClick"));
    assert!(!is_known_style_prop("id"));
    assert!(!is_known_style_prop("className"));
    assert!(!is_known_style_prop("children"));
    assert!(!is_known_style_prop("href"));
    assert!(!is_known_style_prop("aria-label"));
    assert!(!is_known_style_prop("data-testid"));
}

#[test]
fn test_conditions_and_breakpoints() {
    assert!(is_condition_prop("base"));
    assert!(is_condition_prop("sm"));
    assert!(is_condition_prop("md"));
    assert!(is_condition_prop("lg"));
    assert!(is_condition_prop("xl"));
    assert!(is_condition_prop("2xl"));

    assert!(is_condition_prop("_hover"));
    assert!(is_condition_prop("_focusVisible"));
    assert!(is_condition_prop("_dark"));
    assert!(is_condition_prop("&:hover"));
    assert!(is_condition_prop("@media (min-width: 600px)"));

    assert!(!is_condition_prop("hover"));
    assert!(!is_condition_prop("focus"));
}

#[test]
fn test_resolve_canonical_prop() {
    assert_eq!(resolve_canonical_prop("mt"), "marginTop");
    assert_eq!(resolve_canonical_prop("p"), "padding");
    assert_eq!(resolve_canonical_prop("bg"), "background");
    assert_eq!(resolve_canonical_prop("c"), "color");
    assert_eq!(resolve_canonical_prop("color"), "color");
}

#[test]
fn test_class_prefix_for_prop() {
    assert_eq!(class_prefix_for_prop("marginTop"), "mt");
    assert_eq!(class_prefix_for_prop("mt"), "mt");
    assert_eq!(class_prefix_for_prop("padding"), "p");
    assert_eq!(class_prefix_for_prop("p"), "p");
    assert_eq!(class_prefix_for_prop("borderBottomWidth"), "bd-b-w");
}

#[test]
fn test_to_css_declaration_property() {
    assert_eq!(to_css_declaration_property("marginTop"), "margin-top");
    assert_eq!(to_css_declaration_property("mt"), "margin-top");
    assert_eq!(to_css_declaration_property("paddingInline"), "padding-inline");
    assert_eq!(to_css_declaration_property("px"), "padding-inline");
    assert_eq!(to_css_declaration_property("--custom-color"), "--custom-color");
}

#[test]
fn test_native_shorthands() {
    let padding_longhands = native_longhands_for_prop("padding").unwrap();
    assert_eq!(padding_longhands, &["paddingTop", "paddingRight", "paddingBottom", "paddingLeft"]);

    let margin_longhands = native_longhands_for_prop("margin").unwrap();
    assert_eq!(margin_longhands, &["marginTop", "marginRight", "marginBottom", "marginLeft"]);

    let border_longhands = native_longhands_for_prop("border").unwrap();
    assert_eq!(border_longhands, &["borderWidth", "borderStyle", "borderColor"]);

    assert!(native_longhands_for_prop("color").is_none());
}
`;
  fs.writeFileSync(path.join(systemCrateDir, 'tests.rs'), testsRs, 'utf-8');

  console.log('[canon] Successfully generated crates/system/src/canon/*.rs');
}

main().catch((err) => {
  console.error('[canon] Generation failed:', err);
  process.exit(1);
});
