//! Standards-backed color properties and Reference dialect color extensions.
//!
//! Generated by `packages/reference-rs/modules/canon/generate/generate.ts`.
//! Ingests color-syntax CSS properties from W3C specs unioned with dialect color properties.
//! Sorted lexicographically to enable zero-allocation binary search in is_color_prop.
// @generated

/// Standards-backed color-bearing properties and dialect color properties.
pub const COLOR_PROPERTIES: &[&str] = &[
    "accentColor", "background", "backgroundColor",
    "border", "borderBlockColor", "borderBlockEnd",
    "borderBlockEndColor", "borderBlockStart", "borderBlockStartColor",
    "borderBottom", "borderBottomColor", "borderColor",
    "borderInlineColor", "borderInlineEnd", "borderInlineEndColor",
    "borderInlineStart", "borderInlineStartColor", "borderLeft",
    "borderLeftColor", "borderRight", "borderRightColor",
    "borderTop", "borderTopColor", "boxShadowColor",
    "caretColor", "color", "columnRuleColor",
    "divideColor", "fill", "fillColor",
    "fillImage", "floodColor", "focusRingColor",
    "lightingColor", "outlineColor", "rowRuleColor",
    "ruleColor", "scrollbarColor", "stopColor",
    "stroke", "strokeColor", "strokeImage",
    "textDecorationColor", "textEmphasisColor", "textShadowColor",
    "webkitTextFillColor", "webkitTextStroke", "webkitTextStrokeColor",
];
