//! Canonical CSS property switchboard, property struct, and lookup functions.
//!
//! Generated by `packages/reference-rs/modules/canon/generate/generate.ts`.
//! Unifies standards-backed W3C CSS properties with Reference UI dialect class prefixes.
//! Provides zero-allocation binary-search lookups for property metadata, colors, and shorthands.
// @generated

pub mod color;
pub mod longhands;
pub mod properties;

pub use color::COLOR_PROPERTIES;
pub use properties::CANONICAL_PROPERTIES;

/// Canonical property specification in the compiler canon.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Property {
    pub name: &'static str,
    pub css: &'static str,
    pub class_prefix: &'static str,
    pub longhands: &'static [&'static str],
}

impl Property {
    pub const fn new(
        name: &'static str,
        css: &'static str,
        class_prefix: &'static str,
        longhands: &'static [&'static str],
    ) -> Self {
        Self {
            name,
            css,
            class_prefix,
            longhands,
        }
    }
}

/// Returns the Property record for a canonical property name, if known.
pub fn find_property(name: &str) -> Option<&'static Property> {
    CANONICAL_PROPERTIES
        .binary_search_by_key(&name, |p| p.name)
        .ok()
        .map(|idx| &CANONICAL_PROPERTIES[idx])
}

/// Returns true if the given property semantically accepts color values and design tokens.
pub fn is_color_prop(prop: &str) -> bool {
    let canonical = match crate::dialect::resolve_alias(prop) {
        Some(c) => c,
        None => prop,
    };
    COLOR_PROPERTIES.binary_search(&canonical).is_ok()
}

/// Returns the native shorthand longhands for a property, if it is a shorthand.
pub fn native_longhands_for_prop(name: &str) -> Option<&'static [&'static str]> {
    let canonical = match crate::dialect::resolve_alias(name) {
        Some(c) => c,
        None => name,
    };
    match find_property(canonical) {
        Some(p) if !p.longhands.is_empty() => Some(p.longhands),
        _ => None,
    }
}
