//! Canonical CSS property switchboard, property struct, and lookup functions.
//!
//! Generated by `packages/reference-rs/modules/canon/generate/generate.ts`.
//! Unifies standards-backed W3C CSS properties with Reference UI dialect class prefixes.
//! Provides zero-allocation binary-search lookups for property metadata, colors, and shorthands.
// @generated

pub mod color;
pub mod longhands;
pub mod properties;

pub use color::COLOR_PROPERTIES;
pub use properties::CANONICAL_PROPERTIES;

/// Canonical property specification in the compiler canon.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Property {
    pub name: &'static str,
    pub css: &'static str,
    pub class_prefix: &'static str,
    pub longhands: &'static [&'static str],
}

impl Property {
    pub const fn new(
        name: &'static str,
        css: &'static str,
        class_prefix: &'static str,
        longhands: &'static [&'static str],
    ) -> Self {
        Self {
            name,
            css,
            class_prefix,
            longhands,
        }
    }
}

/// Returns the Property record for a canonical property name, if known.
pub fn find_property(name: &str) -> Option<&'static Property> {
    CANONICAL_PROPERTIES
        .binary_search_by_key(&name, |p| p.name)
        .ok()
        .map(|idx| &CANONICAL_PROPERTIES[idx])
}

/// Returns true if the given property semantically accepts color values and design tokens.
pub fn is_color_prop(prop: &str) -> bool {
    let canonical = match crate::dialect::resolve_alias(prop) {
        Some(c) => c,
        None => prop,
    };
    COLOR_PROPERTIES.binary_search(&canonical).is_ok()
}

/// Returns the native shorthand longhands for a property, if it is a shorthand.
pub fn native_longhands_for_prop(name: &str) -> Option<&'static [&'static str]> {
    let canonical = match crate::dialect::resolve_alias(name) {
        Some(c) => c,
        None => name,
    };
    match find_property(canonical) {
        Some(p) if !p.longhands.is_empty() => Some(p.longhands),
        _ => None,
    }
}

/// Cascade rank derived from existing longhand slices: shorthands-of-shorthands,
/// then shorthands, then logical longhands (`Inline` / `Block` in the name), then
/// physical longhands. Lower sorts first so a longhand utility always wins.
pub fn property_cascade_rank(name: &str) -> u8 {
    match native_longhands_for_prop(name) {
        Some(hands) if has_nested_shorthand(hands) => 0,
        Some(_) => 1,
        None if is_logical_longhand(name) => 2,
        None => 3,
    }
}

fn has_nested_shorthand(hands: &[&str]) -> bool {
    hands
        .iter()
        .any(|hand| native_longhands_for_prop(hand).is_some())
}

fn is_logical_longhand(name: &str) -> bool {
    let canonical = match crate::dialect::resolve_alias(name) {
        Some(c) => c,
        None => name,
    };
    canonical.contains("Inline") || canonical.contains("Block")
}

/// Properties whose unitless numbers remain bare in CSS without gaining `px`.
pub const UNITLESS_PROPERTIES: &[&str] = &[
    "animationIterationCount",
    "aspectRatio",
    "borderImageOutset",
    "borderImageSlice",
    "borderImageWidth",
    "boxFlex",
    "boxFlexGroup",
    "boxOrdinalGroup",
    "columnCount",
    "columns",
    "fillOpacity",
    "flex",
    "flexGrow",
    "flexOrder",
    "flexPositive",
    "flexShrink",
    "floodOpacity",
    "fontWeight",
    "gridColumn",
    "gridColumnEnd",
    "gridColumnSpan",
    "gridColumnStart",
    "gridRow",
    "gridRowEnd",
    "gridRowSpan",
    "gridRowStart",
    "lineClamp",
    "lineHeight",
    "mozAnimationIterationCount",
    "mozBoxFlex",
    "mozBoxOrdinalGroup",
    "mozColumnCount",
    "mozColumns",
    "mozOpacity",
    "mozTabSize",
    "msFlex",
    "msFlexPositive",
    "msOrder",
    "opacity",
    "order",
    "orphans",
    "scale",
    "stopOpacity",
    "strokeDasharray",
    "strokeDashoffset",
    "strokeMiterlimit",
    "strokeOpacity",
    "tabSize",
    "webkitAnimationIterationCount",
    "webkitBorderImageSlice",
    "webkitBoxFlex",
    "webkitBoxFlexGroup",
    "webkitBoxOrdinalGroup",
    "webkitColumnCount",
    "webkitColumns",
    "webkitFlex",
    "webkitFlexGrow",
    "webkitFlexShrink",
    "webkitLineClamp",
    "webkitOrder",
    "widows",
    "zIndex",
    "zoom",
];

/// Returns true if a numeric value on this property should stay unitless without gaining `px`.
pub fn is_unitless_prop(prop: &str) -> bool {
    if prop.starts_with("--") {
        return true;
    }
    let canonical = match crate::dialect::resolve_alias(prop) {
        Some(c) => c,
        None => prop,
    };
    UNITLESS_PROPERTIES.binary_search(&canonical).is_ok()
}
