//! Dialect extensions whose `css` form no browser honors.
//!
//! Generated by `packages/reference-rs/modules/canon/generate/generate.ts`.
//! Computed at build from live @webref/css truth: EXTENSIONS rows with css
//! absent from webref, no longhands, and no platform row shadowing the name.
//! Resolve refuses these at the expansion fall-through (warn-and-skip) unless
//! a lowering arm above claims the prop; sorted for binary search.
// @generated

/// Extension names whose served `css` form is fictional per live webref.
pub const UNREALIZABLE_EXTENSIONS: &[&str] = &[
    "animationState",
    "backgroundConic",
    "backgroundGradient",
    "backgroundLinear",
    "backgroundRadial",
    "boxSize",
    "debug",
    "fontSmoothing",
    "gradientFrom",
    "gradientFromPosition",
    "gradientTo",
    "gradientToPosition",
    "gradientVia",
    "gradientViaPosition",
    "hideBelow",
    "hideFrom",
    "scrollSnapStrictness",
    "spaceX",
    "spaceY",
    "srOnly",
    "textGradient",
    "textShadowColor",
    "textStyle",
    "translateX",
    "translateY",
    "translateZ",
    "truncate",
];

/// Returns true if the prop is a dialect extension with no CSS realization.
pub fn is_unrealizable_extension(name: &str) -> bool {
    UNREALIZABLE_EXTENSIONS.binary_search(&name).is_ok()
}
