/**
 * Emits one TSX component per Material Symbols slug: a single component with
 * variant "outline" | "filled", backed by the configured material-symbols weight from
 * @material-symbols-svg/react/icons/<slug>.
 */

import { createRequire } from 'node:module'
import { mkdir, readdir, readFile, rm, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const sp = (...parts) => parts.filter((part) => part !== undefined && part !== '').join(' ')

const require = createRequire(import.meta.url)
const packageRoot = join(dirname(fileURLToPath(import.meta.url)), '..')
const genDir = join(packageRoot, 'src/generated')
const constantsPath = join(packageRoot, 'src/constants.ts')
const jsxNamesPath = join(packageRoot, 'src/jsx-names.ts')

const pkgJsonPath = require.resolve('@material-symbols-svg/react/package.json')
const iconsDir = join(dirname(pkgJsonPath), 'dist/icons')

const exportDeclRe = /export declare const (\w+):/g
const weightDeclRe = /MATERIAL_SYMBOLS_ICON_WEIGHT\s*=\s*(\d+)/

async function resolveConfiguredWeight() {
  const constantsSource = await readFile(constantsPath, 'utf8')
  const match = constantsSource.match(weightDeclRe)
  if (!match) {
    throw new Error(`Unable to read MATERIAL_SYMBOLS_ICON_WEIGHT from ${constantsPath}`)
  }
  return Number.parseInt(match[1], 10)
}

function parseExportedNames(dts) {
  const names = new Set()
  for (const match of dts.matchAll(exportDeclRe)) {
    names.add(match[1])
  }
  return names
}

function componentNameFromOutlineSymbol(outlineSymbol, outlineSuffix) {
  if (!outlineSymbol.endsWith(outlineSuffix)) {
    throw new Error(`Expected outline export *${outlineSuffix}, got ${outlineSymbol}`)
  }
  return `${outlineSymbol.slice(0, -outlineSuffix.length)}Icon`
}

function pickOutlineFill(names, outlineSuffix, fillSuffix) {
  const outline = [...names].find(
    (name) => name.endsWith(outlineSuffix) && !name.endsWith(fillSuffix)
  )
  if (!outline) return null
  const base = outline.slice(0, -outlineSuffix.length)
  const fillName = `${base}${fillSuffix}`
  const fill = names.has(fillName) ? fillName : outline
  return { outline, fill }
}

function emitIconFile(slug, outline, fill, componentName) {
  const mod = `@material-symbols-svg/react/icons/${slug}`
  const line1 = sp('import', '{', outline, ',', fill, '}', 'from', `'${mod}'`)
  const line2 = sp('import', '{', 'createIcon', '}', 'from', `'../createIcon'`)
  const line3 = sp(
    'export',
    'const',
    componentName,
    '=',
    '/*#__PURE__*/',
    'createIcon(',
    outline,
    ',',
    fill,
    ',',
    `'${componentName}'`,
    ')',
  )
  return [line1, line2, line3].join('\n')
}

function emitJsxNamesFile(componentNames) {
  return [
    '/**',
    ' * Generated by scripts/generate.mjs — do not edit.',
    ' * Canonical JSX element names for the generated icon components.',
    ' */',
    `export const ICON_JSX_NAMES = ${JSON.stringify(componentNames, null, 2)} as const`,
    '',
    'export type IconJsxName = (typeof ICON_JSX_NAMES)[number]',
    '',
  ].join('\n')
}

async function main() {
  const weight = await resolveConfiguredWeight()
  const outlineSuffix = `W${weight}`
  const fillSuffix = `FillW${weight}`
  const files = await readdir(iconsDir)
  const dtsFiles = files.filter((fileName) => fileName.endsWith('.d.ts')).sort((a, b) => a.localeCompare(b))

  await rm(genDir, { recursive: true, force: true })
  await mkdir(genDir, { recursive: true })

  const exportNames = new Map()

  for (const fileName of dtsFiles) {
    const slug = fileName.replace(/\.d\.ts$/, '')
    const dts = await readFile(join(iconsDir, fileName), 'utf8')
    const names = parseExportedNames(dts)
    const picked = pickOutlineFill(names, outlineSuffix, fillSuffix)
    if (!picked) continue

    const componentName = componentNameFromOutlineSymbol(picked.outline, outlineSuffix)
    if (exportNames.has(componentName)) {
      throw new Error(`Duplicate component name ${componentName}`)
    }
    exportNames.set(componentName, slug)

    const body = emitIconFile(slug, picked.outline, picked.fill, componentName)
    await writeFile(join(genDir, `${slug}.tsx`), `${body}\n`, 'utf8')
  }

  const barrel = [...exportNames.entries()]
    .sort((a, b) => a[0].localeCompare(b[0]))
    .map(([componentName, slug]) => sp('export', '{', componentName, '}', 'from', `'./${slug}'`))

  const barrelHeader = [
    '/**',
    ' * Generated by scripts/generate.mjs — do not edit.',
    ` * Weight ${weight} outline (*${outlineSuffix}) and filled (*${fillSuffix}).`,
    ' */',
    '',
  ]

  await writeFile(join(genDir, 'index.ts'), `${barrelHeader.join('\n')}${barrel.join('\n')}\n`, 'utf8')
  await writeFile(
    jsxNamesPath,
    emitJsxNamesFile([...exportNames.keys()].sort((a, b) => a.localeCompare(b))),
    'utf8'
  )

  console.error(`reference-icons: ${exportNames.size} icons`)
}

await main()