// Shared input and constants for the Neo generated-folder publishers.
// It takes nothing at runtime and emits the PublishInput shape plus the
// version stamp and banner every generated file carries.

import type {
  EvaluatedSystemSpec,
  NativeRuntimeArtifact,
  PortableFragment,
} from '@reference-ui/rust/contracts'
import type { JsxElementsArtifact } from '../jsx-elements.ts'

export const GENERATED_VERSION = '0.0.0-neo'

export const BASE_SYSTEM_HEADER = '/** Generated by @reference-ui/neo sync — do not edit manually */'

export interface PublishInput {
  outDir: string
  spec: EvaluatedSystemSpec
  portableFragment: string
  stylesheet: string
  portableStylesheet: string
  jsx: JsxElementsArtifact
  runtime?: NativeRuntimeArtifact
  fragments?: PortableFragment[]
}
