// Exact-string goldens for the generated system source builders.
// They take no input and assert every emitted declaration and entry byte.
// These pins name the culprit builder on drift; the end-to-end byte proof
// stays with the resync determinism case.

import { describe, expect, it } from 'vitest'
import {
  baseSystemInterfaceSource,
  baseSystemTypesSource,
  systemEntrySource,
  systemTypesSource,
} from './sources.ts'

const HEADER = '/** Generated by ref sync — do not edit manually */'

const INTERFACE_SOURCE = `export interface SystemStreams {
  name: string
  root?: string
  preamble: string
  reset?: string
  global?: string
  tokens?: string
  tokensPortable?: string
  recipes?: string
  utilities?: string
  package?: string
}
export interface BaseSystem {
  name: string
  fragment: string
  streams?: SystemStreams[]
  jsxElements?: string[]
}
`

const BASE_SYSTEM_TYPES = `${HEADER}
export interface SystemStreams {
  name: string
  root?: string
  preamble: string
  reset?: string
  global?: string
  tokens?: string
  tokensPortable?: string
  recipes?: string
  utilities?: string
  package?: string
}
export interface BaseSystem {
  name: string
  fragment: string
  streams?: SystemStreams[]
  jsxElements?: string[]
}
export declare const baseSystem: BaseSystem
`

const SYSTEM_ENTRY = `${HEADER}
export function defineConfig(config) {
  return config
}
function collect(key, fragment) {
  const bucket = globalThis[key]
  if (Array.isArray(bucket)) {
    bucket.push(fragment)
  }
}
export function tokens(config) {
  collect('__refTokensCollector', config)
}
export function keyframes(config) {
  collect('__refKeyframesCollector', config)
}
export function font(name, options) {
  collect('__refFontCollector', { name, ...options })
}
export function globalCss(config) {
  collect('__refGlobalCssCollector', config)
}
export function getRhythm(num, denom) {
  if (denom !== undefined) {
    return num === 1
      ? \`calc(var(--spacing-root) / \${denom})\`
      : \`calc(\${num} * var(--spacing-root) / \${denom})\`
  }
  if (num === 1) return 'var(--spacing-root)'
  return \`calc(\${num} * var(--spacing-root))\`
}
export { baseSystem } from './baseSystem.mjs'
`

const SYSTEM_TYPES = `${HEADER}
export interface SystemStreams {
  name: string
  root?: string
  preamble: string
  reset?: string
  global?: string
  tokens?: string
  tokensPortable?: string
  recipes?: string
  utilities?: string
  package?: string
}
export interface BaseSystem {
  name: string
  fragment: string
  streams?: SystemStreams[]
  jsxElements?: string[]
}

export interface ReferenceUIConfig {
  name: string
  include: string[]
  extends?: BaseSystem[]
  jsxElements?: string[]
  normalizeCss?: boolean
  debug?: boolean
}
export declare function defineConfig(config: ReferenceUIConfig): ReferenceUIConfig
export declare function tokens(config: Record<string, unknown>): void
export declare function keyframes(config: Record<string, unknown>): void
export declare function font(name: string, options: Record<string, unknown>): void
export declare function globalCss(config: Record<string, unknown>): void
export declare function getRhythm(n: number): string
export declare function getRhythm(num: number, denom: number): string
export declare const baseSystem: BaseSystem
`

describe('system source builders', () => {
  it('pins the portable interface source', () => {
    expect(baseSystemInterfaceSource()).toBe(INTERFACE_SOURCE)
  })

  it('pins the baseSystem declaration source', () => {
    expect(baseSystemTypesSource()).toBe(BASE_SYSTEM_TYPES)
  })

  it('pins the system entry source', () => {
    expect(systemEntrySource()).toBe(SYSTEM_ENTRY)
  })

  it('pins the system types source', () => {
    expect(systemTypesSource()).toBe(SYSTEM_TYPES)
  })
})
