/**
 * Generate font.ts from collected font definitions.
 * Outputs tokens, globalFontface, recipe, and pattern extension.
 * Uses line builder pattern: accumulates lines into an array, joins at end.
 */

import type { FontDefinition } from './extendFontFace'

/** Extract font family name from value like '"Inter", ui-sans-serif' for globalFontface key */
function extractFontFamilyKey(value: string): string {
  const match = value.match(/^["']([^"']+)["']/)
  if (match) {
    const name = match[1]
    return name.includes(' ') ? `"${name}"` : name
  }
  return value.split(',')[0]?.trim() ?? 'unknown'
}

/** Convert fontFace (single or array) to globalFontface format */
function buildGlobalFontface(
  defs: FontDefinition[]
): Record<string, Record<string, string> | Record<string, string>[]> {
  const result: Record<string, Record<string, string> | Record<string, string>[]> = {}
  for (const def of defs) {
    const familyKey = extractFontFamilyKey(def.value)
    const rules = Array.isArray(def.fontFace) ? def.fontFace : [def.fontFace]
    const faces = rules.map(rule => {
      const face: Record<string, string> = {
        src: rule.src,
        fontDisplay: rule.fontDisplay ?? 'swap',
      }
      if (rule.fontWeight) face.fontWeight = rule.fontWeight
      if (rule.fontStyle) face.fontStyle = rule.fontStyle
      if (rule.sizeAdjust) face.sizeAdjust = rule.sizeAdjust
      if (rule.descentOverride) face.descentOverride = rule.descentOverride
      return face
    })
    result[familyKey] = faces.length === 1 ? faces[0]! : faces
  }
  return result
}

/** Build transform body lines: FONT_PRESETS and WEIGHT_TOKENS objects, inlined for Panda codegen */
function buildTransformLines(defs: FontDefinition[]): string[] {
  const fontPresetLines = defs.map(d => {
    const css = d.css ?? {}
    const normalWeight = d.weights.normal ?? '400'
    const fontWeight = css.fontWeight ?? normalWeight
    const parts = [`fontFamily: '${d.name}'`, `fontWeight: '${fontWeight}'`]
    if (css.letterSpacing) parts.push(`letterSpacing: '${css.letterSpacing}'`)
    return `      ${d.name}: { ${parts.join(', ')} },`
  })
  const weightTokenLines = defs.flatMap(d =>
    Object.entries(d.weights)
      .filter(([, v]) => v)
      .map(([name, value]) => `      '${d.name}.${name}': '${value}',`)
  )

  return [
    '    const { font, weight } = props',
    '',
    '    const FONT_PRESETS: Record<string, Record<string, string>> = {',
    ...fontPresetLines,
    '    }',
    '',
    '    const WEIGHT_TOKENS: Record<string, string> = {',
    ...weightTokenLines,
    '    }',
    '',
    '    const result: Record<string, any> = {}',
    '',
    '    if (font && FONT_PRESETS[font]) {',
    '      Object.assign(result, FONT_PRESETS[font])',
    '    }',
    '',
    '    if (weight && WEIGHT_TOKENS[weight]) {',
    '      result.fontWeight = WEIGHT_TOKENS[weight]',
    '    }',
    '',
    '    return result',
  ]
}

export function generateFontSystemContent(defs: FontDefinition[]): string {
  if (defs.length === 0) {
    return ['/** Generated by createFontSystem - no fonts defined */'].join('\n') + '\n'
  }

  const fonts: Record<string, { value: string }> = {}
  const fontWeights: Record<string, { value: string }> = {}
  for (const d of defs) {
    fonts[d.name] = { value: d.value }
    for (const [name, value] of Object.entries(d.weights)) {
      if (value) fontWeights[`${d.name}.${name}`] = { value: value }
    }
  }

  const fontEntries = Object.entries(fonts).map(
    ([k, v]) => `    ${k}: { value: ${JSON.stringify(v.value)} },`
  )
  const fontWeightEntries = Object.entries(fontWeights).map(
    ([k, v]) => `    '${k}': { value: '${v.value}' },`
  )
  const globalFontfaceObj = buildGlobalFontface(defs)
  const globalFontfaceEntries = Object.entries(globalFontfaceObj).flatMap(
    ([key, val]) => {
      const formattedKey = key.includes(' ') ? `'${key}'` : key
      if (Array.isArray(val)) {
        const faceLines = val.flatMap(face => [
          '    {',
          ...Object.entries(face).map(([k, v]) => `      ${k}: '${v}',`),
          '    },',
        ])
        return [`  ${formattedKey}: [`, ...faceLines, '  ],']
      }
      return [
        `  ${formattedKey}: {`,
        ...Object.entries(val).map(([k, v]) => `    ${k}: '${v}',`),
        '  },',
      ]
    }
  )
  const recipeVariantLines = defs.flatMap(d => {
    const css = d.css ?? {}
    const normalWeight = d.weights.normal ?? '400'
    const parts = [`fontFamily: '${d.name}'`]
    if (css.letterSpacing) parts.push(`letterSpacing: '${css.letterSpacing}'`)
    parts.push(`fontWeight: '${css.fontWeight ?? normalWeight}'`)
    return [`        ${d.name}: {`, ...parts.map(p => `          ${p},`), '        },']
  })

  const lines = [
    '/** Generated by createFontSystem - do not edit manually */',
    '',
    "import { extendTokens, extendGlobalFontface, extendRecipe, extendPattern } from '../api'",
    '',
    'extendTokens({',
    '  fonts: {',
    ...fontEntries,
    '  },',
    '  fontWeights: {',
    ...fontWeightEntries,
    '  },',
    '})',
    '',
    'extendGlobalFontface({',
    ...globalFontfaceEntries,
    '})',
    '',
    'extendRecipe({',
    '  fontStyle: {',
    "    className: 'r_font',",
    '    variants: {',
    '      font: {',
    ...recipeVariantLines,
    '      },',
    '    },',
    '  },',
    '})',
    '',
    'extendPattern({',
    '  properties: {',
    "    font: { type: 'string' as const },",
    "    weight: { type: 'string' as const },",
    '  },',
    '  transform(props: Record<string, any>) {',
    ...buildTransformLines(defs),
    '  },',
    '})',
  ]

  return lines.join('\n') + '\n'
}
