// Native generator for the Neo react entry plus its types.
// It takes the system name plus compiled style prop names and emits source.
// String building over the tag set replaces core's Liquid templates; the
// style prop union mirrors the typegen shape until typegen wires in.

import { TAGS, toJsxName } from '../tags.ts'

export interface ReactEntryInput {
  systemName: string
  stylePropNames: readonly string[]
  factoryPath: string
  splitPath: string
  contextPath: string
}

export interface ReactTypesInput {
  stylePropNames: readonly string[]
}

/**
 * Generate the react entry source for one system. Bakes the layer name and
 * style prop list and emits one factory-built component per tag. The css()
 * binding is caller-provided: the publisher prepends a runtime header that
 * imports the style runtime plus this system's runtime-data, registers both,
 * and re-exports css/recipe — styled stays data-only (D4).
 */
export function generateReactEntrySource(input: ReactEntryInput): string {
  const lines = [
    '/** Generated by @reference-ui/neo sync — do not edit manually */',
    `import { Fragment, createElement } from 'react'`,
    `import { createRoot } from 'react-dom/client'`,
    `import { createPrimitive } from ${JSON.stringify(input.factoryPath)}`,
    `import { createPropSplitter } from ${JSON.stringify(input.splitPath)}`,
    '',
    `const splitPrimitiveProps = createPropSplitter(${JSON.stringify([...input.stylePropNames])})`,
    `const layerName = ${JSON.stringify(input.systemName)}`,
    '',
  ]
  for (const tag of TAGS) {
    const name = toJsxName(tag)
    lines.push(
      `export const ${name} = createPrimitive({ tag: ${JSON.stringify(tag)}, displayName: ${JSON.stringify(name)}, layerName, split: splitPrimitiveProps, css })`
    )
  }
  lines.push(
    '',
    'export { Fragment, createElement, createRoot }',
    `export { ColorModeContext, DocumentContext, LayerScopeContext, useColorMode } from ${JSON.stringify(input.contextPath)}`,
    ''
  )
  return lines.join('\n')
}

function stylePropUnion(stylePropNames: readonly string[]): string {
  const names = [...stylePropNames].sort()
  if (names.length === 0) return 'never'
  return names.map(name => JSON.stringify(name)).join(' | ')
}

function primitiveTagUnion(): string {
  return TAGS.map(tag => JSON.stringify(tag)).join(' | ')
}

/**
 * Generate the react entry types for one system. Every tag gets a props
 * type (native props minus styling keys, plus the style prop union) and
 * a ref-as-prop component signature; the file stands alone on react types.
 */
export function generateReactTypesSource(input: ReactTypesInput): string {
  const union = stylePropUnion(input.stylePropNames)
  const lines = [
    '/** Generated by @reference-ui/neo sync — do not edit manually */',
    `import type * as React from 'react'`,
    '',
    '/** Compiled style prop names: the styling keys every primitive accepts. */',
    `export type StylePropName = ${union}`,
    'export type StyleProps = { [K in StylePropName]?: unknown }',
    'export type PrimitiveCssProp = Record<string, unknown>',
    '',
    '/** Every platform tag the generated primitives cover. */',
    `export type PrimitiveTag = ${primitiveTagUnion()}`,
    '',
    '/** React types two tags with the generic HTMLElement instead of the real host. */',
    'interface PrimitiveElementOverrides {',
    '  caption: HTMLTableCaptionElement',
    '  menu: HTMLMenuElement',
    '}',
    '/** Host element for one tag, with the caption/menu overrides applied. */',
    'export type PrimitiveElement<T extends PrimitiveTag> = T extends keyof PrimitiveElementOverrides ? PrimitiveElementOverrides[T] : React.ComponentRef<T>',
    '',
  ]
  for (const tag of TAGS) {
    const name = toJsxName(tag)
    lines.push(
      `export type ${name}Props = Omit<React.ComponentPropsWithoutRef<${JSON.stringify(tag)}>, StylePropName | 'css' | 'colorMode' | 'variant'> & StyleProps & { css?: PrimitiveCssProp; colorMode?: unknown; variant?: unknown }`,
      `export declare const ${name}: (props: ${name}Props & { ref?: React.Ref<React.ComponentRef<${JSON.stringify(tag)}>> }) => React.ReactNode`,
      ''
    )
  }
  lines.push(
    'export declare const LayerScopeContext: React.Context<boolean>',
    'export declare const ColorModeContext: React.Context<string | undefined>',
    'export declare const DocumentContext: React.Context<Document | null>',
    'export declare function useColorMode(): string | undefined',
    `export { Fragment } from 'react'`,
    `export { createElement } from 'react'`,
    `export { createRoot } from 'react-dom/client'`,
    ''
  )
  return lines.join('\n')
}
