// Native generator for the Neo react entry plus its types.
// It takes the system name plus compiled style prop names and emits source.
// The entry binds the live RS primitives roster per system; the tag list
// only names the destructure. The style prop union mirrors the typegen
// shape until typegen wires in.

import { TAGS, toJsxName } from '../tags.ts'

export interface ReactEntryInput {
  systemName: string
  stylePropNames: readonly string[]
  primitivesPath: string
}

export interface ReactTypesInput {
  stylePropNames: readonly string[]
}

/**
 * Generate the react entry source for one system. Binds the live RS
 * primitives roster to this system: one configurePrimitives call carries
 * the layer name plus the compiled style prop list, and destructures the
 * 101 bound components. The primitives path points at the tracked RS
 * generated source, never the gitignored dist build. The css() binding is
 * caller-provided: the publisher prepends a runtime header that imports
 * the style runtime plus this system's runtime-data, registers both, and
 * re-exports css/recipe — styled stays data-only (D4). No react-dom
 * re-export: consumers bring their own copy, so the entry stays react-only
 * and packages built on it import clean without react-dom (core contract).
 */
export function generateReactEntrySource(input: ReactEntryInput): string {
  const bound = TAGS.map(toJsxName)
  const lines = [
    '/** Generated by ref sync — do not edit manually */',
    `import { configurePrimitives, ColorModeContext, DocumentContext, Fragment, LayerScopeContext, createElement, useColorMode } from ${JSON.stringify(input.primitivesPath)}`,
    '',
    `export const { ${bound.join(', ')} } = configurePrimitives({ layerName: ${JSON.stringify(input.systemName)}, stylePropNames: ${JSON.stringify([...input.stylePropNames])}, css })`,
    'export { ColorModeContext, DocumentContext, Fragment, LayerScopeContext, createElement, useColorMode }',
    '',
  ]
  return lines.join('\n')
}

function stylePropUnion(stylePropNames: readonly string[]): string {
  const names = [...stylePropNames].sort()
  if (names.length === 0) return 'never'
  return names.map(name => JSON.stringify(name)).join(' | ')
}

function primitiveTagUnion(): string {
  return TAGS.map(tag => JSON.stringify(tag)).join(' | ')
}

/**
 * Generate the react entry types for one system. Every tag gets a props
 * type (native props minus styling keys, plus the style prop union) and
 * a ref-as-prop component signature; the file stands alone on react types.
 */
export function generateReactTypesSource(input: ReactTypesInput): string {
  const union = stylePropUnion(input.stylePropNames)
  const lines = [
    '/** Generated by ref sync — do not edit manually */',
    `import type * as React from 'react'`,
    '',
    '/** Compiled style prop names: the styling keys every primitive accepts. */',
    `export type StylePropName = ${union}`,
    'export type StyleProps = { [K in StylePropName]?: unknown }',
    'export type PrimitiveCssProp = Record<string, unknown> | Array<Record<string, unknown>>',
    '',
    '/** Every platform tag the generated primitives cover. */',
    `export type PrimitiveTag = ${primitiveTagUnion()}`,
    '',
    '/** React types two tags with the generic HTMLElement instead of the real host. */',
    'interface PrimitiveElementOverrides {',
    '  caption: HTMLTableCaptionElement',
    '  menu: HTMLMenuElement',
    '}',
    '/** Host element for one tag, with the caption/menu overrides applied. */',
    'export type PrimitiveElement<T extends PrimitiveTag> = T extends keyof PrimitiveElementOverrides ? PrimitiveElementOverrides[T] : React.ComponentRef<T>',
    '',
  ]
  for (const tag of TAGS) {
    const name = toJsxName(tag)
    lines.push(
      `export type ${name}Props = Omit<React.ComponentPropsWithoutRef<${JSON.stringify(tag)}>, StylePropName | 'css' | 'colorMode' | 'variant'> & StyleProps & { css?: PrimitiveCssProp; colorMode?: unknown; variant?: unknown }`,
      `export declare const ${name}: (props: ${name}Props & { ref?: React.Ref<React.ComponentRef<${JSON.stringify(tag)}>> }) => React.ReactNode`,
      ''
    )
  }
  lines.push(
    'export declare const LayerScopeContext: React.Context<boolean>',
    'export declare const ColorModeContext: React.Context<string | undefined>',
    'export declare const DocumentContext: React.Context<Document | null>',
    'export declare function useColorMode(): string | undefined',
    `export { Fragment } from 'react'`,
    `export { createElement } from 'react'`,
    ''
  )
  return lines.join('\n')
}
