import { existsSync, mkdirSync, mkdtempSync, readFileSync, renameSync, rmSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { dirname, join } from 'node:path'
import { pathToFileURL } from 'node:url'
import { getOutDirPath } from '../../lib/paths'
import { createFontCollector, type FontDefinition } from '../api/font'

export interface FontTypeRegistry {
  [fontName: string]: string[]
}

const FONT_REGISTRY_FILENAME = 'font-registry.json'
const EMITTED_FONT_REGISTRY_INTERFACE = 'FontRegistry'
const EMITTED_FONT_PROPS_ALIAS = 'FontProps'

function writeFileAtomic(path: string, content: string): void {
  const tempPath = `${path}.tmp-${process.pid}-${Date.now()}`
  writeFileSync(tempPath, content, 'utf-8')
  renameSync(tempPath, path)
}

export function buildFontTypeRegistry(fonts: FontDefinition[]): FontTypeRegistry {
  const registry = new Map<string, Set<string>>()

  for (const font of fonts) {
    const weightNames = registry.get(font.name) ?? new Set<string>()

    for (const weightName of Object.keys(font.weights)) {
      weightNames.add(weightName)
    }

    registry.set(font.name, weightNames)
  }

  return Object.fromEntries(
    [...registry.entries()].map(([fontName, weightNames]) => [fontName, [...weightNames]])
  )
}

export function renderFontRegistryInterface(registry: FontTypeRegistry): string {
  const lines = [
    `interface ${EMITTED_FONT_REGISTRY_INTERFACE} {`,
  ]

  for (const [fontName, weightNames] of Object.entries(registry)) {
    lines.push(`    ${JSON.stringify(fontName)}: {`)

    for (const weightName of weightNames) {
      lines.push(`        ${JSON.stringify(weightName)}: true`)
    }

    lines.push('    }')
  }

  lines.push('}')

  return lines.join('\n')
}

async function collectFontsFromFragment(fragment: string): Promise<FontDefinition[]> {
  const tempDir = mkdtempSync(join(tmpdir(), 'ref-ui-font-types-'))
  const tempFile = join(tempDir, 'font-fragments.mjs')
  const fontCollector = createFontCollector()

  fontCollector.init()
  writeFileSync(tempFile, [fontCollector.toRuntimeFunction(), `;${fragment}`].join('\n'), 'utf-8')

  try {
    await import(`${pathToFileURL(tempFile).href}?t=${Date.now()}`)
    return fontCollector.getFragments()
  } finally {
    fontCollector.cleanup()
    rmSync(tempDir, { recursive: true, force: true })
  }
}

export function renderGeneratedFontRegistryFile(registry: FontTypeRegistry): string {
  return [
    '/** Generated by reference-core — do not edit manually. */',
    renderFontRegistryInterface(registry),
    '',
  ].join('\n')
}

const EMITTED_FONT_PROPS_SHAPE = `{
    font?: ConditionalValue<string>;
    weight?: ConditionalValue<string>;
}`

function getSystemTypesDir(cwd: string): string {
  return join(getOutDirPath(cwd), 'system')
}

function getSystemFontRegistryPath(cwd: string): string {
  return join(getSystemTypesDir(cwd), FONT_REGISTRY_FILENAME)
}

function getSystemGeneratedTypesPath(cwd: string): string {
  return join(getSystemTypesDir(cwd), 'types.generated.d.mts')
}

export async function writeGeneratedSystemFontTypes(
  cwd: string,
  fragment: string
): Promise<FontTypeRegistry> {
  const fonts = await collectFontsFromFragment(fragment)
  const registry = buildFontTypeRegistry(fonts)
  const systemTypesDir = getSystemTypesDir(cwd)

  mkdirSync(systemTypesDir, { recursive: true })
  writeFileSync(getSystemFontRegistryPath(cwd), JSON.stringify(registry, null, 2), 'utf-8')
  writeFileSync(getSystemGeneratedTypesPath(cwd), renderGeneratedFontRegistryFile(registry), 'utf-8')

  return registry
}

export function readGeneratedFontRegistry(cwd: string): FontTypeRegistry {
  const registryPath = getSystemFontRegistryPath(cwd)

  if (!existsSync(registryPath)) {
    return {}
  }

  return JSON.parse(readFileSync(registryPath, 'utf-8')) as FontTypeRegistry
}

function writeFontRegistryIntoTypes(typesPath: string, registry: FontTypeRegistry): void {
  let content = readFileSync(typesPath, 'utf-8')
    .replace("import './types.generated.d.mts';\n", '')
    .replace(
      /interface (?:ReferenceFontRegistry|FontRegistry) \{\n\}/,
      renderFontRegistryInterface(registry)
    )

  if (Object.keys(registry).length > 0) {
    content = content
      .replace(
        /type (?:ReferenceFontProps|FontProps) = \[(?:ReferenceFontName|FontName)\] extends \[never\] \? (?:ReferenceFallbackFontProps|FallbackFontProps) : (?:ReferenceScopedFontProps|ScopedFontProps);/,
        `type ${EMITTED_FONT_PROPS_ALIAS} = ScopedFontProps;`
      )
      .split(EMITTED_FONT_PROPS_SHAPE)
      .join(EMITTED_FONT_PROPS_ALIAS)
  }

  writeFileAtomic(typesPath, content)
}

async function writeGeneratedPackageTypes(
  cwd: string,
  typesPath: string
): Promise<void> {
  if (!existsSync(typesPath)) {
    return
  }

  const registry = readGeneratedFontRegistry(cwd)
  const generatedTypesPath = join(dirname(typesPath), 'types.generated.d.mts')

  writeFileAtomic(generatedTypesPath, renderGeneratedFontRegistryFile(registry))
  writeFontRegistryIntoTypes(typesPath, registry)
}

export async function writeGeneratedSystemTypes(cwd: string, systemTypesPath: string): Promise<void> {
  await writeGeneratedPackageTypes(cwd, systemTypesPath)
}

export async function writeGeneratedReactTypes(cwd: string, reactTypesPath: string): Promise<void> {
  await writeGeneratedPackageTypes(cwd, reactTypesPath)
}
