export const staticCss = {
  css: [
    {
      properties: {
        color: ['*'],
        background: ['*'],
        backgroundColor: ['*'],
        borderColor: ['*'],
        borderTopColor: ['*'],
        borderBottomColor: ['*'],
        borderLeftColor: ['*'],
        borderRightColor: ['*'],
        outlineColor: ['*'],
        fill: ['*'],
        stroke: ['*'],
        padding: ['*'],
        paddingTop: ['*'],
        paddingBottom: ['*'],
        paddingLeft: ['*'],
        paddingRight: ['*'],
        paddingInline: ['*'],
        paddingBlock: ['*'],
        margin: ['*'],
        marginTop: ['*'],
        marginBottom: ['*'],
        marginLeft: ['*'],
        marginRight: ['*'],
        marginInline: ['*'],
        marginBlock: ['*'],
        gap: ['*'],
        width: ['*'],
        height: ['*'],
        size: ['*'],
        borderRadius: ['*'],
      },
    },
  ],
}
