/**
 * Tests for box pattern generation and integration.
 * 
 * Verifies that:
 * 1. Box pattern was generated during build
 * 2. Pattern extensions are collected correctly
 * 3. Generated box.ts has correct structure
 */

import { describe, it, expect } from 'vitest'
import { existsSync, readFileSync } from 'node:fs'
import { join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { dirname } from 'node:path'

const __dirname = dirname(fileURLToPath(import.meta.url))
const cliRoot = join(__dirname, '..', '..', '..', 'reference-cli')
const boxPatternPath = join(cliRoot, 'src/system/internal/box.mjs')

describe('Box pattern generation', () => {
  it('generates box.mjs file during build', () => {
    expect(existsSync(boxPatternPath)).toBe(true)
  })

  it('includes all pattern properties', () => {
    if (!existsSync(boxPatternPath)) {
      console.warn('box.ts not found - run prebuild first')
      return
    }

    const content = readFileSync(boxPatternPath, 'utf-8')
    
    // Check for all expected properties
    expect(content).toContain('container:')
    expect(content).toContain('font:')
    expect(content).toContain('weight:')
    expect(content).toContain('r:')
    
    // Check blocklist
    expect(content).toContain('blocklist:')
    expect(content).toContain('"container"')
    expect(content).toContain('"font"')
    expect(content).toContain('"weight"')
    expect(content).toContain('"r"')
  })

  it('includes transform functions for each extension', () => {
    if (!existsSync(boxPatternPath)) return

    const content = readFileSync(boxPatternPath, 'utf-8')
    
    // Check for transform IIFEs (JavaScript, not TypeScript)
    expect(content).toContain('const _r0 = (function(props) {')
    expect(content).toContain('const _r1 = (function(props) {')
    expect(content).toContain('const _r2 = (function(props) {')
    
    // Check for transform logic
    expect(content).toContain('containerType')
    expect(content).toContain('FONT_PRESETS')
    expect(content).toContain('WEIGHT_TOKENS')
    expect(content).toContain('@container')
  })

  it('combines all transforms with Object.assign', () => {
    if (!existsSync(boxPatternPath)) return

    const content = readFileSync(boxPatternPath, 'utf-8')
    
    // Check final transform return
    expect(content).toMatch(/return Object\.assign\({}, _r\d+, _r\d+, _r\d+, rest\)/)
  })

  it('uses extendPandaConfig API', () => {
    if (!existsSync(boxPatternPath)) return

    const content = readFileSync(boxPatternPath, 'utf-8')
    
    expect(content).toContain("import { extendPandaConfig } from '../api/extendPandaConfig.js'")
    expect(content).toContain('extendPandaConfig({')
    expect(content).toContain('patterns: {')
    expect(content).toContain('extend: {')
    expect(content).toContain('box: {')
  })

  it('includes generation comment', () => {
    if (!existsSync(boxPatternPath)) return

    const content = readFileSync(boxPatternPath, 'utf-8')
    
    expect(content).toMatch(/Generated by build\/boxPattern\.ts/)
    expect(content).toMatch(/do not edit manually/)
  })
})

describe('Pattern prop modules', () => {
  const propsDir = join(cliRoot, 'src/system/internal/props')

  it('has container prop module', () => {
    const containerPath = join(propsDir, 'container.ts')
    expect(existsSync(containerPath)).toBe(true)
    
    const content = readFileSync(containerPath, 'utf-8')
    expect(content).toContain('extendPattern')
    expect(content).toContain('containerType')
  })

  it('has font prop module', () => {
    const fontPath = join(propsDir, 'font.ts')
    expect(existsSync(fontPath)).toBe(true)
    
    const content = readFileSync(fontPath, 'utf-8')
    expect(content).toContain('extendPattern')
    expect(content).toContain('FONT_PRESETS')
    expect(content).toContain('WEIGHT_TOKENS')
  })

  it('has responsive prop module', () => {
    const rPath = join(propsDir, 'r.ts')
    expect(existsSync(rPath)).toBe(true)
    
    const content = readFileSync(rPath, 'utf-8')
    expect(content).toContain('extendPattern')
    expect(content).toContain('@container')
  })
})
