/**
 * Tests for box pattern generation and integration.
 * 
 * Verifies that:
 * 1. Box pattern was generated during build
 * 2. Pattern extensions are collected correctly
 * 3. Generated box.ts has correct structure
 */

import { describe, it, expect } from 'vitest'
import { existsSync, readFileSync } from 'node:fs'
import { join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { dirname } from 'node:path'

const __dirname = dirname(fileURLToPath(import.meta.url))
const cliRoot = join(__dirname, '..', '..', '..', 'reference-cli')
/** Pattern fragment lives under styled/fragments/internal (styled mirrors outDir). */
const patternsFragmentPath = join(cliRoot, 'src/system/styled/fragments/internal/patterns.mjs')

describe('Box pattern generation', () => {
  it('generates patterns.mjs fragment during build', () => {
    expect(existsSync(patternsFragmentPath)).toBe(true)
  })

  it('includes all pattern properties', () => {
    if (!existsSync(patternsFragmentPath)) {
      console.warn('patterns.mjs not found - run prebuild first')
      return
    }

    const content = readFileSync(patternsFragmentPath, 'utf-8')
    
    // Check for expected properties (font is NOT here - it's runtime-generated)
    expect(content).toContain('container:')
    expect(content).toContain('r:')
    
    // Check blocklist
    expect(content).toContain('blocklist:')
    expect(content).toContain('"container"')
    expect(content).toContain('"r"')
    
    // Font should NOT be in the box pattern - it's generated at runtime
    expect(content).not.toContain('"font"')
    expect(content).not.toContain('"weight"')
  })

  it('includes transform functions for each extension', () => {
    if (!existsSync(patternsFragmentPath)) return

    const content = readFileSync(patternsFragmentPath, 'utf-8')
    
    // Check for transform IIFEs (JavaScript, not TypeScript)
    // Should only have 2 extensions now: container and r
    expect(content).toContain('const _r0 = (function(props) {')
    expect(content).toContain('const _r1 = (function(props) {')
    
    // Check for transform logic
    expect(content).toContain('containerType')
    expect(content).toContain('@container')
    
    // Font-related transforms should NOT be in box pattern
    expect(content).not.toContain('FONT_PRESETS')
    expect(content).not.toContain('WEIGHT_TOKENS')
  })

  it('combines all transforms with Object.assign', () => {
    if (!existsSync(patternsFragmentPath)) return

    const content = readFileSync(patternsFragmentPath, 'utf-8')
    
    // Check final transform return (only 2 extensions now)
    expect(content).toMatch(/return Object\.assign\({}, _r\d+, _r\d+, rest\)/)
  })

  it('pushes to panda config collector', () => {
    if (!existsSync(patternsFragmentPath)) return

    const content = readFileSync(patternsFragmentPath, 'utf-8')
    
    expect(content).toContain("__refPandaConfigCollector")
    expect(content).toContain('.push(')
    expect(content).toContain('patterns: {')
    expect(content).toContain('extend: {')
    expect(content).toContain('box: {')
  })

  it('includes generation comment', () => {
    if (!existsSync(patternsFragmentPath)) return

    const content = readFileSync(patternsFragmentPath, 'utf-8')
    
    expect(content).toMatch(/Generated by build\/boxPattern\.ts/)
    expect(content).toMatch(/do not edit manually/)
  })
})

describe('Pattern extension modules', () => {
  it('has container extension module', () => {
    const containerPath = join(cliRoot, 'src/system/internal/container/container.ts')
    expect(existsSync(containerPath)).toBe(true)
    
    const content = readFileSync(containerPath, 'utf-8')
    expect(content).toContain('extendPattern')
    expect(content).toContain('containerType')
  })

  it('has font extension directory (runtime generation)', () => {
    const fontDir = join(cliRoot, 'src/system/internal/font')
    expect(existsSync(fontDir)).toBe(true)
    
    // Font system uses runtime generation, not static pattern file
    const readmePath = join(fontDir, 'README.md')
    expect(existsSync(readmePath)).toBe(true)
  })

  it('has responsive extension module', () => {
    const rPath = join(cliRoot, 'src/system/internal/r/r.ts')
    expect(existsSync(rPath)).toBe(true)
    
    const content = readFileSync(rPath, 'utf-8')
    expect(content).toContain('extendPattern')
    expect(content).toContain('@container')
  })
})
