//! Reference UI StyleProps dialect aliases and custom props.
//!
//! Generated by `packages/reference-rs/system/canon/generate.ts`.
//! Maps concise authoring shorthand aliases to canonical CSS properties and defines Reference-only props.
// @generated

/// StyleProps alias mapping a shorthand alias to its canonical property name.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Alias {
    pub alias: &'static str,
    pub canonical: &'static str,
}

impl Alias {
    pub const fn new(alias: &'static str, canonical: &'static str) -> Self {
        Self { alias, canonical }
    }
}

/// Sorted table of StyleProps shorthand aliases.
pub const ALIASES: &[Alias] = &[
    Alias::new("b", "border"), Alias::new("bd", "border"), Alias::new("bd-b", "borderBottom"),
    Alias::new("bd-l", "borderLeft"), Alias::new("bd-r", "borderRight"), Alias::new("bd-t", "borderTop"),
    Alias::new("bg", "background"), Alias::new("bg-grad", "backgroundGradient"), Alias::new("bgAttachment", "backgroundAttachment"),
    Alias::new("bgBlendMode", "backgroundBlendMode"), Alias::new("bgClip", "backgroundClip"), Alias::new("bgColor", "backgroundColor"),
    Alias::new("bgConic", "backgroundConic"), Alias::new("bgGradient", "backgroundGradient"), Alias::new("bgImage", "backgroundImage"),
    Alias::new("bgLinear", "backgroundLinear"), Alias::new("bgOrigin", "backgroundOrigin"), Alias::new("bgPosition", "backgroundPosition"),
    Alias::new("bgPositionX", "backgroundPositionX"), Alias::new("bgPositionY", "backgroundPositionY"), Alias::new("bgRadial", "backgroundRadial"),
    Alias::new("bgRepeat", "backgroundRepeat"), Alias::new("bgSize", "backgroundSize"), Alias::new("borderB", "borderBottom"),
    Alias::new("borderBlock", "borderBlock"), Alias::new("borderC", "borderColor"), Alias::new("borderEnd", "borderInlineEnd"),
    Alias::new("borderEndC", "borderInlineEndColor"), Alias::new("borderEndWidth", "borderInlineEndWidth"), Alias::new("borderInline", "borderInline"),
    Alias::new("borderL", "borderLeft"), Alias::new("borderR", "borderRight"), Alias::new("borderStart", "borderInlineStart"),
    Alias::new("borderStartC", "borderInlineStartColor"), Alias::new("borderStartWidth", "borderInlineStartWidth"), Alias::new("borderT", "borderTop"),
    Alias::new("borderX", "borderInline"), Alias::new("borderXC", "borderInlineColor"), Alias::new("borderXWidth", "borderInlineWidth"),
    Alias::new("borderY", "borderBlock"), Alias::new("borderYC", "borderBlockColor"), Alias::new("borderYWidth", "borderBlockWidth"),
    Alias::new("boxSize", "boxSize"), Alias::new("c", "color"), Alias::new("col", "gridColumn"),
    Alias::new("end", "insetInlineEnd"), Alias::new("flexDir", "flexDirection"), Alias::new("from", "gradientFrom"),
    Alias::new("grow", "flexGrow"), Alias::new("h", "height"), Alias::new("insetEnd", "insetInlineEnd"),
    Alias::new("insetStart", "insetInlineStart"), Alias::new("insetX", "insetInline"), Alias::new("insetY", "insetBlock"),
    Alias::new("leading", "lineHeight"), Alias::new("m", "margin"), Alias::new("marginEnd", "marginInlineEnd"),
    Alias::new("marginStart", "marginInlineStart"), Alias::new("marginX", "marginInline"), Alias::new("marginY", "marginBlock"),
    Alias::new("maxH", "maxHeight"), Alias::new("maxW", "maxWidth"), Alias::new("mb", "marginBottom"),
    Alias::new("me", "marginInlineEnd"), Alias::new("minH", "minHeight"), Alias::new("minW", "minWidth"),
    Alias::new("ml", "marginLeft"), Alias::new("mr", "marginRight"), Alias::new("ms", "marginInlineStart"),
    Alias::new("mt", "marginTop"), Alias::new("mx", "marginInline"), Alias::new("my", "marginBlock"),
    Alias::new("p", "padding"), Alias::new("paddingEnd", "paddingInlineEnd"), Alias::new("paddingStart", "paddingInlineStart"),
    Alias::new("paddingX", "paddingInline"), Alias::new("paddingY", "paddingBlock"), Alias::new("pb", "paddingBottom"),
    Alias::new("pe", "paddingInlineEnd"), Alias::new("pl", "paddingLeft"), Alias::new("pos", "position"),
    Alias::new("pr", "paddingRight"), Alias::new("ps", "paddingInlineStart"), Alias::new("pt", "paddingTop"),
    Alias::new("px", "paddingInline"), Alias::new("py", "paddingBlock"), Alias::new("ring", "outline"),
    Alias::new("ringColor", "outlineColor"), Alias::new("ringOffset", "outlineOffset"), Alias::new("ringWidth", "outlineWidth"),
    Alias::new("rounded", "borderRadius"), Alias::new("roundedBottom", "borderBottomRadius"), Alias::new("roundedBottomLeft", "borderBottomLeftRadius"),
    Alias::new("roundedBottomRight", "borderBottomRightRadius"), Alias::new("roundedEnd", "borderEndRadius"), Alias::new("roundedEndEnd", "borderEndEndRadius"),
    Alias::new("roundedEndStart", "borderEndStartRadius"), Alias::new("roundedLeft", "borderLeftRadius"), Alias::new("roundedRight", "borderRightRadius"),
    Alias::new("roundedStart", "borderStartRadius"), Alias::new("roundedStartEnd", "borderStartEndRadius"), Alias::new("roundedStartStart", "borderStartStartRadius"),
    Alias::new("roundedTop", "borderTopRadius"), Alias::new("roundedTopLeft", "borderTopLeftRadius"), Alias::new("roundedTopRight", "borderTopRightRadius"),
    Alias::new("row", "gridRow"), Alias::new("scrollMarginX", "scrollMarginInline"), Alias::new("scrollMarginY", "scrollMarginBlock"),
    Alias::new("scrollPaddingX", "scrollPaddingInline"), Alias::new("scrollPaddingY", "scrollPaddingBlock"), Alias::new("shadow", "boxShadow"),
    Alias::new("shadowColor", "boxShadowColor"), Alias::new("shrink", "flexShrink"), Alias::new("start", "insetInlineStart"),
    Alias::new("text-grad", "textGradient"), Alias::new("textShadowColor", "textShadowColor"), Alias::new("to", "gradientTo"),
    Alias::new("tracking", "letterSpacing"), Alias::new("via", "gradientVia"), Alias::new("w", "width"),
    Alias::new("x", "translateX"), Alias::new("y", "translateY"), Alias::new("z", "translateZ"),
];

/// Reference-only custom props (e.g. rhythm multipliers, container macros, variant discriminators).
pub const REFERENCE_PROPS: &[&str] = &[
    "colorMode", "container", "font",
    "r", "variant", "weight",
];

/// Resolves a dialect alias or shorthand to its canonical property name.
pub fn resolve_alias(alias: &str) -> Option<&'static str> {
    ALIASES
        .binary_search_by_key(&alias, |a| a.alias)
        .ok()
        .map(|idx| ALIASES[idx].canonical)
}

/// Returns true if the given name is a Reference-only prop.
pub fn is_reference_prop(name: &str) -> bool {
    REFERENCE_PROPS.binary_search(&name).is_ok()
}
