export const cssSelectorsMatrixConstants = {
  baseTextDecoration: 'none',
  descendantMarginTop: '12px',
  directChildPaddingLeft: '13px',
  adjacentSiblingMarginLeft: '14px',
  generalSiblingPaddingTop: '15px',
  hoverTextDecoration: 'underline',
  focusVisibleOutlineStyle: 'solid',
  focusVisibleOutlineWidth: '2px',
  topLevelBorderStyle: 'solid',
  topLevelBorderTopWidth: '4px',
  selfAttributeBorderTopWidth: '5px',
  selfAttributeHoverBorderTopWidth: '6px',
  selfAttributeQuotedBorderRightWidth: '7px',
  selfAttributeStateBorderLeftWidth: '8px',
  recipeBaseBorderStyle: 'dashed',
  recipeBaseBorderTopWidth: '9px',
  recipeDescendantMarginTop: '10px',
  recipeDirectChildPaddingLeft: '11px',
  recipeHoverTextDecoration: 'overline',
  recipeQuotedBorderRightWidth: '16px',
  recipeStateBorderLeftWidth: '17px',
  recipeCompoundBorderTopWidth: '18px',
} as const