// Version stamp and banner for Neo generated packages.
// It takes nothing and emits the manifest version every generated package.json carries plus the banner every generated file carries.
// Both values are frozen sync output: changing either ripples into every generated folder and the tests that pin it.

export const GENERATED_VERSION = '0.0.0-neo'

export const BASE_SYSTEM_HEADER = '/** Generated by ref sync — do not edit manually */'
