//! Reference UI conditions, pseudo-selectors, and named condition catalog.
//!
//! Generated by `packages/reference-rs/modules/canon/generate/generate.ts`.
//! Defines discriminator prefixes (_ / & / @) for pseudo-classes and media queries.
//! Provides a curated catalog of named conditions for typegen and autocomplete.
// @generated

/// Sorted catalog of curated named condition identifiers.
pub const NAMED_CONDITIONS: &[&str] = &[
    "_active",
    "_after",
    "_autofill",
    "_backdrop",
    "_before",
    "_checked",
    "_closed",
    "_current",
    "_currentPage",
    "_currentStep",
    "_dark",
    "_default",
    "_disabled",
    "_dragging",
    "_empty",
    "_enabled",
    "_even",
    "_expanded",
    "_first",
    "_firstOfType",
    "_focus",
    "_focusVisible",
    "_focusWithin",
    "_fullscreen",
    "_grabbed",
    "_groupActive",
    "_groupChecked",
    "_groupDisabled",
    "_groupExpanded",
    "_groupFocus",
    "_groupFocusVisible",
    "_groupHover",
    "_groupInvalid",
    "_highContrast",
    "_hover",
    "_indeterminate",
    "_invalid",
    "_landscape",
    "_last",
    "_lastOfType",
    "_lessContrast",
    "_light",
    "_loading",
    "_ltr",
    "_marker",
    "_moreContrast",
    "_motionReduce",
    "_motionSafe",
    "_odd",
    "_only",
    "_onlyOfType",
    "_open",
    "_optional",
    "_osDark",
    "_osLight",
    "_peerActive",
    "_peerChecked",
    "_peerDisabled",
    "_peerExpanded",
    "_peerFocus",
    "_peerFocusVisible",
    "_peerHover",
    "_peerInvalid",
    "_placeholder",
    "_placeholderShown",
    "_portrait",
    "_print",
    "_readOnly",
    "_readWrite",
    "_required",
    "_rtl",
    "_selected",
    "_selection",
    "_target",
    "_userInvalid",
    "_userValid",
    "_valid",
    "_visited",
];

/// Alias to NAMED_CONDITIONS for catalog inspection.
pub const CONDITIONS: &[&str] = NAMED_CONDITIONS;

/// Returns true if the given key represents a condition, pseudo selector, or media query.
/// Pure grammar discriminator: condition keys must begin with '_', '&', or '@'.
pub fn is_condition(name: &str) -> bool {
    name.starts_with('_') || name.starts_with('&') || name.starts_with('@')
}
