//! Canonical CSS properties, native shorthand longhands, and utility class prefixes.
//!
//! Generated by `packages/reference-rs/system/canon/generate.ts`.
//! Bridges W3C/WHATWG CSS property definitions with Reference UI class prefixes.
// @generated

/// Canonical property specification in the compiler canon.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Property {
    pub name: &'static str,
    pub css: &'static str,
    pub class_prefix: &'static str,
    pub longhands: &'static [&'static str],
}

impl Property {
    pub const fn new(
        name: &'static str,
        css: &'static str,
        class_prefix: &'static str,
        longhands: &'static [&'static str],
    ) -> Self {
        Self {
            name,
            css,
            class_prefix,
            longhands,
        }
    }
}

// Native shorthand longhand slices
static BORDER_LONGHANDS: &[&str] = &["borderWidth", "borderStyle", "borderColor"];
static BORDERBLOCK_LONGHANDS: &[&str] = &["borderBlockWidth", "borderBlockStyle", "borderBlockColor"];
static BORDERBOTTOM_LONGHANDS: &[&str] = &["borderBottomWidth", "borderBottomStyle", "borderBottomColor"];
static BORDERINLINE_LONGHANDS: &[&str] = &["borderInlineWidth", "borderInlineStyle", "borderInlineColor"];
static BORDERLEFT_LONGHANDS: &[&str] = &["borderLeftWidth", "borderLeftStyle", "borderLeftColor"];
static BORDERRIGHT_LONGHANDS: &[&str] = &["borderRightWidth", "borderRightStyle", "borderRightColor"];
static BORDERTOP_LONGHANDS: &[&str] = &["borderTopWidth", "borderTopStyle", "borderTopColor"];
static INSET_LONGHANDS: &[&str] = &["top", "right", "bottom", "left"];
static MARGIN_LONGHANDS: &[&str] = &["marginTop", "marginRight", "marginBottom", "marginLeft"];
static OUTLINE_LONGHANDS: &[&str] = &["outlineWidth", "outlineStyle", "outlineColor"];
static PADDING_LONGHANDS: &[&str] = &["paddingTop", "paddingRight", "paddingBottom", "paddingLeft"];

/// All canonical CSS and system properties sorted by camelCase property name.
pub const CANONICAL_PROPERTIES: &[Property] = &[
    Property::new("alignContent", "align-content", "ac", &[]), Property::new("alignItems", "align-items", "ai", &[]),
    Property::new("alignSelf", "align-self", "as", &[]), Property::new("animation", "animation", "anim", &[]),
    Property::new("animationDelay", "animation-delay", "anim-delay", &[]), Property::new("animationDirection", "animation-direction", "anim-dir", &[]),
    Property::new("animationDuration", "animation-duration", "anim-dur", &[]), Property::new("animationFillMode", "animation-fill-mode", "anim-fm", &[]),
    Property::new("animationIterationCount", "animation-iteration-count", "anim-ic", &[]), Property::new("animationName", "animation-name", "anim-n", &[]),
    Property::new("animationPlayState", "animation-play-state", "anim-ps", &[]), Property::new("animationState", "animation-state", "anim-s", &[]),
    Property::new("animationTimingFunction", "animation-timing-function", "anim-tf", &[]), Property::new("appearance", "appearance", "ap", &[]),
    Property::new("backdropBlur", "backdrop-blur", "bd-blur", &[]), Property::new("backdropBrightness", "backdrop-brightness", "bd-brightness", &[]),
    Property::new("backdropContrast", "backdrop-contrast", "bd-contrast", &[]), Property::new("backdropFilter", "backdrop-filter", "bd-filter", &[]),
    Property::new("backdropGrayscale", "backdrop-grayscale", "bd-grayscale", &[]), Property::new("backdropHueRotate", "backdrop-hue-rotate", "bd-hue-rotate", &[]),
    Property::new("backdropInvert", "backdrop-invert", "bd-invert", &[]), Property::new("backdropOpacity", "backdrop-opacity", "bd-op", &[]),
    Property::new("backdropSaturate", "backdrop-saturate", "bd-saturate", &[]), Property::new("backdropSepia", "backdrop-sepia", "bd-sepia", &[]),
    Property::new("backfaceVisibility", "backface-visibility", "bfv", &[]), Property::new("background", "background", "bg", &[]),
    Property::new("backgroundAttachment", "background-attachment", "bg-att", &[]), Property::new("backgroundClip", "background-clip", "bg-clip", &[]),
    Property::new("backgroundColor", "background-color", "bg-c", &[]), Property::new("backgroundGradient", "background-gradient", "bg-grad", &[]),
    Property::new("backgroundOrigin", "background-origin", "bg-origin", &[]), Property::new("backgroundPosition", "background-position", "bg-pos", &[]),
    Property::new("backgroundRepeat", "background-repeat", "bg-repeat", &[]), Property::new("backgroundSize", "background-size", "bg-sz", &[]),
    Property::new("blockSize", "block-size", "h-b", &[]), Property::new("blur", "blur", "blur", &[]),
    Property::new("border", "border", "bd", BORDER_LONGHANDS), Property::new("borderBlock", "border-block", "bd-y", BORDERBLOCK_LONGHANDS),
    Property::new("borderBlockColor", "border-block-color", "bd-y-c", &[]), Property::new("borderBlockEndStyle", "border-block-end-style", "bd-be-s", &[]),
    Property::new("borderBlockStartStyle", "border-block-start-style", "bd-bs-s", &[]), Property::new("borderBlockStyle", "border-block-style", "bd-y-s", &[]),
    Property::new("borderBlockWidth", "border-block-width", "bd-y-w", &[]), Property::new("borderBottom", "border-bottom", "bd-b", BORDERBOTTOM_LONGHANDS),
    Property::new("borderBottomColor", "border-bottom-color", "bd-b-c", &[]), Property::new("borderBottomLeftRadius", "border-bottom-left-radius", "rounded-bl", &[]),
    Property::new("borderBottomRadius", "border-bottom-radius", "rounded-b", &[]), Property::new("borderBottomRightRadius", "border-bottom-right-radius", "rounded-br", &[]),
    Property::new("borderBottomStyle", "border-bottom-style", "bd-b-s", &[]), Property::new("borderBottomWidth", "border-bottom-width", "bd-b-w", &[]),
    Property::new("borderColor", "border-color", "bd-c", &[]), Property::new("borderEndRadius", "border-end-radius", "rounded-e", &[]),
    Property::new("borderInline", "border-inline", "bd-x", BORDERINLINE_LONGHANDS), Property::new("borderInlineColor", "border-inline-color", "bd-x-c", &[]),
    Property::new("borderInlineEndStyle", "border-inline-end-style", "bd-e-s", &[]), Property::new("borderInlineStartStyle", "border-inline-start-style", "bd-s-s", &[]),
    Property::new("borderInlineStyle", "border-inline-style", "bd-x-s", &[]), Property::new("borderInlineWidth", "border-inline-width", "bd-x-w", &[]),
    Property::new("borderLeft", "border-left", "bd-l", BORDERLEFT_LONGHANDS), Property::new("borderLeftColor", "border-left-color", "bd-l-c", &[]),
    Property::new("borderLeftRadius", "border-left-radius", "rounded-l", &[]), Property::new("borderLeftStyle", "border-left-style", "bd-l-s", &[]),
    Property::new("borderLeftWidth", "border-left-width", "bd-l-w", &[]), Property::new("borderRadius", "border-radius", "rounded", &[]),
    Property::new("borderRight", "border-right", "bd-r", BORDERRIGHT_LONGHANDS), Property::new("borderRightColor", "border-right-color", "bd-r-c", &[]),
    Property::new("borderRightRadius", "border-right-radius", "rounded-r", &[]), Property::new("borderRightStyle", "border-right-style", "bd-r-s", &[]),
    Property::new("borderRightWidth", "border-right-width", "bd-r-w", &[]), Property::new("borderStartRadius", "border-start-radius", "rounded-s", &[]),
    Property::new("borderStyle", "border-style", "border-style", &[]), Property::new("borderTop", "border-top", "bd-t", BORDERTOP_LONGHANDS),
    Property::new("borderTopColor", "border-top-color", "bd-t-c", &[]), Property::new("borderTopLeftRadius", "border-top-left-radius", "rounded-tl", &[]),
    Property::new("borderTopRadius", "border-top-radius", "rounded-t", &[]), Property::new("borderTopRightRadius", "border-top-right-radius", "rounded-tr", &[]),
    Property::new("borderTopStyle", "border-top-style", "bd-t-s", &[]), Property::new("borderTopWidth", "border-top-width", "bd-t-w", &[]),
    Property::new("borderWidth", "border-width", "bd-w", &[]), Property::new("bottom", "bottom", "bottom", &[]),
    Property::new("boxShadow", "box-shadow", "shadow", &[]), Property::new("boxSize", "box-size", "size", &[]),
    Property::new("boxSizing", "box-sizing", "bx-sz", &[]), Property::new("brightness", "brightness", "brightness", &[]),
    Property::new("clipPath", "clip-path", "cp-path", &[]), Property::new("color", "color", "c", &[]),
    Property::new("columnGap", "column-gap", "col-gap", &[]), Property::new("container", "container", "cq", &[]),
    Property::new("containerName", "container-name", "cq-n", &[]), Property::new("containerType", "container-type", "cq-t", &[]),
    Property::new("contrast", "contrast", "contrast", &[]), Property::new("cursor", "cursor", "cursor", &[]),
    Property::new("debug", "debug", "debug", &[]), Property::new("display", "display", "d", &[]),
    Property::new("dropShadow", "drop-shadow", "drop-shadow", &[]), Property::new("fill", "fill", "fill", &[]),
    Property::new("filter", "filter", "filter", &[]), Property::new("flex", "flex", "flex", &[]),
    Property::new("flexBasis", "flex-basis", "flex-basis", &[]), Property::new("flexDirection", "flex-direction", "flex-dir", &[]),
    Property::new("flexGrow", "flex-grow", "grow", &[]), Property::new("flexShrink", "flex-shrink", "shrink", &[]),
    Property::new("flexWrap", "flex-wrap", "flex-wrap", &[]), Property::new("fontFamily", "font-family", "font-family", &[]),
    Property::new("fontSize", "font-size", "fs", &[]), Property::new("fontWeight", "font-weight", "font-weight", &[]),
    Property::new("gap", "gap", "gap", &[]), Property::new("gradientFrom", "gradient-from", "from", &[]),
    Property::new("gradientTo", "gradient-to", "to", &[]), Property::new("gradientVia", "gradient-via", "via", &[]),
    Property::new("grayscale", "grayscale", "grayscale", &[]), Property::new("gridArea", "grid-area", "grid-area", &[]),
    Property::new("gridAutoColumns", "grid-auto-columns", "auto-cols", &[]), Property::new("gridAutoFlow", "grid-auto-flow", "grid-flow", &[]),
    Property::new("gridAutoRows", "grid-auto-rows", "auto-rows", &[]), Property::new("gridColumn", "grid-column", "col", &[]),
    Property::new("gridColumnEnd", "grid-column-end", "col-end", &[]), Property::new("gridColumnStart", "grid-column-start", "col-start", &[]),
    Property::new("gridRow", "grid-row", "row", &[]), Property::new("gridRowEnd", "grid-row-end", "row-end", &[]),
    Property::new("gridRowStart", "grid-row-start", "row-start", &[]), Property::new("gridTemplateAreas", "grid-template-areas", "grid-areas", &[]),
    Property::new("gridTemplateColumns", "grid-template-columns", "grid-cols", &[]), Property::new("gridTemplateRows", "grid-template-rows", "grid-rows", &[]),
    Property::new("height", "height", "h", &[]), Property::new("hideBelow", "hide-below", "hide-below", &[]),
    Property::new("hideFrom", "hide-from", "hide-from", &[]), Property::new("hueRotate", "hue-rotate", "hue-rotate", &[]),
    Property::new("hyphens", "hyphens", "hy", &[]), Property::new("inlineSize", "inline-size", "w-i", &[]),
    Property::new("inset", "inset", "inset", INSET_LONGHANDS), Property::new("insetBlock", "inset-block", "inset-y", &[]),
    Property::new("insetInline", "inset-inline", "inset-x", &[]), Property::new("insetInlineEnd", "inset-inline-end", "inset-e", &[]),
    Property::new("insetInlineStart", "inset-inline-start", "inset-s", &[]), Property::new("invert", "invert", "invert", &[]),
    Property::new("justifyContent", "justify-content", "jc", &[]), Property::new("justifyItems", "justify-items", "ji", &[]),
    Property::new("justifySelf", "justify-self", "js", &[]), Property::new("left", "left", "left", &[]),
    Property::new("letterSpacing", "letter-spacing", "tracking", &[]), Property::new("lineHeight", "line-height", "leading", &[]),
    Property::new("margin", "margin", "m", MARGIN_LONGHANDS), Property::new("marginBlock", "margin-block", "my", &[]),
    Property::new("marginBottom", "margin-bottom", "mb", &[]), Property::new("marginInline", "margin-inline", "mx", &[]),
    Property::new("marginInlineEnd", "margin-inline-end", "me", &[]), Property::new("marginInlineStart", "margin-inline-start", "ms", &[]),
    Property::new("marginLeft", "margin-left", "ml", &[]), Property::new("marginRight", "margin-right", "mr", &[]),
    Property::new("marginTop", "margin-top", "mt", &[]), Property::new("mask", "mask", "msk", &[]),
    Property::new("maskImage", "mask-image", "msk-i", &[]), Property::new("maskSize", "mask-size", "msk-s", &[]),
    Property::new("maxBlockSize", "max-block-size", "max-h-b", &[]), Property::new("maxHeight", "max-height", "max-h", &[]),
    Property::new("maxInlineSize", "max-inline-size", "max-w-i", &[]), Property::new("maxWidth", "max-width", "max-w", &[]),
    Property::new("minBlockSize", "min-block-size", "min-h-b", &[]), Property::new("minHeight", "min-height", "min-h", &[]),
    Property::new("minInlineSize", "min-inline-size", "min-w-i", &[]), Property::new("minWidth", "min-width", "min-w", &[]),
    Property::new("opacity", "opacity", "op", &[]), Property::new("outline", "outline", "ring", OUTLINE_LONGHANDS),
    Property::new("outlineColor", "outline-color", "ring-c", &[]), Property::new("outlineOffset", "outline-offset", "ring-offset", &[]),
    Property::new("outlineStyle", "outline-style", "ring-s", &[]), Property::new("outlineWidth", "outline-width", "ring-w", &[]),
    Property::new("overflow", "overflow", "ov", &[]), Property::new("overflowAnchor", "overflow-anchor", "ov-a", &[]),
    Property::new("overflowBlock", "overflow-block", "ov-b", &[]), Property::new("overflowClipBox", "overflow-clip-box", "ovcp-bx", &[]),
    Property::new("overflowClipMargin", "overflow-clip-margin", "ovcp-m", &[]), Property::new("overflowInline", "overflow-inline", "ov-i", &[]),
    Property::new("overflowWrap", "overflow-wrap", "ov-wrap", &[]), Property::new("overflowX", "overflow-x", "ov-x", &[]),
    Property::new("overflowY", "overflow-y", "ov-y", &[]), Property::new("overscrollBehaviorBlock", "overscroll-behavior-block", "ovs-bb", &[]),
    Property::new("overscrollBehaviorInline", "overscroll-behavior-inline", "ovs-bi", &[]), Property::new("padding", "padding", "p", PADDING_LONGHANDS),
    Property::new("paddingBlock", "padding-block", "py", &[]), Property::new("paddingBottom", "padding-bottom", "pb", &[]),
    Property::new("paddingInline", "padding-inline", "px", &[]), Property::new("paddingInlineEnd", "padding-inline-end", "pe", &[]),
    Property::new("paddingInlineStart", "padding-inline-start", "ps", &[]), Property::new("paddingLeft", "padding-left", "pl", &[]),
    Property::new("paddingRight", "padding-right", "pr", &[]), Property::new("paddingTop", "padding-top", "pt", &[]),
    Property::new("position", "position", "pos", &[]), Property::new("right", "right", "right", &[]),
    Property::new("rotate", "rotate", "rotate", &[]), Property::new("rotateX", "rotate-x", "rotate-x", &[]),
    Property::new("rotateY", "rotate-y", "rotate-y", &[]), Property::new("rotateZ", "rotate-z", "rotate-z", &[]),
    Property::new("rowGap", "row-gap", "row-gap", &[]), Property::new("saturate", "saturate", "saturate", &[]),
    Property::new("scale", "scale", "scale", &[]), Property::new("scaleX", "scale-x", "scale-x", &[]),
    Property::new("scaleY", "scale-y", "scale-y", &[]), Property::new("scrollBehavior", "scroll-behavior", "scrb", &[]),
    Property::new("scrollMargin", "scroll-margin", "scrm", &[]), Property::new("scrollMarginBottom", "scroll-margin-bottom", "scrm-b", &[]),
    Property::new("scrollMarginLeft", "scroll-margin-left", "scrm-l", &[]), Property::new("scrollMarginRight", "scroll-margin-right", "scrm-r", &[]),
    Property::new("scrollMarginTop", "scroll-margin-top", "scrm-t", &[]), Property::new("scrollPadding", "scroll-padding", "scrp", &[]),
    Property::new("scrollPaddingBottom", "scroll-padding-bottom", "scrp-b", &[]), Property::new("scrollPaddingLeft", "scroll-padding-left", "scrp-l", &[]),
    Property::new("scrollPaddingRight", "scroll-padding-right", "scrp-r", &[]), Property::new("scrollPaddingTop", "scroll-padding-top", "scrp-t", &[]),
    Property::new("scrollSnapAlign", "scroll-snap-align", "scra", &[]), Property::new("scrollSnapPointsX", "scroll-snap-points-x", "scrs-px", &[]),
    Property::new("scrollSnapPointsY", "scroll-snap-points-y", "scrs-py", &[]), Property::new("scrollSnapStop", "scroll-snap-stop", "scrs", &[]),
    Property::new("scrollSnapStrictness", "scroll-snap-strictness", "scrs-s", &[]), Property::new("scrollSnapType", "scroll-snap-type", "scrt", &[]),
    Property::new("scrollSnapTypeX", "scroll-snap-type-x", "scrs-tx", &[]), Property::new("scrollSnapTypeY", "scroll-snap-type-y", "scrs-ty", &[]),
    Property::new("scrollTimeline", "scroll-timeline", "scrtl", &[]), Property::new("scrollTimelineAxis", "scroll-timeline-axis", "scrtl-a", &[]),
    Property::new("scrollTimelineName", "scroll-timeline-name", "scrtl-n", &[]), Property::new("sepia", "sepia", "sepia", &[]),
    Property::new("spaceX", "space-x", "space-x", &[]), Property::new("spaceY", "space-y", "space-y", &[]),
    Property::new("srOnly", "sr-only", "sr", &[]), Property::new("stroke", "stroke", "stroke", &[]),
    Property::new("strokeDasharray", "stroke-dasharray", "stk-dsh", &[]), Property::new("strokeDashoffset", "stroke-dashoffset", "stk-do", &[]),
    Property::new("strokeLinecap", "stroke-linecap", "stk-lc", &[]), Property::new("strokeLinejoin", "stroke-linejoin", "stk-lj", &[]),
    Property::new("strokeMiterlimit", "stroke-miterlimit", "stk-ml", &[]), Property::new("strokeOpacity", "stroke-opacity", "stk-op", &[]),
    Property::new("strokeWidth", "stroke-width", "stk-w", &[]), Property::new("textAlign", "text-align", "ta", &[]),
    Property::new("textDecoration", "text-decoration", "text-decoration", &[]), Property::new("textGradient", "text-gradient", "text-grad", &[]),
    Property::new("textSizeAdjust", "text-size-adjust", "txt-adj", &[]), Property::new("textStyle", "text-style", "textStyle", &[]),
    Property::new("textTransform", "text-transform", "text-transform", &[]), Property::new("textWrap", "text-wrap", "text-wrap", &[]),
    Property::new("top", "top", "top", &[]), Property::new("touchAction", "touch-action", "tch-a", &[]),
    Property::new("transform", "transform", "transform", &[]), Property::new("transition", "transition", "trans", &[]),
    Property::new("transitionDelay", "transition-delay", "trans-delay", &[]), Property::new("transitionDuration", "transition-duration", "trans-dur", &[]),
    Property::new("transitionProperty", "transition-property", "trans-prop", &[]), Property::new("transitionTimingFunction", "transition-timing-function", "trans-tf", &[]),
    Property::new("translate", "translate", "translate", &[]), Property::new("translateX", "translate-x", "x", &[]),
    Property::new("translateY", "translate-y", "y", &[]), Property::new("translateZ", "translate-z", "z", &[]),
    Property::new("userSelect", "user-select", "us", &[]), Property::new("visibility", "visibility", "vis", &[]),
    Property::new("whiteSpace", "white-space", "white-space", &[]), Property::new("width", "width", "w", &[]),
    Property::new("wordBreak", "word-break", "word-break", &[]), Property::new("zIndex", "z-index", "z", &[]),
];

/// Returns the Property record for a canonical property name, if known.
pub fn find_property(name: &str) -> Option<&'static Property> {
    CANONICAL_PROPERTIES
        .binary_search_by_key(&name, |p| p.name)
        .ok()
        .map(|idx| &CANONICAL_PROPERTIES[idx])
}

/// Returns the native shorthand longhands for a property, if it is a shorthand.
pub fn native_longhands_for_prop(name: &str) -> Option<&'static [&'static str]> {
    match find_property(name) {
        Some(p) if !p.longhands.is_empty() => Some(p.longhands),
        _ => None,
    }
}
