//! Reference UI StyleProps dialect aliases and custom props.
//!
//! Generated by `packages/reference-rs/modules/canon/generate/generate.ts`.
//! Maps concise authoring shorthand aliases to canonical CSS properties and defines Reference-only props.
//! Provides zero-allocation lookup functions for resolving aliases during compiler passes.
// @generated

/// StyleProps alias mapping a shorthand alias to its canonical property name.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Alias {
    pub alias: &'static str,
    pub canonical: &'static str,
}

impl Alias {
    pub const fn new(alias: &'static str, canonical: &'static str) -> Self {
        Self { alias, canonical }
    }
}

/// Sorted table of StyleProps shorthand aliases.
pub const ALIASES: &[Alias] = &[
    Alias::new("bg", "background"),
    Alias::new("flexDir", "flexDirection"),
    Alias::new("h", "height"),
    Alias::new("m", "margin"),
    Alias::new("maxH", "maxHeight"),
    Alias::new("maxW", "maxWidth"),
    Alias::new("mb", "marginBottom"),
    Alias::new("minH", "minHeight"),
    Alias::new("minW", "minWidth"),
    Alias::new("ml", "marginLeft"),
    Alias::new("mr", "marginRight"),
    Alias::new("mt", "marginTop"),
    Alias::new("mx", "marginInline"),
    Alias::new("my", "marginBlock"),
    Alias::new("p", "padding"),
    Alias::new("pb", "paddingBottom"),
    Alias::new("pl", "paddingLeft"),
    Alias::new("pr", "paddingRight"),
    Alias::new("pt", "paddingTop"),
    Alias::new("px", "paddingInline"),
    Alias::new("py", "paddingBlock"),
    Alias::new("w", "width"),
];

/// Reference-only custom macro props (e.g. rhythm multipliers, variant discriminators).
pub const REFERENCE_PROPS: &[&str] = &["colorMode", "r", "size", "variant", "weight"];

/// Resolves a dialect alias or shorthand to its canonical property name.
pub fn resolve_alias(alias: &str) -> Option<&'static str> {
    ALIASES
        .binary_search_by_key(&alias, |a| a.alias)
        .ok()
        .map(|idx| ALIASES[idx].canonical)
}

/// Returns true if the given name is a Reference-only macro prop.
pub fn is_reference_prop(name: &str) -> bool {
    REFERENCE_PROPS.binary_search(&name).is_ok()
}
