//! Generated HTML tags and Reference primitive JSX element names.
//!
//! Generated by `packages/reference-rs/system/canon/generate.ts`.
//! Represents the curated subset of HTML elements wrapped as Reference UI JSX primitives.
// @generated

/// Element mapping from lowercase HTML element tag to PascalCase JSX primitive.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Element {
    pub html: &'static str,
    pub jsx: &'static str,
}

impl Element {
    pub const fn new(html: &'static str, jsx: &'static str) -> Self {
        Self { html, jsx }
    }
}

/// All canonical elements supported as Reference UI primitives.
pub const ELEMENTS: &[Element] = &[
    Element::new("a", "A"), Element::new("abbr", "Abbr"), Element::new("address", "Address"),
    Element::new("area", "Area"), Element::new("article", "Article"), Element::new("aside", "Aside"),
    Element::new("audio", "Audio"), Element::new("b", "B"), Element::new("bdi", "Bdi"),
    Element::new("bdo", "Bdo"), Element::new("blockquote", "Blockquote"), Element::new("br", "Br"),
    Element::new("button", "Button"), Element::new("canvas", "Canvas"), Element::new("caption", "Caption"),
    Element::new("cite", "Cite"), Element::new("code", "Code"), Element::new("col", "Col"),
    Element::new("colgroup", "Colgroup"), Element::new("data", "Data"), Element::new("datalist", "Datalist"),
    Element::new("dd", "Dd"), Element::new("del", "Del"), Element::new("details", "Details"),
    Element::new("dfn", "Dfn"), Element::new("dialog", "Dialog"), Element::new("div", "Div"),
    Element::new("dl", "Dl"), Element::new("dt", "Dt"), Element::new("em", "Em"),
    Element::new("embed", "Embed"), Element::new("fieldset", "Fieldset"), Element::new("figcaption", "Figcaption"),
    Element::new("figure", "Figure"), Element::new("footer", "Footer"), Element::new("form", "Form"),
    Element::new("h1", "H1"), Element::new("h2", "H2"), Element::new("h3", "H3"),
    Element::new("h4", "H4"), Element::new("h5", "H5"), Element::new("h6", "H6"),
    Element::new("header", "Header"), Element::new("hgroup", "Hgroup"), Element::new("hr", "Hr"),
    Element::new("i", "I"), Element::new("iframe", "Iframe"), Element::new("img", "Img"),
    Element::new("input", "Input"), Element::new("ins", "Ins"), Element::new("kbd", "Kbd"),
    Element::new("label", "Label"), Element::new("legend", "Legend"), Element::new("li", "Li"),
    Element::new("main", "Main"), Element::new("map", "Map"), Element::new("mark", "Mark"),
    Element::new("menu", "Menu"), Element::new("meter", "Meter"), Element::new("nav", "Nav"),
    Element::new("object", "Obj"), Element::new("ol", "Ol"), Element::new("optgroup", "Optgroup"),
    Element::new("option", "Option"), Element::new("output", "Output"), Element::new("p", "P"),
    Element::new("picture", "Picture"), Element::new("pre", "Pre"), Element::new("progress", "Progress"),
    Element::new("q", "Q"), Element::new("rp", "Rp"), Element::new("rt", "Rt"),
    Element::new("ruby", "Ruby"), Element::new("s", "S"), Element::new("samp", "Samp"),
    Element::new("search", "Search"), Element::new("section", "Section"), Element::new("select", "Select"),
    Element::new("small", "Small"), Element::new("source", "Source"), Element::new("span", "Span"),
    Element::new("strong", "Strong"), Element::new("sub", "Sub"), Element::new("summary", "Summary"),
    Element::new("sup", "Sup"), Element::new("svg", "Svg"), Element::new("table", "Table"),
    Element::new("tbody", "Tbody"), Element::new("td", "Td"), Element::new("textarea", "Textarea"),
    Element::new("tfoot", "Tfoot"), Element::new("th", "Th"), Element::new("thead", "Thead"),
    Element::new("time", "Time"), Element::new("tr", "Tr"), Element::new("track", "Track"),
    Element::new("u", "U"), Element::new("ul", "Ul"), Element::new("var", "Var"),
    Element::new("video", "Video"), Element::new("wbr", "Wbr"),
];

/// Returns true if the given tag name is a valid lowercase HTML element tag in the canon.
pub fn is_html_tag(tag: &str) -> bool {
    ELEMENTS.binary_search_by_key(&tag, |e| e.html).is_ok()
}

/// Returns true if the given identifier is a valid Reference primitive JSX component name.
pub fn is_primitive_jsx_name(name: &str) -> bool {
    ELEMENTS.binary_search_by_key(&name, |e| e.jsx).is_ok()
}

/// Returns true if the given element name is either an HTML tag or a Reference primitive.
pub fn is_reference_primitive(name: &str) -> bool {
    is_html_tag(name) || is_primitive_jsx_name(name)
}
