import type { McpComponent, McpComponentProp } from './types'

function libProp(
  name: string,
  type: string,
  description: string,
  optional = true
): McpComponentProp {
  return {
    name,
    count: 0,
    usage: 'unused',
    type,
    description,
    optional,
    readonly: false,
    origin: 'documented',
    styleProp: false,
  }
}

export const REFERENCE_UI_LIBRARY_COMPONENTS: McpComponent[] = [
  {
    name: 'Accordion',
    kind: 'component',
    source: '@reference-ui/lib',
    count: 0,
    usage: 'unused',
    usedWith: {},
    examples: [
      `<Accordion type="single" collapsible>\n  <Accordion.Item value="item-1">\n    <Accordion.Trigger>Section title</Accordion.Trigger>\n    <Accordion.Content>Section body text</Accordion.Content>\n  </Accordion.Item>\n</Accordion>`,
    ],
    interface: { name: 'AccordionProps', source: '@reference-ui/lib' },
    props: [
      libProp('type', "'single' | 'multiple'", 'Determines whether one or multiple items can be opened simultaneously.'),
      libProp('collapsible', 'boolean', 'When type is single, allows closing content when clicking active trigger.'),
      libProp('value', 'string | string[]', 'The controlled value of the expanded item(s).'),
      libProp('onValueChange', '(value: string | string[]) => void', 'Event handler called when the expanded state changes.'),
      libProp('disabled', 'boolean', 'When true, prevents user from interacting with any accordion item.'),
      libProp('children', 'React.ReactNode', 'Accordion.Item elements.'),
    ],
  },
  {
    name: 'Tabs',
    kind: 'component',
    source: '@reference-ui/lib',
    count: 0,
    usage: 'unused',
    usedWith: {},
    examples: [
      `<Tabs defaultValue="tab1">\n  <Tabs.List>\n    <Tabs.Trigger value="tab1">Account</Tabs.Trigger>\n    <Tabs.Trigger value="tab2">Password</Tabs.Trigger>\n  </Tabs.List>\n  <Tabs.Content value="tab1">Make changes to your account.</Tabs.Content>\n  <Tabs.Content value="tab2">Change your password here.</Tabs.Content>\n</Tabs>`,
    ],
    interface: { name: 'TabsProps', source: '@reference-ui/lib' },
    props: [
      libProp('defaultValue', 'string', 'The value of the tab that should be active by default.'),
      libProp('value', 'string', 'The controlled active tab value.'),
      libProp('onValueChange', '(value: string) => void', 'Event handler called when the active tab changes.'),
      libProp('orientation', "'horizontal' | 'vertical'", 'The orientation of the tabs.'),
      libProp('children', 'React.ReactNode', 'Tabs.List and Tabs.Content elements.'),
    ],
  },
  {
    name: 'Splitter',
    kind: 'component',
    source: '@reference-ui/lib',
    count: 0,
    usage: 'unused',
    usedWith: {},
    examples: [
      `<Splitter orientation="horizontal">\n  <Splitter.Panel defaultSize={30} minSize={20}>Sidebar</Splitter.Panel>\n  <Splitter.Handle />\n  <Splitter.Panel defaultSize={70}>Main Content</Splitter.Panel>\n</Splitter>`,
    ],
    interface: { name: 'SplitterProps', source: '@reference-ui/lib' },
    props: [
      libProp('orientation', "'horizontal' | 'vertical'", 'Direction in which panels are split.'),
      libProp('children', 'React.ReactNode', 'Splitter.Panel and Splitter.Handle elements.'),
    ],
  },
  {
    name: 'Menu',
    kind: 'component',
    source: '@reference-ui/lib',
    count: 0,
    usage: 'unused',
    usedWith: {},
    examples: [
      `<Menu>\n  <Menu.Trigger>\n    <Button>Actions</Button>\n  </Menu.Trigger>\n  <Menu.Content>\n    <Menu.Item onSelect={() => {}}>Edit</Menu.Item>\n    <Menu.Item onSelect={() => {}}>Duplicate</Menu.Item>\n    <Menu.Separator />\n    <Menu.Item destructive onSelect={() => {}}>Delete</Menu.Item>\n  </Menu.Content>\n</Menu>`,
    ],
    interface: { name: 'MenuProps', source: '@reference-ui/lib' },
    props: [
      libProp('open', 'boolean', 'The controlled open state of the menu.'),
      libProp('onOpenChange', '(open: boolean) => void', 'Event handler called when open state changes.'),
      libProp('children', 'React.ReactNode', 'Menu.Trigger and Menu.Content.'),
    ],
  },
  {
    name: 'Popover',
    kind: 'component',
    source: '@reference-ui/lib',
    count: 0,
    usage: 'unused',
    usedWith: {},
    examples: [
      `<Popover>\n  <Popover.Trigger>\n    <Button>Open Popover</Button>\n  </Popover.Trigger>\n  <Popover.Content>\n    <P>Popover content</P>\n  </Popover.Content>\n</Popover>`,
    ],
    interface: { name: 'PopoverProps', source: '@reference-ui/lib' },
    props: [
      libProp('open', 'boolean', 'The controlled open state.'),
      libProp('onOpenChange', '(open: boolean) => void', 'Event handler called when open state changes.'),
      libProp('children', 'React.ReactNode', 'Popover.Trigger and Popover.Content.'),
    ],
  },
  {
    name: 'Tooltip',
    kind: 'component',
    source: '@reference-ui/lib',
    count: 0,
    usage: 'unused',
    usedWith: {},
    examples: [
      `<Tooltip content="Add to library">\n  <Button iconOnly aria-label="Add">+</Button>\n</Tooltip>`,
    ],
    interface: { name: 'TooltipProps', source: '@reference-ui/lib' },
    props: [
      libProp('content', 'React.ReactNode', 'Content rendered inside the tooltip popup.'),
      libProp('delayDuration', 'number', 'Hover duration in ms before showing tooltip.'),
      libProp('children', 'React.ReactNode', 'Trigger element wrapped by the tooltip.'),
    ],
  },
  {
    name: 'Toast',
    kind: 'component',
    source: '@reference-ui/lib',
    count: 0,
    usage: 'unused',
    usedWith: {},
    examples: [
      `import { toast } from '@reference-ui/lib'\n\ntoast.success('Changes saved successfully!')`,
    ],
    interface: { name: 'ToastProps', source: '@reference-ui/lib' },
    props: [
      libProp('title', 'string', 'Toast notification title.'),
      libProp('description', 'string', 'Secondary toast text.'),
    ],
  },
  {
    name: 'Switch',
    kind: 'component',
    source: '@reference-ui/lib',
    count: 0,
    usage: 'unused',
    usedWith: {},
    examples: [
      `<Switch checked={enabled} onCheckedChange={setEnabled}>\n  Enable notifications\n</Switch>`,
    ],
    interface: { name: 'SwitchProps', source: '@reference-ui/lib' },
    props: [
      libProp('checked', 'boolean', 'Controlled boolean state of switch.'),
      libProp('defaultChecked', 'boolean', 'Default boolean state when uncontrolled.'),
      libProp('onCheckedChange', '(checked: boolean) => void', 'Event handler called when toggle changes.'),
      libProp('disabled', 'boolean', 'When true, disables switch toggle.'),
    ],
  },
  {
    name: 'Slider',
    kind: 'component',
    source: '@reference-ui/lib',
    count: 0,
    usage: 'unused',
    usedWith: {},
    examples: [
      `<Slider value={[volume]} onValueChange={([val]) => setVolume(val)} min={0} max={100} step={1} />`,
    ],
    interface: { name: 'SliderProps', source: '@reference-ui/lib' },
    props: [
      libProp('value', 'number[]', 'Controlled array of slider thumb values.'),
      libProp('defaultValue', 'number[]', 'Default array of thumb values.'),
      libProp('onValueChange', '(value: number[]) => void', 'Event handler called when values change.'),
      libProp('min', 'number', 'Minimum slider value.'),
      libProp('max', 'number', 'Maximum slider value.'),
      libProp('step', 'number', 'Stepping increment.'),
    ],
  },
  {
    name: 'Combobox',
    kind: 'component',
    source: '@reference-ui/lib',
    count: 0,
    usage: 'unused',
    usedWith: {},
    examples: [
      `<Combobox items={options}>\n  <Combobox.Input placeholder="Select item..." />\n  <Combobox.Content>\n    {item => <Combobox.Item key={item.id} value={item.id}>{item.label}</Combobox.Item>}\n  </Combobox.Content>\n</Combobox>`,
    ],
    interface: { name: 'ComboboxProps', source: '@reference-ui/lib' },
    props: [
      libProp('items', 'T[]', 'Array of items displayed in combobox popup.'),
      libProp('value', 'string', 'Selected item value.'),
      libProp('onValueChange', '(value: string) => void', 'Handler called when selection changes.'),
    ],
  },
  {
    name: 'Calendar',
    kind: 'component',
    source: '@reference-ui/lib',
    count: 0,
    usage: 'unused',
    usedWith: {},
    examples: [
      `<Calendar mode="day" value={selectedDate} onChange={setSelectedDate} />`,
      `<Calendar mode="range" value={{ start: startDate, end: endDate }} onChange={setRange} />`,
    ],
    interface: { name: 'CalendarProps', source: '@reference-ui/lib' },
    props: [
      libProp('mode', "'day' | 'range' | 'month' | 'year'", 'Selection mode for the calendar.'),
      libProp('value', 'ISODate | DateRangeValue | null', 'The controlled calendar date value.'),
      libProp('defaultValue', 'ISODate | DateRangeValue | null', 'Default date value when uncontrolled.'),
      libProp('onChange', '(value: any) => void', 'Event handler called when selected date changes.'),
      libProp('locale', 'string', 'BCP 47 language tag for calendar localization (e.g. "en-US").'),
      libProp('min', 'string', 'Earliest selectable ISO date (YYYY-MM-DD).'),
      libProp('max', 'string', 'Latest selectable ISO date (YYYY-MM-DD).'),
      libProp('disabled', 'boolean', 'When true, disables date interaction.'),
    ],
  },
  {
    name: 'DateField',
    kind: 'component',
    source: '@reference-ui/lib',
    count: 0,
    usage: 'unused',
    usedWith: {},
    examples: [
      `<DateField value={date} onChange={setDate}>\n  <DateField.Input />\n  <DateField.PickerButton />\n</DateField>`,
    ],
    interface: { name: 'DateFieldProps', source: '@reference-ui/lib' },
    props: [
      libProp('value', 'string | null', 'Controlled ISO date string (YYYY-MM-DD).'),
      libProp('defaultValue', 'string | null', 'Default ISO date string.'),
      libProp('onChange', '(value: string | null) => void', 'Handler called when date value changes.'),
      libProp('locale', 'string', 'BCP 47 language tag for date formatting.'),
      libProp('min', 'string', 'Minimum allowed date.'),
      libProp('max', 'string', 'Maximum allowed date.'),
      libProp('disabled', 'boolean', 'Disables date field input.'),
    ],
  },
  {
    name: 'NumberField',
    kind: 'component',
    source: '@reference-ui/lib',
    count: 0,
    usage: 'unused',
    usedWith: {},
    examples: [
      `<NumberField value={count} onChange={setCount} min={0} max={10}>\n  <NumberField.Decrement />\n  <NumberField.Input />\n  <NumberField.Increment />\n</NumberField>`,
    ],
    interface: { name: 'NumberFieldProps', source: '@reference-ui/lib' },
    props: [
      libProp('value', 'number | null', 'Controlled numeric value.'),
      libProp('defaultValue', 'number | null', 'Default numeric value.'),
      libProp('onChange', '(value: number | null) => void', 'Handler called when value changes.'),
      libProp('min', 'number', 'Minimum allowed number.'),
      libProp('max', 'number', 'Maximum allowed number.'),
      libProp('step', 'number', 'Step increment for adjustments.'),
      libProp('disabled', 'boolean', 'Disables numeric field.'),
    ],
  },
  {
    name: 'Tree',
    kind: 'component',
    source: '@reference-ui/lib',
    count: 0,
    usage: 'unused',
    usedWith: {},
    examples: [
      `<Tree value={selected} onChange={setSelected}>\n  <Tree.Item id="file-1">index.ts</Tree.Item>\n  <Tree.Branch id="folder-1">\n    <Tree.BranchTrigger>src</Tree.BranchTrigger>\n    <Tree.BranchContent>\n      <Tree.Item id="file-2">app.ts</Tree.Item>\n    </Tree.BranchContent>\n  </Tree.Branch>\n</Tree>`,
    ],
    interface: { name: 'TreeProps', source: '@reference-ui/lib' },
    props: [
      libProp('value', 'string | null', 'Selected item id.'),
      libProp('defaultValue', 'string | null', 'Default selected item id.'),
      libProp('onChange', '(value: string | null) => void', 'Handler called when selection changes.'),
      libProp('expanded', 'string[]', 'Controlled array of expanded branch ids.'),
      libProp('defaultExpanded', 'string[]', 'Default expanded branch ids.'),
      libProp('onExpandedChange', '(expanded: string[]) => void', 'Handler called when branches expand/collapse.'),
      libProp('disabled', 'boolean', 'Disables tree navigation.'),
    ],
  },
  {
    name: 'Listbox',
    kind: 'component',
    source: '@reference-ui/lib',
    count: 0,
    usage: 'unused',
    usedWith: {},
    examples: [
      `<Listbox selection="single" value={selected} onChange={setSelected}>\n  <Listbox.Option value="opt1">Option 1</Listbox.Option>\n  <Listbox.Option value="opt2">Option 2</Listbox.Option>\n</Listbox>`,
    ],
    interface: { name: 'ListboxProps', source: '@reference-ui/lib' },
    props: [
      libProp('selection', "'single' | 'multiple'", 'Selection mode.'),
      libProp('value', 'string | string[] | null', 'Controlled selected value.'),
      libProp('defaultValue', 'string | string[] | null', 'Default selected value.'),
      libProp('onChange', '(value: any) => void', 'Handler called when selection changes.'),
      libProp('orientation', "'horizontal' | 'vertical'", 'Layout orientation for arrow navigation.'),
      libProp('disabled', 'boolean', 'Disables listbox options.'),
    ],
  },
  {
    name: 'Collapsible',
    kind: 'component',
    source: '@reference-ui/lib',
    count: 0,
    usage: 'unused',
    usedWith: {},
    examples: [
      `<Collapsible open={isOpen} onOpenChange={setIsOpen}>\n  <Collapsible.Trigger>Toggle Details</Collapsible.Trigger>\n  <Collapsible.Content>Detailed section text</Collapsible.Content>\n</Collapsible>`,
    ],
    interface: { name: 'CollapsibleProps', source: '@reference-ui/lib' },
    props: [
      libProp('open', 'boolean', 'Controlled open state.'),
      libProp('defaultOpen', 'boolean', 'Default open state.'),
      libProp('onOpenChange', '(open: boolean) => void', 'Handler called when open state changes.'),
      libProp('disabled', 'boolean', 'Disables collapsible trigger.'),
    ],
  },
  {
    name: 'Field',
    kind: 'component',
    source: '@reference-ui/lib',
    count: 0,
    usage: 'unused',
    usedWith: {},
    examples: [
      `<Field status={hasError ? 'warning' : undefined}>\n  <Label>Username</Label>\n  <Input />\n</Field>`,
    ],
    interface: { name: 'FieldProps', source: '@reference-ui/lib' },
    props: [
      libProp('status', "'warning'", 'Validation state flag.'),
      libProp('children', 'React.ReactNode', 'Form control, label, and description children.'),
    ],
  },
  {
    name: 'Overlay',
    kind: 'component',
    source: '@reference-ui/lib',
    count: 0,
    usage: 'unused',
    usedWith: {},
    examples: [
      `<Overlay open={isOpen} onDismiss={() => setIsOpen(false)} placement="bottom">\n  <Overlay.Surface>Floating overlay surface</Overlay.Surface>\n</Overlay>`,
    ],
    interface: { name: 'OverlayProps', source: '@reference-ui/lib' },
    props: [
      libProp('open', 'boolean', 'Controlled open state of overlay.'),
      libProp('defaultOpen', 'boolean', 'Default open state.'),
      libProp('onOpenChange', '(open: boolean) => void', 'Handler called when open changes.'),
      libProp('placement', 'string', 'Placement relative to anchor.'),
      libProp('isolation', 'boolean | object', 'Scroll and focus lock options.'),
      libProp('onDismiss', '() => void', 'Handler called on outside click or escape.'),
    ],
  },
  {
    name: 'Portal',
    kind: 'component',
    source: '@reference-ui/lib',
    count: 0,
    usage: 'unused',
    usedWith: {},
    examples: [
      `<Portal>\n  <Div position="fixed" top="0">Portaled content</Div>\n</Portal>`,
    ],
    interface: { name: 'PortalProps', source: '@reference-ui/lib' },
    props: [
      libProp('container', 'Element | null', 'Target DOM container to portal children into.'),
      libProp('children', 'React.ReactNode', 'Elements rendered into portal container.'),
    ],
  },
  {
    name: 'FocusLock',
    kind: 'component',
    source: '@reference-ui/lib',
    count: 0,
    usage: 'unused',
    usedWith: {},
    examples: [
      `<FocusLock>\n  <Div role="dialog">\n    <Button>Modal Action</Button>\n  </Div>\n</FocusLock>`,
    ],
    interface: { name: 'FocusLockProps', source: '@reference-ui/lib' },
    props: [
      libProp('disabled', 'boolean', 'When true, focus trapping is disabled.'),
      libProp('initialFocus', 'HTMLElement | boolean', 'Initial element to focus on mount.'),
      libProp('restoreFocus', 'HTMLElement | boolean', 'Element to restore focus to on unmount.'),
    ],
  },
  {
    name: 'RovingFocus',
    kind: 'component',
    source: '@reference-ui/lib',
    count: 0,
    usage: 'unused',
    usedWith: {},
    examples: [
      `<RovingFocus orientation="horizontal">\n  <RovingFocus.Item id="item-1"><Button>First</Button></RovingFocus.Item>\n  <RovingFocus.Item id="item-2"><Button>Second</Button></RovingFocus.Item>\n</RovingFocus>`,
    ],
    interface: { name: 'RovingFocusRootProps', source: '@reference-ui/lib' },
    props: [
      libProp('orientation', "'horizontal' | 'vertical' | 'both'", 'Direction of keyboard navigation.'),
      libProp('loop', 'boolean', 'When true, wraps around navigation boundaries.'),
      libProp('currentId', 'string', 'Controlled active item id.'),
      libProp('onCurrentIdChange', '(id: string) => void', 'Handler called when active focus changes.'),
    ],
  },
  {
    name: 'Presence',
    kind: 'component',
    source: '@reference-ui/lib',
    count: 0,
    usage: 'unused',
    usedWith: {},
    examples: [
      `<Presence present={isOpen}>\n  <Div data-state={isOpen ? 'open' : 'closed'}>Animated element</Div>\n</Presence>`,
    ],
    interface: { name: 'PresenceProps', source: '@reference-ui/lib' },
    props: [
      libProp('present', 'boolean', 'Controls mounted/visible animation presence.'),
      libProp('children', 'React.ReactNode', 'Single element whose exit transitions are waited on.'),
    ],
  },
  {
    name: 'Slot',
    kind: 'component',
    source: '@reference-ui/lib',
    count: 0,
    usage: 'unused',
    usedWith: {},
    examples: [
      `<Slot>\n  <Button onClick={handleClick}>Slotted Child</Button>\n</Slot>`,
    ],
    interface: { name: 'SlotProps', source: '@reference-ui/lib' },
    props: [
      libProp('children', 'React.ReactElement', 'Single child element to which slotted props are merged.'),
    ],
  },
  {
    name: 'ReferenceLibrary',
    kind: 'component',
    source: '@reference-ui/lib',
    count: 0,
    usage: 'unused',
    usedWith: {},
    examples: [
      `<ReferenceLibrary>\n  <App />\n</ReferenceLibrary>`,
    ],
    interface: { name: 'ReferenceLibraryProps', source: '@reference-ui/lib' },
    props: [
      libProp('toaster', 'object', 'Toaster configuration (defaultPosition, duration, limit).'),
      libProp('tooltip', 'object', 'Global tooltip configuration (skipDelay).'),
      libProp('children', 'React.ReactNode', 'Application tree.'),
    ],
  },
]

export function findReferenceUiLibraryComponent(name: string): McpComponent | null {
  const comp = REFERENCE_UI_LIBRARY_COMPONENTS.find(
    c => c.name.toLowerCase() === name.toLowerCase()
  )
  return comp ? { ...comp } : null
}
