/**
 * Font-registry codegen.
 *
 * Builds a per-system `FontRegistry` interface from collected font fragments
 * and writes it into the consumer's generated package layout. The code that
 * patches emitted declaration files (`writeFontRegistryIntoTypes`) is the last
 * place this generator reaches into emitted output; it exists because tsgo
 * cannot emit augmenting declarations from an empty interface graph.
 */
import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { dirname, join } from 'node:path'
import { pathToFileURL } from 'node:url'
import { writeFileAtomic } from '../../lib/fs/write-file-atomic'
import { createFontCollector, type FontDefinition } from '../../system/api/font'
import {
  getSystemFontRegistryPath,
  getSystemGeneratedTypesPath,
  getSystemTypesDir,
} from './shared'

export interface FontTypeRegistry {
  [fontName: string]: string[]
}

const EMITTED_FONT_REGISTRY_INTERFACE = 'FontRegistry'
const EMITTED_FONT_PROPS_ALIAS = 'FontProps'

const EMITTED_FONT_PROPS_SHAPE = `{
    font?: ConditionalValue<string>;
    weight?: ConditionalValue<string>;
}`

export function buildFontTypeRegistry(fonts: FontDefinition[]): FontTypeRegistry {
  const registry = new Map<string, Set<string>>()

  for (const font of fonts) {
    const weightNames = registry.get(font.name) ?? new Set<string>()

    for (const weightName of Object.keys(font.weights)) {
      weightNames.add(weightName)
    }

    registry.set(font.name, weightNames)
  }

  return Object.fromEntries(
    [...registry.entries()].map(([fontName, weightNames]) => [fontName, [...weightNames]])
  )
}

export function renderFontRegistryInterface(registry: FontTypeRegistry): string {
  const lines = [
    `interface ${EMITTED_FONT_REGISTRY_INTERFACE} {`,
  ]

  for (const [fontName, weightNames] of Object.entries(registry)) {
    lines.push(`    ${JSON.stringify(fontName)}: {`)

    for (const weightName of weightNames) {
      lines.push(`        ${JSON.stringify(weightName)}: true`)
    }

    lines.push('    }')
  }

  lines.push('}')

  return lines.join('\n')
}

export function renderGeneratedFontRegistryFile(registry: FontTypeRegistry): string {
  return [
    '/** Generated by reference-core — do not edit manually. */',
    renderFontRegistryInterface(registry),
    '',
  ].join('\n')
}

async function collectFontsFromFragment(fragment: string): Promise<FontDefinition[]> {
  const tempDir = mkdtempSync(join(tmpdir(), 'ref-ui-font-types-'))
  const tempFile = join(tempDir, 'font-fragments.mjs')
  const fontCollector = createFontCollector()

  fontCollector.init()
  writeFileSync(tempFile, [fontCollector.toRuntimeFunction(), `;${fragment}`].join('\n'), 'utf-8')

  try {
    await import(`${pathToFileURL(tempFile).href}?t=${Date.now()}`)
    return fontCollector.getFragments()
  } finally {
    fontCollector.cleanup()
    rmSync(tempDir, { recursive: true, force: true })
  }
}

export async function writeGeneratedSystemFontTypes(
  cwd: string,
  fragment: string
): Promise<FontTypeRegistry> {
  const fonts = await collectFontsFromFragment(fragment)
  const registry = buildFontTypeRegistry(fonts)
  const systemTypesDir = getSystemTypesDir(cwd)

  mkdirSync(systemTypesDir, { recursive: true })
  writeFileSync(getSystemFontRegistryPath(cwd), JSON.stringify(registry, null, 2), 'utf-8')
  writeFileSync(getSystemGeneratedTypesPath(cwd), renderGeneratedFontRegistryFile(registry), 'utf-8')

  return registry
}

export function readGeneratedFontRegistry(cwd: string): FontTypeRegistry {
  const registryPath = getSystemFontRegistryPath(cwd)

  if (!existsSync(registryPath)) {
    return {}
  }

  return JSON.parse(readFileSync(registryPath, 'utf-8')) as FontTypeRegistry
}

export function writeFontRegistryIntoTypes(typesPath: string, registry: FontTypeRegistry): void {
  let content = readFileSync(typesPath, 'utf-8')
    .replace("import './types.generated.d.mts';\n", '')
    .replace(
      /interface (?:ReferenceFontRegistry|FontRegistry) \{\n\}/,
      renderFontRegistryInterface(registry)
    )

  if (Object.keys(registry).length > 0) {
    content = content
      .replace(
        /type (?:ReferenceFontProps|FontProps) = \[(?:ReferenceFontName|FontName)\] extends \[never\] \? (?:ReferenceFallbackFontProps|FallbackFontProps) : (?:ReferenceScopedFontProps|ScopedFontProps);/,
        `type ${EMITTED_FONT_PROPS_ALIAS} = ScopedFontProps;`
      )
      .split(EMITTED_FONT_PROPS_SHAPE)
      .join(EMITTED_FONT_PROPS_ALIAS)
  }

  writeFileAtomic(typesPath, content, 'utf-8')
}

/**
 * Refresh the generated font-registry artefact alongside an emitted package.
 * Called by the orchestrator after `tsgo` has produced the package's root types.
 */
export function refreshGeneratedTypesArtefact(cwd: string, typesPath: string): FontTypeRegistry {
  const registry = readGeneratedFontRegistry(cwd)
  const generatedTypesPath = join(dirname(typesPath), 'types.generated.d.mts')
  writeFileAtomic(generatedTypesPath, renderGeneratedFontRegistryFile(registry), 'utf-8')
  return registry
}
