/**
 * Strict-token system-style-object codegen.
 *
 * Renders the canonical `system-style-object.d.ts` for a generated package
 * based on the consumer's `ui.config.ts` `strict` array. The packager calls
 * `writeStrictSystemStyleObject(typesPath)` after `tsgo` emits, but the file
 * content is computed deterministically from config — this generator does NOT
 * read or pattern-match the emitted output to decide what to write.
 *
 * Identity and strict wraps both print an owned `BaseSystemStyleObject`
 * (csstype + canon aliases) and intersect nested condition/selector keys.
 * Wrapping the recursive `SystemStyleObject` alias is TS2456.
 *
 * Generated `.d.ts` imports `Properties` from the Panda-vendored
 * `styled/types/csstype` sibling (not the `csstype` package). Consumers do
 * not install `csstype`; a `from 'csstype'` specifier here makes
 * `SystemStyleObject` resolve to `any` and strips primitive event handlers.
 */
import { readFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { writeFileAtomic } from '../../lib/fs/write-file-atomic'
import { getConfig } from '../../config/store'
import type { StrictTokenCategory } from '../../config/types'

const STRICT_WRAPPER_BY_CATEGORY: Record<StrictTokenCategory, string | null> = {
  colors: 'StrictColorProps',
  radii: 'StrictRadiiProps',
  spacing: null,
}

const SOURCE_MODULE_BY_CATEGORY: Record<StrictTokenCategory, string | null> = {
  colors: './strict-colors',
  radii: './strict-radii',
  spacing: null,
}

const SYSTEM_STYLE_OBJECT_BASENAME = 'system-style-object.d.ts'

const OWNED_BASE_BODY = [
  'type CssProperties = {',
  '  [K in keyof Properties]?: StylePropValue<NonNullable<Properties[K]>>;',
  '};',
  '',
  'type CanonAliasMap = {',
  "  m: 'margin';",
  "  mt: 'marginTop';",
  "  mb: 'marginBottom';",
  "  ml: 'marginLeft';",
  "  mr: 'marginRight';",
  "  mx: 'marginInline';",
  "  my: 'marginBlock';",
  "  p: 'padding';",
  "  pt: 'paddingTop';",
  "  pb: 'paddingBottom';",
  "  pl: 'paddingLeft';",
  "  pr: 'paddingRight';",
  "  px: 'paddingInline';",
  "  py: 'paddingBlock';",
  "  w: 'width';",
  "  h: 'height';",
  "  minW: 'minWidth';",
  "  minH: 'minHeight';",
  "  maxW: 'maxWidth';",
  "  maxH: 'maxHeight';",
  "  bg: 'background';",
  "  flexDir: 'flexDirection';",
  '};',
  '',
  'type CanonAliasOverlay = {',
  '  [K in keyof CanonAliasMap]?: StylePropValue<',
  "    NonNullable<Properties[CanonAliasMap[K]]>",
  '  >;',
  '};',
  '',
  'export interface BaseSystemStyleObject extends CssProperties, CanonAliasOverlay {}',
].join('\n')

const NESTED_KEYS = [
  ' & {',
  '  [K in StyleConditionKey]?: SystemStyleObject;',
  '} & {',
  '  [K in `&${string}`]?: SystemStyleObject;',
  '};',
].join('\n')

function getSystemStyleObjectDtsPath(typesPath: string): string {
  return join(dirname(typesPath), 'types', 'public', SYSTEM_STYLE_OBJECT_BASENAME)
}

function selectActiveCategories(strict: readonly StrictTokenCategory[]): StrictTokenCategory[] {
  const seen = new Set<StrictTokenCategory>()
  const result: StrictTokenCategory[] = []

  for (const category of strict) {
    if (seen.has(category)) continue
    if (STRICT_WRAPPER_BY_CATEGORY[category] == null) continue
    seen.add(category)
    result.push(category)
  }

  return result
}

export function renderSystemStyleObjectDts(
  strict: readonly StrictTokenCategory[]
): string {
  const active = selectActiveCategories(strict)

  const importLines = [
    "import type { Properties } from '../../../styled/types/csstype';",
    "import type { StyleConditionKey } from './conditions';",
    "import type { StylePropValue } from './style-prop';",
  ]

  for (const category of active) {
    const wrapper = STRICT_WRAPPER_BY_CATEGORY[category]
    const source = SOURCE_MODULE_BY_CATEGORY[category]

    if (!wrapper || !source) continue

    importLines.push(`import type { ${wrapper} } from '${source}';`)
  }

  const wrapped = active.reduce<string>((acc, category) => {
    const wrapper = STRICT_WRAPPER_BY_CATEGORY[category]
    return wrapper ? `${wrapper}<${acc}>` : acc
  }, 'BaseSystemStyleObject')

  return [
    '/** Generated by reference-core — do not edit manually. */',
    ...importLines,
    '/**',
    ' * Reference UI authored style object, with the strict-token wrappers from',
    ` * ui.config.ts applied (${active.length === 0 ? 'none' : active.join(', ')}).`,
    ' */',
    OWNED_BASE_BODY,
    '/**',
    ' * Wrap the property map, then intersect nested keys. Wrapping the',
    ' * recursive alias is TS2456.',
    ' */',
    `export type SystemStyleObject = ${wrapped}${NESTED_KEYS}`,
    '',
  ].join('\n')
}

export function writeStrictSystemStyleObject(typesPath: string): void {
  const dtsPath = getSystemStyleObjectDtsPath(typesPath)
  const config = getConfig()
  const strict = config?.strict ?? []
  const next = renderSystemStyleObjectDts(strict)

  let current: string | undefined
  try {
    current = readFileSync(dtsPath, 'utf-8')
  } catch {
    current = undefined
  }

  if (current === next) return

  writeFileAtomic(dtsPath, next, 'utf-8')
}
