/**
 * Strict-token system-style-object codegen.
 *
 * Renders the canonical `system-style-object.d.ts` for a generated package
 * based on the consumer's `ui.config.ts` `strict` array. The packager calls
 * `writeStrictSystemStyleObject(typesPath)` after `tsgo` emits, but the file
 * content is computed deterministically from config — this generator does NOT
 * read or pattern-match the emitted output to decide what to write.
 */
import { readFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { writeFileAtomic } from '../../lib/fs/write-file-atomic'
import { getConfig } from '../../config/store'
import type { StrictTokenCategory } from '../../config/types'

const STRICT_WRAPPER_BY_CATEGORY: Record<StrictTokenCategory, string | null> = {
  colors: 'StrictColorProps',
  radii: 'StrictRadiiProps',
  spacing: null,
}

const SOURCE_MODULE_BY_CATEGORY: Record<StrictTokenCategory, string | null> = {
  colors: './strict-colors',
  radii: './strict-radii',
  spacing: null,
}

const SYSTEM_STYLE_OBJECT_BASENAME = 'system-style-object.d.ts'

function getSystemStyleObjectDtsPath(typesPath: string): string {
  return join(dirname(typesPath), 'types', 'public', SYSTEM_STYLE_OBJECT_BASENAME)
}

function selectActiveCategories(strict: readonly StrictTokenCategory[]): StrictTokenCategory[] {
  const seen = new Set<StrictTokenCategory>()
  const result: StrictTokenCategory[] = []

  for (const category of strict) {
    if (seen.has(category)) continue
    if (STRICT_WRAPPER_BY_CATEGORY[category] == null) continue
    seen.add(category)
    result.push(category)
  }

  return result
}

export function renderSystemStyleObjectDts(
  strict: readonly StrictTokenCategory[]
): string {
  const active = selectActiveCategories(strict)

  const importLines = [
    "import type { SystemStyleObject as StyledSystemStyleObject } from '@reference-ui/styled/types';",
  ]

  for (const category of active) {
    const wrapper = STRICT_WRAPPER_BY_CATEGORY[category]
    const source = SOURCE_MODULE_BY_CATEGORY[category]

    if (!wrapper || !source) continue

    importLines.push(`import type { ${wrapper} } from '${source}';`)
  }

  const wrapped = active.reduce<string>((acc, category) => {
    const wrapper = STRICT_WRAPPER_BY_CATEGORY[category]
    return wrapper ? `${wrapper}<${acc}>` : acc
  }, 'StyledSystemStyleObject')

  return [
    '/** Generated by reference-core — do not edit manually. */',
    ...importLines,
    '/**',
    ' * Reference UI authored style object, with the strict-token wrappers from',
    ` * ui.config.ts applied (${active.length === 0 ? 'none' : active.join(', ')}).`,
    ' */',
    `export type SystemStyleObject = ${wrapped};`,
    '',
  ].join('\n')
}

export function writeStrictSystemStyleObject(typesPath: string): void {
  const dtsPath = getSystemStyleObjectDtsPath(typesPath)
  const config = getConfig()
  const strict = config?.strict ?? []
  const next = renderSystemStyleObjectDts(strict)

  let current: string | undefined
  try {
    current = readFileSync(dtsPath, 'utf-8')
  } catch {
    current = undefined
  }

  if (current === next) return

  writeFileAtomic(dtsPath, next, 'utf-8')
}
