import { existsSync, mkdirSync, readdirSync, rmSync, writeFileSync } from 'node:fs'
import { join, resolve } from 'node:path'
import { microBundlePanda } from '../../lib/microBundle'
import { scanDirectories } from '../../eval/scanner'
import { buildPandaEntryContent } from './entryTemplate'

/**
 * Mini-compiler: Bundle files that call extendPandaConfig into panda.config.ts.
 *
 * Uses esbuild to bundle all config files, properly inlining functions and their closures.
 * This handles TypeScript properly and inlines all dependencies.
 *
 * @param coreDir - Package root (reference-core)
 */
export async function createPandaConfig(coreDir: string): Promise<void> {
  try {
    const refDir = join(coreDir, '.ref')
    if (!existsSync(refDir)) {
      mkdirSync(refDir, { recursive: true })
    }

    // Step 1: Find all files that need to be bundled
    console.log('[createPandaConfig] Scanning for config files...')
    const basePath = resolve(coreDir, 'panda.base.ts')
    const styledDir = resolve(coreDir, 'src/styled')
    const scannedPaths = scanDirectories([styledDir])
    const configFiles = [basePath, ...scannedPaths].filter(p => existsSync(p))
    console.log(`[createPandaConfig] Found ${configFiles.length} config files`)

    // Step 2: Create entry file from template
    const entryPath = join(refDir, 'panda-entry.ts')
    const initCollectorPath = resolve(coreDir, 'src/cli/panda/config/initCollector.ts')
    const extendPandaPath = resolve(coreDir, 'src/cli/panda/config/extendPandaConfig.ts')
    const deepMergePath = resolve(coreDir, 'src/cli/panda/config/deepMerge.ts')

    const entryContent = buildPandaEntryContent({
      refDir,
      initCollectorPath,
      extendPandaConfigPath: extendPandaPath,
      deepMergePath,
      configFilePaths: configFiles
    })
    writeFileSync(entryPath, entryContent)
    console.log('[createPandaConfig] Created entry file')

    // Step 3: Bundle with esbuild (reusable helper, in-memory output)
    console.log('[createPandaConfig] Bundling with esbuild...')
    const bundled = await microBundlePanda(entryPath)
    console.log('[createPandaConfig] Bundle complete')

    // Step 4: Write final panda.config.ts
    const configPath = resolve(coreDir, 'panda.config.ts')
    const finalConfig = `/** Generated by createPandaConfig - do not edit manually */
              ${bundled}
`
    writeFileSync(configPath, finalConfig)
    console.log(`[createPandaConfig] Wrote final config to ${configPath}`)

    // Clean up temp files in .ref
    const refFiles = readdirSync(refDir)
    for (const file of refFiles) {
      rmSync(join(refDir, file), { force: true, recursive: true })
    }
  } catch (error) {
    console.error('[createPandaConfig] ERROR:', error)
    throw error
  }
}
