/** Generated by createFontSystem - do not edit manually */

import { extendTokens, extendGlobalFontface, extendRecipe, extendPattern } from '../api'

extendTokens({
  fonts: {
    sans: { value: "\"Inter\", ui-sans-serif, sans-serif" },
    serif: { value: "\"Literata\", ui-serif, serif" },
    mono: { value: "\"JetBrains Mono\", ui-monospace, monospace" },
  },
  fontWeights: {
    'sans.thin': { value: '200' },
    'sans.light': { value: '300' },
    'sans.normal': { value: '400' },
    'sans.semibold': { value: '600' },
    'sans.bold': { value: '700' },
    'sans.black': { value: '900' },
    'serif.thin': { value: '100' },
    'serif.light': { value: '300' },
    'serif.normal': { value: '373' },
    'serif.semibold': { value: '600' },
    'serif.bold': { value: '700' },
    'serif.black': { value: '900' },
    'mono.thin': { value: '100' },
    'mono.light': { value: '300' },
    'mono.normal': { value: '393' },
    'mono.semibold': { value: '600' },
    'mono.bold': { value: '700' },
  },
})

extendGlobalFontface({
  Inter: {
    src: 'url(https://fonts.gstatic.com/s/inter/v20/UcC73FwrK3iLTeHuS_nVMrMxCp50SjIa1ZL7W0Q5nw.woff2) format("woff2")',
    fontDisplay: 'swap',
    fontWeight: '100 900',
    fontStyle: 'normal',
  },
  Literata: {
    src: 'url(https://fonts.gstatic.com/s/literata/v40/or38Q6P12-iJxAIgLa78DkrbXsDgk0oVDaDlbJ5W7i5aOg.woff2) format("woff2")',
    fontDisplay: 'swap',
    fontWeight: '200 900',
    fontStyle: 'normal',
    sizeAdjust: '104%',
    descentOverride: '47%',
  },
  '"JetBrains Mono"': {
    src: 'url(https://fonts.gstatic.com/s/jetbrainsmono/v24/tDbV2o-flEEny0FZhsfKu5WU4xD7OwGtT0rU.woff2) format("woff2")',
    fontDisplay: 'swap',
    fontWeight: '100 800',
    fontStyle: 'normal',
    sizeAdjust: '101%',
  },
})

extendRecipe({
  fontStyle: {
    className: 'r_font',
    variants: {
      font: {
        sans: {
          fontFamily: 'sans',
          letterSpacing: '-0.01em',
          fontWeight: 'normal',
        },
        serif: {
          fontFamily: 'serif',
          letterSpacing: 'normal',
          fontWeight: 'normal',
        },
        mono: {
          fontFamily: 'mono',
          letterSpacing: '-0.04em',
          fontWeight: 'normal',
        },
      },
    },
  },
})

extendPattern({
  properties: {
    font: { type: 'string' as const },
    weight: { type: 'string' as const },
  },
  transform(props: Record<string, any>) {
    const { font, weight } = props

    const FONT_PRESETS: Record<string, Record<string, string>> = {
      sans: { fontFamily: 'sans', fontWeight: 'normal', letterSpacing: '-0.01em' },
      serif: { fontFamily: 'serif', fontWeight: 'normal', letterSpacing: 'normal' },
      mono: { fontFamily: 'mono', fontWeight: 'normal', letterSpacing: '-0.04em' },
    }

    const WEIGHT_TOKENS: Record<string, string> = {
      'sans.thin': '200',
      'sans.light': '300',
      'sans.normal': '400',
      'sans.semibold': '600',
      'sans.bold': '700',
      'sans.black': '900',
      'serif.thin': '100',
      'serif.light': '300',
      'serif.normal': '373',
      'serif.semibold': '600',
      'serif.bold': '700',
      'serif.black': '900',
      'mono.thin': '100',
      'mono.light': '300',
      'mono.normal': '393',
      'mono.semibold': '600',
      'mono.bold': '700',
    }

    const result: Record<string, any> = {}

    if (font && FONT_PRESETS[font]) {
      Object.assign(result, FONT_PRESETS[font])
    }

    if (weight && WEIGHT_TOKENS[weight]) {
      result.fontWeight = WEIGHT_TOKENS[weight]
    }

    return result
  },
})
