import { mkdtempSync, mkdirSync, rmSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { afterEach, describe, expect, it } from 'vitest'
import { createPrimitiveSource } from './generate'

const createdDirs: string[] = []

function createTempDir(): string {
  const dir = mkdtempSync(join(tmpdir(), 'reference-ui-primitives-generate-'))
  createdDirs.push(dir)
  return dir
}

function writeTagsFile(cliRoot: string, content: string): void {
  const tagsPath = join(cliRoot, 'src/system/primitives/tags.ts')
  const dir = join(cliRoot, 'src/system/primitives')
  mkdirSync(dir, { recursive: true })
  writeFileSync(tagsPath, content, 'utf-8')
}

afterEach(() => {
  for (const dir of createdDirs.splice(0)) {
    rmSync(dir, { recursive: true, force: true })
  }
})

describe('system/primitives/generate', () => {
  it('throws when tags.ts has no opening bracket', async () => {
    const cliRoot = createTempDir()
    writeTagsFile(cliRoot, "export const TAGS = 'div' as const")

    await expect(createPrimitiveSource(cliRoot)).rejects.toThrow(
      'Could not parse TAGS from system/primitives/tags.ts',
    )
  })

  it('throws when tags.ts has no "] as const"', async () => {
    const cliRoot = createTempDir()
    writeTagsFile(cliRoot, "export const TAGS = ['div']")

    await expect(createPrimitiveSource(cliRoot)).rejects.toThrow(
      'Could not parse TAGS from system/primitives/tags.ts',
    )
  })

  it('emits banner, imports from shared, and forwardRef primitive wrappers', async () => {
    const cliRoot = createTempDir()
    writeTagsFile(cliRoot, "export const TAGS = ['div', 'span'] as const")

    const out = await createPrimitiveSource(cliRoot)

    expect(out).toContain('Generated by `tsx src/system/primitives/generate/index.ts`')
    expect(out).toContain("import { css } from '../runtime'")
    expect(out).toContain("import { box } from '@reference-ui/styled/patterns/box'")
    expect(out).toContain("import {")
    expect(out).toContain("  splitPrimitiveProps,")
    expect(out).toContain("  usePrimitiveContext,")
    expect(out).toContain("} from './shared'")
    expect(out).toContain("export const Div: Components.DivComponent = React.forwardRef<")
    expect(out).toContain("PrimitiveElement<'div'>")
    expect(out).toContain("PrimitiveProps<'div'>")
    expect(out).toContain("export const Span: Components.SpanComponent = React.forwardRef<")
    expect(out).toContain("PrimitiveElement<'span'>")
    expect(out).toContain("PrimitiveProps<'span'>")
    expect(out).toContain("primitiveClass = 'ref-div'")
    expect(out).toContain("primitiveClass = 'ref-span'")
    expect(out).toContain("export type DivProps = PrimitiveProps<'div'>")
    expect(out).toContain("export type SpanProps = PrimitiveProps<'span'>")
    expect(out).toContain("Div.displayName = 'Div'")
    expect(out).toContain("Span.displayName = 'Span'")
  })

  it('maps object -> Obj, var -> Var, single-letter a -> A', async () => {
    const cliRoot = createTempDir()
    writeTagsFile(cliRoot, "export const TAGS = ['a', 'object', 'var'] as const")

    const out = await createPrimitiveSource(cliRoot)

    expect(out).toContain("export const A: Components.AComponent = React.forwardRef<")
    expect(out).toContain("export const Obj: Components.ObjComponent = React.forwardRef<")
    expect(out).toContain("export const Var: Components.VarComponent = React.forwardRef<")
    expect(out).toContain("'ref-a'")
    expect(out).toContain("'ref-object'")
    expect(out).toContain("'ref-var'")
    expect(out).toContain("export type AProps = PrimitiveProps<'a'>")
    expect(out).toContain("export type ObjProps = PrimitiveProps<'object'>")
    expect(out).toContain("export type VarProps = PrimitiveProps<'var'>")
  })
})
