//! Reference UI conditions, pseudo-selectors, and default responsive breakpoints.
//!
//! Generated by `packages/reference-rs/canon/generate.ts`.
//! Defines discriminator keys for pseudo-classes, responsive breakpoints, and media queries.
// @generated

/// Canonical ordered list of default responsive breakpoints.
pub const DEFAULT_BREAKPOINTS: &[&str] = &[
    "base", "sm", "md", "lg", "xl", "2xl",
];

/// Sorted list of recognized condition keys.
pub const CONDITIONS: &[&str] = &[
    "2xl", "_active", "_after", "_anyPointerCoarse",
    "_anyPointerFine", "_anyPointerNone", "_atValue", "_autofill",
    "_backdrop", "_before", "_checked", "_closed",
    "_complete", "_current", "_currentPage", "_currentStep",
    "_dark", "_default", "_disabled", "_dragging",
    "_empty", "_enabled", "_even", "_expanded",
    "_file", "_first", "_firstLetter", "_firstLine",
    "_firstOfType", "_focus", "_focusVisible", "_focusWithin",
    "_fullscreen", "_grabbed", "_groupActive", "_groupChecked",
    "_groupDisabled", "_groupExpanded", "_groupFocus", "_groupFocusVisible",
    "_groupFocusWithin", "_groupHover", "_groupInvalid", "_hidden",
    "_highContrast", "_highlighted", "_horizontal", "_hover",
    "_icon", "_inRange", "_incomplete", "_indeterminate",
    "_inert", "_invalid", "_invertedColors", "_landscape",
    "_last", "_lastOfType", "_lessContrast", "_light",
    "_loading", "_ltr", "_marker", "_moreContrast",
    "_motionReduce", "_motionSafe", "_noscript", "_now",
    "_odd", "_only", "_onlyOfType", "_open",
    "_optional", "_osDark", "_osLight", "_outOfRange",
    "_overValue", "_peerActive", "_peerChecked", "_peerDisabled",
    "_peerExpanded", "_peerFocus", "_peerFocusVisible", "_peerFocusWithin",
    "_peerHover", "_peerInvalid", "_peerPlaceholderShown", "_placeholder",
    "_placeholderShown", "_pointerCoarse", "_pointerFine", "_pointerNone",
    "_portrait", "_pressed", "_print", "_rangeEnd",
    "_rangeStart", "_readOnly", "_readWrite", "_required",
    "_rtl", "_scrollbar", "_scrollbarThumb", "_scrollbarTrack",
    "_selected", "_selection", "_starting", "_target",
    "_today", "_topmost", "_unavailable", "_underValue",
    "_userInvalid", "_userValid", "_valid", "_vertical",
    "_visited", "base", "lg", "md",
    "sm", "xl",
];

/// Returns true if the given key represents a condition, pseudo selector, or breakpoint.
pub fn is_condition(name: &str) -> bool {
    if name.starts_with('_') || name.starts_with('&') || name.starts_with('@') {
        return true;
    }
    CONDITIONS.binary_search(&name).is_ok()
}

/// Returns the default responsive breakpoint name for an array index.
pub fn default_breakpoint_for_index(idx: usize) -> Option<&'static str> {
    DEFAULT_BREAKPOINTS.get(idx).copied()
}
