//! Canonical CSS properties, native shorthand longhands, and utility class prefixes.
//!
//! Generated by `packages/reference-rs/canon/generate.ts`.
//! Bridges W3C/WHATWG CSS property definitions with Reference UI class prefixes.
// @generated

/// Canonical property specification in the compiler canon.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Property {
    pub name: &'static str,
    pub css: &'static str,
    pub class_prefix: &'static str,
    pub longhands: &'static [&'static str],
}

impl Property {
    pub const fn new(
        name: &'static str,
        css: &'static str,
        class_prefix: &'static str,
        longhands: &'static [&'static str],
    ) -> Self {
        Self {
            name,
            css,
            class_prefix,
            longhands,
        }
    }
}

// Native shorthand longhand slices
static BORDER_LONGHANDS: &[&str] = &["borderWidth", "borderStyle", "borderColor"];
static BORDERBLOCK_LONGHANDS: &[&str] = &["borderBlockWidth", "borderBlockStyle", "borderBlockColor"];
static BORDERBOTTOM_LONGHANDS: &[&str] = &["borderBottomWidth", "borderBottomStyle", "borderBottomColor"];
static BORDERINLINE_LONGHANDS: &[&str] = &["borderInlineWidth", "borderInlineStyle", "borderInlineColor"];
static BORDERLEFT_LONGHANDS: &[&str] = &["borderLeftWidth", "borderLeftStyle", "borderLeftColor"];
static BORDERRIGHT_LONGHANDS: &[&str] = &["borderRightWidth", "borderRightStyle", "borderRightColor"];
static BORDERTOP_LONGHANDS: &[&str] = &["borderTopWidth", "borderTopStyle", "borderTopColor"];
static INSET_LONGHANDS: &[&str] = &["top", "right", "bottom", "left"];
static MARGIN_LONGHANDS: &[&str] = &["marginTop", "marginRight", "marginBottom", "marginLeft"];
static OUTLINE_LONGHANDS: &[&str] = &["outlineWidth", "outlineStyle", "outlineColor"];
static PADDING_LONGHANDS: &[&str] = &["paddingTop", "paddingRight", "paddingBottom", "paddingLeft"];

/// All canonical CSS and system properties sorted by camelCase property name.
pub const CANONICAL_PROPERTIES: &[Property] = &[
    Property::new("accentColor", "accent-color", "accent-c", &[]), Property::new("alignContent", "align-content", "ac", &[]),
    Property::new("alignItems", "align-items", "ai", &[]), Property::new("alignSelf", "align-self", "as", &[]),
    Property::new("animation", "animation", "anim", &[]), Property::new("animationComposition", "animation-composition", "anim-comp", &[]),
    Property::new("animationDelay", "animation-delay", "anim-dly", &[]), Property::new("animationDirection", "animation-direction", "anim-dir", &[]),
    Property::new("animationDuration", "animation-duration", "anim-dur", &[]), Property::new("animationFillMode", "animation-fill-mode", "anim-fm", &[]),
    Property::new("animationIterationCount", "animation-iteration-count", "anim-ic", &[]), Property::new("animationName", "animation-name", "anim-n", &[]),
    Property::new("animationPlayState", "animation-play-state", "anim-ps", &[]), Property::new("animationRange", "animation-range", "anim-r", &[]),
    Property::new("animationRangeEnd", "animation-range-end", "anim-re", &[]), Property::new("animationRangeStart", "animation-range-start", "anim-rs", &[]),
    Property::new("animationState", "animation-state", "anim-s", &[]), Property::new("animationTimeline", "animation-timeline", "anim-tl", &[]),
    Property::new("animationTimingFunction", "animation-timing-function", "anim-tmf", &[]), Property::new("appearance", "appearance", "ap", &[]),
    Property::new("aspectRatio", "aspect-ratio", "asp", &[]), Property::new("backdropBlur", "backdrop-blur", "bkdp-blur", &[]),
    Property::new("backdropBrightness", "backdrop-brightness", "bkdp-brightness", &[]), Property::new("backdropContrast", "backdrop-contrast", "bkdp-contrast", &[]),
    Property::new("backdropFilter", "backdrop-filter", "bkdp", &[]), Property::new("backdropGrayscale", "backdrop-grayscale", "bkdp-grayscale", &[]),
    Property::new("backdropHueRotate", "backdrop-hue-rotate", "bkdp-hue-rotate", &[]), Property::new("backdropInvert", "backdrop-invert", "bkdp-invert", &[]),
    Property::new("backdropOpacity", "backdrop-opacity", "bkdp-opacity", &[]), Property::new("backdropSaturate", "backdrop-saturate", "bkdp-saturate", &[]),
    Property::new("backdropSepia", "backdrop-sepia", "bkdp-sepia", &[]), Property::new("backfaceVisibility", "backface-visibility", "bfv", &[]),
    Property::new("background", "background", "bg", &[]), Property::new("backgroundAttachment", "background-attachment", "bg-a", &[]),
    Property::new("backgroundBlendMode", "background-blend-mode", "bg-bm", &[]), Property::new("backgroundClip", "background-clip", "bg-cp", &[]),
    Property::new("backgroundColor", "background-color", "bg-c", &[]), Property::new("backgroundConic", "background-conic", "bg-conic", &[]),
    Property::new("backgroundGradient", "background-gradient", "bg-grad", &[]), Property::new("backgroundImage", "background-image", "bg-i", &[]),
    Property::new("backgroundLinear", "background-linear", "bg-linear", &[]), Property::new("backgroundOrigin", "background-origin", "bg-o", &[]),
    Property::new("backgroundPosition", "background-position", "bg-p", &[]), Property::new("backgroundPositionX", "background-position-x", "bg-p-x", &[]),
    Property::new("backgroundPositionY", "background-position-y", "bg-p-y", &[]), Property::new("backgroundRadial", "background-radial", "bg-radial", &[]),
    Property::new("backgroundRepeat", "background-repeat", "bg-r", &[]), Property::new("backgroundSize", "background-size", "bg-s", &[]),
    Property::new("blockSize", "block-size", "h-bs", &[]), Property::new("blur", "blur", "blur", &[]),
    Property::new("border", "border", "bd", BORDER_LONGHANDS), Property::new("borderBlock", "border-block", "bd-y", BORDERBLOCK_LONGHANDS),
    Property::new("borderBlockColor", "border-block-color", "bd-y-c", &[]), Property::new("borderBlockEnd", "border-block-end", "bd-be", &[]),
    Property::new("borderBlockEndColor", "border-block-end-color", "bd-be-c", &[]), Property::new("borderBlockEndStyle", "border-block-end-style", "bd-be-s", &[]),
    Property::new("borderBlockEndWidth", "border-block-end-width", "bd-be-w", &[]), Property::new("borderBlockStart", "border-block-start", "bd-bs", &[]),
    Property::new("borderBlockStartColor", "border-block-start-color", "bd-bs-c", &[]), Property::new("borderBlockStartStyle", "border-block-start-style", "bd-bs-s", &[]),
    Property::new("borderBlockStartWidth", "border-block-start-width", "bd-bs-w", &[]), Property::new("borderBlockStyle", "border-block-style", "bd-y-s", &[]),
    Property::new("borderBlockWidth", "border-block-width", "bd-y-w", &[]), Property::new("borderBottom", "border-bottom", "bd-b", BORDERBOTTOM_LONGHANDS),
    Property::new("borderBottomColor", "border-bottom-color", "bd-b-c", &[]), Property::new("borderBottomLeftRadius", "border-bottom-left-radius", "bdr-bl", &[]),
    Property::new("borderBottomRadius", "border-bottom-radius", "bdr-b", &[]), Property::new("borderBottomRightRadius", "border-bottom-right-radius", "bdr-br", &[]),
    Property::new("borderBottomStyle", "border-bottom-style", "bd-b-s", &[]), Property::new("borderBottomWidth", "border-bottom-width", "bd-b-w", &[]),
    Property::new("borderCollapse", "border-collapse", "bd-cl", &[]), Property::new("borderColor", "border-color", "bd-c", &[]),
    Property::new("borderEndEndRadius", "border-end-end-radius", "bdr-ee", &[]), Property::new("borderEndRadius", "border-end-radius", "bdr-e", &[]),
    Property::new("borderEndStartRadius", "border-end-start-radius", "bdr-es", &[]), Property::new("borderInline", "border-inline", "bd-x", BORDERINLINE_LONGHANDS),
    Property::new("borderInlineColor", "border-inline-color", "bd-x-c", &[]), Property::new("borderInlineEnd", "border-inline-end", "bd-e", &[]),
    Property::new("borderInlineEndColor", "border-inline-end-color", "bd-e-c", &[]), Property::new("borderInlineEndStyle", "border-inline-end-style", "bd-e-s", &[]),
    Property::new("borderInlineEndWidth", "border-inline-end-width", "bd-e-w", &[]), Property::new("borderInlineStart", "border-inline-start", "bd-s", &[]),
    Property::new("borderInlineStartColor", "border-inline-start-color", "bd-s-c", &[]), Property::new("borderInlineStartStyle", "border-inline-start-style", "bd-s-s", &[]),
    Property::new("borderInlineStartWidth", "border-inline-start-width", "bd-s-w", &[]), Property::new("borderInlineStyle", "border-inline-style", "bd-x-s", &[]),
    Property::new("borderInlineWidth", "border-inline-width", "bd-x-w", &[]), Property::new("borderLeft", "border-left", "bd-l", BORDERLEFT_LONGHANDS),
    Property::new("borderLeftColor", "border-left-color", "bd-l-c", &[]), Property::new("borderLeftRadius", "border-left-radius", "bdr-l", &[]),
    Property::new("borderLeftStyle", "border-left-style", "bd-l-s", &[]), Property::new("borderLeftWidth", "border-left-width", "bd-l-w", &[]),
    Property::new("borderRadius", "border-radius", "bdr", &[]), Property::new("borderRight", "border-right", "bd-r", BORDERRIGHT_LONGHANDS),
    Property::new("borderRightColor", "border-right-color", "bd-r-c", &[]), Property::new("borderRightRadius", "border-right-radius", "bdr-r", &[]),
    Property::new("borderRightStyle", "border-right-style", "bd-r-s", &[]), Property::new("borderRightWidth", "border-right-width", "bd-r-w", &[]),
    Property::new("borderSpacing", "border-spacing", "bd-sp", &[]), Property::new("borderSpacingX", "border-spacing-x", "bd-sx", &[]),
    Property::new("borderSpacingY", "border-spacing-y", "bd-sy", &[]), Property::new("borderStartEndRadius", "border-start-end-radius", "bdr-se", &[]),
    Property::new("borderStartRadius", "border-start-radius", "bdr-s", &[]), Property::new("borderStartStartRadius", "border-start-start-radius", "bdr-ss", &[]),
    Property::new("borderStyle", "border-style", "border-style", &[]), Property::new("borderTop", "border-top", "bd-t", BORDERTOP_LONGHANDS),
    Property::new("borderTopColor", "border-top-color", "bd-t-c", &[]), Property::new("borderTopLeftRadius", "border-top-left-radius", "bdr-tl", &[]),
    Property::new("borderTopRadius", "border-top-radius", "bdr-t", &[]), Property::new("borderTopRightRadius", "border-top-right-radius", "bdr-tr", &[]),
    Property::new("borderTopStyle", "border-top-style", "bd-t-s", &[]), Property::new("borderTopWidth", "border-top-width", "bd-t-w", &[]),
    Property::new("borderWidth", "border-width", "bd-w", &[]), Property::new("bottom", "bottom", "bottom", &[]),
    Property::new("boxDecorationBreak", "box-decoration-break", "bx-db", &[]), Property::new("boxShadow", "box-shadow", "bx-sh", &[]),
    Property::new("boxShadowColor", "box-shadow-color", "bx-sh-c", &[]), Property::new("boxSize", "box-size", "size", &[]),
    Property::new("boxSizing", "box-sizing", "bx-s", &[]), Property::new("brightness", "brightness", "brightness", &[]),
    Property::new("caretColor", "caret-color", "caret-c", &[]), Property::new("clipPath", "clip-path", "cp-path", &[]),
    Property::new("color", "color", "c", &[]), Property::new("columnGap", "column-gap", "cg", &[]),
    Property::new("container", "container", "cq", &[]), Property::new("containerName", "container-name", "cq-n", &[]),
    Property::new("containerType", "container-type", "cq-t", &[]), Property::new("contrast", "contrast", "contrast", &[]),
    Property::new("cursor", "cursor", "cursor", &[]), Property::new("debug", "debug", "debug", &[]),
    Property::new("display", "display", "d", &[]), Property::new("divideColor", "divide-color", "divide-c", &[]),
    Property::new("divideStyle", "divide-style", "dvd-s", &[]), Property::new("divideX", "divide-x", "dvd-x", &[]),
    Property::new("divideY", "divide-y", "dvd-y", &[]), Property::new("dropShadow", "drop-shadow", "drop-shadow", &[]),
    Property::new("fill", "fill", "fill", &[]), Property::new("filter", "filter", "filter", &[]),
    Property::new("flex", "flex", "flex", &[]), Property::new("flexBasis", "flex-basis", "flex-b", &[]),
    Property::new("flexDirection", "flex-direction", "flex-d", &[]), Property::new("flexGrow", "flex-grow", "flex-g", &[]),
    Property::new("flexShrink", "flex-shrink", "flex-sh", &[]), Property::new("float", "float", "float", &[]),
    Property::new("focusRing", "focus-ring", "focus-ring", &[]), Property::new("focusRingColor", "focus-ring-color", "focus-ring-c", &[]),
    Property::new("focusRingOffset", "focus-ring-offset", "focus-ring-o", &[]), Property::new("focusRingStyle", "focus-ring-style", "focus-ring-s", &[]),
    Property::new("focusRingWidth", "focus-ring-width", "focus-ring-w", &[]), Property::new("focusVisibleRing", "focus-visible-ring", "focus-v-ring", &[]),
    Property::new("fontFamily", "font-family", "ff", &[]), Property::new("fontFeatureSettings", "font-feature-settings", "ff-s", &[]),
    Property::new("fontKerning", "font-kerning", "fk", &[]), Property::new("fontPalette", "font-palette", "fp", &[]),
    Property::new("fontSize", "font-size", "fs", &[]), Property::new("fontSizeAdjust", "font-size-adjust", "fs-a", &[]),
    Property::new("fontSmoothing", "font-smoothing", "fsmt", &[]), Property::new("fontVariant", "font-variant", "fv", &[]),
    Property::new("fontVariantAlternates", "font-variant-alternates", "fv-alt", &[]), Property::new("fontVariantCaps", "font-variant-caps", "fv-caps", &[]),
    Property::new("fontVariantNumeric", "font-variant-numeric", "fv-num", &[]), Property::new("fontVariationSettings", "font-variation-settings", "fv-s", &[]),
    Property::new("fontWeight", "font-weight", "fw", &[]), Property::new("gap", "gap", "gap", &[]),
    Property::new("gradientFrom", "gradient-from", "grad-from", &[]), Property::new("gradientFromPosition", "gradient-from-position", "grad-from-pos", &[]),
    Property::new("gradientTo", "gradient-to", "grad-to", &[]), Property::new("gradientToPosition", "gradient-to-position", "grad-to-pos", &[]),
    Property::new("gradientVia", "gradient-via", "grad-via", &[]), Property::new("gradientViaPosition", "gradient-via-position", "grad-via-pos", &[]),
    Property::new("grayscale", "grayscale", "grayscale", &[]), Property::new("gridAutoColumns", "grid-auto-columns", "grid-ac", &[]),
    Property::new("gridAutoFlow", "grid-auto-flow", "grid-af", &[]), Property::new("gridAutoRows", "grid-auto-rows", "grid-ar", &[]),
    Property::new("gridColumn", "grid-column", "grid-c", &[]), Property::new("gridColumnEnd", "grid-column-end", "grid-ce", &[]),
    Property::new("gridColumnGap", "grid-column-gap", "grid-cg", &[]), Property::new("gridColumnStart", "grid-column-start", "grid-cs", &[]),
    Property::new("gridGap", "grid-gap", "grid-g", &[]), Property::new("gridRow", "grid-row", "grid-r", &[]),
    Property::new("gridRowGap", "grid-row-gap", "grid-rg", &[]), Property::new("gridTemplateColumns", "grid-template-columns", "grid-tc", &[]),
    Property::new("gridTemplateRows", "grid-template-rows", "grid-tr", &[]), Property::new("height", "height", "h", &[]),
    Property::new("hideBelow", "hide-below", "show", &[]), Property::new("hideFrom", "hide-from", "hide", &[]),
    Property::new("hueRotate", "hue-rotate", "hue-rotate", &[]), Property::new("hyphens", "hyphens", "hy", &[]),
    Property::new("inlineSize", "inline-size", "w-is", &[]), Property::new("inset", "inset", "inset", INSET_LONGHANDS),
    Property::new("insetBlock", "inset-block", "inset-y", &[]), Property::new("insetBlockEnd", "inset-block-end", "inset-be", &[]),
    Property::new("insetBlockStart", "inset-block-start", "inset-bs", &[]), Property::new("insetInline", "inset-inline", "inset-x", &[]),
    Property::new("insetInlineEnd", "inset-inline-end", "inset-e", &[]), Property::new("insetInlineStart", "inset-inline-start", "inset-s", &[]),
    Property::new("invert", "invert", "invert", &[]), Property::new("justifyContent", "justify-content", "jc", &[]),
    Property::new("left", "left", "left", &[]), Property::new("letterSpacing", "letter-spacing", "ls", &[]),
    Property::new("lineClamp", "line-clamp", "lc", &[]), Property::new("lineHeight", "line-height", "lh", &[]),
    Property::new("listStyle", "list-style", "li-s", &[]), Property::new("listStyleImage", "list-style-image", "li-img", &[]),
    Property::new("listStylePosition", "list-style-position", "li-pos", &[]), Property::new("listStyleType", "list-style-type", "li-t", &[]),
    Property::new("margin", "margin", "m", MARGIN_LONGHANDS), Property::new("marginBlock", "margin-block", "my", &[]),
    Property::new("marginBlockEnd", "margin-block-end", "mbe", &[]), Property::new("marginBlockStart", "margin-block-start", "mbs", &[]),
    Property::new("marginBottom", "margin-bottom", "mb", &[]), Property::new("marginInline", "margin-inline", "mx", &[]),
    Property::new("marginInlineEnd", "margin-inline-end", "me", &[]), Property::new("marginInlineStart", "margin-inline-start", "ms", &[]),
    Property::new("marginLeft", "margin-left", "ml", &[]), Property::new("marginRight", "margin-right", "mr", &[]),
    Property::new("marginTop", "margin-top", "mt", &[]), Property::new("mask", "mask", "msk", &[]),
    Property::new("maskImage", "mask-image", "msk-i", &[]), Property::new("maskSize", "mask-size", "msk-s", &[]),
    Property::new("maxBlockSize", "max-block-size", "max-b", &[]), Property::new("maxHeight", "max-height", "max-h", &[]),
    Property::new("maxInlineSize", "max-inline-size", "max-w-is", &[]), Property::new("maxWidth", "max-width", "max-w", &[]),
    Property::new("minBlockSize", "min-block-size", "min-h-bs", &[]), Property::new("minHeight", "min-height", "min-h", &[]),
    Property::new("minInlineSize", "min-inline-size", "min-w-is", &[]), Property::new("minWidth", "min-width", "min-w", &[]),
    Property::new("mixBlendMode", "mix-blend-mode", "mix-bm", &[]), Property::new("objectFit", "object-fit", "obj-f", &[]),
    Property::new("objectPosition", "object-position", "obj-p", &[]), Property::new("opacity", "opacity", "op", &[]),
    Property::new("outline", "outline", "ring", OUTLINE_LONGHANDS), Property::new("outlineColor", "outline-color", "ring-c", &[]),
    Property::new("outlineOffset", "outline-offset", "ring-o", &[]), Property::new("outlineStyle", "outline-style", "ring-s", &[]),
    Property::new("outlineWidth", "outline-width", "ring-w", &[]), Property::new("overflow", "overflow", "ov", &[]),
    Property::new("overflowAnchor", "overflow-anchor", "ov-a", &[]), Property::new("overflowBlock", "overflow-block", "ov-b", &[]),
    Property::new("overflowClipBox", "overflow-clip-box", "ovcp-bx", &[]), Property::new("overflowClipMargin", "overflow-clip-margin", "ovcp-m", &[]),
    Property::new("overflowInline", "overflow-inline", "ov-i", &[]), Property::new("overflowWrap", "overflow-wrap", "ov-wrap", &[]),
    Property::new("overflowX", "overflow-x", "ov-x", &[]), Property::new("overflowY", "overflow-y", "ov-y", &[]),
    Property::new("overscrollBehavior", "overscroll-behavior", "ovs-b", &[]), Property::new("overscrollBehaviorBlock", "overscroll-behavior-block", "ovs-bb", &[]),
    Property::new("overscrollBehaviorInline", "overscroll-behavior-inline", "ovs-bi", &[]), Property::new("overscrollBehaviorX", "overscroll-behavior-x", "ovs-bx", &[]),
    Property::new("overscrollBehaviorY", "overscroll-behavior-y", "ovs-by", &[]), Property::new("padding", "padding", "p", PADDING_LONGHANDS),
    Property::new("paddingBlock", "padding-block", "py", &[]), Property::new("paddingBlockEnd", "padding-block-end", "pbe", &[]),
    Property::new("paddingBlockStart", "padding-block-start", "pbs", &[]), Property::new("paddingBottom", "padding-bottom", "pb", &[]),
    Property::new("paddingInline", "padding-inline", "px", &[]), Property::new("paddingInlineEnd", "padding-inline-end", "pe", &[]),
    Property::new("paddingInlineStart", "padding-inline-start", "ps", &[]), Property::new("paddingLeft", "padding-left", "pl", &[]),
    Property::new("paddingRight", "padding-right", "pr", &[]), Property::new("paddingTop", "padding-top", "pt", &[]),
    Property::new("position", "position", "pos", &[]), Property::new("right", "right", "right", &[]),
    Property::new("rotate", "rotate", "rotate", &[]), Property::new("rotateX", "rotate-x", "rotate-x", &[]),
    Property::new("rotateY", "rotate-y", "rotate-y", &[]), Property::new("rotateZ", "rotate-z", "rotate-z", &[]),
    Property::new("rowGap", "row-gap", "rg", &[]), Property::new("saturate", "saturate", "saturate", &[]),
    Property::new("scale", "scale", "scale", &[]), Property::new("scaleX", "scale-x", "scale-x", &[]),
    Property::new("scaleY", "scale-y", "scale-y", &[]), Property::new("scrollbar", "scrollbar", "scr-bar", &[]),
    Property::new("scrollbarColor", "scrollbar-color", "scrollbar-c", &[]), Property::new("scrollbarGutter", "scrollbar-gutter", "scr-bar-g", &[]),
    Property::new("scrollbarWidth", "scrollbar-width", "scr-bar-w", &[]), Property::new("scrollBehavior", "scroll-behavior", "scr-bhv", &[]),
    Property::new("scrollMargin", "scroll-margin", "scr-m", &[]), Property::new("scrollMarginBlock", "scroll-margin-block", "scr-my", &[]),
    Property::new("scrollMarginBlockEnd", "scroll-margin-block-end", "scr-mbe", &[]), Property::new("scrollMarginBlockStart", "scroll-margin-block-start", "scr-mbt", &[]),
    Property::new("scrollMarginBottom", "scroll-margin-bottom", "scr-mb", &[]), Property::new("scrollMarginInline", "scroll-margin-inline", "scr-mx", &[]),
    Property::new("scrollMarginInlineEnd", "scroll-margin-inline-end", "scr-me", &[]), Property::new("scrollMarginInlineStart", "scroll-margin-inline-start", "scr-ms", &[]),
    Property::new("scrollMarginLeft", "scroll-margin-left", "scr-ml", &[]), Property::new("scrollMarginRight", "scroll-margin-right", "scr-mr", &[]),
    Property::new("scrollMarginTop", "scroll-margin-top", "scr-mt", &[]), Property::new("scrollPadding", "scroll-padding", "scr-p", &[]),
    Property::new("scrollPaddingBlock", "scroll-padding-block", "scr-py", &[]), Property::new("scrollPaddingBlockEnd", "scroll-padding-block-end", "scr-pbe", &[]),
    Property::new("scrollPaddingBlockStart", "scroll-padding-block-start", "scr-pbs", &[]), Property::new("scrollPaddingBottom", "scroll-padding-bottom", "scr-pb", &[]),
    Property::new("scrollPaddingInline", "scroll-padding-inline", "scr-px", &[]), Property::new("scrollPaddingInlineEnd", "scroll-padding-inline-end", "scr-pe", &[]),
    Property::new("scrollPaddingInlineStart", "scroll-padding-inline-start", "scr-ps", &[]), Property::new("scrollPaddingLeft", "scroll-padding-left", "scr-pl", &[]),
    Property::new("scrollPaddingRight", "scroll-padding-right", "scr-pr", &[]), Property::new("scrollPaddingTop", "scroll-padding-top", "scr-pt", &[]),
    Property::new("scrollSnapAlign", "scroll-snap-align", "scr-sa", &[]), Property::new("scrollSnapCoordinate", "scroll-snap-coordinate", "scrs-c", &[]),
    Property::new("scrollSnapDestination", "scroll-snap-destination", "scrs-d", &[]), Property::new("scrollSnapMargin", "scroll-snap-margin", "scrs-m", &[]),
    Property::new("scrollSnapMarginBottom", "scroll-snap-margin-bottom", "scrs-mb", &[]), Property::new("scrollSnapMarginLeft", "scroll-snap-margin-left", "scrs-ml", &[]),
    Property::new("scrollSnapMarginRight", "scroll-snap-margin-right", "scrs-mr", &[]), Property::new("scrollSnapMarginTop", "scroll-snap-margin-top", "scrs-mt", &[]),
    Property::new("scrollSnapPointsX", "scroll-snap-points-x", "scrs-px", &[]), Property::new("scrollSnapPointsY", "scroll-snap-points-y", "scrs-py", &[]),
    Property::new("scrollSnapStop", "scroll-snap-stop", "scrs-s", &[]), Property::new("scrollSnapStrictness", "scroll-snap-strictness", "scrs-strt", &[]),
    Property::new("scrollSnapType", "scroll-snap-type", "scrs-t", &[]), Property::new("scrollSnapTypeX", "scroll-snap-type-x", "scrs-tx", &[]),
    Property::new("scrollSnapTypeY", "scroll-snap-type-y", "scrs-ty", &[]), Property::new("scrollTimeline", "scroll-timeline", "scrtl", &[]),
    Property::new("scrollTimelineAxis", "scroll-timeline-axis", "scrtl-a", &[]), Property::new("scrollTimelineName", "scroll-timeline-name", "scrtl-n", &[]),
    Property::new("sepia", "sepia", "sepia", &[]), Property::new("spaceX", "space-x", "sx", &[]),
    Property::new("spaceY", "space-y", "sy", &[]), Property::new("srOnly", "sr-only", "sr", &[]),
    Property::new("stroke", "stroke", "stroke", &[]), Property::new("strokeDasharray", "stroke-dasharray", "stk-dsh", &[]),
    Property::new("strokeDashoffset", "stroke-dashoffset", "stk-do", &[]), Property::new("strokeLinecap", "stroke-linecap", "stk-lc", &[]),
    Property::new("strokeLinejoin", "stroke-linejoin", "stk-lj", &[]), Property::new("strokeMiterlimit", "stroke-miterlimit", "stk-ml", &[]),
    Property::new("strokeOpacity", "stroke-opacity", "stk-op", &[]), Property::new("strokeWidth", "stroke-width", "stk-w", &[]),
    Property::new("tableLayout", "table-layout", "tbl", &[]), Property::new("textAlign", "text-align", "ta", &[]),
    Property::new("textDecoration", "text-decoration", "td", &[]), Property::new("textDecorationColor", "text-decoration-color", "text-decor-c", &[]),
    Property::new("textDecorationStyle", "text-decoration-style", "td-s", &[]), Property::new("textDecorationThickness", "text-decoration-thickness", "td-t", &[]),
    Property::new("textEmphasisColor", "text-emphasis-color", "text-emphasis-c", &[]), Property::new("textGradient", "text-gradient", "txt-grad", &[]),
    Property::new("textIndent", "text-indent", "ti", &[]), Property::new("textOverflow", "text-overflow", "tov", &[]),
    Property::new("textShadow", "text-shadow", "tsh", &[]), Property::new("textShadowColor", "text-shadow-color", "tsh-c", &[]),
    Property::new("textSizeAdjust", "text-size-adjust", "txt-adj", &[]), Property::new("textStyle", "text-style", "textStyle", &[]),
    Property::new("textTransform", "text-transform", "tt", &[]), Property::new("textUnderlineOffset", "text-underline-offset", "tu-o", &[]),
    Property::new("textWrap", "text-wrap", "tw", &[]), Property::new("top", "top", "top", &[]),
    Property::new("touchAction", "touch-action", "tch-a", &[]), Property::new("transform", "transform", "trf", &[]),
    Property::new("transformBox", "transform-box", "trf-b", &[]), Property::new("transformOrigin", "transform-origin", "trf-o", &[]),
    Property::new("transformStyle", "transform-style", "trf-s", &[]), Property::new("transition", "transition", "trs", &[]),
    Property::new("transitionDelay", "transition-delay", "trs-dly", &[]), Property::new("transitionDuration", "transition-duration", "trs-dur", &[]),
    Property::new("transitionProperty", "transition-property", "trs-prop", &[]), Property::new("transitionTimingFunction", "transition-timing-function", "trs-tmf", &[]),
    Property::new("translate", "translate", "translate", &[]), Property::new("translateX", "translate-x", "translate-x", &[]),
    Property::new("translateY", "translate-y", "translate-y", &[]), Property::new("translateZ", "translate-z", "translate-z", &[]),
    Property::new("truncate", "truncate", "trunc", &[]), Property::new("userSelect", "user-select", "us", &[]),
    Property::new("verticalAlign", "vertical-align", "va", &[]), Property::new("visibility", "visibility", "vis", &[]),
    Property::new("WebkitTextFillColor", "webkit-text-fill-color", "wktf-c", &[]), Property::new("width", "width", "w", &[]),
    Property::new("wordBreak", "word-break", "wb", &[]), Property::new("zIndex", "z-index", "z", &[]),
];

/// Returns the Property record for a canonical property name, if known.
pub fn find_property(name: &str) -> Option<&'static Property> {
    CANONICAL_PROPERTIES
        .binary_search_by_key(&name, |p| p.name)
        .ok()
        .map(|idx| &CANONICAL_PROPERTIES[idx])
}

/// Returns the native shorthand longhands for a property, if it is a shorthand.
pub fn native_longhands_for_prop(name: &str) -> Option<&'static [&'static str]> {
    match find_property(name) {
        Some(p) if !p.longhands.is_empty() => Some(p.longhands),
        _ => None,
    }
}
