// Eval-safe primitives barrel behind the Neo react source entry.
// It takes the factory, splitter, contexts, and tags and emits the 101 tag
// components plus the shared color-mode and layer-scope surface. The sync
// bootstrap aliases @reference-ui/react at the entry, so fragment files
// execute before any generated package exists; nothing here renders, so the
// empty splitter and blank layer name stay unreachable by construction.

import { css } from '../runtime/index.ts'
import { createPrimitive } from './runtime/factory.ts'
import { createPropSplitter } from './runtime/split.ts'

export { useColorMode, LayerScopeContext, ColorModeContext, DocumentContext } from './runtime/context.ts'
export { TAGS as HTML_TAGS, type Tag as HtmlTag } from './tags.ts'

// Shared build-time wiring: the splitter carries no compiled style prop
// names and the layer scope stays blank — fragment evaluation imports these
// components but never renders them, so style resolution never runs.
const split = createPropSplitter([])

export const A = createPrimitive({ tag: 'a', displayName: 'A', layerName: '', split, css })
export const Abbr = createPrimitive({ tag: 'abbr', displayName: 'Abbr', layerName: '', split, css })
export const Address = createPrimitive({ tag: 'address', displayName: 'Address', layerName: '', split, css })
export const Area = createPrimitive({ tag: 'area', displayName: 'Area', layerName: '', split, css })
export const Article = createPrimitive({ tag: 'article', displayName: 'Article', layerName: '', split, css })
export const Aside = createPrimitive({ tag: 'aside', displayName: 'Aside', layerName: '', split, css })
export const Audio = createPrimitive({ tag: 'audio', displayName: 'Audio', layerName: '', split, css })
export const B = createPrimitive({ tag: 'b', displayName: 'B', layerName: '', split, css })
export const Bdi = createPrimitive({ tag: 'bdi', displayName: 'Bdi', layerName: '', split, css })
export const Bdo = createPrimitive({ tag: 'bdo', displayName: 'Bdo', layerName: '', split, css })
export const Blockquote = createPrimitive({ tag: 'blockquote', displayName: 'Blockquote', layerName: '', split, css })
export const Br = createPrimitive({ tag: 'br', displayName: 'Br', layerName: '', split, css })
export const Button = createPrimitive({ tag: 'button', displayName: 'Button', layerName: '', split, css })
export const Canvas = createPrimitive({ tag: 'canvas', displayName: 'Canvas', layerName: '', split, css })
export const Caption = createPrimitive({ tag: 'caption', displayName: 'Caption', layerName: '', split, css })
export const Cite = createPrimitive({ tag: 'cite', displayName: 'Cite', layerName: '', split, css })
export const Code = createPrimitive({ tag: 'code', displayName: 'Code', layerName: '', split, css })
export const Col = createPrimitive({ tag: 'col', displayName: 'Col', layerName: '', split, css })
export const Colgroup = createPrimitive({ tag: 'colgroup', displayName: 'Colgroup', layerName: '', split, css })
export const Data = createPrimitive({ tag: 'data', displayName: 'Data', layerName: '', split, css })
export const Datalist = createPrimitive({ tag: 'datalist', displayName: 'Datalist', layerName: '', split, css })
export const Dd = createPrimitive({ tag: 'dd', displayName: 'Dd', layerName: '', split, css })
export const Del = createPrimitive({ tag: 'del', displayName: 'Del', layerName: '', split, css })
export const Details = createPrimitive({ tag: 'details', displayName: 'Details', layerName: '', split, css })
export const Dfn = createPrimitive({ tag: 'dfn', displayName: 'Dfn', layerName: '', split, css })
export const Dialog = createPrimitive({ tag: 'dialog', displayName: 'Dialog', layerName: '', split, css })
export const Div = createPrimitive({ tag: 'div', displayName: 'Div', layerName: '', split, css })
export const Dl = createPrimitive({ tag: 'dl', displayName: 'Dl', layerName: '', split, css })
export const Dt = createPrimitive({ tag: 'dt', displayName: 'Dt', layerName: '', split, css })
export const Em = createPrimitive({ tag: 'em', displayName: 'Em', layerName: '', split, css })
export const Embed = createPrimitive({ tag: 'embed', displayName: 'Embed', layerName: '', split, css })
export const Fieldset = createPrimitive({ tag: 'fieldset', displayName: 'Fieldset', layerName: '', split, css })
export const Figcaption = createPrimitive({ tag: 'figcaption', displayName: 'Figcaption', layerName: '', split, css })
export const Figure = createPrimitive({ tag: 'figure', displayName: 'Figure', layerName: '', split, css })
export const Footer = createPrimitive({ tag: 'footer', displayName: 'Footer', layerName: '', split, css })
export const Form = createPrimitive({ tag: 'form', displayName: 'Form', layerName: '', split, css })
export const H1 = createPrimitive({ tag: 'h1', displayName: 'H1', layerName: '', split, css })
export const H2 = createPrimitive({ tag: 'h2', displayName: 'H2', layerName: '', split, css })
export const H3 = createPrimitive({ tag: 'h3', displayName: 'H3', layerName: '', split, css })
export const H4 = createPrimitive({ tag: 'h4', displayName: 'H4', layerName: '', split, css })
export const H5 = createPrimitive({ tag: 'h5', displayName: 'H5', layerName: '', split, css })
export const H6 = createPrimitive({ tag: 'h6', displayName: 'H6', layerName: '', split, css })
export const Header = createPrimitive({ tag: 'header', displayName: 'Header', layerName: '', split, css })
export const Hgroup = createPrimitive({ tag: 'hgroup', displayName: 'Hgroup', layerName: '', split, css })
export const Hr = createPrimitive({ tag: 'hr', displayName: 'Hr', layerName: '', split, css })
export const I = createPrimitive({ tag: 'i', displayName: 'I', layerName: '', split, css })
export const Iframe = createPrimitive({ tag: 'iframe', displayName: 'Iframe', layerName: '', split, css })
export const Img = createPrimitive({ tag: 'img', displayName: 'Img', layerName: '', split, css })
export const Input = createPrimitive({ tag: 'input', displayName: 'Input', layerName: '', split, css })
export const Ins = createPrimitive({ tag: 'ins', displayName: 'Ins', layerName: '', split, css })
export const Kbd = createPrimitive({ tag: 'kbd', displayName: 'Kbd', layerName: '', split, css })
export const Label = createPrimitive({ tag: 'label', displayName: 'Label', layerName: '', split, css })
export const Legend = createPrimitive({ tag: 'legend', displayName: 'Legend', layerName: '', split, css })
export const Li = createPrimitive({ tag: 'li', displayName: 'Li', layerName: '', split, css })
export const Main = createPrimitive({ tag: 'main', displayName: 'Main', layerName: '', split, css })
// Map keeps its core export name through an alias: a local binding named Map
// would shadow the global, which the gate forbids.
const MapPrimitive = createPrimitive({ tag: 'map', displayName: 'Map', layerName: '', split, css })
export { MapPrimitive as Map }
export const Mark = createPrimitive({ tag: 'mark', displayName: 'Mark', layerName: '', split, css })
export const Menu = createPrimitive({ tag: 'menu', displayName: 'Menu', layerName: '', split, css })
export const Meter = createPrimitive({ tag: 'meter', displayName: 'Meter', layerName: '', split, css })
export const Nav = createPrimitive({ tag: 'nav', displayName: 'Nav', layerName: '', split, css })
export const Obj = createPrimitive({ tag: 'object', displayName: 'Obj', layerName: '', split, css })
export const Ol = createPrimitive({ tag: 'ol', displayName: 'Ol', layerName: '', split, css })
export const Optgroup = createPrimitive({ tag: 'optgroup', displayName: 'Optgroup', layerName: '', split, css })
export const Option = createPrimitive({ tag: 'option', displayName: 'Option', layerName: '', split, css })
export const Output = createPrimitive({ tag: 'output', displayName: 'Output', layerName: '', split, css })
export const P = createPrimitive({ tag: 'p', displayName: 'P', layerName: '', split, css })
export const Picture = createPrimitive({ tag: 'picture', displayName: 'Picture', layerName: '', split, css })
export const Pre = createPrimitive({ tag: 'pre', displayName: 'Pre', layerName: '', split, css })
export const Progress = createPrimitive({ tag: 'progress', displayName: 'Progress', layerName: '', split, css })
export const Q = createPrimitive({ tag: 'q', displayName: 'Q', layerName: '', split, css })
export const Rp = createPrimitive({ tag: 'rp', displayName: 'Rp', layerName: '', split, css })
export const Rt = createPrimitive({ tag: 'rt', displayName: 'Rt', layerName: '', split, css })
export const Ruby = createPrimitive({ tag: 'ruby', displayName: 'Ruby', layerName: '', split, css })
export const S = createPrimitive({ tag: 's', displayName: 'S', layerName: '', split, css })
export const Samp = createPrimitive({ tag: 'samp', displayName: 'Samp', layerName: '', split, css })
export const Search = createPrimitive({ tag: 'search', displayName: 'Search', layerName: '', split, css })
export const Section = createPrimitive({ tag: 'section', displayName: 'Section', layerName: '', split, css })
export const Select = createPrimitive({ tag: 'select', displayName: 'Select', layerName: '', split, css })
export const Small = createPrimitive({ tag: 'small', displayName: 'Small', layerName: '', split, css })
export const Source = createPrimitive({ tag: 'source', displayName: 'Source', layerName: '', split, css })
export const Span = createPrimitive({ tag: 'span', displayName: 'Span', layerName: '', split, css })
export const Strong = createPrimitive({ tag: 'strong', displayName: 'Strong', layerName: '', split, css })
export const Sub = createPrimitive({ tag: 'sub', displayName: 'Sub', layerName: '', split, css })
export const Summary = createPrimitive({ tag: 'summary', displayName: 'Summary', layerName: '', split, css })
export const Sup = createPrimitive({ tag: 'sup', displayName: 'Sup', layerName: '', split, css })
export const Svg = createPrimitive({ tag: 'svg', displayName: 'Svg', layerName: '', split, css })
export const Table = createPrimitive({ tag: 'table', displayName: 'Table', layerName: '', split, css })
export const Tbody = createPrimitive({ tag: 'tbody', displayName: 'Tbody', layerName: '', split, css })
export const Td = createPrimitive({ tag: 'td', displayName: 'Td', layerName: '', split, css })
export const Textarea = createPrimitive({ tag: 'textarea', displayName: 'Textarea', layerName: '', split, css })
export const Tfoot = createPrimitive({ tag: 'tfoot', displayName: 'Tfoot', layerName: '', split, css })
export const Th = createPrimitive({ tag: 'th', displayName: 'Th', layerName: '', split, css })
export const Thead = createPrimitive({ tag: 'thead', displayName: 'Thead', layerName: '', split, css })
export const Time = createPrimitive({ tag: 'time', displayName: 'Time', layerName: '', split, css })
export const Tr = createPrimitive({ tag: 'tr', displayName: 'Tr', layerName: '', split, css })
export const Track = createPrimitive({ tag: 'track', displayName: 'Track', layerName: '', split, css })
export const U = createPrimitive({ tag: 'u', displayName: 'U', layerName: '', split, css })
export const Ul = createPrimitive({ tag: 'ul', displayName: 'Ul', layerName: '', split, css })
export const Var = createPrimitive({ tag: 'var', displayName: 'Var', layerName: '', split, css })
export const Video = createPrimitive({ tag: 'video', displayName: 'Video', layerName: '', split, css })
export const Wbr = createPrimitive({ tag: 'wbr', displayName: 'Wbr', layerName: '', split, css })
