/**
 * Code emitters for Reference UI Rust canon modules.
 * Generates formatted Rust source code strings for HTML elements, CSS properties,
 * StyleProps aliases, responsive conditions, and lookup switchboards.
 * Emits zero-allocation binary-searchable static slices and lookup helpers.
 */

import type { DialectData, DialectProperty } from './dialect';

export function formatChunks(items: string[], indent = '    ', perLine = 2): string {
  const lines: string[] = [];
  for (let i = 0; i < items.length; i += perLine) {
    const chunk = items.slice(i, i + perLine).join(', ');
    lines.push(`${indent}${chunk},`);
  }
  return lines.join('\n');
}

export function emitHtmlRs(dialect: DialectData): string {
  const elementChunks = dialect.elements.map(
    (e) => `Element::new("${e.html}", "${e.jsx}")`
  );
  return `//! Generated HTML tags and Reference primitive JSX element names.
//!
//! Generated by \`packages/reference-rs/modules/canon/generate/generate.ts\`.
//! Represents the curated subset of HTML elements wrapped as Reference UI JSX primitives.
// @generated

/// Element mapping from lowercase HTML element tag to PascalCase JSX primitive.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Element {
    pub html: &'static str,
    pub jsx: &'static str,
}

impl Element {
    pub const fn new(html: &'static str, jsx: &'static str) -> Self {
        Self { html, jsx }
    }
}

/// All canonical elements supported as Reference UI primitives.
pub const ELEMENTS: &[Element] = &[
${formatChunks(elementChunks, '    ', 3)}
];

/// Returns true if the given tag name is a valid lowercase HTML element tag in the canon.
pub fn is_html_tag(tag: &str) -> bool {
    ELEMENTS.binary_search_by_key(&tag, |e| e.html).is_ok()
}

/// Returns true if the given identifier is a valid Reference primitive JSX component name.
pub fn is_primitive_jsx_name(name: &str) -> bool {
    ELEMENTS.binary_search_by_key(&name, |e| e.jsx).is_ok()
}

/// Returns true if the given element name is either an HTML tag or a Reference primitive.
pub fn is_reference_primitive(name: &str) -> bool {
    is_html_tag(name) || is_primitive_jsx_name(name)
}
`;
}

function buildLonghandDefs(properties: DialectProperty[]): {
  longhandSlices: Map<string, string>;
  longhandSliceDefs: string[];
} {
  const longhandSlices = new Map<string, string>();
  const longhandSliceDefs: string[] = [];
  for (const p of properties) {
    if (p.longhands.length > 0) {
      const sliceConstName = `${p.name.toUpperCase()}_LONGHANDS`;
      longhandSlices.set(p.name, sliceConstName);
      const itemsStr = p.longhands.map((s) => `"${s}"`).join(', ');
      longhandSliceDefs.push(`static ${sliceConstName}: &[&str] = &[${itemsStr}];`);
    }
  }
  return { longhandSlices, longhandSliceDefs };
}

export function emitCssRs(dialect: DialectData): string {
  const { longhandSlices, longhandSliceDefs } = buildLonghandDefs(dialect.canonicalProperties);
  const propertyChunks = dialect.canonicalProperties.map((p) => {
    const sliceName = longhandSlices.get(p.name) ?? '&[]';
    return `Property::new("${p.name}", "${p.css}", "${p.classPrefix}", ${sliceName})`;
  });

  return `//! Canonical CSS properties, native shorthand longhands, and utility class prefixes.
//!
//! Generated by \`packages/reference-rs/modules/canon/generate/generate.ts\`.
//! Bridges W3C/WHATWG CSS property definitions with Reference UI class prefixes.
// @generated

/// Canonical property specification in the compiler canon.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Property {
    pub name: &'static str,
    pub css: &'static str,
    pub class_prefix: &'static str,
    pub longhands: &'static [&'static str],
}

impl Property {
    pub const fn new(
        name: &'static str,
        css: &'static str,
        class_prefix: &'static str,
        longhands: &'static [&'static str],
    ) -> Self {
        Self {
            name,
            css,
            class_prefix,
            longhands,
        }
    }
}

// Native shorthand longhand slices
${longhandSliceDefs.join('\n')}

/// All canonical CSS and system properties sorted by camelCase property name.
pub const CANONICAL_PROPERTIES: &[Property] = &[
${formatChunks(propertyChunks, '    ', 2)}
];

/// Returns the Property record for a canonical property name, if known.
pub fn find_property(name: &str) -> Option<&'static Property> {
    CANONICAL_PROPERTIES
        .binary_search_by_key(&name, |p| p.name)
        .ok()
        .map(|idx| &CANONICAL_PROPERTIES[idx])
}

/// Returns the native shorthand longhands for a property, if it is a shorthand.
pub fn native_longhands_for_prop(name: &str) -> Option<&'static [&'static str]> {
    match find_property(name) {
        Some(p) if !p.longhands.is_empty() => Some(p.longhands),
        _ => None,
    }
}
`;
}

export function emitDialectRs(dialect: DialectData): string {
  const aliasChunks = dialect.aliases.map((a) => `Alias::new("${a.alias}", "${a.canonical}")`);
  const refPropChunks = dialect.referenceProps.map((p) => `"${p}"`);

  return `//! Reference UI StyleProps dialect aliases and custom props.
//!
//! Generated by \`packages/reference-rs/modules/canon/generate/generate.ts\`.
//! Maps concise authoring shorthand aliases to canonical CSS properties and defines Reference-only props.
// @generated

/// StyleProps alias mapping a shorthand alias to its canonical property name.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Alias {
    pub alias: &'static str,
    pub canonical: &'static str,
}

impl Alias {
    pub const fn new(alias: &'static str, canonical: &'static str) -> Self {
        Self { alias, canonical }
    }
}

/// Sorted table of StyleProps shorthand aliases.
pub const ALIASES: &[Alias] = &[
${formatChunks(aliasChunks, '    ', 3)}
];

/// Reference-only custom props (e.g. rhythm multipliers, container macros, variant discriminators).
pub const REFERENCE_PROPS: &[&str] = &[
${formatChunks(refPropChunks, '    ', 3)}
];

/// Resolves a dialect alias or shorthand to its canonical property name.
pub fn resolve_alias(alias: &str) -> Option<&'static str> {
    ALIASES
        .binary_search_by_key(&alias, |a| a.alias)
        .ok()
        .map(|idx| ALIASES[idx].canonical)
}

/// Returns true if the given name is a Reference-only prop.
pub fn is_reference_prop(name: &str) -> bool {
    REFERENCE_PROPS.binary_search(&name).is_ok()
}
`;
}

export function emitConditionsRs(dialect: DialectData): string {
  const bpChunks = dialect.breakpoints.map((b) => `"${b}"`);
  const condChunks = dialect.conditions.map((c) => `"${c}"`);

  return `//! Reference UI conditions, pseudo-selectors, and default responsive breakpoints.
//!
//! Generated by \`packages/reference-rs/modules/canon/generate/generate.ts\`.
//! Defines discriminator keys for pseudo-classes, responsive breakpoints, and media queries.
// @generated

/// Canonical ordered list of default responsive breakpoints.
pub const DEFAULT_BREAKPOINTS: &[&str] = &[
${formatChunks(bpChunks, '    ', 6)}
];

/// Sorted list of recognized condition keys.
pub const CONDITIONS: &[&str] = &[
${formatChunks(condChunks, '    ', 4)}
];

/// Returns true if the given key represents a condition, pseudo selector, or breakpoint.
pub fn is_condition(name: &str) -> bool {
    if name.starts_with('_') || name.starts_with('&') || name.starts_with('@') {
        return true;
    }
    CONDITIONS.binary_search(&name).is_ok()
}

/// Returns the default responsive breakpoint name for an array index.
pub fn default_breakpoint_for_index(idx: usize) -> Option<&'static str> {
    DEFAULT_BREAKPOINTS.get(idx).copied()
}
`;
}

export function emitLibRs(): string {
  return `//! The official set of platform elements, CSS properties, aliases, and conditions.
//!
//! Serves as the central dictionary consulted by all compiler stages (extract, resolve, stylesheet).
//! Joins living W3C/WHATWG specifications with Reference UI design system dialects.

pub mod conditions;
pub mod css;
pub mod dialect;
pub mod html;
#[cfg(test)]
mod tests;

pub use conditions::{default_breakpoint_for_index, is_condition, CONDITIONS, DEFAULT_BREAKPOINTS};
pub use css::{find_property, native_longhands_for_prop, Property, CANONICAL_PROPERTIES};
pub use dialect::{is_reference_prop, resolve_alias, Alias, ALIASES, REFERENCE_PROPS};
pub use html::{is_html_tag, is_primitive_jsx_name, is_reference_primitive, Element, ELEMENTS};

/// Returns true if the given property name is a recognized Reference UI style prop.
pub fn is_known_style_prop(name: &str) -> bool {
    if name.starts_with("--") {
        return true;
    }
    is_reference_prop(name) || resolve_alias(name).is_some() || find_property(name).is_some()
}

/// Returns true if the given key represents a condition, pseudo selector, or breakpoint.
pub fn is_condition_prop(name: &str) -> bool {
    is_condition(name)
}

/// Resolves a shorthand or alias to its canonical camelCase property name.
pub fn resolve_canonical_prop(prop: &str) -> &str {
    resolve_alias(prop).unwrap_or(prop)
}

/// Returns the atomic class name prefix for a property.
pub fn class_prefix_for_prop(prop: &str) -> &str {
    let canonical = resolve_canonical_prop(prop);
    if let Some(p) = find_property(canonical) {
        p.class_prefix
    } else {
        canonical
    }
}

/// Converts a camelCase property name to a CSS kebab-case property name.
pub fn to_css_declaration_property(prop: &str) -> String {
    let canonical = resolve_canonical_prop(prop);
    if canonical.starts_with("--") {
        return canonical.to_string();
    }
    if let Some(p) = find_property(canonical) {
        return p.css.to_string();
    }
    let mut out = String::with_capacity(canonical.len() + 4);
    for ch in canonical.chars() {
        if ch.is_ascii_uppercase() {
            out.push('-');
            out.push(ch.to_ascii_lowercase());
        } else {
            out.push(ch);
        }
    }
    out
}
`;
}
