/**
 * Code emitters for Reference UI Rust canon modules.
 * Generates formatted Rust source code strings for HTML/SVG elements,
 * StyleProps aliases, responsive conditions, and lookup switchboards.
 * Emits zero-allocation binary-searchable static slices and lookup helpers.
 */

import type { DialectData } from './dialect';

export function formatChunks(items: string[], indent = '    ', perLine = 2): string {
  const lines: string[] = [];
  for (let i = 0; i < items.length; i += perLine) {
    const chunk = items.slice(i, i + perLine).join(', ');
    lines.push(`${indent}${chunk},`);
  }
  return lines.join('\n');
}

export function emitHtmlRs(dialect: DialectData): string {
  const elementChunks = dialect.elements.map(
    (e) => `Element::new("${e.html}", "${e.jsx}")`
  );
  const jsxChunks = dialect.primitiveJsx.map((j) => `"${j}"`);
  return `//! Generated HTML and SVG tags and Reference primitive JSX element names.
//!
//! Generated by \`packages/reference-rs/modules/canon/generate/generate.ts\`.
//! Represents the curated subset of HTML and SVG host elements wrapped as Reference UI JSX primitives.
//! Maps lowercase DOM tag names to PascalCase JSX primitive component names.
// @generated

/// Element mapping from lowercase HTML/SVG element tag to PascalCase JSX primitive.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Element {
    pub html: &'static str,
    pub jsx: &'static str,
}

impl Element {
    pub const fn new(html: &'static str, jsx: &'static str) -> Self {
        Self { html, jsx }
    }
}

/// All canonical elements supported as Reference UI primitives.
pub const ELEMENTS: &[Element] = &[
${formatChunks(elementChunks, '    ', 3)}
];

/// All canonical JSX primitive component names, sorted lexicographically.
pub const PRIMITIVE_JSX: &[&'static str] = &[
${formatChunks(jsxChunks, '    ', 4)}
];

/// Returns true if the given tag name is a valid lowercase HTML/SVG element tag in the canon.
pub fn is_html_tag(tag: &str) -> bool {
    if tag.len() > 64 {
        return false;
    }
    let mut buf = [0u8; 64];
    for (i, &b) in tag.as_bytes().iter().enumerate() {
        buf[i] = b.to_ascii_lowercase();
    }
    let lower = match std::str::from_utf8(&buf[..tag.len()]) {
        Ok(s) => s,
        Err(_) => return false,
    };
    ELEMENTS.binary_search_by_key(&lower, |e| e.html).is_ok()
}

/// Returns true if the given identifier is a valid Reference primitive JSX component name.
pub fn is_primitive_jsx_name(name: &str) -> bool {
    PRIMITIVE_JSX.binary_search(&name).is_ok()
}

/// Returns true if the given element name is either an HTML tag or a Reference primitive.
pub fn is_reference_primitive(name: &str) -> bool {
    is_html_tag(name) || is_primitive_jsx_name(name)
}
`;
}

export function emitDialectRs(dialect: DialectData): string {
  const aliasChunks = dialect.aliases.map((a) => `Alias::new("${a.alias}", "${a.canonical}")`);
  const refPropChunks = dialect.referenceProps.map((p) => `"${p}"`);

  return `//! Reference UI StyleProps dialect aliases and custom props.
//!
//! Generated by \`packages/reference-rs/modules/canon/generate/generate.ts\`.
//! Maps concise authoring shorthand aliases to canonical CSS properties and defines Reference-only props.
//! Provides zero-allocation lookup functions for resolving aliases during compiler passes.
// @generated

/// StyleProps alias mapping a shorthand alias to its canonical property name.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Alias {
    pub alias: &'static str,
    pub canonical: &'static str,
}

impl Alias {
    pub const fn new(alias: &'static str, canonical: &'static str) -> Self {
        Self { alias, canonical }
    }
}

/// Sorted table of StyleProps shorthand aliases.
pub const ALIASES: &[Alias] = &[
${formatChunks(aliasChunks, '    ', 3)}
];

/// Reference-only custom macro props (e.g. rhythm multipliers, variant discriminators).
pub const REFERENCE_PROPS: &[&str] = &[
${formatChunks(refPropChunks, '    ', 3)}
];

/// Resolves a dialect alias or shorthand to its canonical property name.
pub fn resolve_alias(alias: &str) -> Option<&'static str> {
    ALIASES
        .binary_search_by_key(&alias, |a| a.alias)
        .ok()
        .map(|idx| ALIASES[idx].canonical)
}

/// Returns true if the given name is a Reference-only macro prop.
pub fn is_reference_prop(name: &str) -> bool {
    REFERENCE_PROPS.binary_search(&name).is_ok()
}
`;
}

export function emitConditionsRs(dialect: DialectData): string {
  const bpChunks = dialect.breakpoints.map((b) => `"${b}"`);
  const condChunks = dialect.conditions.map((c) => `"${c}"`);

  return `//! Reference UI conditions, pseudo-selectors, and default responsive breakpoints.
//!
//! Generated by \`packages/reference-rs/modules/canon/generate/generate.ts\`.
//! Defines discriminator keys for pseudo-classes, responsive breakpoints, and media queries.
//! Enables responsive array and object syntax parsing across compiler passes.
// @generated

/// Canonical ordered list of default responsive breakpoints.
pub const DEFAULT_BREAKPOINTS: &[&str] = &[
${formatChunks(bpChunks, '    ', 6)}
];

/// Sorted list of recognized condition keys.
pub const CONDITIONS: &[&str] = &[
${formatChunks(condChunks, '    ', 4)}
];

/// Returns true if the given key represents a condition, pseudo selector, or breakpoint.
pub fn is_condition(name: &str) -> bool {
    if name.starts_with('_') || name.starts_with('&') || name.starts_with('@') {
        return true;
    }
    CONDITIONS.binary_search(&name).is_ok()
}

/// Returns the default responsive breakpoint name for an array index.
pub fn default_breakpoint_for_index(idx: usize) -> Option<&'static str> {
    DEFAULT_BREAKPOINTS.get(idx).copied()
}
`;
}

export function emitLibRs(): string {
  return `//! The official set of platform elements, CSS properties, aliases, and conditions.
//!
//! Serves as the central dictionary consulted by all compiler stages (extract, resolve, stylesheet).
//! Joins living W3C/WHATWG specifications with Reference UI design system dialects.
//! Provides zero-allocation lookup functions and standard conversion routines for style engine passes.
// @generated

pub mod conditions;
pub mod css;
pub mod dialect;
pub mod html;
#[cfg(test)]
mod tests;

pub use conditions::{default_breakpoint_for_index, is_condition, CONDITIONS, DEFAULT_BREAKPOINTS};
pub use css::{
    find_property, is_color_prop, native_longhands_for_prop, Property, CANONICAL_PROPERTIES,
    COLOR_PROPERTIES,
};
pub use dialect::{is_reference_prop, resolve_alias, Alias, ALIASES, REFERENCE_PROPS};
pub use html::{is_html_tag, is_primitive_jsx_name, is_reference_primitive, Element, ELEMENTS, PRIMITIVE_JSX};

/// Returns true if the given property name is a recognized Reference UI style prop.
pub fn is_known_style_prop(name: &str) -> bool {
    if name.starts_with("--") {
        return true;
    }
    is_reference_prop(name) || resolve_alias(name).is_some() || find_property(name).is_some()
}

/// Returns true if the given key represents a condition, pseudo selector, or breakpoint.
pub fn is_condition_prop(name: &str) -> bool {
    is_condition(name)
}

/// Resolves a shorthand or alias to its canonical camelCase property name.
pub fn resolve_canonical_prop(prop: &str) -> &str {
    resolve_alias(prop).unwrap_or(prop)
}

/// Returns the atomic class name prefix for a property.
pub fn class_prefix_for_prop(prop: &str) -> &str {
    let canonical = resolve_canonical_prop(prop);
    if let Some(p) = find_property(canonical) {
        p.class_prefix
    } else {
        canonical
    }
}

/// Converts a property name or alias to its CSS declaration property name.
pub fn to_css_declaration_property(prop: &str) -> &str {
    let canonical = resolve_canonical_prop(prop);
    if canonical.starts_with("--") {
        return canonical;
    }
    if let Some(p) = find_property(canonical) {
        return p.css;
    }
    canonical
}
`;
}
