/**
 * Generate the fully inlined box pattern from collected extensions.
 * Transform is self-contained (no closure variables) so Panda codegen emits valid box.js.
 */

export interface CollectedExtension {
  properties: Record<string, any>
  transformSource: string
}

function formatProperties(properties: Record<string, any>): string {
  return Object.entries(properties)
    .map(([k, v]) => `      ${k}: ${JSON.stringify(v)} as const`)
    .join(',\n')
}

/**
 * Generate box.ts content from collected extensions.
 * Inlines each extension's transform body into the combined transform.
 */
export function generateBoxPatternContent(extensions: CollectedExtension[]): string {
  const properties: Record<string, any> = {}
  for (const ext of extensions) {
    Object.assign(properties, ext.properties)
  }
  const blocklist = Object.keys(properties)
  const blocklistStr = JSON.stringify(blocklist)

  const resultVars = extensions.map((_, i) => `_r${i}`)
  const indent = (s: string) => (s ? '      ' + s : '')
  const iifeBlocks = extensions.flatMap((ext, i) => {
    const body = ext.transformSource
      .split('\n')
      .map(line => '    ' + line)
      .join('\n')
    return [
      `const ${resultVars[i]} = (function(props: Record<string, any>) {`,
      body,
      `})(props)`,
    ]
  })

  const transformLines = [
    `const blocklist = ${blocklistStr}`,
    `const extensionKeys = new Set(blocklist)`,
    `const rest = Object.fromEntries(`,
    `  Object.entries(props).filter(([k]) => !extensionKeys.has(k))`,
    `)`,
    ``,
    ...iifeBlocks,
    ``,
    `return Object.assign({}, ${resultVars.join(', ')}, rest)`,
  ]

  const lines = [
    `/** Generated by createBoxPattern - do not edit manually */`,
    ``,
    `import { extendPandaConfig } from '../../cli/panda/config/extendPandaConfig'`,
    `import { PRIMITIVE_JSX_NAMES } from '../../primitives/tags'`,
    ``,
    `extendPandaConfig({`,
    `  patterns: { extend: { box: {`,
    `    jsx: [...PRIMITIVE_JSX_NAMES],`,
    `    properties: {`,
    ...formatProperties(properties).split('\n'),
    `    },`,
    `    blocklist: ${blocklistStr},`,
    `    transform(props: Record<string, any>) {`,
    ...transformLines.map(indent),
    `    },`,
    `  } } }`,
    `})`,
    ``,
  ]

  return lines.join('\n')
}
