/** Generated by createBoxPattern - do not edit manually */

import { extendPandaConfig } from '../../cli/panda/config/extendPandaConfig'
import { PRIMITIVE_JSX_NAMES } from '../../primitives/tags'

extendPandaConfig({
  patterns: { extend: { box: {
    jsx: [...PRIMITIVE_JSX_NAMES],
    properties: {
      container: {"type":"string"} as const,
      font: {"type":"string"} as const,
      r: {"type":"object"} as const
    },
    blocklist: ["container","font","r"],
    transform(props: Record<string, any>) {
      const blocklist = ["container","font","r"]
      const extensionKeys = new Set(blocklist)
      const rest = Object.fromEntries(
        Object.entries(props).filter(([k]) => !extensionKeys.has(k))
      )

      const _r0 = (function(props: Record<string, any>) {
          const { container } = props;
        if (container === void 0) return {};
        return {
          containerType: "inline-size",
          ...typeof container === "string" && container && { containerName: container }
        };
      })(props)
      const _r1 = (function(props: Record<string, any>) {
          const { font } = props;
        if (!font) return {};
        const FONT_PRESETS = {
          sans: { fontFamily: "sans", letterSpacing: "-0.01em", fontWeight: "400" },
          serif: { fontFamily: "serif", letterSpacing: "normal", fontWeight: "373" },
          mono: { fontFamily: "mono", letterSpacing: "-0.04em", fontWeight: "393" }
        };
        return FONT_PRESETS[font] || {};
      })(props)
      const _r2 = (function(props: Record<string, any>) {
          const { r, container } = props;
        if (!r) return {};
        const prefix = container ? `@container ${container} (min-width:` : `@container (min-width:`;
        return Object.fromEntries(
          Object.entries(r).map(([bp, styles]) => [`${prefix} ${bp}px)`, styles])
        );
      })(props)

      return Object.assign({}, _r0, _r1, _r2, rest)
    },
  } } }
})
