import { writeFileSync, mkdirSync } from 'node:fs'
import { dirname } from 'node:path'
import { bundleFragments } from '../../lib/fragments'
import type { FragmentCollector } from '../../lib/fragments'
import { deepMergeFnLines } from './utils/deepMerge'

export interface CreatePandaConfigOptions {
  /** Absolute path to write the final panda.config.ts */
  outputPath: string
  /** Absolute paths to source files that call fragment functions (from scanForFragments) */
  fragmentFiles: string[]
  /** Collectors whose globalThis slots will be initialised in the output file */
  collectors: FragmentCollector[]
}

export async function createPandaConfig(
  options: CreatePandaConfigOptions
): Promise<void> {
  const { outputPath, fragmentFiles, collectors } = options

  const bundles = await bundleFragments({ files: fragmentFiles })
  const collectorKeys = collectors.map(c => `'${c.config.globalKey}'`).join(', ')

  const lines: string[] = [
    '// Generated by reference-cli — do not edit manually',
    "import { defineConfig } from '@pandacss/dev'",
    '',

    '// Collector setup — each collector initialises its own globalThis slot',
    ...collectors.map(c => c.toScript()),
    '',

    '// Fragment bundles (each self-contained IIFE, functions intact)',
    ...bundles.map(({ bundle }) => `;${bundle}`),
    '',

    // deepMerge function — inlined verbatim into generated config output
    ...deepMergeFnLines,
    '',

    `const __fragments = [${collectorKeys}].flatMap(function(k) { return globalThis[k] || [] })`,
    `  ;[${collectorKeys}].forEach(function(k) { delete globalThis[k] })`,
    'const __config = __fragments.reduce((acc, frag) => deepMerge(acc, frag), {})',
    '',
    'export default defineConfig(__config)',
  ]

  mkdirSync(dirname(outputPath), { recursive: true })
  writeFileSync(outputPath, lines.join('\n'), 'utf-8')
}
