import { existsSync, mkdirSync, readdirSync, rmSync, writeFileSync } from 'node:fs'
import { join, resolve } from 'node:path'
import { emit } from '../../event-bus'
import { log } from '../../lib/log'
import { microBundlePanda } from '../../lib/microbundle'
import { scanDirectories } from '../eval/scanner'
import { buildPandaEntryContent } from './entryTemplate'

export interface CreatePandaConfigOptions {
  /** When true, add codegen to include so Panda scans the codegen folder (used by sync only). */
  includeCodegen?: boolean
  /** Additional directories to scan for config files (e.g., user project directories) */
  userDirectories?: string[]
}

/**
 * Mini-compiler: Bundle files that call extendPandaConfig into panda.config.ts.
 *
 * Uses esbuild to bundle all config files, properly inlining functions and their closures.
 * This handles TypeScript properly and inlines all dependencies.
 *
 * @param coreDir - Package root (reference-core)
 * @param options - includeCodegen: set when called from sync so generated config scans codegen/
 *                  userDirectories: additional directories to scan (from config.include)
 */
export async function createPandaConfig(
  coreDir: string,
  options: CreatePandaConfigOptions = {}
): Promise<void> {
  try {
    const refDir = join(coreDir, '.ref')
    if (!existsSync(refDir)) {
      mkdirSync(refDir, { recursive: true })
    }

    // Step 1: Find all files that need to be bundled
    log.debug('system:config', 'Scanning for config files...')
    const basePath = resolve(coreDir, 'panda.base.ts')
    const styledDir = resolve(coreDir, 'src/styled')
    const dirsToScan = [styledDir, ...(options.userDirectories || [])]
    log.debug('system:config', `Scanning directories: ${dirsToScan.join(', ')}`)
    const scannedPaths = scanDirectories(dirsToScan)
    const configFiles = [basePath, ...scannedPaths].filter(p => existsSync(p))
    log.debug('system:config', `Found ${configFiles.length} config files`)

    // Step 2: Create entry file from template
    const entryPath = join(refDir, 'panda-entry.ts')
    const initCollectorPath = resolve(coreDir, 'src/cli/system/config/initCollector.ts')
    const extendPandaPath = resolve(coreDir, 'src/cli/system/config/extendPandaConfig.ts')
    const deepMergePath = resolve(coreDir, 'src/cli/system/config/deepMerge.ts')

    const entryContent = buildPandaEntryContent({
      refDir,
      initCollectorPath,
      extendPandaConfigPath: extendPandaPath,
      deepMergePath,
      configFilePaths: configFiles,
    })
    writeFileSync(entryPath, entryContent)
    log.debug('system:config', 'Created entry file')

    // Step 3: Bundle with esbuild (reusable helper, in-memory output)
    log.debug('system:config', 'Bundling with esbuild...')
    const bundled = await microBundlePanda(entryPath)
    log.debug('system:config', 'Bundle complete')

    // Step 4: Write final panda.config.ts (inject codegen into include only when sync requested it)
    let output = bundled
    if (options.includeCodegen) {
      const srcPattern = '"src/**/*.{ts,tsx}"'
      output = output.replace(srcPattern, `${srcPattern}, "codegen/**/*.{ts,tsx,jsx}"`)
    }

    const configPath = resolve(coreDir, 'panda.config.ts')
    const finalConfig = `/** Generated by createPandaConfig - do not edit manually */
              ${output}
`
    log.debug('system:config', `Writing config to ${configPath}...`)
    writeFileSync(configPath, finalConfig)
    log.debug('system:config', 'Config written successfully')

    // Emit event so other systems know config is ready
    emit('system:config:created', { configPath })

    // Clean up temp files in .ref
    const refFiles = readdirSync(refDir)
    for (const file of refFiles) {
      rmSync(join(refDir, file), { force: true, recursive: true })
    }
  } catch (error) {
    log.error('[system:config] ERROR:', error)
    throw error
  }
}
