/**
 * Internal design tokens.
 * Scaffold — contributes to panda.config via the tokens() fragment.
 * 
 * Note: Font tokens are now generated by build/fontSystem.ts from
 * font definitions in internal/fonts.ts
 */

import { tokens } from '../api/tokens'

tokens({
  colors: {
    mySpecialToken: { value: 'red' },
    brand: {
      primary: { value: '#0066cc' },
      secondary: { value: '#ff6600' },
    },
  },
  spacing: {
    r: { value: '1rem' },
    sm: { value: '0.5rem' },
    md: { value: '1rem' },
    lg: { value: '1.5rem' },
  },
  letterSpacings: {
    tight: { value: '-0.04em' },
    normal: { value: 'normal' },
    snug: { value: '-0.01em' },
  },
})
