/**
 * Properties whose unitless numbers stay bare in CSS without gaining `px`.
 * Mirrors the React unitless-number set for the platform tail (opacity,
 * zIndex, flex factors, grid spans, lineClamp, fontWeight, ...). Vendor
 * additions live in vendors.ts (VENDOR_UNITLESS); dialect.ts unions both.
 */

export const UNITLESS_PROPS: readonly string[] = [
  'animationIterationCount',
  'aspectRatio',
  'borderImageOutset',
  'borderImageSlice',
  'borderImageWidth',
  'boxFlex',
  'boxFlexGroup',
  'boxOrdinalGroup',
  'columnCount',
  'columns',
  'fillOpacity',
  'flex',
  'flexGrow',
  'flexOrder',
  'flexPositive',
  'flexShrink',
  'floodOpacity',
  'fontWeight',
  'gridColumn',
  'gridColumnEnd',
  'gridColumnSpan',
  'gridColumnStart',
  'gridRow',
  'gridRowEnd',
  'gridRowSpan',
  'gridRowStart',
  'lineClamp',
  'lineHeight',
  'opacity',
  'order',
  'orphans',
  'scale',
  'stopOpacity',
  'strokeDasharray',
  'strokeDashoffset',
  'strokeMiterlimit',
  'strokeOpacity',
  'tabSize',
  'widows',
  'zIndex',
  'zoom',
];
