/**
 * Vendor-prefixed CSS properties absent from @webref/css (GAP-04a).
 * Webref ships 70 lowercase-first webkit props and zero moz/ms rows; React
 * authors write capital-first Webkit/Moz spellings, so those spellings were
 * dropped as unknown. Canonical rows below cover every csstype vendor prop
 * missing from webref (lowercase-first, webref convention); aliases cover
 * every capital-first React spelling. Opera (O) excluded: Presto is dead.
 *
 * Provenance: csstype@3.2.3 vendor interface (92 Moz, 69 ms, 132 Webkit)
 * minus the 70 webref webkit rows = 223 canonical rows + 293 aliases.
 * Derived 2026-09-19; re-derive from csstype, never hand-extend.
 */

import type { ExtensionProp } from './extensions';

export interface VendorAlias {
  alias: string;
  canonical: string;
}

export const VENDOR_EXTENSIONS = [
  { name: 'mozAnimation', css: '-moz-animation', classPrefix: '-moz-animation' },
  { name: 'mozAnimationDelay', css: '-moz-animation-delay', classPrefix: '-moz-animation-delay' },
  { name: 'mozAnimationDirection', css: '-moz-animation-direction', classPrefix: '-moz-animation-direction' },
  { name: 'mozAnimationDuration', css: '-moz-animation-duration', classPrefix: '-moz-animation-duration' },
  { name: 'mozAnimationFillMode', css: '-moz-animation-fill-mode', classPrefix: '-moz-animation-fill-mode' },
  { name: 'mozAnimationIterationCount', css: '-moz-animation-iteration-count', classPrefix: '-moz-animation-iteration-count' },
  { name: 'mozAnimationName', css: '-moz-animation-name', classPrefix: '-moz-animation-name' },
  { name: 'mozAnimationPlayState', css: '-moz-animation-play-state', classPrefix: '-moz-animation-play-state' },
  { name: 'mozAnimationTimingFunction', css: '-moz-animation-timing-function', classPrefix: '-moz-animation-timing-function' },
  { name: 'mozAppearance', css: '-moz-appearance', classPrefix: '-moz-appearance' },
  { name: 'mozBackfaceVisibility', css: '-moz-backface-visibility', classPrefix: '-moz-backface-visibility' },
  { name: 'mozBackgroundClip', css: '-moz-background-clip', classPrefix: '-moz-background-clip' },
  { name: 'mozBackgroundOrigin', css: '-moz-background-origin', classPrefix: '-moz-background-origin' },
  { name: 'mozBackgroundSize', css: '-moz-background-size', classPrefix: '-moz-background-size' },
  { name: 'mozBinding', css: '-moz-binding', classPrefix: '-moz-binding' },
  { name: 'mozBorderBottomColors', css: '-moz-border-bottom-colors', classPrefix: '-moz-border-bottom-colors', color: true },
  { name: 'mozBorderEndColor', css: '-moz-border-end-color', classPrefix: '-moz-border-end-color', color: true },
  { name: 'mozBorderEndStyle', css: '-moz-border-end-style', classPrefix: '-moz-border-end-style' },
  { name: 'mozBorderEndWidth', css: '-moz-border-end-width', classPrefix: '-moz-border-end-width' },
  { name: 'mozBorderImage', css: '-moz-border-image', classPrefix: '-moz-border-image' },
  { name: 'mozBorderLeftColors', css: '-moz-border-left-colors', classPrefix: '-moz-border-left-colors', color: true },
  { name: 'mozBorderRadius', css: '-moz-border-radius', classPrefix: '-moz-border-radius' },
  { name: 'mozBorderRadiusBottomleft', css: '-moz-border-radius-bottomleft', classPrefix: '-moz-border-radius-bottomleft' },
  { name: 'mozBorderRadiusBottomright', css: '-moz-border-radius-bottomright', classPrefix: '-moz-border-radius-bottomright' },
  { name: 'mozBorderRadiusTopleft', css: '-moz-border-radius-topleft', classPrefix: '-moz-border-radius-topleft' },
  { name: 'mozBorderRadiusTopright', css: '-moz-border-radius-topright', classPrefix: '-moz-border-radius-topright' },
  { name: 'mozBorderRightColors', css: '-moz-border-right-colors', classPrefix: '-moz-border-right-colors', color: true },
  { name: 'mozBorderStartColor', css: '-moz-border-start-color', classPrefix: '-moz-border-start-color', color: true },
  { name: 'mozBorderStartStyle', css: '-moz-border-start-style', classPrefix: '-moz-border-start-style' },
  { name: 'mozBorderTopColors', css: '-moz-border-top-colors', classPrefix: '-moz-border-top-colors', color: true },
  { name: 'mozBoxAlign', css: '-moz-box-align', classPrefix: '-moz-box-align' },
  { name: 'mozBoxDirection', css: '-moz-box-direction', classPrefix: '-moz-box-direction' },
  { name: 'mozBoxFlex', css: '-moz-box-flex', classPrefix: '-moz-box-flex' },
  { name: 'mozBoxOrdinalGroup', css: '-moz-box-ordinal-group', classPrefix: '-moz-box-ordinal-group' },
  { name: 'mozBoxOrient', css: '-moz-box-orient', classPrefix: '-moz-box-orient' },
  { name: 'mozBoxPack', css: '-moz-box-pack', classPrefix: '-moz-box-pack' },
  { name: 'mozBoxShadow', css: '-moz-box-shadow', classPrefix: '-moz-box-shadow' },
  { name: 'mozBoxSizing', css: '-moz-box-sizing', classPrefix: '-moz-box-sizing' },
  { name: 'mozColumnCount', css: '-moz-column-count', classPrefix: '-moz-column-count' },
  { name: 'mozColumnFill', css: '-moz-column-fill', classPrefix: '-moz-column-fill' },
  { name: 'mozColumnRule', css: '-moz-column-rule', classPrefix: '-moz-column-rule' },
  { name: 'mozColumnRuleColor', css: '-moz-column-rule-color', classPrefix: '-moz-column-rule-color', color: true },
  { name: 'mozColumnRuleStyle', css: '-moz-column-rule-style', classPrefix: '-moz-column-rule-style' },
  { name: 'mozColumnRuleWidth', css: '-moz-column-rule-width', classPrefix: '-moz-column-rule-width' },
  { name: 'mozColumnWidth', css: '-moz-column-width', classPrefix: '-moz-column-width' },
  { name: 'mozColumns', css: '-moz-columns', classPrefix: '-moz-columns' },
  { name: 'mozContextProperties', css: '-moz-context-properties', classPrefix: '-moz-context-properties' },
  { name: 'mozFloatEdge', css: '-moz-float-edge', classPrefix: '-moz-float-edge' },
  { name: 'mozFontFeatureSettings', css: '-moz-font-feature-settings', classPrefix: '-moz-font-feature-settings' },
  { name: 'mozFontLanguageOverride', css: '-moz-font-language-override', classPrefix: '-moz-font-language-override' },
  { name: 'mozForceBrokenImageIcon', css: '-moz-force-broken-image-icon', classPrefix: '-moz-force-broken-image-icon' },
  { name: 'mozHyphens', css: '-moz-hyphens', classPrefix: '-moz-hyphens' },
  { name: 'mozMarginEnd', css: '-moz-margin-end', classPrefix: '-moz-margin-end' },
  { name: 'mozMarginStart', css: '-moz-margin-start', classPrefix: '-moz-margin-start' },
  { name: 'mozOpacity', css: '-moz-opacity', classPrefix: '-moz-opacity' },
  { name: 'mozOrient', css: '-moz-orient', classPrefix: '-moz-orient' },
  { name: 'mozOsxFontSmoothing', css: '-moz-osx-font-smoothing', classPrefix: '-moz-osx-font-smoothing' },
  { name: 'mozOutline', css: '-moz-outline', classPrefix: '-moz-outline' },
  { name: 'mozOutlineColor', css: '-moz-outline-color', classPrefix: '-moz-outline-color', color: true },
  { name: 'mozOutlineRadius', css: '-moz-outline-radius', classPrefix: '-moz-outline-radius' },
  { name: 'mozOutlineRadiusBottomleft', css: '-moz-outline-radius-bottomleft', classPrefix: '-moz-outline-radius-bottomleft' },
  { name: 'mozOutlineRadiusBottomright', css: '-moz-outline-radius-bottomright', classPrefix: '-moz-outline-radius-bottomright' },
  { name: 'mozOutlineRadiusTopleft', css: '-moz-outline-radius-topleft', classPrefix: '-moz-outline-radius-topleft' },
  { name: 'mozOutlineRadiusTopright', css: '-moz-outline-radius-topright', classPrefix: '-moz-outline-radius-topright' },
  { name: 'mozOutlineStyle', css: '-moz-outline-style', classPrefix: '-moz-outline-style' },
  { name: 'mozOutlineWidth', css: '-moz-outline-width', classPrefix: '-moz-outline-width' },
  { name: 'mozPaddingEnd', css: '-moz-padding-end', classPrefix: '-moz-padding-end' },
  { name: 'mozPaddingStart', css: '-moz-padding-start', classPrefix: '-moz-padding-start' },
  { name: 'mozPerspective', css: '-moz-perspective', classPrefix: '-moz-perspective' },
  { name: 'mozPerspectiveOrigin', css: '-moz-perspective-origin', classPrefix: '-moz-perspective-origin' },
  { name: 'mozStackSizing', css: '-moz-stack-sizing', classPrefix: '-moz-stack-sizing' },
  { name: 'mozTabSize', css: '-moz-tab-size', classPrefix: '-moz-tab-size' },
  { name: 'mozTextAlignLast', css: '-moz-text-align-last', classPrefix: '-moz-text-align-last' },
  { name: 'mozTextBlink', css: '-moz-text-blink', classPrefix: '-moz-text-blink' },
  { name: 'mozTextDecorationColor', css: '-moz-text-decoration-color', classPrefix: '-moz-text-decoration-color', color: true },
  { name: 'mozTextDecorationLine', css: '-moz-text-decoration-line', classPrefix: '-moz-text-decoration-line' },
  { name: 'mozTextDecorationStyle', css: '-moz-text-decoration-style', classPrefix: '-moz-text-decoration-style' },
  { name: 'mozTextSizeAdjust', css: '-moz-text-size-adjust', classPrefix: '-moz-text-size-adjust' },
  { name: 'mozTransform', css: '-moz-transform', classPrefix: '-moz-transform' },
  { name: 'mozTransformOrigin', css: '-moz-transform-origin', classPrefix: '-moz-transform-origin' },
  { name: 'mozTransformStyle', css: '-moz-transform-style', classPrefix: '-moz-transform-style' },
  { name: 'mozTransition', css: '-moz-transition', classPrefix: '-moz-transition' },
  { name: 'mozTransitionDelay', css: '-moz-transition-delay', classPrefix: '-moz-transition-delay' },
  { name: 'mozTransitionDuration', css: '-moz-transition-duration', classPrefix: '-moz-transition-duration' },
  { name: 'mozTransitionProperty', css: '-moz-transition-property', classPrefix: '-moz-transition-property' },
  { name: 'mozTransitionTimingFunction', css: '-moz-transition-timing-function', classPrefix: '-moz-transition-timing-function' },
  { name: 'mozUserFocus', css: '-moz-user-focus', classPrefix: '-moz-user-focus' },
  { name: 'mozUserInput', css: '-moz-user-input', classPrefix: '-moz-user-input' },
  { name: 'mozUserModify', css: '-moz-user-modify', classPrefix: '-moz-user-modify' },
  { name: 'mozUserSelect', css: '-moz-user-select', classPrefix: '-moz-user-select' },
  { name: 'mozWindowDragging', css: '-moz-window-dragging', classPrefix: '-moz-window-dragging' },
  { name: 'mozWindowShadow', css: '-moz-window-shadow', classPrefix: '-moz-window-shadow' },
  { name: 'msAccelerator', css: '-ms-accelerator', classPrefix: '-ms-accelerator' },
  { name: 'msBlockProgression', css: '-ms-block-progression', classPrefix: '-ms-block-progression' },
  { name: 'msContentZoomChaining', css: '-ms-content-zoom-chaining', classPrefix: '-ms-content-zoom-chaining' },
  { name: 'msContentZoomLimit', css: '-ms-content-zoom-limit', classPrefix: '-ms-content-zoom-limit' },
  { name: 'msContentZoomLimitMax', css: '-ms-content-zoom-limit-max', classPrefix: '-ms-content-zoom-limit-max' },
  { name: 'msContentZoomLimitMin', css: '-ms-content-zoom-limit-min', classPrefix: '-ms-content-zoom-limit-min' },
  { name: 'msContentZoomSnap', css: '-ms-content-zoom-snap', classPrefix: '-ms-content-zoom-snap' },
  { name: 'msContentZoomSnapPoints', css: '-ms-content-zoom-snap-points', classPrefix: '-ms-content-zoom-snap-points' },
  { name: 'msContentZoomSnapType', css: '-ms-content-zoom-snap-type', classPrefix: '-ms-content-zoom-snap-type' },
  { name: 'msContentZooming', css: '-ms-content-zooming', classPrefix: '-ms-content-zooming' },
  { name: 'msFilter', css: '-ms-filter', classPrefix: '-ms-filter' },
  { name: 'msFlex', css: '-ms-flex', classPrefix: '-ms-flex' },
  { name: 'msFlexDirection', css: '-ms-flex-direction', classPrefix: '-ms-flex-direction' },
  { name: 'msFlexPositive', css: '-ms-flex-positive', classPrefix: '-ms-flex-positive' },
  { name: 'msFlowFrom', css: '-ms-flow-from', classPrefix: '-ms-flow-from' },
  { name: 'msFlowInto', css: '-ms-flow-into', classPrefix: '-ms-flow-into' },
  { name: 'msGridColumns', css: '-ms-grid-columns', classPrefix: '-ms-grid-columns' },
  { name: 'msGridRows', css: '-ms-grid-rows', classPrefix: '-ms-grid-rows' },
  { name: 'msHighContrastAdjust', css: '-ms-high-contrast-adjust', classPrefix: '-ms-high-contrast-adjust' },
  { name: 'msHyphenateLimitChars', css: '-ms-hyphenate-limit-chars', classPrefix: '-ms-hyphenate-limit-chars' },
  { name: 'msHyphenateLimitLines', css: '-ms-hyphenate-limit-lines', classPrefix: '-ms-hyphenate-limit-lines' },
  { name: 'msHyphenateLimitZone', css: '-ms-hyphenate-limit-zone', classPrefix: '-ms-hyphenate-limit-zone' },
  { name: 'msHyphens', css: '-ms-hyphens', classPrefix: '-ms-hyphens' },
  { name: 'msImeAlign', css: '-ms-ime-align', classPrefix: '-ms-ime-align' },
  { name: 'msImeMode', css: '-ms-ime-mode', classPrefix: '-ms-ime-mode' },
  { name: 'msLineBreak', css: '-ms-line-break', classPrefix: '-ms-line-break' },
  { name: 'msOrder', css: '-ms-order', classPrefix: '-ms-order' },
  { name: 'msOverflowStyle', css: '-ms-overflow-style', classPrefix: '-ms-overflow-style' },
  { name: 'msOverflowX', css: '-ms-overflow-x', classPrefix: '-ms-overflow-x' },
  { name: 'msOverflowY', css: '-ms-overflow-y', classPrefix: '-ms-overflow-y' },
  { name: 'msScrollChaining', css: '-ms-scroll-chaining', classPrefix: '-ms-scroll-chaining' },
  { name: 'msScrollLimit', css: '-ms-scroll-limit', classPrefix: '-ms-scroll-limit' },
  { name: 'msScrollLimitXMax', css: '-ms-scroll-limit-xmax', classPrefix: '-ms-scroll-limit-xmax' },
  { name: 'msScrollLimitXMin', css: '-ms-scroll-limit-xmin', classPrefix: '-ms-scroll-limit-xmin' },
  { name: 'msScrollLimitYMax', css: '-ms-scroll-limit-ymax', classPrefix: '-ms-scroll-limit-ymax' },
  { name: 'msScrollLimitYMin', css: '-ms-scroll-limit-ymin', classPrefix: '-ms-scroll-limit-ymin' },
  { name: 'msScrollRails', css: '-ms-scroll-rails', classPrefix: '-ms-scroll-rails' },
  { name: 'msScrollSnapPointsX', css: '-ms-scroll-snap-points-x', classPrefix: '-ms-scroll-snap-points-x' },
  { name: 'msScrollSnapPointsY', css: '-ms-scroll-snap-points-y', classPrefix: '-ms-scroll-snap-points-y' },
  { name: 'msScrollSnapType', css: '-ms-scroll-snap-type', classPrefix: '-ms-scroll-snap-type' },
  { name: 'msScrollSnapX', css: '-ms-scroll-snap-x', classPrefix: '-ms-scroll-snap-x' },
  { name: 'msScrollSnapY', css: '-ms-scroll-snap-y', classPrefix: '-ms-scroll-snap-y' },
  { name: 'msScrollTranslation', css: '-ms-scroll-translation', classPrefix: '-ms-scroll-translation' },
  { name: 'msScrollbar3dlightColor', css: '-ms-scrollbar-3dlight-color', classPrefix: '-ms-scrollbar-3dlight-color', color: true },
  { name: 'msScrollbarArrowColor', css: '-ms-scrollbar-arrow-color', classPrefix: '-ms-scrollbar-arrow-color', color: true },
  { name: 'msScrollbarBaseColor', css: '-ms-scrollbar-base-color', classPrefix: '-ms-scrollbar-base-color', color: true },
  { name: 'msScrollbarDarkshadowColor', css: '-ms-scrollbar-darkshadow-color', classPrefix: '-ms-scrollbar-darkshadow-color', color: true },
  { name: 'msScrollbarFaceColor', css: '-ms-scrollbar-face-color', classPrefix: '-ms-scrollbar-face-color', color: true },
  { name: 'msScrollbarHighlightColor', css: '-ms-scrollbar-highlight-color', classPrefix: '-ms-scrollbar-highlight-color', color: true },
  { name: 'msScrollbarShadowColor', css: '-ms-scrollbar-shadow-color', classPrefix: '-ms-scrollbar-shadow-color', color: true },
  { name: 'msScrollbarTrackColor', css: '-ms-scrollbar-track-color', classPrefix: '-ms-scrollbar-track-color', color: true },
  { name: 'msTextAutospace', css: '-ms-text-autospace', classPrefix: '-ms-text-autospace' },
  { name: 'msTextCombineHorizontal', css: '-ms-text-combine-horizontal', classPrefix: '-ms-text-combine-horizontal' },
  { name: 'msTextOverflow', css: '-ms-text-overflow', classPrefix: '-ms-text-overflow' },
  { name: 'msTouchAction', css: '-ms-touch-action', classPrefix: '-ms-touch-action' },
  { name: 'msTouchSelect', css: '-ms-touch-select', classPrefix: '-ms-touch-select' },
  { name: 'msTransform', css: '-ms-transform', classPrefix: '-ms-transform' },
  { name: 'msTransformOrigin', css: '-ms-transform-origin', classPrefix: '-ms-transform-origin' },
  { name: 'msTransition', css: '-ms-transition', classPrefix: '-ms-transition' },
  { name: 'msTransitionDelay', css: '-ms-transition-delay', classPrefix: '-ms-transition-delay' },
  { name: 'msTransitionDuration', css: '-ms-transition-duration', classPrefix: '-ms-transition-duration' },
  { name: 'msTransitionProperty', css: '-ms-transition-property', classPrefix: '-ms-transition-property' },
  { name: 'msTransitionTimingFunction', css: '-ms-transition-timing-function', classPrefix: '-ms-transition-timing-function' },
  { name: 'msUserSelect', css: '-ms-user-select', classPrefix: '-ms-user-select' },
  { name: 'msWordBreak', css: '-ms-word-break', classPrefix: '-ms-word-break' },
  { name: 'msWrapFlow', css: '-ms-wrap-flow', classPrefix: '-ms-wrap-flow' },
  { name: 'msWrapMargin', css: '-ms-wrap-margin', classPrefix: '-ms-wrap-margin' },
  { name: 'msWrapThrough', css: '-ms-wrap-through', classPrefix: '-ms-wrap-through' },
  { name: 'msWritingMode', css: '-ms-writing-mode', classPrefix: '-ms-writing-mode' },
  { name: 'webkitBackdropFilter', css: '-webkit-backdrop-filter', classPrefix: '-webkit-backdrop-filter' },
  { name: 'webkitBorderBefore', css: '-webkit-border-before', classPrefix: '-webkit-border-before' },
  { name: 'webkitBorderBeforeColor', css: '-webkit-border-before-color', classPrefix: '-webkit-border-before-color', color: true },
  { name: 'webkitBorderBeforeStyle', css: '-webkit-border-before-style', classPrefix: '-webkit-border-before-style' },
  { name: 'webkitBorderBeforeWidth', css: '-webkit-border-before-width', classPrefix: '-webkit-border-before-width' },
  { name: 'webkitBorderImage', css: '-webkit-border-image', classPrefix: '-webkit-border-image' },
  { name: 'webkitBorderImageSlice', css: '-webkit-border-image-slice', classPrefix: '-webkit-border-image-slice' },
  { name: 'webkitBoxDecorationBreak', css: '-webkit-box-decoration-break', classPrefix: '-webkit-box-decoration-break' },
  { name: 'webkitBoxDirection', css: '-webkit-box-direction', classPrefix: '-webkit-box-direction' },
  { name: 'webkitBoxFlexGroup', css: '-webkit-box-flex-group', classPrefix: '-webkit-box-flex-group' },
  { name: 'webkitBoxLines', css: '-webkit-box-lines', classPrefix: '-webkit-box-lines' },
  { name: 'webkitBoxReflect', css: '-webkit-box-reflect', classPrefix: '-webkit-box-reflect' },
  { name: 'webkitClipPath', css: '-webkit-clip-path', classPrefix: '-webkit-clip-path' },
  { name: 'webkitColumnCount', css: '-webkit-column-count', classPrefix: '-webkit-column-count' },
  { name: 'webkitColumnFill', css: '-webkit-column-fill', classPrefix: '-webkit-column-fill' },
  { name: 'webkitColumnRule', css: '-webkit-column-rule', classPrefix: '-webkit-column-rule' },
  { name: 'webkitColumnRuleColor', css: '-webkit-column-rule-color', classPrefix: '-webkit-column-rule-color', color: true },
  { name: 'webkitColumnRuleStyle', css: '-webkit-column-rule-style', classPrefix: '-webkit-column-rule-style' },
  { name: 'webkitColumnRuleWidth', css: '-webkit-column-rule-width', classPrefix: '-webkit-column-rule-width' },
  { name: 'webkitColumnSpan', css: '-webkit-column-span', classPrefix: '-webkit-column-span' },
  { name: 'webkitColumnWidth', css: '-webkit-column-width', classPrefix: '-webkit-column-width' },
  { name: 'webkitColumns', css: '-webkit-columns', classPrefix: '-webkit-columns' },
  { name: 'webkitFontFeatureSettings', css: '-webkit-font-feature-settings', classPrefix: '-webkit-font-feature-settings' },
  { name: 'webkitFontKerning', css: '-webkit-font-kerning', classPrefix: '-webkit-font-kerning' },
  { name: 'webkitFontSmoothing', css: '-webkit-font-smoothing', classPrefix: '-webkit-font-smoothing' },
  { name: 'webkitFontVariantLigatures', css: '-webkit-font-variant-ligatures', classPrefix: '-webkit-font-variant-ligatures' },
  { name: 'webkitHyphenateCharacter', css: '-webkit-hyphenate-character', classPrefix: '-webkit-hyphenate-character' },
  { name: 'webkitHyphens', css: '-webkit-hyphens', classPrefix: '-webkit-hyphens' },
  { name: 'webkitInitialLetter', css: '-webkit-initial-letter', classPrefix: '-webkit-initial-letter' },
  { name: 'webkitLineBreak', css: '-webkit-line-break', classPrefix: '-webkit-line-break' },
  { name: 'webkitLogicalHeight', css: '-webkit-logical-height', classPrefix: '-webkit-logical-height' },
  { name: 'webkitLogicalWidth', css: '-webkit-logical-width', classPrefix: '-webkit-logical-width' },
  { name: 'webkitMarginEnd', css: '-webkit-margin-end', classPrefix: '-webkit-margin-end' },
  { name: 'webkitMarginStart', css: '-webkit-margin-start', classPrefix: '-webkit-margin-start' },
  { name: 'webkitMaskAttachment', css: '-webkit-mask-attachment', classPrefix: '-webkit-mask-attachment' },
  { name: 'webkitMaskPositionX', css: '-webkit-mask-position-x', classPrefix: '-webkit-mask-position-x' },
  { name: 'webkitMaskPositionY', css: '-webkit-mask-position-y', classPrefix: '-webkit-mask-position-y' },
  { name: 'webkitMaskRepeatX', css: '-webkit-mask-repeat-x', classPrefix: '-webkit-mask-repeat-x' },
  { name: 'webkitMaskRepeatY', css: '-webkit-mask-repeat-y', classPrefix: '-webkit-mask-repeat-y' },
  { name: 'webkitMaxInlineSize', css: '-webkit-max-inline-size', classPrefix: '-webkit-max-inline-size' },
  { name: 'webkitOverflowScrolling', css: '-webkit-overflow-scrolling', classPrefix: '-webkit-overflow-scrolling' },
  { name: 'webkitPaddingEnd', css: '-webkit-padding-end', classPrefix: '-webkit-padding-end' },
  { name: 'webkitPaddingStart', css: '-webkit-padding-start', classPrefix: '-webkit-padding-start' },
  { name: 'webkitPrintColorAdjust', css: '-webkit-print-color-adjust', classPrefix: '-webkit-print-color-adjust' },
  { name: 'webkitRubyPosition', css: '-webkit-ruby-position', classPrefix: '-webkit-ruby-position' },
  { name: 'webkitScrollSnapType', css: '-webkit-scroll-snap-type', classPrefix: '-webkit-scroll-snap-type' },
  { name: 'webkitShapeMargin', css: '-webkit-shape-margin', classPrefix: '-webkit-shape-margin' },
  { name: 'webkitTapHighlightColor', css: '-webkit-tap-highlight-color', classPrefix: '-webkit-tap-highlight-color', color: true },
  { name: 'webkitTextCombine', css: '-webkit-text-combine', classPrefix: '-webkit-text-combine' },
  { name: 'webkitTextDecorationColor', css: '-webkit-text-decoration-color', classPrefix: '-webkit-text-decoration-color', color: true },
  { name: 'webkitTextDecorationLine', css: '-webkit-text-decoration-line', classPrefix: '-webkit-text-decoration-line' },
  { name: 'webkitTextDecorationSkip', css: '-webkit-text-decoration-skip', classPrefix: '-webkit-text-decoration-skip' },
  { name: 'webkitTextDecorationStyle', css: '-webkit-text-decoration-style', classPrefix: '-webkit-text-decoration-style' },
  { name: 'webkitTextEmphasis', css: '-webkit-text-emphasis', classPrefix: '-webkit-text-emphasis' },
  { name: 'webkitTextEmphasisColor', css: '-webkit-text-emphasis-color', classPrefix: '-webkit-text-emphasis-color', color: true },
  { name: 'webkitTextEmphasisPosition', css: '-webkit-text-emphasis-position', classPrefix: '-webkit-text-emphasis-position' },
  { name: 'webkitTextEmphasisStyle', css: '-webkit-text-emphasis-style', classPrefix: '-webkit-text-emphasis-style' },
  { name: 'webkitTextOrientation', css: '-webkit-text-orientation', classPrefix: '-webkit-text-orientation' },
  { name: 'webkitTextUnderlinePosition', css: '-webkit-text-underline-position', classPrefix: '-webkit-text-underline-position' },
  { name: 'webkitTouchCallout', css: '-webkit-touch-callout', classPrefix: '-webkit-touch-callout' },
  { name: 'webkitUserModify', css: '-webkit-user-modify', classPrefix: '-webkit-user-modify' },
  { name: 'webkitWritingMode', css: '-webkit-writing-mode', classPrefix: '-webkit-writing-mode' },
] as const satisfies readonly ExtensionProp[];

export const VENDOR_ALIASES: readonly VendorAlias[] = [
  { alias: 'MozAnimation', canonical: 'mozAnimation' },
  { alias: 'MozAnimationDelay', canonical: 'mozAnimationDelay' },
  { alias: 'MozAnimationDirection', canonical: 'mozAnimationDirection' },
  { alias: 'MozAnimationDuration', canonical: 'mozAnimationDuration' },
  { alias: 'MozAnimationFillMode', canonical: 'mozAnimationFillMode' },
  { alias: 'MozAnimationIterationCount', canonical: 'mozAnimationIterationCount' },
  { alias: 'MozAnimationName', canonical: 'mozAnimationName' },
  { alias: 'MozAnimationPlayState', canonical: 'mozAnimationPlayState' },
  { alias: 'MozAnimationTimingFunction', canonical: 'mozAnimationTimingFunction' },
  { alias: 'MozAppearance', canonical: 'mozAppearance' },
  { alias: 'MozBackfaceVisibility', canonical: 'mozBackfaceVisibility' },
  { alias: 'MozBackgroundClip', canonical: 'mozBackgroundClip' },
  { alias: 'MozBackgroundOrigin', canonical: 'mozBackgroundOrigin' },
  { alias: 'MozBackgroundSize', canonical: 'mozBackgroundSize' },
  { alias: 'MozBinding', canonical: 'mozBinding' },
  { alias: 'MozBorderBottomColors', canonical: 'mozBorderBottomColors' },
  { alias: 'MozBorderEndColor', canonical: 'mozBorderEndColor' },
  { alias: 'MozBorderEndStyle', canonical: 'mozBorderEndStyle' },
  { alias: 'MozBorderEndWidth', canonical: 'mozBorderEndWidth' },
  { alias: 'MozBorderImage', canonical: 'mozBorderImage' },
  { alias: 'MozBorderLeftColors', canonical: 'mozBorderLeftColors' },
  { alias: 'MozBorderRadius', canonical: 'mozBorderRadius' },
  { alias: 'MozBorderRadiusBottomleft', canonical: 'mozBorderRadiusBottomleft' },
  { alias: 'MozBorderRadiusBottomright', canonical: 'mozBorderRadiusBottomright' },
  { alias: 'MozBorderRadiusTopleft', canonical: 'mozBorderRadiusTopleft' },
  { alias: 'MozBorderRadiusTopright', canonical: 'mozBorderRadiusTopright' },
  { alias: 'MozBorderRightColors', canonical: 'mozBorderRightColors' },
  { alias: 'MozBorderStartColor', canonical: 'mozBorderStartColor' },
  { alias: 'MozBorderStartStyle', canonical: 'mozBorderStartStyle' },
  { alias: 'MozBorderTopColors', canonical: 'mozBorderTopColors' },
  { alias: 'MozBoxAlign', canonical: 'mozBoxAlign' },
  { alias: 'MozBoxDirection', canonical: 'mozBoxDirection' },
  { alias: 'MozBoxFlex', canonical: 'mozBoxFlex' },
  { alias: 'MozBoxOrdinalGroup', canonical: 'mozBoxOrdinalGroup' },
  { alias: 'MozBoxOrient', canonical: 'mozBoxOrient' },
  { alias: 'MozBoxPack', canonical: 'mozBoxPack' },
  { alias: 'MozBoxShadow', canonical: 'mozBoxShadow' },
  { alias: 'MozBoxSizing', canonical: 'mozBoxSizing' },
  { alias: 'MozColumnCount', canonical: 'mozColumnCount' },
  { alias: 'MozColumnFill', canonical: 'mozColumnFill' },
  { alias: 'MozColumnRule', canonical: 'mozColumnRule' },
  { alias: 'MozColumnRuleColor', canonical: 'mozColumnRuleColor' },
  { alias: 'MozColumnRuleStyle', canonical: 'mozColumnRuleStyle' },
  { alias: 'MozColumnRuleWidth', canonical: 'mozColumnRuleWidth' },
  { alias: 'MozColumnWidth', canonical: 'mozColumnWidth' },
  { alias: 'MozColumns', canonical: 'mozColumns' },
  { alias: 'MozContextProperties', canonical: 'mozContextProperties' },
  { alias: 'MozFloatEdge', canonical: 'mozFloatEdge' },
  { alias: 'MozFontFeatureSettings', canonical: 'mozFontFeatureSettings' },
  { alias: 'MozFontLanguageOverride', canonical: 'mozFontLanguageOverride' },
  { alias: 'MozForceBrokenImageIcon', canonical: 'mozForceBrokenImageIcon' },
  { alias: 'MozHyphens', canonical: 'mozHyphens' },
  { alias: 'MozMarginEnd', canonical: 'mozMarginEnd' },
  { alias: 'MozMarginStart', canonical: 'mozMarginStart' },
  { alias: 'MozOpacity', canonical: 'mozOpacity' },
  { alias: 'MozOrient', canonical: 'mozOrient' },
  { alias: 'MozOsxFontSmoothing', canonical: 'mozOsxFontSmoothing' },
  { alias: 'MozOutline', canonical: 'mozOutline' },
  { alias: 'MozOutlineColor', canonical: 'mozOutlineColor' },
  { alias: 'MozOutlineRadius', canonical: 'mozOutlineRadius' },
  { alias: 'MozOutlineRadiusBottomleft', canonical: 'mozOutlineRadiusBottomleft' },
  { alias: 'MozOutlineRadiusBottomright', canonical: 'mozOutlineRadiusBottomright' },
  { alias: 'MozOutlineRadiusTopleft', canonical: 'mozOutlineRadiusTopleft' },
  { alias: 'MozOutlineRadiusTopright', canonical: 'mozOutlineRadiusTopright' },
  { alias: 'MozOutlineStyle', canonical: 'mozOutlineStyle' },
  { alias: 'MozOutlineWidth', canonical: 'mozOutlineWidth' },
  { alias: 'MozPaddingEnd', canonical: 'mozPaddingEnd' },
  { alias: 'MozPaddingStart', canonical: 'mozPaddingStart' },
  { alias: 'MozPerspective', canonical: 'mozPerspective' },
  { alias: 'MozPerspectiveOrigin', canonical: 'mozPerspectiveOrigin' },
  { alias: 'MozStackSizing', canonical: 'mozStackSizing' },
  { alias: 'MozTabSize', canonical: 'mozTabSize' },
  { alias: 'MozTextAlignLast', canonical: 'mozTextAlignLast' },
  { alias: 'MozTextBlink', canonical: 'mozTextBlink' },
  { alias: 'MozTextDecorationColor', canonical: 'mozTextDecorationColor' },
  { alias: 'MozTextDecorationLine', canonical: 'mozTextDecorationLine' },
  { alias: 'MozTextDecorationStyle', canonical: 'mozTextDecorationStyle' },
  { alias: 'MozTextSizeAdjust', canonical: 'mozTextSizeAdjust' },
  { alias: 'MozTransform', canonical: 'mozTransform' },
  { alias: 'MozTransformOrigin', canonical: 'mozTransformOrigin' },
  { alias: 'MozTransformStyle', canonical: 'mozTransformStyle' },
  { alias: 'MozTransition', canonical: 'mozTransition' },
  { alias: 'MozTransitionDelay', canonical: 'mozTransitionDelay' },
  { alias: 'MozTransitionDuration', canonical: 'mozTransitionDuration' },
  { alias: 'MozTransitionProperty', canonical: 'mozTransitionProperty' },
  { alias: 'MozTransitionTimingFunction', canonical: 'mozTransitionTimingFunction' },
  { alias: 'MozUserFocus', canonical: 'mozUserFocus' },
  { alias: 'MozUserInput', canonical: 'mozUserInput' },
  { alias: 'MozUserModify', canonical: 'mozUserModify' },
  { alias: 'MozUserSelect', canonical: 'mozUserSelect' },
  { alias: 'MozWindowDragging', canonical: 'mozWindowDragging' },
  { alias: 'MozWindowShadow', canonical: 'mozWindowShadow' },
  { alias: 'MsAccelerator', canonical: 'msAccelerator' },
  { alias: 'MsBlockProgression', canonical: 'msBlockProgression' },
  { alias: 'MsContentZoomChaining', canonical: 'msContentZoomChaining' },
  { alias: 'MsContentZoomLimit', canonical: 'msContentZoomLimit' },
  { alias: 'MsContentZoomLimitMax', canonical: 'msContentZoomLimitMax' },
  { alias: 'MsContentZoomLimitMin', canonical: 'msContentZoomLimitMin' },
  { alias: 'MsContentZoomSnap', canonical: 'msContentZoomSnap' },
  { alias: 'MsContentZoomSnapPoints', canonical: 'msContentZoomSnapPoints' },
  { alias: 'MsContentZoomSnapType', canonical: 'msContentZoomSnapType' },
  { alias: 'MsContentZooming', canonical: 'msContentZooming' },
  { alias: 'MsFilter', canonical: 'msFilter' },
  { alias: 'MsFlex', canonical: 'msFlex' },
  { alias: 'MsFlexDirection', canonical: 'msFlexDirection' },
  { alias: 'MsFlexPositive', canonical: 'msFlexPositive' },
  { alias: 'MsFlowFrom', canonical: 'msFlowFrom' },
  { alias: 'MsFlowInto', canonical: 'msFlowInto' },
  { alias: 'MsGridColumns', canonical: 'msGridColumns' },
  { alias: 'MsGridRows', canonical: 'msGridRows' },
  { alias: 'MsHighContrastAdjust', canonical: 'msHighContrastAdjust' },
  { alias: 'MsHyphenateLimitChars', canonical: 'msHyphenateLimitChars' },
  { alias: 'MsHyphenateLimitLines', canonical: 'msHyphenateLimitLines' },
  { alias: 'MsHyphenateLimitZone', canonical: 'msHyphenateLimitZone' },
  { alias: 'MsHyphens', canonical: 'msHyphens' },
  { alias: 'MsImeAlign', canonical: 'msImeAlign' },
  { alias: 'MsImeMode', canonical: 'msImeMode' },
  { alias: 'MsLineBreak', canonical: 'msLineBreak' },
  { alias: 'MsOrder', canonical: 'msOrder' },
  { alias: 'MsOverflowStyle', canonical: 'msOverflowStyle' },
  { alias: 'MsOverflowX', canonical: 'msOverflowX' },
  { alias: 'MsOverflowY', canonical: 'msOverflowY' },
  { alias: 'MsScrollChaining', canonical: 'msScrollChaining' },
  { alias: 'MsScrollLimit', canonical: 'msScrollLimit' },
  { alias: 'MsScrollLimitXMax', canonical: 'msScrollLimitXMax' },
  { alias: 'MsScrollLimitXMin', canonical: 'msScrollLimitXMin' },
  { alias: 'MsScrollLimitYMax', canonical: 'msScrollLimitYMax' },
  { alias: 'MsScrollLimitYMin', canonical: 'msScrollLimitYMin' },
  { alias: 'MsScrollRails', canonical: 'msScrollRails' },
  { alias: 'MsScrollSnapPointsX', canonical: 'msScrollSnapPointsX' },
  { alias: 'MsScrollSnapPointsY', canonical: 'msScrollSnapPointsY' },
  { alias: 'MsScrollSnapType', canonical: 'msScrollSnapType' },
  { alias: 'MsScrollSnapX', canonical: 'msScrollSnapX' },
  { alias: 'MsScrollSnapY', canonical: 'msScrollSnapY' },
  { alias: 'MsScrollTranslation', canonical: 'msScrollTranslation' },
  { alias: 'MsScrollbar3dlightColor', canonical: 'msScrollbar3dlightColor' },
  { alias: 'MsScrollbarArrowColor', canonical: 'msScrollbarArrowColor' },
  { alias: 'MsScrollbarBaseColor', canonical: 'msScrollbarBaseColor' },
  { alias: 'MsScrollbarDarkshadowColor', canonical: 'msScrollbarDarkshadowColor' },
  { alias: 'MsScrollbarFaceColor', canonical: 'msScrollbarFaceColor' },
  { alias: 'MsScrollbarHighlightColor', canonical: 'msScrollbarHighlightColor' },
  { alias: 'MsScrollbarShadowColor', canonical: 'msScrollbarShadowColor' },
  { alias: 'MsScrollbarTrackColor', canonical: 'msScrollbarTrackColor' },
  { alias: 'MsTextAutospace', canonical: 'msTextAutospace' },
  { alias: 'MsTextCombineHorizontal', canonical: 'msTextCombineHorizontal' },
  { alias: 'MsTextOverflow', canonical: 'msTextOverflow' },
  { alias: 'MsTouchAction', canonical: 'msTouchAction' },
  { alias: 'MsTouchSelect', canonical: 'msTouchSelect' },
  { alias: 'MsTransform', canonical: 'msTransform' },
  { alias: 'MsTransformOrigin', canonical: 'msTransformOrigin' },
  { alias: 'MsTransition', canonical: 'msTransition' },
  { alias: 'MsTransitionDelay', canonical: 'msTransitionDelay' },
  { alias: 'MsTransitionDuration', canonical: 'msTransitionDuration' },
  { alias: 'MsTransitionProperty', canonical: 'msTransitionProperty' },
  { alias: 'MsTransitionTimingFunction', canonical: 'msTransitionTimingFunction' },
  { alias: 'MsUserSelect', canonical: 'msUserSelect' },
  { alias: 'MsWordBreak', canonical: 'msWordBreak' },
  { alias: 'MsWrapFlow', canonical: 'msWrapFlow' },
  { alias: 'MsWrapMargin', canonical: 'msWrapMargin' },
  { alias: 'MsWrapThrough', canonical: 'msWrapThrough' },
  { alias: 'MsWritingMode', canonical: 'msWritingMode' },
  { alias: 'WebkitAlignContent', canonical: 'webkitAlignContent' },
  { alias: 'WebkitAlignItems', canonical: 'webkitAlignItems' },
  { alias: 'WebkitAlignSelf', canonical: 'webkitAlignSelf' },
  { alias: 'WebkitAnimation', canonical: 'webkitAnimation' },
  { alias: 'WebkitAnimationDelay', canonical: 'webkitAnimationDelay' },
  { alias: 'WebkitAnimationDirection', canonical: 'webkitAnimationDirection' },
  { alias: 'WebkitAnimationDuration', canonical: 'webkitAnimationDuration' },
  { alias: 'WebkitAnimationFillMode', canonical: 'webkitAnimationFillMode' },
  { alias: 'WebkitAnimationIterationCount', canonical: 'webkitAnimationIterationCount' },
  { alias: 'WebkitAnimationName', canonical: 'webkitAnimationName' },
  { alias: 'WebkitAnimationPlayState', canonical: 'webkitAnimationPlayState' },
  { alias: 'WebkitAnimationTimingFunction', canonical: 'webkitAnimationTimingFunction' },
  { alias: 'WebkitAppearance', canonical: 'webkitAppearance' },
  { alias: 'WebkitBackdropFilter', canonical: 'webkitBackdropFilter' },
  { alias: 'WebkitBackfaceVisibility', canonical: 'webkitBackfaceVisibility' },
  { alias: 'WebkitBackgroundClip', canonical: 'webkitBackgroundClip' },
  { alias: 'WebkitBackgroundOrigin', canonical: 'webkitBackgroundOrigin' },
  { alias: 'WebkitBackgroundSize', canonical: 'webkitBackgroundSize' },
  { alias: 'WebkitBorderBefore', canonical: 'webkitBorderBefore' },
  { alias: 'WebkitBorderBeforeColor', canonical: 'webkitBorderBeforeColor' },
  { alias: 'WebkitBorderBeforeStyle', canonical: 'webkitBorderBeforeStyle' },
  { alias: 'WebkitBorderBeforeWidth', canonical: 'webkitBorderBeforeWidth' },
  { alias: 'WebkitBorderBottomLeftRadius', canonical: 'webkitBorderBottomLeftRadius' },
  { alias: 'WebkitBorderBottomRightRadius', canonical: 'webkitBorderBottomRightRadius' },
  { alias: 'WebkitBorderImage', canonical: 'webkitBorderImage' },
  { alias: 'WebkitBorderImageSlice', canonical: 'webkitBorderImageSlice' },
  { alias: 'WebkitBorderRadius', canonical: 'webkitBorderRadius' },
  { alias: 'WebkitBorderTopLeftRadius', canonical: 'webkitBorderTopLeftRadius' },
  { alias: 'WebkitBorderTopRightRadius', canonical: 'webkitBorderTopRightRadius' },
  { alias: 'WebkitBoxAlign', canonical: 'webkitBoxAlign' },
  { alias: 'WebkitBoxDecorationBreak', canonical: 'webkitBoxDecorationBreak' },
  { alias: 'WebkitBoxDirection', canonical: 'webkitBoxDirection' },
  { alias: 'WebkitBoxFlex', canonical: 'webkitBoxFlex' },
  { alias: 'WebkitBoxFlexGroup', canonical: 'webkitBoxFlexGroup' },
  { alias: 'WebkitBoxLines', canonical: 'webkitBoxLines' },
  { alias: 'WebkitBoxOrdinalGroup', canonical: 'webkitBoxOrdinalGroup' },
  { alias: 'WebkitBoxOrient', canonical: 'webkitBoxOrient' },
  { alias: 'WebkitBoxPack', canonical: 'webkitBoxPack' },
  { alias: 'WebkitBoxReflect', canonical: 'webkitBoxReflect' },
  { alias: 'WebkitBoxShadow', canonical: 'webkitBoxShadow' },
  { alias: 'WebkitBoxSizing', canonical: 'webkitBoxSizing' },
  { alias: 'WebkitClipPath', canonical: 'webkitClipPath' },
  { alias: 'WebkitColumnCount', canonical: 'webkitColumnCount' },
  { alias: 'WebkitColumnFill', canonical: 'webkitColumnFill' },
  { alias: 'WebkitColumnRule', canonical: 'webkitColumnRule' },
  { alias: 'WebkitColumnRuleColor', canonical: 'webkitColumnRuleColor' },
  { alias: 'WebkitColumnRuleStyle', canonical: 'webkitColumnRuleStyle' },
  { alias: 'WebkitColumnRuleWidth', canonical: 'webkitColumnRuleWidth' },
  { alias: 'WebkitColumnSpan', canonical: 'webkitColumnSpan' },
  { alias: 'WebkitColumnWidth', canonical: 'webkitColumnWidth' },
  { alias: 'WebkitColumns', canonical: 'webkitColumns' },
  { alias: 'WebkitFilter', canonical: 'webkitFilter' },
  { alias: 'WebkitFlex', canonical: 'webkitFlex' },
  { alias: 'WebkitFlexBasis', canonical: 'webkitFlexBasis' },
  { alias: 'WebkitFlexDirection', canonical: 'webkitFlexDirection' },
  { alias: 'WebkitFlexFlow', canonical: 'webkitFlexFlow' },
  { alias: 'WebkitFlexGrow', canonical: 'webkitFlexGrow' },
  { alias: 'WebkitFlexShrink', canonical: 'webkitFlexShrink' },
  { alias: 'WebkitFlexWrap', canonical: 'webkitFlexWrap' },
  { alias: 'WebkitFontFeatureSettings', canonical: 'webkitFontFeatureSettings' },
  { alias: 'WebkitFontKerning', canonical: 'webkitFontKerning' },
  { alias: 'WebkitFontSmoothing', canonical: 'webkitFontSmoothing' },
  { alias: 'WebkitFontVariantLigatures', canonical: 'webkitFontVariantLigatures' },
  { alias: 'WebkitHyphenateCharacter', canonical: 'webkitHyphenateCharacter' },
  { alias: 'WebkitHyphens', canonical: 'webkitHyphens' },
  { alias: 'WebkitInitialLetter', canonical: 'webkitInitialLetter' },
  { alias: 'WebkitJustifyContent', canonical: 'webkitJustifyContent' },
  { alias: 'WebkitLineBreak', canonical: 'webkitLineBreak' },
  { alias: 'WebkitLineClamp', canonical: 'webkitLineClamp' },
  { alias: 'WebkitLogicalHeight', canonical: 'webkitLogicalHeight' },
  { alias: 'WebkitLogicalWidth', canonical: 'webkitLogicalWidth' },
  { alias: 'WebkitMarginEnd', canonical: 'webkitMarginEnd' },
  { alias: 'WebkitMarginStart', canonical: 'webkitMarginStart' },
  { alias: 'WebkitMask', canonical: 'webkitMask' },
  { alias: 'WebkitMaskAttachment', canonical: 'webkitMaskAttachment' },
  { alias: 'WebkitMaskBoxImage', canonical: 'webkitMaskBoxImage' },
  { alias: 'WebkitMaskBoxImageOutset', canonical: 'webkitMaskBoxImageOutset' },
  { alias: 'WebkitMaskBoxImageRepeat', canonical: 'webkitMaskBoxImageRepeat' },
  { alias: 'WebkitMaskBoxImageSlice', canonical: 'webkitMaskBoxImageSlice' },
  { alias: 'WebkitMaskBoxImageSource', canonical: 'webkitMaskBoxImageSource' },
  { alias: 'WebkitMaskBoxImageWidth', canonical: 'webkitMaskBoxImageWidth' },
  { alias: 'WebkitMaskClip', canonical: 'webkitMaskClip' },
  { alias: 'WebkitMaskComposite', canonical: 'webkitMaskComposite' },
  { alias: 'WebkitMaskImage', canonical: 'webkitMaskImage' },
  { alias: 'WebkitMaskOrigin', canonical: 'webkitMaskOrigin' },
  { alias: 'WebkitMaskPosition', canonical: 'webkitMaskPosition' },
  { alias: 'WebkitMaskPositionX', canonical: 'webkitMaskPositionX' },
  { alias: 'WebkitMaskPositionY', canonical: 'webkitMaskPositionY' },
  { alias: 'WebkitMaskRepeat', canonical: 'webkitMaskRepeat' },
  { alias: 'WebkitMaskRepeatX', canonical: 'webkitMaskRepeatX' },
  { alias: 'WebkitMaskRepeatY', canonical: 'webkitMaskRepeatY' },
  { alias: 'WebkitMaskSize', canonical: 'webkitMaskSize' },
  { alias: 'WebkitMaxInlineSize', canonical: 'webkitMaxInlineSize' },
  { alias: 'WebkitOrder', canonical: 'webkitOrder' },
  { alias: 'WebkitOverflowScrolling', canonical: 'webkitOverflowScrolling' },
  { alias: 'WebkitPaddingEnd', canonical: 'webkitPaddingEnd' },
  { alias: 'WebkitPaddingStart', canonical: 'webkitPaddingStart' },
  { alias: 'WebkitPerspective', canonical: 'webkitPerspective' },
  { alias: 'WebkitPerspectiveOrigin', canonical: 'webkitPerspectiveOrigin' },
  { alias: 'WebkitPrintColorAdjust', canonical: 'webkitPrintColorAdjust' },
  { alias: 'WebkitRubyPosition', canonical: 'webkitRubyPosition' },
  { alias: 'WebkitScrollSnapType', canonical: 'webkitScrollSnapType' },
  { alias: 'WebkitShapeMargin', canonical: 'webkitShapeMargin' },
  { alias: 'WebkitTapHighlightColor', canonical: 'webkitTapHighlightColor' },
  { alias: 'WebkitTextCombine', canonical: 'webkitTextCombine' },
  { alias: 'WebkitTextDecorationColor', canonical: 'webkitTextDecorationColor' },
  { alias: 'WebkitTextDecorationLine', canonical: 'webkitTextDecorationLine' },
  { alias: 'WebkitTextDecorationSkip', canonical: 'webkitTextDecorationSkip' },
  { alias: 'WebkitTextDecorationStyle', canonical: 'webkitTextDecorationStyle' },
  { alias: 'WebkitTextEmphasis', canonical: 'webkitTextEmphasis' },
  { alias: 'WebkitTextEmphasisColor', canonical: 'webkitTextEmphasisColor' },
  { alias: 'WebkitTextEmphasisPosition', canonical: 'webkitTextEmphasisPosition' },
  { alias: 'WebkitTextEmphasisStyle', canonical: 'webkitTextEmphasisStyle' },
  { alias: 'WebkitTextFillColor', canonical: 'webkitTextFillColor' },
  { alias: 'WebkitTextOrientation', canonical: 'webkitTextOrientation' },
  { alias: 'WebkitTextSizeAdjust', canonical: 'webkitTextSizeAdjust' },
  { alias: 'WebkitTextStroke', canonical: 'webkitTextStroke' },
  { alias: 'WebkitTextStrokeColor', canonical: 'webkitTextStrokeColor' },
  { alias: 'WebkitTextStrokeWidth', canonical: 'webkitTextStrokeWidth' },
  { alias: 'WebkitTextUnderlinePosition', canonical: 'webkitTextUnderlinePosition' },
  { alias: 'WebkitTouchCallout', canonical: 'webkitTouchCallout' },
  { alias: 'WebkitTransform', canonical: 'webkitTransform' },
  { alias: 'WebkitTransformOrigin', canonical: 'webkitTransformOrigin' },
  { alias: 'WebkitTransformStyle', canonical: 'webkitTransformStyle' },
  { alias: 'WebkitTransition', canonical: 'webkitTransition' },
  { alias: 'WebkitTransitionDelay', canonical: 'webkitTransitionDelay' },
  { alias: 'WebkitTransitionDuration', canonical: 'webkitTransitionDuration' },
  { alias: 'WebkitTransitionProperty', canonical: 'webkitTransitionProperty' },
  { alias: 'WebkitTransitionTimingFunction', canonical: 'webkitTransitionTimingFunction' },
  { alias: 'WebkitUserModify', canonical: 'webkitUserModify' },
  { alias: 'WebkitUserSelect', canonical: 'webkitUserSelect' },
  { alias: 'WebkitWritingMode', canonical: 'webkitWritingMode' },
];

export const VENDOR_UNITLESS: readonly string[] = [
  'mozAnimationIterationCount',
  'mozBoxFlex',
  'mozBoxOrdinalGroup',
  'mozColumnCount',
  'mozColumns',
  'mozOpacity',
  'mozTabSize',
  'msFlex',
  'msFlexPositive',
  'msOrder',
  'webkitAnimationIterationCount',
  'webkitBorderImageSlice',
  'webkitBoxFlex',
  'webkitBoxFlexGroup',
  'webkitBoxOrdinalGroup',
  'webkitColumnCount',
  'webkitColumns',
  'webkitFlex',
  'webkitFlexGrow',
  'webkitFlexShrink',
  'webkitLineClamp',
  'webkitOrder',
];
