//! Harvest `auto`/`none` validity tables and the kind gate.
//!
//! `auto` and `none` are the only Keyword values that are not CSS-wide, so
//! the canon kind gate narrows them to the props where each is valid CSS
//! (the tables below). Every other pair rides the `prop_accepts` gate
//! unchanged. Custom props pass: the validator skips `--*`, like resolve.

use canon::ValueKind;

/// Canonical props where `auto` is valid CSS, probed from css-tree's lexer —
/// the same oracle as the cssIsValid standing gauge, so gate and gauge
/// agree by construction. `auto` is the only Keyword value besides `none`
/// that is not CSS-wide. Sorted for binary search; regenerate on css-tree
/// upgrades (Forge Slice 4 generator, `/tmp` only).
const AUTO_PROPS: &[&str] = &[
    "accentColor",
    "alignSelf",
    "animationDuration",
    "animationName",
    "appearance",
    "aspectRatio",
    "backgroundSize",
    "baselineSource",
    "blockSize",
    "bottom",
    "breakAfter",
    "breakBefore",
    "breakInside",
    "caret",
    "caretAnimation",
    "caretColor",
    "caretShape",
    "clip",
    "colorScheme",
    "columnCount",
    "columnFill",
    "columnHeight",
    "columnWidth",
    "columnWrap",
    "containerName",
    "counterReset",
    "counterSet",
    "cursor",
    "filter",
    "flex",
    "flexBasis",
    "fontFamily",
    "fontKerning",
    "gridAutoColumns",
    "gridAutoRows",
    "gridColumnEnd",
    "gridColumnStart",
    "gridRowEnd",
    "gridRowStart",
    "gridTemplateRows",
    "height",
    "hyphens",
    "imageRendering",
    "inlineSize",
    "inset",
    "insetBlockEnd",
    "insetInlineEnd",
    "insetInlineStart",
    "interactivity",
    "isolation",
    "justifySelf",
    "left",
    "lineBreak",
    "listStyleType",
    "margin",
    "marginBottom",
    "marginInlineEnd",
    "marginInlineStart",
    "marginLeft",
    "marginRight",
    "marginTop",
    "maskSize",
    "minBlockSize",
    "minHeight",
    "minInlineSize",
    "minWidth",
    "mozAnimation",
    "mozColumnFill",
    "mozColumns",
    "mozHyphens",
    "mozOutline",
    "mozTransition",
    "mozUserInput",
    "msFlex",
    "msFlowFrom",
    "msFlowInto",
    "msGridColumns",
    "msGridRows",
    "msHyphens",
    "msImeAlign",
    "msImeMode",
    "msLineBreak",
    "msOverflowX",
    "msOverflowY",
    "msTouchAction",
    "msTransition",
    "msWrapFlow",
    "offsetAnchor",
    "offsetPosition",
    "offsetRotate",
    "outlineColor",
    "outlineStyle",
    "overflowAnchor",
    "overflowBlock",
    "overflowInline",
    "overflowX",
    "overflowY",
    "overlay",
    "page",
    "pointerEvents",
    "positionAnchor",
    "quotes",
    "right",
    "rubyMerge",
    "rubyOverhang",
    "scrollBehavior",
    "scrollPaddingLeft",
    "scrollPaddingRight",
    "scrollPaddingTop",
    "scrollbarColor",
    "scrollbarWidth",
    "shapeRendering",
    "speak",
    "tableLayout",
    "textAlignLast",
    "textAutospace",
    "textBox",
    "textBoxEdge",
    "textJustify",
    "textRendering",
    "textSizeAdjust",
    "textWrapStyle",
    "top",
    "touchAction",
    "userSelect",
    "voiceDuration",
    "voiceFamily",
    "webkitColumns",
    "webkitFilter",
    "webkitHyphens",
    "width",
    "willChange",
    "zIndex",
];

/// Canonical props where `none` is valid CSS (see `AUTO_PROPS`).
const NONE_PROPS: &[&str] = &[
    "anchorName",
    "anchorScope",
    "animationFillMode",
    "animationName",
    "appearance",
    "backdropFilter",
    "border",
    "borderBottomStyle",
    "borderLeftStyle",
    "borderRightStyle",
    "borderTopStyle",
    "clear",
    "clipPath",
    "colorScheme",
    "columnSpan",
    "contain",
    "containerName",
    "content",
    "counterReset",
    "counterSet",
    "cue",
    "cueAfter",
    "cueBefore",
    "cursor",
    "d",
    "display",
    "fill",
    "filter",
    "flex",
    "float",
    "fontFamily",
    "fontKerning",
    "grid",
    "gridColumnEnd",
    "gridColumnStart",
    "gridRowEnd",
    "gridRowStart",
    "gridTemplateRows",
    "hyphens",
    "listStyleType",
    "marginTrim",
    "markerEnd",
    "markerMid",
    "markerStart",
    "mask",
    "maskImage",
    "maxBlockSize",
    "maxHeight",
    "maxInlineSize",
    "maxLines",
    "maxWidth",
    "mozAnimation",
    "mozAppearance",
    "mozBinding",
    "mozBoxShadow",
    "mozColumnRule",
    "mozHyphens",
    "mozOutline",
    "mozTextBlink",
    "mozTransform",
    "mozTransition",
    "mozUserFocus",
    "mozUserInput",
    "mozUserSelect",
    "msFlex",
    "msFlowFrom",
    "msFlowInto",
    "msGridColumns",
    "msGridRows",
    "msHyphens",
    "msScrollRails",
    "msTouchAction",
    "msTouchSelect",
    "msTransform",
    "msTransition",
    "msUserSelect",
    "msWrapThrough",
    "objectFit",
    "objectViewBox",
    "offsetPath",
    "outlineStyle",
    "overflowAnchor",
    "overlay",
    "page",
    "pause",
    "pauseAfter",
    "pauseBefore",
    "perspective",
    "pointerEvents",
    "positionAnchor",
    "positionArea",
    "quotes",
    "resize",
    "rest",
    "restAfter",
    "restBefore",
    "rotate",
    "rubyOverhang",
    "scale",
    "scrollSnapAlign",
    "scrollSnapType",
    "scrollTimelineName",
    "scrollbarWidth",
    "shapeOutside",
    "stroke",
    "strokeDasharray",
    "textBox",
    "textBoxTrim",
    "textJustify",
    "textShadow",
    "textSizeAdjust",
    "textTransform",
    "timelineScope",
    "touchAction",
    "transform",
    "translate",
    "triggerScope",
    "userSelect",
    "vectorEffect",
    "voiceFamily",
    "voiceStress",
    "webkitFilter",
    "webkitHyphens",
    "willChange",
];

/// True when the pool value may mint onto the sink prop: the canon kind
/// gate, narrowed for `auto`/`none` (the only Keyword values that are not
/// CSS-wide) to the props where each is valid CSS. Custom props pass: the
/// validator skips `--*`, like resolve.
pub(crate) fn harvest_accepts(prop: &str, canonical: &str, kind: ValueKind, value: &str) -> bool {
    if !canon::prop_accepts(prop, kind) {
        return false;
    }
    if kind != ValueKind::Keyword {
        return true;
    }
    if !value.eq_ignore_ascii_case("auto") && !value.eq_ignore_ascii_case("none") {
        return true;
    }
    if prop.starts_with("--") {
        return true;
    }
    let table = if value.eq_ignore_ascii_case("auto") {
        AUTO_PROPS
    } else {
        NONE_PROPS
    };
    table.binary_search(&canonical).is_ok()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn validity_tables_stay_sorted() {
        for table in [AUTO_PROPS, NONE_PROPS] {
            let mut sorted = table.to_vec();
            sorted.sort_unstable();
            assert_eq!(table, sorted.as_slice());
        }
    }
}
