/** Generated. Run: node scripts/generate-primitives.cjs */

import { createPrimitive } from './createPrimitive'
import type { PrimitiveProps, PrimitiveElement } from './types.js'

import { abbrStyle, bStyle, blockquoteStyle, citeStyle, codeStyle, emStyle, h1Style, h2Style, h3Style, h4Style, h5Style, h6Style, iStyle, kbdStyle, markStyle, pStyle, preStyle, qStyle, sStyle, sampStyle, smallStyle, strongStyle, subStyle, supStyle, uStyle, varStyle } from '../system/recipes'

export { TAGS as HTML_TAGS, type Tag as HtmlTag } from './tags'
export type { PrimitiveElement, PrimitiveProps } from './types'


export type AProps = PrimitiveProps<'a'>
export type AbbrProps = PrimitiveProps<'abbr'>
export type AddressProps = PrimitiveProps<'address'>
export type AreaProps = PrimitiveProps<'area'>
export type ArticleProps = PrimitiveProps<'article'>
export type AsideProps = PrimitiveProps<'aside'>
export type AudioProps = PrimitiveProps<'audio'>
export type BProps = PrimitiveProps<'b'>
export type BdiProps = PrimitiveProps<'bdi'>
export type BdoProps = PrimitiveProps<'bdo'>
export type BlockquoteProps = PrimitiveProps<'blockquote'>
export type BrProps = PrimitiveProps<'br'>
export type ButtonProps = PrimitiveProps<'button'>
export type CanvasProps = PrimitiveProps<'canvas'>
export type CaptionProps = PrimitiveProps<'caption'>
export type CiteProps = PrimitiveProps<'cite'>
export type CodeProps = PrimitiveProps<'code'>
export type ColProps = PrimitiveProps<'col'>
export type ColgroupProps = PrimitiveProps<'colgroup'>
export type DataProps = PrimitiveProps<'data'>
export type DatalistProps = PrimitiveProps<'datalist'>
export type DdProps = PrimitiveProps<'dd'>
export type DelProps = PrimitiveProps<'del'>
export type DetailsProps = PrimitiveProps<'details'>
export type DfnProps = PrimitiveProps<'dfn'>
export type DialogProps = PrimitiveProps<'dialog'>
export type DivProps = PrimitiveProps<'div'>
export type DlProps = PrimitiveProps<'dl'>
export type DtProps = PrimitiveProps<'dt'>
export type EmProps = PrimitiveProps<'em'>
export type EmbedProps = PrimitiveProps<'embed'>
export type FieldsetProps = PrimitiveProps<'fieldset'>
export type FigcaptionProps = PrimitiveProps<'figcaption'>
export type FigureProps = PrimitiveProps<'figure'>
export type FooterProps = PrimitiveProps<'footer'>
export type FormProps = PrimitiveProps<'form'>
export type H1Props = PrimitiveProps<'h1'>
export type H2Props = PrimitiveProps<'h2'>
export type H3Props = PrimitiveProps<'h3'>
export type H4Props = PrimitiveProps<'h4'>
export type H5Props = PrimitiveProps<'h5'>
export type H6Props = PrimitiveProps<'h6'>
export type HeaderProps = PrimitiveProps<'header'>
export type HgroupProps = PrimitiveProps<'hgroup'>
export type HrProps = PrimitiveProps<'hr'>
export type IProps = PrimitiveProps<'i'>
export type IframeProps = PrimitiveProps<'iframe'>
export type ImgProps = PrimitiveProps<'img'>
export type InputProps = PrimitiveProps<'input'>
export type InsProps = PrimitiveProps<'ins'>
export type KbdProps = PrimitiveProps<'kbd'>
export type LabelProps = PrimitiveProps<'label'>
export type LegendProps = PrimitiveProps<'legend'>
export type LiProps = PrimitiveProps<'li'>
export type MainProps = PrimitiveProps<'main'>
export type MapProps = PrimitiveProps<'map'>
export type MarkProps = PrimitiveProps<'mark'>
export type MenuProps = PrimitiveProps<'menu'>
export type MeterProps = PrimitiveProps<'meter'>
export type NavProps = PrimitiveProps<'nav'>
export type ObjProps = PrimitiveProps<'object'>
export type OlProps = PrimitiveProps<'ol'>
export type OptgroupProps = PrimitiveProps<'optgroup'>
export type OptionProps = PrimitiveProps<'option'>
export type OutputProps = PrimitiveProps<'output'>
export type PProps = PrimitiveProps<'p'>
export type PictureProps = PrimitiveProps<'picture'>
export type PreProps = PrimitiveProps<'pre'>
export type ProgressProps = PrimitiveProps<'progress'>
export type QProps = PrimitiveProps<'q'>
export type RpProps = PrimitiveProps<'rp'>
export type RtProps = PrimitiveProps<'rt'>
export type RubyProps = PrimitiveProps<'ruby'>
export type SProps = PrimitiveProps<'s'>
export type SampProps = PrimitiveProps<'samp'>
export type SearchProps = PrimitiveProps<'search'>
export type SectionProps = PrimitiveProps<'section'>
export type SelectProps = PrimitiveProps<'select'>
export type SmallProps = PrimitiveProps<'small'>
export type SourceProps = PrimitiveProps<'source'>
export type SpanProps = PrimitiveProps<'span'>
export type StrongProps = PrimitiveProps<'strong'>
export type SubProps = PrimitiveProps<'sub'>
export type SummaryProps = PrimitiveProps<'summary'>
export type SupProps = PrimitiveProps<'sup'>
export type SvgProps = PrimitiveProps<'svg'>
export type TableProps = PrimitiveProps<'table'>
export type TbodyProps = PrimitiveProps<'tbody'>
export type TdProps = PrimitiveProps<'td'>
export type TextareaProps = PrimitiveProps<'textarea'>
export type TfootProps = PrimitiveProps<'tfoot'>
export type ThProps = PrimitiveProps<'th'>
export type TheadProps = PrimitiveProps<'thead'>
export type TimeProps = PrimitiveProps<'time'>
export type TrProps = PrimitiveProps<'tr'>
export type TrackProps = PrimitiveProps<'track'>
export type UProps = PrimitiveProps<'u'>
export type UlProps = PrimitiveProps<'ul'>
export type VarProps = PrimitiveProps<'var'>
export type VideoProps = PrimitiveProps<'video'>
export type WbrProps = PrimitiveProps<'wbr'>

export const A = createPrimitive('a', undefined)
export const Abbr = createPrimitive('abbr', abbrStyle())
export const Address = createPrimitive('address', undefined)
export const Area = createPrimitive('area', undefined)
export const Article = createPrimitive('article', undefined)
export const Aside = createPrimitive('aside', undefined)
export const Audio = createPrimitive('audio', undefined)
export const B = createPrimitive('b', bStyle())
export const Bdi = createPrimitive('bdi', undefined)
export const Bdo = createPrimitive('bdo', undefined)
export const Blockquote = createPrimitive('blockquote', blockquoteStyle())
export const Br = createPrimitive('br', undefined)
export const Button = createPrimitive('button', undefined)
export const Canvas = createPrimitive('canvas', undefined)
export const Caption = createPrimitive('caption', undefined)
export const Cite = createPrimitive('cite', citeStyle())
export const Code = createPrimitive('code', codeStyle())
export const Col = createPrimitive('col', undefined)
export const Colgroup = createPrimitive('colgroup', undefined)
export const Data = createPrimitive('data', undefined)
export const Datalist = createPrimitive('datalist', undefined)
export const Dd = createPrimitive('dd', undefined)
export const Del = createPrimitive('del', undefined)
export const Details = createPrimitive('details', undefined)
export const Dfn = createPrimitive('dfn', undefined)
export const Dialog = createPrimitive('dialog', undefined)
export const Div = createPrimitive('div', undefined)
export const Dl = createPrimitive('dl', undefined)
export const Dt = createPrimitive('dt', undefined)
export const Em = createPrimitive('em', emStyle())
export const Embed = createPrimitive('embed', undefined)
export const Fieldset = createPrimitive('fieldset', undefined)
export const Figcaption = createPrimitive('figcaption', undefined)
export const Figure = createPrimitive('figure', undefined)
export const Footer = createPrimitive('footer', undefined)
export const Form = createPrimitive('form', undefined)
export const H1 = createPrimitive('h1', h1Style())
export const H2 = createPrimitive('h2', h2Style())
export const H3 = createPrimitive('h3', h3Style())
export const H4 = createPrimitive('h4', h4Style())
export const H5 = createPrimitive('h5', h5Style())
export const H6 = createPrimitive('h6', h6Style())
export const Header = createPrimitive('header', undefined)
export const Hgroup = createPrimitive('hgroup', undefined)
export const Hr = createPrimitive('hr', undefined)
export const I = createPrimitive('i', iStyle())
export const Iframe = createPrimitive('iframe', undefined)
export const Img = createPrimitive('img', undefined)
export const Input = createPrimitive('input', undefined)
export const Ins = createPrimitive('ins', undefined)
export const Kbd = createPrimitive('kbd', kbdStyle())
export const Label = createPrimitive('label', undefined)
export const Legend = createPrimitive('legend', undefined)
export const Li = createPrimitive('li', undefined)
export const Main = createPrimitive('main', undefined)
export const Map = createPrimitive('map', undefined)
export const Mark = createPrimitive('mark', markStyle())
export const Menu = createPrimitive('menu', undefined)
export const Meter = createPrimitive('meter', undefined)
export const Nav = createPrimitive('nav', undefined)
export const Obj = createPrimitive('object', undefined)
export const Ol = createPrimitive('ol', undefined)
export const Optgroup = createPrimitive('optgroup', undefined)
export const Option = createPrimitive('option', undefined)
export const Output = createPrimitive('output', undefined)
export const P = createPrimitive('p', pStyle())
export const Picture = createPrimitive('picture', undefined)
export const Pre = createPrimitive('pre', preStyle())
export const Progress = createPrimitive('progress', undefined)
export const Q = createPrimitive('q', qStyle())
export const Rp = createPrimitive('rp', undefined)
export const Rt = createPrimitive('rt', undefined)
export const Ruby = createPrimitive('ruby', undefined)
export const S = createPrimitive('s', sStyle())
export const Samp = createPrimitive('samp', sampStyle())
export const Search = createPrimitive('search', undefined)
export const Section = createPrimitive('section', undefined)
export const Select = createPrimitive('select', undefined)
export const Small = createPrimitive('small', smallStyle())
export const Source = createPrimitive('source', undefined)
export const Span = createPrimitive('span', undefined)
export const Strong = createPrimitive('strong', strongStyle())
export const Sub = createPrimitive('sub', subStyle())
export const Summary = createPrimitive('summary', undefined)
export const Sup = createPrimitive('sup', supStyle())
export const Svg = createPrimitive('svg', undefined)
export const Table = createPrimitive('table', undefined)
export const Tbody = createPrimitive('tbody', undefined)
export const Td = createPrimitive('td', undefined)
export const Textarea = createPrimitive('textarea', undefined)
export const Tfoot = createPrimitive('tfoot', undefined)
export const Th = createPrimitive('th', undefined)
export const Thead = createPrimitive('thead', undefined)
export const Time = createPrimitive('time', undefined)
export const Tr = createPrimitive('tr', undefined)
export const Track = createPrimitive('track', undefined)
export const U = createPrimitive('u', uStyle())
export const Ul = createPrimitive('ul', undefined)
export const Var = createPrimitive('var', varStyle())
export const Video = createPrimitive('video', undefined)
export const Wbr = createPrimitive('wbr', undefined)