/** Generated. Run: node scripts/generate-primitives.cjs
 * styled[tag] + box pattern (r, container, font, weight) + recipes where available.
 */

import * as React from 'react'
import { forwardRef } from 'react'
import { splitProps } from '../system/helpers.js'
import { box } from '../system/patterns/box.js'
import { styled } from '../system/jsx/index.js'
import { abbrStyle, bStyle, blockquoteStyle, citeStyle, codeStyle, emStyle, h1Style, h2Style, h3Style, h4Style, h5Style, h6Style, iStyle, kbdStyle, markStyle, pStyle, preStyle, qStyle, sStyle, sampStyle, smallStyle, strongStyle, subStyle, supStyle, uStyle, varStyle } from '../system/recipes/index.js'
import type { PrimitiveElement, PrimitiveProps } from './types'

export { TAGS as HTML_TAGS, type Tag as HtmlTag } from './tags'
export type { PrimitiveElement, PrimitiveProps } from './types'

const BOX_KEYS = ['font', 'weight', 'container', 'r'] as const
const LAYER_KEYS = ['layer'] as const
const splitBoxProps = <T extends Record<string, unknown>>(props: T) => splitProps(props, BOX_KEYS)
const splitLayerProps = <T extends Record<string, unknown>>(props: T) => splitProps(props, LAYER_KEYS)


const StyledA = styled['a']; export const A = forwardRef((props, ref) => { const [p, r] = splitBoxProps(props); const [layerProps, rest] = splitLayerProps(r); const dataLayerAttr = layerProps.layer != null ? { 'data-layer': layerProps.layer } : {}; return <StyledA ref={ref} {...(box.raw(p) as object)} {...rest} {...dataLayerAttr} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'a'> & React.RefAttributes<PrimitiveElement<'a'>>>
const StyledAbbr = styled['abbr']; export const Abbr = forwardRef<PrimitiveElement<'abbr'>, PrimitiveProps<'abbr'>>(({ className, ...props }, ref) => { const [p, r] = splitBoxProps(props); const [layerProps, rest] = splitLayerProps(r); const dataLayerAttr = layerProps.layer != null ? { 'data-layer': layerProps.layer } : {}; const recipeClass = abbrStyle(); return <StyledAbbr ref={ref} className={recipeClass + (className ? ' ' + className : '')} {...(box.raw(p) as object)} {...rest} {...dataLayerAttr} /> })
const StyledAddress = styled['address']; export const Address = forwardRef((props, ref) => { const [p, r] = splitBoxProps(props); const [layerProps, rest] = splitLayerProps(r); const dataLayerAttr = layerProps.layer != null ? { 'data-layer': layerProps.layer } : {}; return <StyledAddress ref={ref} {...(box.raw(p) as object)} {...rest} {...dataLayerAttr} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'address'> & React.RefAttributes<PrimitiveElement<'address'>>>
const StyledArea = styled['area']; export const Area = forwardRef((props, ref) => { const [p, r] = splitBoxProps(props); const [layerProps, rest] = splitLayerProps(r); const dataLayerAttr = layerProps.layer != null ? { 'data-layer': layerProps.layer } : {}; return <StyledArea ref={ref} {...(box.raw(p) as object)} {...rest} {...dataLayerAttr} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'area'> & React.RefAttributes<PrimitiveElement<'area'>>>
const StyledArticle = styled['article']; export const Article = forwardRef((props, ref) => { const [p, r] = splitBoxProps(props); const [layerProps, rest] = splitLayerProps(r); const dataLayerAttr = layerProps.layer != null ? { 'data-layer': layerProps.layer } : {}; return <StyledArticle ref={ref} {...(box.raw(p) as object)} {...rest} {...dataLayerAttr} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'article'> & React.RefAttributes<PrimitiveElement<'article'>>>
const StyledAside = styled['aside']; export const Aside = forwardRef((props, ref) => { const [p, r] = splitBoxProps(props); const [layerProps, rest] = splitLayerProps(r); const dataLayerAttr = layerProps.layer != null ? { 'data-layer': layerProps.layer } : {}; return <StyledAside ref={ref} {...(box.raw(p) as object)} {...rest} {...dataLayerAttr} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'aside'> & React.RefAttributes<PrimitiveElement<'aside'>>>
const StyledAudio = styled['audio']; export const Audio = forwardRef((props, ref) => { const [p, r] = splitBoxProps(props); const [layerProps, rest] = splitLayerProps(r); const dataLayerAttr = layerProps.layer != null ? { 'data-layer': layerProps.layer } : {}; return <StyledAudio ref={ref} {...(box.raw(p) as object)} {...rest} {...dataLayerAttr} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'audio'> & React.RefAttributes<PrimitiveElement<'audio'>>>
const StyledB = styled['b']; export const B = forwardRef<PrimitiveElement<'b'>, PrimitiveProps<'b'>>(({ className, ...props }, ref) => { const [p, r] = splitBoxProps(props); const [layerProps, rest] = splitLayerProps(r); const dataLayerAttr = layerProps.layer != null ? { 'data-layer': layerProps.layer } : {}; const recipeClass = bStyle(); return <StyledB ref={ref} className={recipeClass + (className ? ' ' + className : '')} {...(box.raw(p) as object)} {...rest} {...dataLayerAttr} /> })
const StyledBdi = styled['bdi']; export const Bdi = forwardRef((props, ref) => { const [p, r] = splitBoxProps(props); const [layerProps, rest] = splitLayerProps(r); const dataLayerAttr = layerProps.layer != null ? { 'data-layer': layerProps.layer } : {}; return <StyledBdi ref={ref} {...(box.raw(p) as object)} {...rest} {...dataLayerAttr} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'bdi'> & React.RefAttributes<PrimitiveElement<'bdi'>>>
const StyledBdo = styled['bdo']; export const Bdo = forwardRef((props, ref) => { const [p, r] = splitBoxProps(props); const [layerProps, rest] = splitLayerProps(r); const dataLayerAttr = layerProps.layer != null ? { 'data-layer': layerProps.layer } : {}; return <StyledBdo ref={ref} {...(box.raw(p) as object)} {...rest} {...dataLayerAttr} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'bdo'> & React.RefAttributes<PrimitiveElement<'bdo'>>>
const StyledBlockquote = styled['blockquote']; export const Blockquote = forwardRef<PrimitiveElement<'blockquote'>, PrimitiveProps<'blockquote'>>(({ className, ...props }, ref) => { const [p, r] = splitBoxProps(props); const [layerProps, rest] = splitLayerProps(r); const dataLayerAttr = layerProps.layer != null ? { 'data-layer': layerProps.layer } : {}; const recipeClass = blockquoteStyle(); return <StyledBlockquote ref={ref} className={recipeClass + (className ? ' ' + className : '')} {...(box.raw(p) as object)} {...rest} {...dataLayerAttr} /> })
const StyledBr = styled['br']; export const Br = forwardRef((props, ref) => { const [p, r] = splitBoxProps(props); const [layerProps, rest] = splitLayerProps(r); const dataLayerAttr = layerProps.layer != null ? { 'data-layer': layerProps.layer } : {}; return <StyledBr ref={ref} {...(box.raw(p) as object)} {...rest} {...dataLayerAttr} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'br'> & React.RefAttributes<PrimitiveElement<'br'>>>
const StyledButton = styled['button']; export const Button = forwardRef((props, ref) => { const [p, r] = splitBoxProps(props); const [layerProps, rest] = splitLayerProps(r); const dataLayerAttr = layerProps.layer != null ? { 'data-layer': layerProps.layer } : {}; return <StyledButton ref={ref} {...(box.raw(p) as object)} {...rest} {...dataLayerAttr} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'button'> & React.RefAttributes<PrimitiveElement<'button'>>>
const StyledCanvas = styled['canvas']; export const Canvas = forwardRef((props, ref) => { const [p, r] = splitBoxProps(props); const [layerProps, rest] = splitLayerProps(r); const dataLayerAttr = layerProps.layer != null ? { 'data-layer': layerProps.layer } : {}; return <StyledCanvas ref={ref} {...(box.raw(p) as object)} {...rest} {...dataLayerAttr} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'canvas'> & React.RefAttributes<PrimitiveElement<'canvas'>>>
const StyledCaption = styled['caption']; export const Caption = forwardRef((props, ref) => { const [p, r] = splitBoxProps(props); const [layerProps, rest] = splitLayerProps(r); const dataLayerAttr = layerProps.layer != null ? { 'data-layer': layerProps.layer } : {}; return <StyledCaption ref={ref} {...(box.raw(p) as object)} {...rest} {...dataLayerAttr} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'caption'> & React.RefAttributes<PrimitiveElement<'caption'>>>
const StyledCite = styled['cite']; export const Cite = forwardRef<PrimitiveElement<'cite'>, PrimitiveProps<'cite'>>(({ className, ...props }, ref) => { const [p, r] = splitBoxProps(props); const [layerProps, rest] = splitLayerProps(r); const dataLayerAttr = layerProps.layer != null ? { 'data-layer': layerProps.layer } : {}; const recipeClass = citeStyle(); return <StyledCite ref={ref} className={recipeClass + (className ? ' ' + className : '')} {...(box.raw(p) as object)} {...rest} {...dataLayerAttr} /> })
const StyledCode = styled['code']; export const Code = forwardRef<PrimitiveElement<'code'>, PrimitiveProps<'code'>>(({ className, ...props }, ref) => { const [p, r] = splitBoxProps(props); const [layerProps, rest] = splitLayerProps(r); const dataLayerAttr = layerProps.layer != null ? { 'data-layer': layerProps.layer } : {}; const recipeClass = codeStyle(); return <StyledCode ref={ref} className={recipeClass + (className ? ' ' + className : '')} {...(box.raw(p) as object)} {...rest} {...dataLayerAttr} /> })
const StyledCol = styled['col']; export const Col = forwardRef((props, ref) => { const [p, r] = splitBoxProps(props); const [layerProps, rest] = splitLayerProps(r); const dataLayerAttr = layerProps.layer != null ? { 'data-layer': layerProps.layer } : {}; return <StyledCol ref={ref} {...(box.raw(p) as object)} {...rest} {...dataLayerAttr} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'col'> & React.RefAttributes<PrimitiveElement<'col'>>>
const StyledColgroup = styled['colgroup']; export const Colgroup = forwardRef((props, ref) => { const [p, r] = splitBoxProps(props); const [layerProps, rest] = splitLayerProps(r); const dataLayerAttr = layerProps.layer != null ? { 'data-layer': layerProps.layer } : {}; return <StyledColgroup ref={ref} {...(box.raw(p) as object)} {...rest} {...dataLayerAttr} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'colgroup'> & React.RefAttributes<PrimitiveElement<'colgroup'>>>
const StyledData = styled['data']; export const Data = forwardRef((props, ref) => { const [p, r] = splitBoxProps(props); const [layerProps, rest] = splitLayerProps(r); const dataLayerAttr = layerProps.layer != null ? { 'data-layer': layerProps.layer } : {}; return <StyledData ref={ref} {...(box.raw(p) as object)} {...rest} {...dataLayerAttr} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'data'> & React.RefAttributes<PrimitiveElement<'data'>>>
const StyledDatalist = styled['datalist']; export const Datalist = forwardRef((props, ref) => { const [p, r] = splitBoxProps(props); const [layerProps, rest] = splitLayerProps(r); const dataLayerAttr = layerProps.layer != null ? { 'data-layer': layerProps.layer } : {}; return <StyledDatalist ref={ref} {...(box.raw(p) as object)} {...rest} {...dataLayerAttr} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'datalist'> & React.RefAttributes<PrimitiveElement<'datalist'>>>
const StyledDd = styled['dd']; export const Dd = forwardRef((props, ref) => { const [p, r] = splitBoxProps(props); const [layerProps, rest] = splitLayerProps(r); const dataLayerAttr = layerProps.layer != null ? { 'data-layer': layerProps.layer } : {}; return <StyledDd ref={ref} {...(box.raw(p) as object)} {...rest} {...dataLayerAttr} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'dd'> & React.RefAttributes<PrimitiveElement<'dd'>>>
const StyledDel = styled['del']; export const Del = forwardRef((props, ref) => { const [p, r] = splitBoxProps(props); const [layerProps, rest] = splitLayerProps(r); const dataLayerAttr = layerProps.layer != null ? { 'data-layer': layerProps.layer } : {}; return <StyledDel ref={ref} {...(box.raw(p) as object)} {...rest} {...dataLayerAttr} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'del'> & React.RefAttributes<PrimitiveElement<'del'>>>
const StyledDetails = styled['details']; export const Details = forwardRef((props, ref) => { const [p, r] = splitBoxProps(props); const [layerProps, rest] = splitLayerProps(r); const dataLayerAttr = layerProps.layer != null ? { 'data-layer': layerProps.layer } : {}; return <StyledDetails ref={ref} {...(box.raw(p) as object)} {...rest} {...dataLayerAttr} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'details'> & React.RefAttributes<PrimitiveElement<'details'>>>
const StyledDfn = styled['dfn']; export const Dfn = forwardRef((props, ref) => { const [p, r] = splitBoxProps(props); const [layerProps, rest] = splitLayerProps(r); const dataLayerAttr = layerProps.layer != null ? { 'data-layer': layerProps.layer } : {}; return <StyledDfn ref={ref} {...(box.raw(p) as object)} {...rest} {...dataLayerAttr} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'dfn'> & React.RefAttributes<PrimitiveElement<'dfn'>>>
const StyledDialog = styled['dialog']; export const Dialog = forwardRef((props, ref) => { const [p, r] = splitBoxProps(props); const [layerProps, rest] = splitLayerProps(r); const dataLayerAttr = layerProps.layer != null ? { 'data-layer': layerProps.layer } : {}; return <StyledDialog ref={ref} {...(box.raw(p) as object)} {...rest} {...dataLayerAttr} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'dialog'> & React.RefAttributes<PrimitiveElement<'dialog'>>>
const StyledDiv = styled['div']; export const Div = forwardRef((props, ref) => { const [p, r] = splitBoxProps(props); const [layerProps, rest] = splitLayerProps(r); const dataLayerAttr = layerProps.layer != null ? { 'data-layer': layerProps.layer } : {}; return <StyledDiv ref={ref} {...(box.raw(p) as object)} {...rest} {...dataLayerAttr} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'div'> & React.RefAttributes<PrimitiveElement<'div'>>>
const StyledDl = styled['dl']; export const Dl = forwardRef((props, ref) => { const [p, r] = splitBoxProps(props); const [layerProps, rest] = splitLayerProps(r); const dataLayerAttr = layerProps.layer != null ? { 'data-layer': layerProps.layer } : {}; return <StyledDl ref={ref} {...(box.raw(p) as object)} {...rest} {...dataLayerAttr} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'dl'> & React.RefAttributes<PrimitiveElement<'dl'>>>
const StyledDt = styled['dt']; export const Dt = forwardRef((props, ref) => { const [p, r] = splitBoxProps(props); const [layerProps, rest] = splitLayerProps(r); const dataLayerAttr = layerProps.layer != null ? { 'data-layer': layerProps.layer } : {}; return <StyledDt ref={ref} {...(box.raw(p) as object)} {...rest} {...dataLayerAttr} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'dt'> & React.RefAttributes<PrimitiveElement<'dt'>>>
const StyledEm = styled['em']; export const Em = forwardRef<PrimitiveElement<'em'>, PrimitiveProps<'em'>>(({ className, ...props }, ref) => { const [p, r] = splitBoxProps(props); const [layerProps, rest] = splitLayerProps(r); const dataLayerAttr = layerProps.layer != null ? { 'data-layer': layerProps.layer } : {}; const recipeClass = emStyle(); return <StyledEm ref={ref} className={recipeClass + (className ? ' ' + className : '')} {...(box.raw(p) as object)} {...rest} {...dataLayerAttr} /> })
const StyledEmbed = styled['embed']; export const Embed = forwardRef((props, ref) => { const [p, r] = splitBoxProps(props); const [layerProps, rest] = splitLayerProps(r); const dataLayerAttr = layerProps.layer != null ? { 'data-layer': layerProps.layer } : {}; return <StyledEmbed ref={ref} {...(box.raw(p) as object)} {...rest} {...dataLayerAttr} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'embed'> & React.RefAttributes<PrimitiveElement<'embed'>>>
const StyledFieldset = styled['fieldset']; export const Fieldset = forwardRef((props, ref) => { const [p, r] = splitBoxProps(props); const [layerProps, rest] = splitLayerProps(r); const dataLayerAttr = layerProps.layer != null ? { 'data-layer': layerProps.layer } : {}; return <StyledFieldset ref={ref} {...(box.raw(p) as object)} {...rest} {...dataLayerAttr} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'fieldset'> & React.RefAttributes<PrimitiveElement<'fieldset'>>>
const StyledFigcaption = styled['figcaption']; export const Figcaption = forwardRef((props, ref) => { const [p, r] = splitBoxProps(props); const [layerProps, rest] = splitLayerProps(r); const dataLayerAttr = layerProps.layer != null ? { 'data-layer': layerProps.layer } : {}; return <StyledFigcaption ref={ref} {...(box.raw(p) as object)} {...rest} {...dataLayerAttr} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'figcaption'> & React.RefAttributes<PrimitiveElement<'figcaption'>>>
const StyledFigure = styled['figure']; export const Figure = forwardRef((props, ref) => { const [p, r] = splitBoxProps(props); const [layerProps, rest] = splitLayerProps(r); const dataLayerAttr = layerProps.layer != null ? { 'data-layer': layerProps.layer } : {}; return <StyledFigure ref={ref} {...(box.raw(p) as object)} {...rest} {...dataLayerAttr} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'figure'> & React.RefAttributes<PrimitiveElement<'figure'>>>
const StyledFooter = styled['footer']; export const Footer = forwardRef((props, ref) => { const [p, r] = splitBoxProps(props); const [layerProps, rest] = splitLayerProps(r); const dataLayerAttr = layerProps.layer != null ? { 'data-layer': layerProps.layer } : {}; return <StyledFooter ref={ref} {...(box.raw(p) as object)} {...rest} {...dataLayerAttr} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'footer'> & React.RefAttributes<PrimitiveElement<'footer'>>>
const StyledForm = styled['form']; export const Form = forwardRef((props, ref) => { const [p, r] = splitBoxProps(props); const [layerProps, rest] = splitLayerProps(r); const dataLayerAttr = layerProps.layer != null ? { 'data-layer': layerProps.layer } : {}; return <StyledForm ref={ref} {...(box.raw(p) as object)} {...rest} {...dataLayerAttr} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'form'> & React.RefAttributes<PrimitiveElement<'form'>>>
const StyledH1 = styled['h1']; export const H1 = forwardRef<PrimitiveElement<'h1'>, PrimitiveProps<'h1'>>(({ className, ...props }, ref) => { const [p, r] = splitBoxProps(props); const [layerProps, rest] = splitLayerProps(r); const dataLayerAttr = layerProps.layer != null ? { 'data-layer': layerProps.layer } : {}; const recipeClass = h1Style(); return <StyledH1 ref={ref} className={recipeClass + (className ? ' ' + className : '')} {...(box.raw(p) as object)} {...rest} {...dataLayerAttr} /> })
const StyledH2 = styled['h2']; export const H2 = forwardRef<PrimitiveElement<'h2'>, PrimitiveProps<'h2'>>(({ className, ...props }, ref) => { const [p, r] = splitBoxProps(props); const [layerProps, rest] = splitLayerProps(r); const dataLayerAttr = layerProps.layer != null ? { 'data-layer': layerProps.layer } : {}; const recipeClass = h2Style(); return <StyledH2 ref={ref} className={recipeClass + (className ? ' ' + className : '')} {...(box.raw(p) as object)} {...rest} {...dataLayerAttr} /> })
const StyledH3 = styled['h3']; export const H3 = forwardRef<PrimitiveElement<'h3'>, PrimitiveProps<'h3'>>(({ className, ...props }, ref) => { const [p, r] = splitBoxProps(props); const [layerProps, rest] = splitLayerProps(r); const dataLayerAttr = layerProps.layer != null ? { 'data-layer': layerProps.layer } : {}; const recipeClass = h3Style(); return <StyledH3 ref={ref} className={recipeClass + (className ? ' ' + className : '')} {...(box.raw(p) as object)} {...rest} {...dataLayerAttr} /> })
const StyledH4 = styled['h4']; export const H4 = forwardRef<PrimitiveElement<'h4'>, PrimitiveProps<'h4'>>(({ className, ...props }, ref) => { const [p, r] = splitBoxProps(props); const [layerProps, rest] = splitLayerProps(r); const dataLayerAttr = layerProps.layer != null ? { 'data-layer': layerProps.layer } : {}; const recipeClass = h4Style(); return <StyledH4 ref={ref} className={recipeClass + (className ? ' ' + className : '')} {...(box.raw(p) as object)} {...rest} {...dataLayerAttr} /> })
const StyledH5 = styled['h5']; export const H5 = forwardRef<PrimitiveElement<'h5'>, PrimitiveProps<'h5'>>(({ className, ...props }, ref) => { const [p, r] = splitBoxProps(props); const [layerProps, rest] = splitLayerProps(r); const dataLayerAttr = layerProps.layer != null ? { 'data-layer': layerProps.layer } : {}; const recipeClass = h5Style(); return <StyledH5 ref={ref} className={recipeClass + (className ? ' ' + className : '')} {...(box.raw(p) as object)} {...rest} {...dataLayerAttr} /> })
const StyledH6 = styled['h6']; export const H6 = forwardRef<PrimitiveElement<'h6'>, PrimitiveProps<'h6'>>(({ className, ...props }, ref) => { const [p, r] = splitBoxProps(props); const [layerProps, rest] = splitLayerProps(r); const dataLayerAttr = layerProps.layer != null ? { 'data-layer': layerProps.layer } : {}; const recipeClass = h6Style(); return <StyledH6 ref={ref} className={recipeClass + (className ? ' ' + className : '')} {...(box.raw(p) as object)} {...rest} {...dataLayerAttr} /> })
const StyledHeader = styled['header']; export const Header = forwardRef((props, ref) => { const [p, r] = splitBoxProps(props); const [layerProps, rest] = splitLayerProps(r); const dataLayerAttr = layerProps.layer != null ? { 'data-layer': layerProps.layer } : {}; return <StyledHeader ref={ref} {...(box.raw(p) as object)} {...rest} {...dataLayerAttr} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'header'> & React.RefAttributes<PrimitiveElement<'header'>>>
const StyledHgroup = styled['hgroup']; export const Hgroup = forwardRef((props, ref) => { const [p, r] = splitBoxProps(props); const [layerProps, rest] = splitLayerProps(r); const dataLayerAttr = layerProps.layer != null ? { 'data-layer': layerProps.layer } : {}; return <StyledHgroup ref={ref} {...(box.raw(p) as object)} {...rest} {...dataLayerAttr} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'hgroup'> & React.RefAttributes<PrimitiveElement<'hgroup'>>>
const StyledHr = styled['hr']; export const Hr = forwardRef((props, ref) => { const [p, r] = splitBoxProps(props); const [layerProps, rest] = splitLayerProps(r); const dataLayerAttr = layerProps.layer != null ? { 'data-layer': layerProps.layer } : {}; return <StyledHr ref={ref} {...(box.raw(p) as object)} {...rest} {...dataLayerAttr} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'hr'> & React.RefAttributes<PrimitiveElement<'hr'>>>
const StyledI = styled['i']; export const I = forwardRef<PrimitiveElement<'i'>, PrimitiveProps<'i'>>(({ className, ...props }, ref) => { const [p, r] = splitBoxProps(props); const [layerProps, rest] = splitLayerProps(r); const dataLayerAttr = layerProps.layer != null ? { 'data-layer': layerProps.layer } : {}; const recipeClass = iStyle(); return <StyledI ref={ref} className={recipeClass + (className ? ' ' + className : '')} {...(box.raw(p) as object)} {...rest} {...dataLayerAttr} /> })
const StyledIframe = styled['iframe']; export const Iframe = forwardRef((props, ref) => { const [p, r] = splitBoxProps(props); const [layerProps, rest] = splitLayerProps(r); const dataLayerAttr = layerProps.layer != null ? { 'data-layer': layerProps.layer } : {}; return <StyledIframe ref={ref} {...(box.raw(p) as object)} {...rest} {...dataLayerAttr} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'iframe'> & React.RefAttributes<PrimitiveElement<'iframe'>>>
const StyledImg = styled['img']; export const Img = forwardRef((props, ref) => { const [p, r] = splitBoxProps(props); const [layerProps, rest] = splitLayerProps(r); const dataLayerAttr = layerProps.layer != null ? { 'data-layer': layerProps.layer } : {}; return <StyledImg ref={ref} {...(box.raw(p) as object)} {...rest} {...dataLayerAttr} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'img'> & React.RefAttributes<PrimitiveElement<'img'>>>
const StyledInput = styled['input']; export const Input = forwardRef((props, ref) => { const [p, r] = splitBoxProps(props); const [layerProps, rest] = splitLayerProps(r); const dataLayerAttr = layerProps.layer != null ? { 'data-layer': layerProps.layer } : {}; return <StyledInput ref={ref} {...(box.raw(p) as object)} {...rest} {...dataLayerAttr} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'input'> & React.RefAttributes<PrimitiveElement<'input'>>>
const StyledIns = styled['ins']; export const Ins = forwardRef((props, ref) => { const [p, r] = splitBoxProps(props); const [layerProps, rest] = splitLayerProps(r); const dataLayerAttr = layerProps.layer != null ? { 'data-layer': layerProps.layer } : {}; return <StyledIns ref={ref} {...(box.raw(p) as object)} {...rest} {...dataLayerAttr} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'ins'> & React.RefAttributes<PrimitiveElement<'ins'>>>
const StyledKbd = styled['kbd']; export const Kbd = forwardRef<PrimitiveElement<'kbd'>, PrimitiveProps<'kbd'>>(({ className, ...props }, ref) => { const [p, r] = splitBoxProps(props); const [layerProps, rest] = splitLayerProps(r); const dataLayerAttr = layerProps.layer != null ? { 'data-layer': layerProps.layer } : {}; const recipeClass = kbdStyle(); return <StyledKbd ref={ref} className={recipeClass + (className ? ' ' + className : '')} {...(box.raw(p) as object)} {...rest} {...dataLayerAttr} /> })
const StyledLabel = styled['label']; export const Label = forwardRef((props, ref) => { const [p, r] = splitBoxProps(props); const [layerProps, rest] = splitLayerProps(r); const dataLayerAttr = layerProps.layer != null ? { 'data-layer': layerProps.layer } : {}; return <StyledLabel ref={ref} {...(box.raw(p) as object)} {...rest} {...dataLayerAttr} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'label'> & React.RefAttributes<PrimitiveElement<'label'>>>
const StyledLegend = styled['legend']; export const Legend = forwardRef((props, ref) => { const [p, r] = splitBoxProps(props); const [layerProps, rest] = splitLayerProps(r); const dataLayerAttr = layerProps.layer != null ? { 'data-layer': layerProps.layer } : {}; return <StyledLegend ref={ref} {...(box.raw(p) as object)} {...rest} {...dataLayerAttr} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'legend'> & React.RefAttributes<PrimitiveElement<'legend'>>>
const StyledLi = styled['li']; export const Li = forwardRef((props, ref) => { const [p, r] = splitBoxProps(props); const [layerProps, rest] = splitLayerProps(r); const dataLayerAttr = layerProps.layer != null ? { 'data-layer': layerProps.layer } : {}; return <StyledLi ref={ref} {...(box.raw(p) as object)} {...rest} {...dataLayerAttr} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'li'> & React.RefAttributes<PrimitiveElement<'li'>>>
const StyledMain = styled['main']; export const Main = forwardRef((props, ref) => { const [p, r] = splitBoxProps(props); const [layerProps, rest] = splitLayerProps(r); const dataLayerAttr = layerProps.layer != null ? { 'data-layer': layerProps.layer } : {}; return <StyledMain ref={ref} {...(box.raw(p) as object)} {...rest} {...dataLayerAttr} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'main'> & React.RefAttributes<PrimitiveElement<'main'>>>
const StyledMap = styled['map']; export const Map = forwardRef((props, ref) => { const [p, r] = splitBoxProps(props); const [layerProps, rest] = splitLayerProps(r); const dataLayerAttr = layerProps.layer != null ? { 'data-layer': layerProps.layer } : {}; return <StyledMap ref={ref} {...(box.raw(p) as object)} {...rest} {...dataLayerAttr} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'map'> & React.RefAttributes<PrimitiveElement<'map'>>>
const StyledMark = styled['mark']; export const Mark = forwardRef<PrimitiveElement<'mark'>, PrimitiveProps<'mark'>>(({ className, ...props }, ref) => { const [p, r] = splitBoxProps(props); const [layerProps, rest] = splitLayerProps(r); const dataLayerAttr = layerProps.layer != null ? { 'data-layer': layerProps.layer } : {}; const recipeClass = markStyle(); return <StyledMark ref={ref} className={recipeClass + (className ? ' ' + className : '')} {...(box.raw(p) as object)} {...rest} {...dataLayerAttr} /> })
const StyledMenu = styled['menu']; export const Menu = forwardRef((props, ref) => { const [p, r] = splitBoxProps(props); const [layerProps, rest] = splitLayerProps(r); const dataLayerAttr = layerProps.layer != null ? { 'data-layer': layerProps.layer } : {}; return <StyledMenu ref={ref} {...(box.raw(p) as object)} {...rest} {...dataLayerAttr} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'menu'> & React.RefAttributes<PrimitiveElement<'menu'>>>
const StyledMeter = styled['meter']; export const Meter = forwardRef((props, ref) => { const [p, r] = splitBoxProps(props); const [layerProps, rest] = splitLayerProps(r); const dataLayerAttr = layerProps.layer != null ? { 'data-layer': layerProps.layer } : {}; return <StyledMeter ref={ref} {...(box.raw(p) as object)} {...rest} {...dataLayerAttr} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'meter'> & React.RefAttributes<PrimitiveElement<'meter'>>>
const StyledNav = styled['nav']; export const Nav = forwardRef((props, ref) => { const [p, r] = splitBoxProps(props); const [layerProps, rest] = splitLayerProps(r); const dataLayerAttr = layerProps.layer != null ? { 'data-layer': layerProps.layer } : {}; return <StyledNav ref={ref} {...(box.raw(p) as object)} {...rest} {...dataLayerAttr} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'nav'> & React.RefAttributes<PrimitiveElement<'nav'>>>
const StyledObj = styled['object']; export const Obj = forwardRef((props, ref) => { const [p, r] = splitBoxProps(props); const [layerProps, rest] = splitLayerProps(r); const dataLayerAttr = layerProps.layer != null ? { 'data-layer': layerProps.layer } : {}; return <StyledObj ref={ref} {...(box.raw(p) as object)} {...rest} {...dataLayerAttr} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'object'> & React.RefAttributes<PrimitiveElement<'object'>>>
const StyledOl = styled['ol']; export const Ol = forwardRef((props, ref) => { const [p, r] = splitBoxProps(props); const [layerProps, rest] = splitLayerProps(r); const dataLayerAttr = layerProps.layer != null ? { 'data-layer': layerProps.layer } : {}; return <StyledOl ref={ref} {...(box.raw(p) as object)} {...rest} {...dataLayerAttr} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'ol'> & React.RefAttributes<PrimitiveElement<'ol'>>>
const StyledOptgroup = styled['optgroup']; export const Optgroup = forwardRef((props, ref) => { const [p, r] = splitBoxProps(props); const [layerProps, rest] = splitLayerProps(r); const dataLayerAttr = layerProps.layer != null ? { 'data-layer': layerProps.layer } : {}; return <StyledOptgroup ref={ref} {...(box.raw(p) as object)} {...rest} {...dataLayerAttr} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'optgroup'> & React.RefAttributes<PrimitiveElement<'optgroup'>>>
const StyledOption = styled['option']; export const Option = forwardRef((props, ref) => { const [p, r] = splitBoxProps(props); const [layerProps, rest] = splitLayerProps(r); const dataLayerAttr = layerProps.layer != null ? { 'data-layer': layerProps.layer } : {}; return <StyledOption ref={ref} {...(box.raw(p) as object)} {...rest} {...dataLayerAttr} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'option'> & React.RefAttributes<PrimitiveElement<'option'>>>
const StyledOutput = styled['output']; export const Output = forwardRef((props, ref) => { const [p, r] = splitBoxProps(props); const [layerProps, rest] = splitLayerProps(r); const dataLayerAttr = layerProps.layer != null ? { 'data-layer': layerProps.layer } : {}; return <StyledOutput ref={ref} {...(box.raw(p) as object)} {...rest} {...dataLayerAttr} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'output'> & React.RefAttributes<PrimitiveElement<'output'>>>
const StyledP = styled['p']; export const P = forwardRef<PrimitiveElement<'p'>, PrimitiveProps<'p'>>(({ className, ...props }, ref) => { const [p, r] = splitBoxProps(props); const [layerProps, rest] = splitLayerProps(r); const dataLayerAttr = layerProps.layer != null ? { 'data-layer': layerProps.layer } : {}; const recipeClass = pStyle(); return <StyledP ref={ref} className={recipeClass + (className ? ' ' + className : '')} {...(box.raw(p) as object)} {...rest} {...dataLayerAttr} /> })
const StyledPicture = styled['picture']; export const Picture = forwardRef((props, ref) => { const [p, r] = splitBoxProps(props); const [layerProps, rest] = splitLayerProps(r); const dataLayerAttr = layerProps.layer != null ? { 'data-layer': layerProps.layer } : {}; return <StyledPicture ref={ref} {...(box.raw(p) as object)} {...rest} {...dataLayerAttr} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'picture'> & React.RefAttributes<PrimitiveElement<'picture'>>>
const StyledPre = styled['pre']; export const Pre = forwardRef<PrimitiveElement<'pre'>, PrimitiveProps<'pre'>>(({ className, ...props }, ref) => { const [p, r] = splitBoxProps(props); const [layerProps, rest] = splitLayerProps(r); const dataLayerAttr = layerProps.layer != null ? { 'data-layer': layerProps.layer } : {}; const recipeClass = preStyle(); return <StyledPre ref={ref} className={recipeClass + (className ? ' ' + className : '')} {...(box.raw(p) as object)} {...rest} {...dataLayerAttr} /> })
const StyledProgress = styled['progress']; export const Progress = forwardRef((props, ref) => { const [p, r] = splitBoxProps(props); const [layerProps, rest] = splitLayerProps(r); const dataLayerAttr = layerProps.layer != null ? { 'data-layer': layerProps.layer } : {}; return <StyledProgress ref={ref} {...(box.raw(p) as object)} {...rest} {...dataLayerAttr} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'progress'> & React.RefAttributes<PrimitiveElement<'progress'>>>
const StyledQ = styled['q']; export const Q = forwardRef<PrimitiveElement<'q'>, PrimitiveProps<'q'>>(({ className, ...props }, ref) => { const [p, r] = splitBoxProps(props); const [layerProps, rest] = splitLayerProps(r); const dataLayerAttr = layerProps.layer != null ? { 'data-layer': layerProps.layer } : {}; const recipeClass = qStyle(); return <StyledQ ref={ref} className={recipeClass + (className ? ' ' + className : '')} {...(box.raw(p) as object)} {...rest} {...dataLayerAttr} /> })
const StyledRp = styled['rp']; export const Rp = forwardRef((props, ref) => { const [p, r] = splitBoxProps(props); const [layerProps, rest] = splitLayerProps(r); const dataLayerAttr = layerProps.layer != null ? { 'data-layer': layerProps.layer } : {}; return <StyledRp ref={ref} {...(box.raw(p) as object)} {...rest} {...dataLayerAttr} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'rp'> & React.RefAttributes<PrimitiveElement<'rp'>>>
const StyledRt = styled['rt']; export const Rt = forwardRef((props, ref) => { const [p, r] = splitBoxProps(props); const [layerProps, rest] = splitLayerProps(r); const dataLayerAttr = layerProps.layer != null ? { 'data-layer': layerProps.layer } : {}; return <StyledRt ref={ref} {...(box.raw(p) as object)} {...rest} {...dataLayerAttr} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'rt'> & React.RefAttributes<PrimitiveElement<'rt'>>>
const StyledRuby = styled['ruby']; export const Ruby = forwardRef((props, ref) => { const [p, r] = splitBoxProps(props); const [layerProps, rest] = splitLayerProps(r); const dataLayerAttr = layerProps.layer != null ? { 'data-layer': layerProps.layer } : {}; return <StyledRuby ref={ref} {...(box.raw(p) as object)} {...rest} {...dataLayerAttr} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'ruby'> & React.RefAttributes<PrimitiveElement<'ruby'>>>
const StyledS = styled['s']; export const S = forwardRef<PrimitiveElement<'s'>, PrimitiveProps<'s'>>(({ className, ...props }, ref) => { const [p, r] = splitBoxProps(props); const [layerProps, rest] = splitLayerProps(r); const dataLayerAttr = layerProps.layer != null ? { 'data-layer': layerProps.layer } : {}; const recipeClass = sStyle(); return <StyledS ref={ref} className={recipeClass + (className ? ' ' + className : '')} {...(box.raw(p) as object)} {...rest} {...dataLayerAttr} /> })
const StyledSamp = styled['samp']; export const Samp = forwardRef<PrimitiveElement<'samp'>, PrimitiveProps<'samp'>>(({ className, ...props }, ref) => { const [p, r] = splitBoxProps(props); const [layerProps, rest] = splitLayerProps(r); const dataLayerAttr = layerProps.layer != null ? { 'data-layer': layerProps.layer } : {}; const recipeClass = sampStyle(); return <StyledSamp ref={ref} className={recipeClass + (className ? ' ' + className : '')} {...(box.raw(p) as object)} {...rest} {...dataLayerAttr} /> })
const StyledSearch = styled['search']; export const Search = forwardRef((props, ref) => { const [p, r] = splitBoxProps(props); const [layerProps, rest] = splitLayerProps(r); const dataLayerAttr = layerProps.layer != null ? { 'data-layer': layerProps.layer } : {}; return <StyledSearch ref={ref} {...(box.raw(p) as object)} {...rest} {...dataLayerAttr} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'search'> & React.RefAttributes<PrimitiveElement<'search'>>>
const StyledSection = styled['section']; export const Section = forwardRef((props, ref) => { const [p, r] = splitBoxProps(props); const [layerProps, rest] = splitLayerProps(r); const dataLayerAttr = layerProps.layer != null ? { 'data-layer': layerProps.layer } : {}; return <StyledSection ref={ref} {...(box.raw(p) as object)} {...rest} {...dataLayerAttr} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'section'> & React.RefAttributes<PrimitiveElement<'section'>>>
const StyledSelect = styled['select']; export const Select = forwardRef((props, ref) => { const [p, r] = splitBoxProps(props); const [layerProps, rest] = splitLayerProps(r); const dataLayerAttr = layerProps.layer != null ? { 'data-layer': layerProps.layer } : {}; return <StyledSelect ref={ref} {...(box.raw(p) as object)} {...rest} {...dataLayerAttr} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'select'> & React.RefAttributes<PrimitiveElement<'select'>>>
const StyledSmall = styled['small']; export const Small = forwardRef<PrimitiveElement<'small'>, PrimitiveProps<'small'>>(({ className, ...props }, ref) => { const [p, r] = splitBoxProps(props); const [layerProps, rest] = splitLayerProps(r); const dataLayerAttr = layerProps.layer != null ? { 'data-layer': layerProps.layer } : {}; const recipeClass = smallStyle(); return <StyledSmall ref={ref} className={recipeClass + (className ? ' ' + className : '')} {...(box.raw(p) as object)} {...rest} {...dataLayerAttr} /> })
const StyledSource = styled['source']; export const Source = forwardRef((props, ref) => { const [p, r] = splitBoxProps(props); const [layerProps, rest] = splitLayerProps(r); const dataLayerAttr = layerProps.layer != null ? { 'data-layer': layerProps.layer } : {}; return <StyledSource ref={ref} {...(box.raw(p) as object)} {...rest} {...dataLayerAttr} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'source'> & React.RefAttributes<PrimitiveElement<'source'>>>
const StyledSpan = styled['span']; export const Span = forwardRef((props, ref) => { const [p, r] = splitBoxProps(props); const [layerProps, rest] = splitLayerProps(r); const dataLayerAttr = layerProps.layer != null ? { 'data-layer': layerProps.layer } : {}; return <StyledSpan ref={ref} {...(box.raw(p) as object)} {...rest} {...dataLayerAttr} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'span'> & React.RefAttributes<PrimitiveElement<'span'>>>
const StyledStrong = styled['strong']; export const Strong = forwardRef<PrimitiveElement<'strong'>, PrimitiveProps<'strong'>>(({ className, ...props }, ref) => { const [p, r] = splitBoxProps(props); const [layerProps, rest] = splitLayerProps(r); const dataLayerAttr = layerProps.layer != null ? { 'data-layer': layerProps.layer } : {}; const recipeClass = strongStyle(); return <StyledStrong ref={ref} className={recipeClass + (className ? ' ' + className : '')} {...(box.raw(p) as object)} {...rest} {...dataLayerAttr} /> })
const StyledSub = styled['sub']; export const Sub = forwardRef<PrimitiveElement<'sub'>, PrimitiveProps<'sub'>>(({ className, ...props }, ref) => { const [p, r] = splitBoxProps(props); const [layerProps, rest] = splitLayerProps(r); const dataLayerAttr = layerProps.layer != null ? { 'data-layer': layerProps.layer } : {}; const recipeClass = subStyle(); return <StyledSub ref={ref} className={recipeClass + (className ? ' ' + className : '')} {...(box.raw(p) as object)} {...rest} {...dataLayerAttr} /> })
const StyledSummary = styled['summary']; export const Summary = forwardRef((props, ref) => { const [p, r] = splitBoxProps(props); const [layerProps, rest] = splitLayerProps(r); const dataLayerAttr = layerProps.layer != null ? { 'data-layer': layerProps.layer } : {}; return <StyledSummary ref={ref} {...(box.raw(p) as object)} {...rest} {...dataLayerAttr} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'summary'> & React.RefAttributes<PrimitiveElement<'summary'>>>
const StyledSup = styled['sup']; export const Sup = forwardRef<PrimitiveElement<'sup'>, PrimitiveProps<'sup'>>(({ className, ...props }, ref) => { const [p, r] = splitBoxProps(props); const [layerProps, rest] = splitLayerProps(r); const dataLayerAttr = layerProps.layer != null ? { 'data-layer': layerProps.layer } : {}; const recipeClass = supStyle(); return <StyledSup ref={ref} className={recipeClass + (className ? ' ' + className : '')} {...(box.raw(p) as object)} {...rest} {...dataLayerAttr} /> })
const StyledSvg = styled['svg']; export const Svg = forwardRef((props, ref) => { const [p, r] = splitBoxProps(props); const [layerProps, rest] = splitLayerProps(r); const dataLayerAttr = layerProps.layer != null ? { 'data-layer': layerProps.layer } : {}; return <StyledSvg ref={ref} {...(box.raw(p) as object)} {...rest} {...dataLayerAttr} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'svg'> & React.RefAttributes<PrimitiveElement<'svg'>>>
const StyledTable = styled['table']; export const Table = forwardRef((props, ref) => { const [p, r] = splitBoxProps(props); const [layerProps, rest] = splitLayerProps(r); const dataLayerAttr = layerProps.layer != null ? { 'data-layer': layerProps.layer } : {}; return <StyledTable ref={ref} {...(box.raw(p) as object)} {...rest} {...dataLayerAttr} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'table'> & React.RefAttributes<PrimitiveElement<'table'>>>
const StyledTbody = styled['tbody']; export const Tbody = forwardRef((props, ref) => { const [p, r] = splitBoxProps(props); const [layerProps, rest] = splitLayerProps(r); const dataLayerAttr = layerProps.layer != null ? { 'data-layer': layerProps.layer } : {}; return <StyledTbody ref={ref} {...(box.raw(p) as object)} {...rest} {...dataLayerAttr} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'tbody'> & React.RefAttributes<PrimitiveElement<'tbody'>>>
const StyledTd = styled['td']; export const Td = forwardRef((props, ref) => { const [p, r] = splitBoxProps(props); const [layerProps, rest] = splitLayerProps(r); const dataLayerAttr = layerProps.layer != null ? { 'data-layer': layerProps.layer } : {}; return <StyledTd ref={ref} {...(box.raw(p) as object)} {...rest} {...dataLayerAttr} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'td'> & React.RefAttributes<PrimitiveElement<'td'>>>
const StyledTextarea = styled['textarea']; export const Textarea = forwardRef((props, ref) => { const [p, r] = splitBoxProps(props); const [layerProps, rest] = splitLayerProps(r); const dataLayerAttr = layerProps.layer != null ? { 'data-layer': layerProps.layer } : {}; return <StyledTextarea ref={ref} {...(box.raw(p) as object)} {...rest} {...dataLayerAttr} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'textarea'> & React.RefAttributes<PrimitiveElement<'textarea'>>>
const StyledTfoot = styled['tfoot']; export const Tfoot = forwardRef((props, ref) => { const [p, r] = splitBoxProps(props); const [layerProps, rest] = splitLayerProps(r); const dataLayerAttr = layerProps.layer != null ? { 'data-layer': layerProps.layer } : {}; return <StyledTfoot ref={ref} {...(box.raw(p) as object)} {...rest} {...dataLayerAttr} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'tfoot'> & React.RefAttributes<PrimitiveElement<'tfoot'>>>
const StyledTh = styled['th']; export const Th = forwardRef((props, ref) => { const [p, r] = splitBoxProps(props); const [layerProps, rest] = splitLayerProps(r); const dataLayerAttr = layerProps.layer != null ? { 'data-layer': layerProps.layer } : {}; return <StyledTh ref={ref} {...(box.raw(p) as object)} {...rest} {...dataLayerAttr} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'th'> & React.RefAttributes<PrimitiveElement<'th'>>>
const StyledThead = styled['thead']; export const Thead = forwardRef((props, ref) => { const [p, r] = splitBoxProps(props); const [layerProps, rest] = splitLayerProps(r); const dataLayerAttr = layerProps.layer != null ? { 'data-layer': layerProps.layer } : {}; return <StyledThead ref={ref} {...(box.raw(p) as object)} {...rest} {...dataLayerAttr} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'thead'> & React.RefAttributes<PrimitiveElement<'thead'>>>
const StyledTime = styled['time']; export const Time = forwardRef((props, ref) => { const [p, r] = splitBoxProps(props); const [layerProps, rest] = splitLayerProps(r); const dataLayerAttr = layerProps.layer != null ? { 'data-layer': layerProps.layer } : {}; return <StyledTime ref={ref} {...(box.raw(p) as object)} {...rest} {...dataLayerAttr} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'time'> & React.RefAttributes<PrimitiveElement<'time'>>>
const StyledTr = styled['tr']; export const Tr = forwardRef((props, ref) => { const [p, r] = splitBoxProps(props); const [layerProps, rest] = splitLayerProps(r); const dataLayerAttr = layerProps.layer != null ? { 'data-layer': layerProps.layer } : {}; return <StyledTr ref={ref} {...(box.raw(p) as object)} {...rest} {...dataLayerAttr} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'tr'> & React.RefAttributes<PrimitiveElement<'tr'>>>
const StyledTrack = styled['track']; export const Track = forwardRef((props, ref) => { const [p, r] = splitBoxProps(props); const [layerProps, rest] = splitLayerProps(r); const dataLayerAttr = layerProps.layer != null ? { 'data-layer': layerProps.layer } : {}; return <StyledTrack ref={ref} {...(box.raw(p) as object)} {...rest} {...dataLayerAttr} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'track'> & React.RefAttributes<PrimitiveElement<'track'>>>
const StyledU = styled['u']; export const U = forwardRef<PrimitiveElement<'u'>, PrimitiveProps<'u'>>(({ className, ...props }, ref) => { const [p, r] = splitBoxProps(props); const [layerProps, rest] = splitLayerProps(r); const dataLayerAttr = layerProps.layer != null ? { 'data-layer': layerProps.layer } : {}; const recipeClass = uStyle(); return <StyledU ref={ref} className={recipeClass + (className ? ' ' + className : '')} {...(box.raw(p) as object)} {...rest} {...dataLayerAttr} /> })
const StyledUl = styled['ul']; export const Ul = forwardRef((props, ref) => { const [p, r] = splitBoxProps(props); const [layerProps, rest] = splitLayerProps(r); const dataLayerAttr = layerProps.layer != null ? { 'data-layer': layerProps.layer } : {}; return <StyledUl ref={ref} {...(box.raw(p) as object)} {...rest} {...dataLayerAttr} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'ul'> & React.RefAttributes<PrimitiveElement<'ul'>>>
const StyledVar = styled['var']; export const Var = forwardRef<PrimitiveElement<'var'>, PrimitiveProps<'var'>>(({ className, ...props }, ref) => { const [p, r] = splitBoxProps(props); const [layerProps, rest] = splitLayerProps(r); const dataLayerAttr = layerProps.layer != null ? { 'data-layer': layerProps.layer } : {}; const recipeClass = varStyle(); return <StyledVar ref={ref} className={recipeClass + (className ? ' ' + className : '')} {...(box.raw(p) as object)} {...rest} {...dataLayerAttr} /> })
const StyledVideo = styled['video']; export const Video = forwardRef((props, ref) => { const [p, r] = splitBoxProps(props); const [layerProps, rest] = splitLayerProps(r); const dataLayerAttr = layerProps.layer != null ? { 'data-layer': layerProps.layer } : {}; return <StyledVideo ref={ref} {...(box.raw(p) as object)} {...rest} {...dataLayerAttr} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'video'> & React.RefAttributes<PrimitiveElement<'video'>>>
const StyledWbr = styled['wbr']; export const Wbr = forwardRef((props, ref) => { const [p, r] = splitBoxProps(props); const [layerProps, rest] = splitLayerProps(r); const dataLayerAttr = layerProps.layer != null ? { 'data-layer': layerProps.layer } : {}; return <StyledWbr ref={ref} {...(box.raw(p) as object)} {...rest} {...dataLayerAttr} /> }) as React.ForwardRefExoticComponent<PrimitiveProps<'wbr'> & React.RefAttributes<PrimitiveElement<'wbr'>>>

export type AProps = PrimitiveProps<'a'>
export type AbbrProps = PrimitiveProps<'abbr'>
export type AddressProps = PrimitiveProps<'address'>
export type AreaProps = PrimitiveProps<'area'>
export type ArticleProps = PrimitiveProps<'article'>
export type AsideProps = PrimitiveProps<'aside'>
export type AudioProps = PrimitiveProps<'audio'>
export type BProps = PrimitiveProps<'b'>
export type BdiProps = PrimitiveProps<'bdi'>
export type BdoProps = PrimitiveProps<'bdo'>
export type BlockquoteProps = PrimitiveProps<'blockquote'>
export type BrProps = PrimitiveProps<'br'>
export type ButtonProps = PrimitiveProps<'button'>
export type CanvasProps = PrimitiveProps<'canvas'>
export type CaptionProps = PrimitiveProps<'caption'>
export type CiteProps = PrimitiveProps<'cite'>
export type CodeProps = PrimitiveProps<'code'>
export type ColProps = PrimitiveProps<'col'>
export type ColgroupProps = PrimitiveProps<'colgroup'>
export type DataProps = PrimitiveProps<'data'>
export type DatalistProps = PrimitiveProps<'datalist'>
export type DdProps = PrimitiveProps<'dd'>
export type DelProps = PrimitiveProps<'del'>
export type DetailsProps = PrimitiveProps<'details'>
export type DfnProps = PrimitiveProps<'dfn'>
export type DialogProps = PrimitiveProps<'dialog'>
export type DivProps = PrimitiveProps<'div'>
export type DlProps = PrimitiveProps<'dl'>
export type DtProps = PrimitiveProps<'dt'>
export type EmProps = PrimitiveProps<'em'>
export type EmbedProps = PrimitiveProps<'embed'>
export type FieldsetProps = PrimitiveProps<'fieldset'>
export type FigcaptionProps = PrimitiveProps<'figcaption'>
export type FigureProps = PrimitiveProps<'figure'>
export type FooterProps = PrimitiveProps<'footer'>
export type FormProps = PrimitiveProps<'form'>
export type H1Props = PrimitiveProps<'h1'>
export type H2Props = PrimitiveProps<'h2'>
export type H3Props = PrimitiveProps<'h3'>
export type H4Props = PrimitiveProps<'h4'>
export type H5Props = PrimitiveProps<'h5'>
export type H6Props = PrimitiveProps<'h6'>
export type HeaderProps = PrimitiveProps<'header'>
export type HgroupProps = PrimitiveProps<'hgroup'>
export type HrProps = PrimitiveProps<'hr'>
export type IProps = PrimitiveProps<'i'>
export type IframeProps = PrimitiveProps<'iframe'>
export type ImgProps = PrimitiveProps<'img'>
export type InputProps = PrimitiveProps<'input'>
export type InsProps = PrimitiveProps<'ins'>
export type KbdProps = PrimitiveProps<'kbd'>
export type LabelProps = PrimitiveProps<'label'>
export type LegendProps = PrimitiveProps<'legend'>
export type LiProps = PrimitiveProps<'li'>
export type MainProps = PrimitiveProps<'main'>
export type MapProps = PrimitiveProps<'map'>
export type MarkProps = PrimitiveProps<'mark'>
export type MenuProps = PrimitiveProps<'menu'>
export type MeterProps = PrimitiveProps<'meter'>
export type NavProps = PrimitiveProps<'nav'>
export type ObjProps = PrimitiveProps<'object'>
export type OlProps = PrimitiveProps<'ol'>
export type OptgroupProps = PrimitiveProps<'optgroup'>
export type OptionProps = PrimitiveProps<'option'>
export type OutputProps = PrimitiveProps<'output'>
export type PProps = PrimitiveProps<'p'>
export type PictureProps = PrimitiveProps<'picture'>
export type PreProps = PrimitiveProps<'pre'>
export type ProgressProps = PrimitiveProps<'progress'>
export type QProps = PrimitiveProps<'q'>
export type RpProps = PrimitiveProps<'rp'>
export type RtProps = PrimitiveProps<'rt'>
export type RubyProps = PrimitiveProps<'ruby'>
export type SProps = PrimitiveProps<'s'>
export type SampProps = PrimitiveProps<'samp'>
export type SearchProps = PrimitiveProps<'search'>
export type SectionProps = PrimitiveProps<'section'>
export type SelectProps = PrimitiveProps<'select'>
export type SmallProps = PrimitiveProps<'small'>
export type SourceProps = PrimitiveProps<'source'>
export type SpanProps = PrimitiveProps<'span'>
export type StrongProps = PrimitiveProps<'strong'>
export type SubProps = PrimitiveProps<'sub'>
export type SummaryProps = PrimitiveProps<'summary'>
export type SupProps = PrimitiveProps<'sup'>
export type SvgProps = PrimitiveProps<'svg'>
export type TableProps = PrimitiveProps<'table'>
export type TbodyProps = PrimitiveProps<'tbody'>
export type TdProps = PrimitiveProps<'td'>
export type TextareaProps = PrimitiveProps<'textarea'>
export type TfootProps = PrimitiveProps<'tfoot'>
export type ThProps = PrimitiveProps<'th'>
export type TheadProps = PrimitiveProps<'thead'>
export type TimeProps = PrimitiveProps<'time'>
export type TrProps = PrimitiveProps<'tr'>
export type TrackProps = PrimitiveProps<'track'>
export type UProps = PrimitiveProps<'u'>
export type UlProps = PrimitiveProps<'ul'>
export type VarProps = PrimitiveProps<'var'>
export type VideoProps = PrimitiveProps<'video'>
export type WbrProps = PrimitiveProps<'wbr'>