/*
 * This file is generated and managed by pipeline.
 * DO NOT EDIT THIS FILE DIRECTLY!
 * To update this configuration, edit: pipeline/src/testing/matrix/managed/playwright/templates/playwright.config.ts.liquid
 */
import { defineConfig } from '@playwright/test'

export default defineConfig({
  reporter: 'line',
  testDir: './tests/e2e',
  timeout: 180_000,
  workers: 1,
  fullyParallel: false,
  use: {
    headless: true,
  },
  projects: [
    {
      name: 'vite7',
      use: {
        baseURL: 'http://127.0.0.1:4173',
      },
    }
  ],
  webServer: [
    {
      command: 'pnpm exec vite --host 127.0.0.1 --port 4173 --strictPort',
      url: 'http://127.0.0.1:4173',
      reuseExistingServer: false,
      timeout: 120_000,
      stdout: 'pipe',
      stderr: 'pipe',
    }
  ],
})
