/** Generated by createPandaConfig - do not edit manually */
              var __defProp = Object.defineProperty;
var __name = (target, value) => __defProp(target, "name", { value, configurable: true });
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};

// ../reference-core/src/cli/panda/config/extendPandaConfig.ts
var COLLECTOR_KEY = "__refPandaConfigCollector";
function extendPandaConfig(partial) {
  const collector = globalThis[COLLECTOR_KEY];
  if (Array.isArray(collector)) {
    collector.push(partial);
  }
}
__name(extendPandaConfig, "extendPandaConfig");

// ../reference-core/src/cli/panda/config/initCollector.ts
globalThis[COLLECTOR_KEY] = [];

// ../reference-core/.ref/panda-entry.ts
import { defineConfig as defineConfig2 } from "@pandacss/dev";

// ../reference-core/src/cli/panda/config/deepMerge.ts
function deepMerge(target, ...sources) {
  const result = { ...target };
  for (const source of sources) {
    if (!source || typeof source !== "object") continue;
    for (const key of Object.keys(source)) {
      const targetVal = result[key];
      const sourceVal = source[key];
      if (sourceVal === void 0) continue;
      if (Array.isArray(sourceVal) || typeof sourceVal === "function") {
        result[key] = sourceVal;
        continue;
      }
      if (sourceVal !== null && typeof sourceVal === "object" && targetVal !== null && typeof targetVal === "object" && !Array.isArray(targetVal)) {
        result[key] = deepMerge({ ...targetVal }, sourceVal);
      } else {
        result[key] = sourceVal;
      }
    }
  }
  return result;
}
__name(deepMerge, "deepMerge");

// ../reference-core/panda.base.ts
var panda_base_exports = {};
__export(panda_base_exports, {
  baseConfig: () => baseConfig,
  default: () => panda_base_default
});
import { defineConfig } from "@pandacss/dev";

// ../reference-core/src/cli/lib/microBundle.ts
import * as esbuild from "esbuild";

// ../reference-core/src/cli/eval/scanner.ts
import fg from "fast-glob";

// ../reference-core/src/styled/index.ts
var styled_exports = {};
__export(styled_exports, {
  colors: () => colors,
  defaultGlobalFontface: () => defaultGlobalFontface,
  defaultStaticCss: () => defaultStaticCss,
  defaultTheme: () => defaultTheme,
  getRhythm: () => getRhythm,
  tokens: () => tokens2
});
import { defineTokens as defineTokens2 } from "@pandacss/dev";

// ../reference-core/src/styled/colors.ts
var colors_exports = {};
__export(colors_exports, {
  colors: () => colors
});

// ../reference-core/src/styled/api/tokens.ts
var tokens_exports = {};
__export(tokens_exports, {
  tokens: () => tokens
});
function tokens(tokenConfig) {
  extendPandaConfig({
    theme: {
      tokens: tokenConfig
    }
  });
}
__name(tokens, "tokens");

// ../reference-core/src/styled/colors.ts
var colors = {
  gray: {
    50: { value: "oklch(98.5% 0.002 247.839)" },
    100: { value: "oklch(96.7% 0.003 264.542)" },
    200: { value: "oklch(92.8% 0.006 264.531)" },
    300: { value: "oklch(87.2% 0.01 258.338)" },
    400: { value: "oklch(70.7% 0.022 261.325)" },
    500: { value: "oklch(55.1% 0.027 264.364)" },
    600: { value: "oklch(44.6% 0.03 256.802)" },
    700: { value: "oklch(37.3% 0.034 259.733)" },
    800: { value: "oklch(27.8% 0.033 256.848)" },
    900: { value: "oklch(21% 0.034 264.665)" },
    950: { value: "oklch(13% 0.028 261.692)" }
  },
  red: {
    50: { value: "oklch(97.1% 0.013 17.38)" },
    100: { value: "oklch(93.6% 0.032 17.717)" },
    200: { value: "oklch(88.5% 0.062 18.334)" },
    300: { value: "oklch(80.8% 0.114 19.571)" },
    400: { value: "oklch(70.4% 0.191 22.216)" },
    500: { value: "oklch(63.7% 0.237 25.331)" },
    600: { value: "oklch(57.7% 0.245 27.325)" },
    700: { value: "oklch(50.5% 0.213 27.518)" },
    800: { value: "oklch(44.4% 0.177 26.899)" },
    900: { value: "oklch(39.6% 0.141 25.723)" },
    950: { value: "oklch(25.8% 0.092 26.042)" }
  },
  orange: {
    50: { value: "oklch(98% 0.016 73.684)" },
    100: { value: "oklch(95.4% 0.038 75.164)" },
    200: { value: "oklch(90.1% 0.076 70.697)" },
    300: { value: "oklch(83.7% 0.128 66.29)" },
    400: { value: "oklch(75% 0.183 55.934)" },
    500: { value: "oklch(70.5% 0.213 47.604)" },
    600: { value: "oklch(64.6% 0.222 41.116)" },
    700: { value: "oklch(55.3% 0.195 38.402)" },
    800: { value: "oklch(47% 0.157 37.304)" },
    900: { value: "oklch(40.8% 0.123 38.172)" },
    950: { value: "oklch(26.6% 0.079 36.259)" }
  },
  amber: {
    50: { value: "oklch(98.7% 0.022 95.277)" },
    100: { value: "oklch(96.2% 0.059 95.617)" },
    200: { value: "oklch(92.4% 0.12 95.746)" },
    300: { value: "oklch(87.9% 0.169 91.605)" },
    400: { value: "oklch(82.8% 0.189 84.429)" },
    500: { value: "oklch(76.9% 0.188 70.08)" },
    600: { value: "oklch(66.6% 0.179 58.318)" },
    700: { value: "oklch(55.5% 0.163 48.998)" },
    800: { value: "oklch(47.3% 0.137 46.201)" },
    900: { value: "oklch(41.4% 0.112 45.904)" },
    950: { value: "oklch(27.9% 0.077 45.635)" }
  },
  yellow: {
    50: { value: "oklch(98.7% 0.026 102.212)" },
    100: { value: "oklch(97.3% 0.071 103.193)" },
    200: { value: "oklch(94.5% 0.129 101.54)" },
    300: { value: "oklch(90.5% 0.182 98.111)" },
    400: { value: "oklch(85.2% 0.199 91.936)" },
    500: { value: "oklch(79.5% 0.184 86.047)" },
    600: { value: "oklch(68.1% 0.162 75.834)" },
    700: { value: "oklch(55.4% 0.135 66.442)" },
    800: { value: "oklch(47.6% 0.114 61.907)" },
    900: { value: "oklch(42.1% 0.095 57.708)" },
    950: { value: "oklch(28.6% 0.066 53.813)" }
  },
  lime: {
    50: { value: "oklch(98.6% 0.031 120.757)" },
    100: { value: "oklch(96.7% 0.067 122.328)" },
    200: { value: "oklch(93.8% 0.127 124.321)" },
    300: { value: "oklch(89.7% 0.196 126.665)" },
    400: { value: "oklch(84.1% 0.238 128.85)" },
    500: { value: "oklch(76.8% 0.233 130.85)" },
    600: { value: "oklch(64.8% 0.2 131.684)" },
    700: { value: "oklch(53.2% 0.157 131.589)" },
    800: { value: "oklch(45.3% 0.124 130.933)" },
    900: { value: "oklch(40.5% 0.101 131.063)" },
    950: { value: "oklch(27.4% 0.072 132.109)" }
  },
  green: {
    50: { value: "oklch(98.2% 0.018 155.826)" },
    100: { value: "oklch(96.2% 0.044 156.743)" },
    200: { value: "oklch(92.5% 0.084 155.995)" },
    300: { value: "oklch(87.1% 0.15 154.449)" },
    400: { value: "oklch(79.2% 0.209 151.711)" },
    500: { value: "oklch(72.3% 0.219 149.579)" },
    600: { value: "oklch(62.7% 0.194 149.214)" },
    700: { value: "oklch(52.7% 0.154 150.069)" },
    800: { value: "oklch(44.8% 0.119 151.328)" },
    900: { value: "oklch(39.3% 0.095 152.535)" },
    950: { value: "oklch(26.6% 0.065 152.934)" }
  },
  emerald: {
    50: { value: "oklch(97.9% 0.021 166.113)" },
    100: { value: "oklch(95% 0.052 163.051)" },
    200: { value: "oklch(90.5% 0.093 164.15)" },
    300: { value: "oklch(84.5% 0.143 164.978)" },
    400: { value: "oklch(76.5% 0.177 163.223)" },
    500: { value: "oklch(69.6% 0.17 162.48)" },
    600: { value: "oklch(59.6% 0.145 163.225)" },
    700: { value: "oklch(50.8% 0.118 165.612)" },
    800: { value: "oklch(43.2% 0.095 166.913)" },
    900: { value: "oklch(37.8% 0.077 168.94)" },
    950: { value: "oklch(26.2% 0.051 172.552)" }
  },
  teal: {
    50: { value: "oklch(98.4% 0.014 180.72)" },
    100: { value: "oklch(95.3% 0.051 180.801)" },
    200: { value: "oklch(91% 0.096 180.426)" },
    300: { value: "oklch(85.5% 0.138 181.071)" },
    400: { value: "oklch(77.7% 0.152 181.912)" },
    500: { value: "oklch(70.4% 0.14 182.503)" },
    600: { value: "oklch(60% 0.118 184.704)" },
    700: { value: "oklch(51.1% 0.096 186.391)" },
    800: { value: "oklch(43.7% 0.078 188.216)" },
    900: { value: "oklch(38.6% 0.063 188.416)" },
    950: { value: "oklch(27.7% 0.046 192.524)" }
  },
  cyan: {
    50: { value: "oklch(98.4% 0.019 200.873)" },
    100: { value: "oklch(95.6% 0.045 203.388)" },
    200: { value: "oklch(91.7% 0.08 205.041)" },
    300: { value: "oklch(86.5% 0.127 207.078)" },
    400: { value: "oklch(78.9% 0.154 211.53)" },
    500: { value: "oklch(71.5% 0.143 215.221)" },
    600: { value: "oklch(60.9% 0.126 221.723)" },
    700: { value: "oklch(52% 0.105 223.128)" },
    800: { value: "oklch(45% 0.085 224.283)" },
    900: { value: "oklch(39.8% 0.07 227.392)" },
    950: { value: "oklch(30.2% 0.056 229.695)" }
  },
  sky: {
    50: { value: "oklch(97.7% 0.013 236.62)" },
    100: { value: "oklch(95.1% 0.026 236.824)" },
    200: { value: "oklch(90.1% 0.058 230.902)" },
    300: { value: "oklch(82.8% 0.111 230.318)" },
    400: { value: "oklch(74.6% 0.16 232.661)" },
    500: { value: "oklch(68.5% 0.169 237.323)" },
    600: { value: "oklch(58.8% 0.158 241.966)" },
    700: { value: "oklch(50% 0.134 242.749)" },
    800: { value: "oklch(44.3% 0.11 240.79)" },
    900: { value: "oklch(39.1% 0.09 240.876)" },
    950: { value: "oklch(29.3% 0.066 243.157)" }
  },
  blue: {
    50: { value: "oklch(97% 0.014 254.604)" },
    100: { value: "oklch(93.2% 0.032 255.585)" },
    200: { value: "oklch(88.2% 0.059 254.128)" },
    300: { value: "oklch(80.9% 0.105 251.813)" },
    400: { value: "oklch(70.7% 0.165 254.624)" },
    500: { value: "oklch(62.3% 0.214 259.815)" },
    600: { value: "oklch(54.6% 0.245 262.881)" },
    700: { value: "oklch(48.8% 0.243 264.376)" },
    800: { value: "oklch(42.4% 0.199 265.638)" },
    900: { value: "oklch(37.9% 0.146 265.522)" },
    950: { value: "oklch(28.2% 0.091 267.935)" }
  },
  indigo: {
    50: { value: "oklch(96.2% 0.018 272.314)" },
    100: { value: "oklch(93% 0.034 272.788)" },
    200: { value: "oklch(87% 0.065 274.039)" },
    300: { value: "oklch(78.5% 0.115 274.713)" },
    400: { value: "oklch(67.3% 0.182 276.935)" },
    500: { value: "oklch(58.5% 0.233 277.117)" },
    600: { value: "oklch(51.1% 0.262 276.966)" },
    700: { value: "oklch(45.7% 0.24 277.023)" },
    800: { value: "oklch(39.8% 0.195 277.366)" },
    900: { value: "oklch(35.9% 0.144 278.697)" },
    950: { value: "oklch(25.7% 0.09 281.288)" }
  },
  violet: {
    50: { value: "oklch(96.9% 0.016 293.756)" },
    100: { value: "oklch(94.3% 0.029 294.588)" },
    200: { value: "oklch(89.4% 0.057 293.283)" },
    300: { value: "oklch(81.1% 0.111 293.571)" },
    400: { value: "oklch(70.2% 0.183 293.541)" },
    500: { value: "oklch(60.6% 0.25 292.717)" },
    600: { value: "oklch(54.1% 0.281 293.009)" },
    700: { value: "oklch(49.1% 0.27 292.581)" },
    800: { value: "oklch(43.2% 0.232 292.759)" },
    900: { value: "oklch(38% 0.189 293.745)" },
    950: { value: "oklch(28.3% 0.141 291.089)" }
  },
  purple: {
    50: { value: "oklch(97.7% 0.014 308.299)" },
    100: { value: "oklch(94.6% 0.033 307.174)" },
    200: { value: "oklch(90.2% 0.063 306.703)" },
    300: { value: "oklch(82.7% 0.119 306.383)" },
    400: { value: "oklch(71.4% 0.203 305.504)" },
    500: { value: "oklch(62.7% 0.265 303.9)" },
    600: { value: "oklch(55.8% 0.288 302.321)" },
    700: { value: "oklch(49.6% 0.265 301.924)" },
    800: { value: "oklch(43.8% 0.218 303.724)" },
    900: { value: "oklch(38.1% 0.176 304.987)" },
    950: { value: "oklch(29.1% 0.149 302.717)" }
  },
  magenta: {
    50: { value: "oklch(97.7% 0.017 320.058)" },
    100: { value: "oklch(95.2% 0.037 318.852)" },
    200: { value: "oklch(90.3% 0.076 319.62)" },
    300: { value: "oklch(83.3% 0.145 321.434)" },
    400: { value: "oklch(74% 0.238 322.16)" },
    500: { value: "oklch(66.7% 0.295 322.15)" },
    600: { value: "oklch(59.1% 0.293 322.896)" },
    700: { value: "oklch(51.8% 0.253 323.949)" },
    800: { value: "oklch(45.2% 0.211 324.591)" },
    900: { value: "oklch(40.1% 0.17 325.612)" },
    950: { value: "oklch(29.3% 0.136 325.661)" }
  },
  pink: {
    50: { value: "oklch(97.1% 0.014 343.198)" },
    100: { value: "oklch(94.8% 0.028 342.258)" },
    200: { value: "oklch(89.9% 0.061 343.231)" },
    300: { value: "oklch(82.3% 0.12 346.018)" },
    400: { value: "oklch(71.8% 0.202 349.761)" },
    500: { value: "oklch(65.6% 0.241 354.308)" },
    600: { value: "oklch(59.2% 0.249 0.584)" },
    700: { value: "oklch(52.5% 0.223 3.958)" },
    800: { value: "oklch(45.9% 0.187 3.815)" },
    900: { value: "oklch(40.8% 0.153 2.432)" },
    950: { value: "oklch(28.4% 0.109 3.907)" }
  },
  rose: {
    50: { value: "oklch(96.9% 0.015 12.422)" },
    100: { value: "oklch(94.1% 0.03 12.58)" },
    200: { value: "oklch(89.2% 0.058 10.001)" },
    300: { value: "oklch(81% 0.117 11.638)" },
    400: { value: "oklch(71.2% 0.194 13.428)" },
    500: { value: "oklch(64.5% 0.246 16.439)" },
    600: { value: "oklch(58.6% 0.253 17.585)" },
    700: { value: "oklch(51.4% 0.222 16.935)" },
    800: { value: "oklch(45.5% 0.188 13.697)" },
    900: { value: "oklch(41% 0.159 10.272)" },
    950: { value: "oklch(27.1% 0.105 12.094)" }
  }
};
tokens({
  colors
});

// ../reference-core/src/styled/font.ts
var font_exports = {};
__export(font_exports, {
  defaultGlobalFontface: () => defaultGlobalFontface,
  fontStaticCssProperties: () => fontStaticCssProperties,
  fontTokens: () => fontTokens
});
import { defineTokens } from "@pandacss/dev";
var fontTokens = defineTokens({
  fonts: {
    sans: {
      value: '"Inter", ui-serif, serif'
    },
    serif: {
      value: '"Literata", ui-sans-serif, sans-serif'
    },
    mono: {
      value: '"JetBrains Mono", ui-monospace, monospace'
    }
  }
});
var defaultGlobalFontface = {
  // Inter - sans-serif variable font (latin subset)
  Inter: {
    src: 'url(https://fonts.gstatic.com/s/inter/v20/UcC73FwrK3iLTeHuS_nVMrMxCp50SjIa1ZL7W0Q5nw.woff2) format("woff2")',
    fontWeight: "100 900",
    fontStyle: "normal",
    fontDisplay: "swap"
  },
  // Literata - serif variable font (latin subset)
  Literata: {
    src: 'url(https://fonts.gstatic.com/s/literata/v40/or38Q6P12-iJxAIgLa78DkrbXsDgk0oVDaDlbJ5W7i5aOg.woff2) format("woff2")',
    fontWeight: "200 900",
    fontStyle: "normal",
    fontDisplay: "swap",
    sizeAdjust: "104%",
    descentOverride: "47%"
  },
  // JetBrains Mono - monospace variable font (latin subset)
  '"JetBrains Mono"': {
    src: 'url(https://fonts.gstatic.com/s/jetbrainsmono/v24/tDbV2o-flEEny0FZhsfKu5WU4xD7OwGtT0rU.woff2) format("woff2")',
    fontWeight: "100 800",
    fontStyle: "normal",
    fontDisplay: "swap",
    sizeAdjust: "101%"
  }
};
var fontStaticCssProperties = {
  fontSize: ["*"],
  fontWeight: ["*"],
  fontFamily: ["*"]
};

// ../reference-core/src/styled/rhythm.ts
function getRhythm(num, denom) {
  if (denom !== void 0) {
    return num === 1 ? `calc(var(--spacing-r) / ${denom})` : `calc(${num} * var(--spacing-r) / ${denom})`;
  }
  if (num === 1) return "var(--spacing-r)";
  return `calc(${num} * var(--spacing-r))`;
}
__name(getRhythm, "getRhythm");
function resolveRhythm(value) {
  if (typeof value === "string" && value.endsWith("r")) {
    const n = Number(value.slice(0, -1));
    if (!Number.isNaN(n)) {
      return `calc(${n} * var(--spacing-r))`;
    }
  }
  return value;
}
__name(resolveRhythm, "resolveRhythm");
var rhythmTransform = /* @__PURE__ */ __name((property) => ({
  property,
  values: "spacing",
  transform: /* @__PURE__ */ __name((value) => ({
    [property]: resolveRhythm(value)
  }), "transform")
}), "rhythmTransform");
var rhythmUtilities = {
  width: rhythmTransform("width"),
  height: rhythmTransform("height"),
  fontSize: rhythmTransform("fontSize"),
  lineHeight: rhythmTransform("lineHeight"),
  letterSpacing: rhythmTransform("letterSpacing"),
  padding: rhythmTransform("padding"),
  paddingTop: rhythmTransform("paddingTop"),
  paddingBottom: rhythmTransform("paddingBottom"),
  paddingLeft: rhythmTransform("paddingLeft"),
  paddingRight: rhythmTransform("paddingRight"),
  paddingInline: rhythmTransform("paddingInline"),
  paddingInlineStart: rhythmTransform("paddingInlineStart"),
  paddingInlineEnd: rhythmTransform("paddingInlineEnd"),
  paddingBlock: rhythmTransform("paddingBlock"),
  paddingBlockStart: rhythmTransform("paddingBlockStart"),
  paddingBlockEnd: rhythmTransform("paddingBlockEnd"),
  margin: rhythmTransform("margin"),
  marginTop: rhythmTransform("marginTop"),
  marginBottom: rhythmTransform("marginBottom"),
  marginLeft: rhythmTransform("marginLeft"),
  marginRight: rhythmTransform("marginRight"),
  marginInline: rhythmTransform("marginInline"),
  marginInlineStart: rhythmTransform("marginInlineStart"),
  marginInlineEnd: rhythmTransform("marginInlineEnd"),
  marginBlock: rhythmTransform("marginBlock"),
  marginBlockStart: rhythmTransform("marginBlockStart"),
  marginBlockEnd: rhythmTransform("marginBlockEnd"),
  gap: rhythmTransform("gap"),
  rowGap: rhythmTransform("rowGap"),
  columnGap: rhythmTransform("columnGap"),
  gridGap: rhythmTransform("gridGap"),
  gridRowGap: rhythmTransform("gridRowGap"),
  gridColumnGap: rhythmTransform("gridColumnGap"),
  inset: rhythmTransform("inset"),
  insetBlock: rhythmTransform("insetBlock"),
  insetBlockStart: rhythmTransform("insetBlockStart"),
  insetBlockEnd: rhythmTransform("insetBlockEnd"),
  insetInline: rhythmTransform("insetInline"),
  insetInlineStart: rhythmTransform("insetInlineStart"),
  insetInlineEnd: rhythmTransform("insetInlineEnd"),
  top: rhythmTransform("top"),
  right: rhythmTransform("right"),
  bottom: rhythmTransform("bottom"),
  left: rhythmTransform("left"),
  scrollMargin: rhythmTransform("scrollMargin"),
  scrollMarginTop: rhythmTransform("scrollMarginTop"),
  scrollMarginRight: rhythmTransform("scrollMarginRight"),
  scrollMarginBottom: rhythmTransform("scrollMarginBottom"),
  scrollMarginLeft: rhythmTransform("scrollMarginLeft"),
  scrollMarginBlock: rhythmTransform("scrollMarginBlock"),
  scrollMarginBlockStart: rhythmTransform("scrollMarginBlockStart"),
  scrollMarginBlockEnd: rhythmTransform("scrollMarginBlockEnd"),
  scrollMarginInline: rhythmTransform("scrollMarginInline"),
  scrollMarginInlineStart: rhythmTransform("scrollMarginInlineStart"),
  scrollMarginInlineEnd: rhythmTransform("scrollMarginInlineEnd"),
  scrollPadding: rhythmTransform("scrollPadding"),
  scrollPaddingTop: rhythmTransform("scrollPaddingTop"),
  scrollPaddingRight: rhythmTransform("scrollPaddingRight"),
  scrollPaddingBottom: rhythmTransform("scrollPaddingBottom"),
  scrollPaddingLeft: rhythmTransform("scrollPaddingLeft"),
  scrollPaddingBlock: rhythmTransform("scrollPaddingBlock"),
  scrollPaddingBlockStart: rhythmTransform("scrollPaddingBlockStart"),
  scrollPaddingBlockEnd: rhythmTransform("scrollPaddingBlockEnd"),
  scrollPaddingInline: rhythmTransform("scrollPaddingInline"),
  scrollPaddingInlineStart: rhythmTransform("scrollPaddingInlineStart"),
  scrollPaddingInlineEnd: rhythmTransform("scrollPaddingInlineEnd"),
  outlineOffset: rhythmTransform("outlineOffset"),
  borderSpacing: rhythmTransform("borderSpacing")
};

// ../reference-core/src/styled/index.ts
var tokens2 = defineTokens2({
  ...fontTokens,
  spacing: {
    px: { value: "1px" },
    r: { value: "0.25rem" },
    "0.5r": { value: getRhythm(0.5) },
    "1/2r": { value: getRhythm(1, 2) },
    "1/3r": { value: getRhythm(1, 3) },
    "1/4r": { value: getRhythm(1, 4) },
    "1/5r": { value: getRhythm(1, 5) },
    "1/6r": { value: getRhythm(1, 6) },
    "1r": { value: getRhythm(1) },
    "1.5r": { value: getRhythm(1.5) },
    "2r": { value: getRhythm(2) },
    "3r": { value: getRhythm(3) },
    "4r": { value: getRhythm(4) },
    "5r": { value: getRhythm(5) },
    "6r": { value: getRhythm(6) },
    "8r": { value: getRhythm(8) },
    "10r": { value: getRhythm(10) },
    "12r": { value: getRhythm(12) }
  },
  radii: {
    none: { value: "0" },
    sm: { value: "0.125rem" },
    base: { value: "0.25rem" },
    md: { value: "0.375rem" },
    lg: { value: "0.5rem" },
    xl: { value: "0.75rem" },
    "2xl": { value: "1rem" },
    "3xl": { value: "1.5rem" },
    full: { value: "9999px" }
  }
});
var defaultTheme = {
  extend: {
    tokens: tokens2
  }
};
var defaultStaticCss = {
  css: [
    {
      properties: {
        backgroundColor: ["*"],
        color: ["*"],
        borderColor: ["*"],
        padding: ["*"],
        paddingLeft: ["*"],
        paddingRight: ["*"],
        paddingTop: ["*"],
        paddingBottom: ["*"],
        margin: ["*"],
        gap: ["*"],
        ...fontStaticCssProperties,
        borderRadius: ["*"],
        borderWidth: ["*"],
        font: ["*"]
      }
    }
  ],
  recipes: {
    fontStyle: ["*"]
  }
};

// ../reference-core/src/primitives/css/h1.style.ts
import { defineRecipe } from "@pandacss/dev";

// ../reference-core/src/primitives/css/base.typography.ts
var baseTypography = {
  fontFamily: "sans",
  letterSpacing: "-0.01em",
  color: "gray.900"
};

// ../reference-core/src/primitives/css/h1.style.ts
var h1Style = defineRecipe({
  className: "r_h1",
  base: {
    ...baseTypography,
    fontSize: "9r",
    fontWeight: "bold",
    lineHeight: "15r",
    marginTop: "0",
    marginBottom: "3r"
  }
});

// ../reference-core/src/primitives/css/h2.style.ts
import { defineRecipe as defineRecipe2 } from "@pandacss/dev";
var h2Style = defineRecipe2({
  className: "r_h2",
  base: {
    ...baseTypography,
    fontSize: "6r",
    fontWeight: "bold",
    lineHeight: "10r",
    marginTop: "0",
    marginBottom: "3r"
  }
});

// ../reference-core/src/primitives/css/h3.style.ts
import { defineRecipe as defineRecipe3 } from "@pandacss/dev";
var h3Style = defineRecipe3({
  className: "r_h3",
  base: {
    ...baseTypography,
    fontSize: "5r",
    fontWeight: "bold",
    lineHeight: "10r",
    marginTop: "0",
    marginBottom: "3r"
  }
});

// ../reference-core/src/primitives/css/h4.style.ts
import { defineRecipe as defineRecipe4 } from "@pandacss/dev";
var h4Style = defineRecipe4({
  className: "r_h4",
  base: {
    ...baseTypography,
    fontSize: "4.5r",
    fontWeight: "bold",
    lineHeight: "8r",
    marginTop: "0",
    marginBottom: "3r"
  }
});

// ../reference-core/src/primitives/css/h5.style.ts
import { defineRecipe as defineRecipe5 } from "@pandacss/dev";
var h5Style = defineRecipe5({
  className: "r_h5",
  base: {
    ...baseTypography,
    fontSize: "4.5r",
    fontWeight: "500",
    lineHeight: "8r",
    marginTop: "0",
    marginBottom: "3r"
  }
});

// ../reference-core/src/primitives/css/h6.style.ts
import { defineRecipe as defineRecipe6 } from "@pandacss/dev";
var h6Style = defineRecipe6({
  className: "r_h6",
  base: {
    ...baseTypography,
    fontSize: "3.5r",
    fontWeight: "600",
    lineHeight: "8r",
    marginTop: "0",
    marginBottom: "3r",
    textTransform: "uppercase"
  }
});

// ../reference-core/src/primitives/css/p.style.ts
import { defineRecipe as defineRecipe7 } from "@pandacss/dev";
var pStyle = defineRecipe7({
  className: "r_p",
  base: {
    ...baseTypography,
    fontSize: "4r",
    lineHeight: "1.6",
    marginTop: "0",
    marginBottom: "1em"
  }
});

// ../reference-core/src/primitives/css/strong.style.ts
import { defineRecipe as defineRecipe8 } from "@pandacss/dev";
var strongStyle = defineRecipe8({
  className: "r_strong",
  base: {
    ...baseTypography,
    fontWeight: "bold"
  }
});

// ../reference-core/src/primitives/css/em.style.ts
import { defineRecipe as defineRecipe9 } from "@pandacss/dev";
var emStyle = defineRecipe9({
  className: "r_em",
  base: {
    ...baseTypography,
    fontStyle: "italic"
  }
});

// ../reference-core/src/primitives/css/b.style.ts
import { defineRecipe as defineRecipe10 } from "@pandacss/dev";
var bStyle = defineRecipe10({
  className: "r_b",
  base: {
    ...baseTypography,
    fontWeight: "bold"
  }
});

// ../reference-core/src/primitives/css/i.style.ts
import { defineRecipe as defineRecipe11 } from "@pandacss/dev";
var iStyle = defineRecipe11({
  className: "r_i",
  base: {
    ...baseTypography,
    fontStyle: "italic"
  }
});

// ../reference-core/src/primitives/css/u.style.ts
import { defineRecipe as defineRecipe12 } from "@pandacss/dev";
var uStyle = defineRecipe12({
  className: "r_u",
  base: {
    ...baseTypography,
    textDecoration: "underline",
    textUnderlineOffset: "0.15em",
    textDecorationThickness: "0.08em"
  }
});

// ../reference-core/src/primitives/css/s.style.ts
import { defineRecipe as defineRecipe13 } from "@pandacss/dev";
var sStyle = defineRecipe13({
  className: "r_s",
  base: {
    ...baseTypography,
    textDecoration: "line-through",
    opacity: "0.7"
  }
});

// ../reference-core/src/primitives/css/small.style.ts
import { defineRecipe as defineRecipe14 } from "@pandacss/dev";
var smallStyle = defineRecipe14({
  className: "r_small",
  base: {
    ...baseTypography,
    fontSize: "small",
    lineHeight: "1.4"
  }
});

// ../reference-core/src/primitives/css/mark.style.ts
import { defineRecipe as defineRecipe15 } from "@pandacss/dev";
var markStyle = defineRecipe15({
  className: "r_mark",
  base: {
    ...baseTypography,
    backgroundColor: "yellow.200",
    color: "gray.900",
    paddingInline: "0.25em",
    borderRadius: "sm"
  }
});

// ../reference-core/src/primitives/css/sub.style.ts
import { defineRecipe as defineRecipe16 } from "@pandacss/dev";
var subStyle = defineRecipe16({
  className: "r_sub",
  base: {
    ...baseTypography,
    fontSize: "xs",
    verticalAlign: "sub",
    lineHeight: "0"
  }
});

// ../reference-core/src/primitives/css/sup.style.ts
import { defineRecipe as defineRecipe17 } from "@pandacss/dev";
var supStyle = defineRecipe17({
  className: "r_sup",
  base: {
    ...baseTypography,
    fontSize: "xs",
    verticalAlign: "super",
    lineHeight: "0"
  }
});

// ../reference-core/src/primitives/css/abbr.style.ts
import { defineRecipe as defineRecipe18 } from "@pandacss/dev";
var abbrStyle = defineRecipe18({
  className: "r_abbr",
  base: {
    ...baseTypography,
    textDecoration: "underline dotted",
    textUnderlineOffset: "0.15em",
    cursor: "help"
  }
});

// ../reference-core/src/primitives/css/code.style.ts
import { defineRecipe as defineRecipe19 } from "@pandacss/dev";
var codeStyle = defineRecipe19({
  className: "r_code",
  base: {
    ...baseTypography,
    fontFamily: "mono",
    fontSize: "0.9em",
    backgroundColor: "gray.100",
    color: "pink.600",
    paddingInline: "0.4em",
    paddingBlock: "0.15em",
    borderRadius: "sm"
  }
});

// ../reference-core/src/primitives/css/pre.style.ts
import { defineRecipe as defineRecipe20 } from "@pandacss/dev";
var preStyle = defineRecipe20({
  className: "r_pre",
  base: {
    ...baseTypography,
    fontFamily: "mono",
    letterSpacing: "-0.02em",
    fontSize: "small",
    lineHeight: "1.6",
    backgroundColor: "gray.900",
    color: "gray.100",
    padding: "1em",
    borderRadius: "md",
    overflowX: "auto",
    whiteSpace: "pre",
    marginTop: "0",
    marginBottom: "1em"
  }
});

// ../reference-core/src/primitives/css/kbd.style.ts
import { defineRecipe as defineRecipe21 } from "@pandacss/dev";
var kbdStyle = defineRecipe21({
  className: "r_kbd",
  base: {
    ...baseTypography,
    fontFamily: "mono",
    letterSpacing: "-0.02em",
    fontSize: "0.85em",
    backgroundColor: "gray.100",
    color: "gray.800",
    paddingInline: "0.4em",
    paddingBlock: "0.2em",
    borderRadius: "sm",
    borderWidth: "1px",
    borderBottomWidth: "2px",
    borderStyle: "solid",
    borderColor: "gray.300",
    boxShadow: "0 1px 1px rgba(0,0,0,0.1)"
  }
});

// ../reference-core/src/primitives/css/samp.style.ts
import { defineRecipe as defineRecipe22 } from "@pandacss/dev";
var sampStyle = defineRecipe22({
  className: "r_samp",
  base: {
    ...baseTypography,
    fontFamily: "mono",
    letterSpacing: "-0.02em",
    fontSize: "0.9em",
    backgroundColor: "gray.50",
    color: "gray.700",
    paddingInline: "0.3em",
    paddingBlock: "0.1em",
    borderRadius: "sm"
  }
});

// ../reference-core/src/primitives/css/var.style.ts
import { defineRecipe as defineRecipe23 } from "@pandacss/dev";
var varStyle = defineRecipe23({
  className: "r_var",
  base: {
    ...baseTypography,
    fontFamily: "serif",
    letterSpacing: "normal",
    fontStyle: "italic",
    color: "blue.600"
  }
});

// ../reference-core/src/primitives/css/blockquote.style.ts
import { defineRecipe as defineRecipe24 } from "@pandacss/dev";
var blockquoteStyle = defineRecipe24({
  className: "r_blockquote",
  base: {
    ...baseTypography,
    fontSize: "h5",
    fontStyle: "italic",
    lineHeight: "1.6",
    color: "gray.600",
    borderLeftWidth: "4px",
    borderLeftStyle: "solid",
    borderLeftColor: "gray.300",
    paddingLeft: "1em",
    marginLeft: "0",
    marginRight: "0",
    marginTop: "0",
    marginBottom: "1em"
  }
});

// ../reference-core/src/primitives/css/q.style.ts
import { defineRecipe as defineRecipe25 } from "@pandacss/dev";
var qStyle = defineRecipe25({
  className: "r_q",
  base: {
    ...baseTypography,
    fontStyle: "italic",
    _before: {
      content: '"\\201C"'
    },
    _after: {
      content: '"\\201D"'
    }
  }
});

// ../reference-core/src/primitives/css/cite.style.ts
import { defineRecipe as defineRecipe26 } from "@pandacss/dev";
var citeStyle = defineRecipe26({
  className: "r_cite",
  base: {
    ...baseTypography,
    fontStyle: "italic",
    color: "gray.500"
  }
});

// ../reference-core/src/primitives/recipes.ts
var primitiveCSS = {
  h1Style,
  h2Style,
  h3Style,
  h4Style,
  h5Style,
  h6Style,
  pStyle,
  strongStyle,
  emStyle,
  bStyle,
  iStyle,
  uStyle,
  sStyle,
  smallStyle,
  markStyle,
  subStyle,
  supStyle,
  abbrStyle,
  codeStyle,
  preStyle,
  kbdStyle,
  sampStyle,
  varStyle,
  blockquoteStyle,
  qStyle,
  citeStyle
};

// ../reference-core/src/styled/patterns.ts
var patterns_exports = {};
__export(patterns_exports, {
  patternsGlobalCss: () => patternsGlobalCss
});
var rhythmTokens = {
  ":root": {
    "--r-base": "16px",
    "--r-density": "1",
    "--spacing-r": "calc(var(--r-base) * var(--r-density))"
  }
};
var bodyDefaults = {
  body: {
    fontFamily: "sans",
    letterSpacing: "-0.01em",
    fontSize: "body"
  }
};
var densityVariants = {
  '[data-density="compact"]': { "--r-density": "0.75" },
  '[data-density="comfortable"]': { "--r-density": "1" },
  '[data-density="spacious"]': { "--r-density": "1.25" }
};
var patternsGlobalCss = {
  ...rhythmTokens,
  ...bodyDefaults,
  ...densityVariants
};

// ../reference-core/src/styled/props/index.ts
var props_exports = {};

// ../reference-core/panda.base.ts
var baseConfig = {
  presets: [],
  jsxFramework: "react",
  preflight: true,
  include: [
    "src/**/*.{ts,tsx}",
    "codegen/**/*.{ts,tsx,jsx}"
  ],
  exclude: [
    "**/node_modules/**",
    "**/*.test.*",
    "**/*.spec.*",
    "src/system/**",
    "src/cli/**",
    "src/config/**"
  ],
  dependencies: [],
  outdir: "src/system",
  outExtension: "js",
  hash: false,
  staticCss: defaultStaticCss,
  utilities: {
    extend: {
      ...rhythmUtilities
    }
  },
  theme: {
    tokens: defaultTheme.extend.tokens,
    extend: {
      recipes: {
        ...primitiveCSS
      }
    }
  },
  globalCss: patternsGlobalCss,
  globalFontface: defaultGlobalFontface
};
extendPandaConfig(baseConfig);
var panda_base_default = defineConfig(baseConfig);

// ../reference-core/src/styled/api/index.ts
var api_exports = {};
__export(api_exports, {
  patterns: () => patterns,
  recipe: () => recipe,
  slotRecipe: () => slotRecipe,
  tokens: () => tokens
});

// ../reference-core/src/styled/api/patterns.ts
var patterns_exports2 = {};
__export(patterns_exports2, {
  patterns: () => patterns
});
function asExtendablePatterns(p) {
  return p;
}
__name(asExtendablePatterns, "asExtendablePatterns");
function patterns(patternConfig) {
  extendPandaConfig({
    patterns: {
      extend: asExtendablePatterns(patternConfig)
    }
  });
}
__name(patterns, "patterns");

// ../reference-core/src/styled/api/recipe.ts
var recipe_exports = {};
__export(recipe_exports, {
  recipe: () => recipe,
  slotRecipe: () => slotRecipe
});
function recipe(recipeConfig) {
  extendPandaConfig({
    theme: {
      extend: {
        recipes: recipeConfig
      }
    }
  });
}
__name(recipe, "recipe");
function slotRecipe(slotRecipeConfig) {
  extendPandaConfig({
    theme: {
      extend: {
        slotRecipes: slotRecipeConfig
      }
    }
  });
}
__name(slotRecipe, "slotRecipe");

// ../reference-core/src/styled/props/container.ts
var container_exports = {};

// ../reference-core/src/primitives/tags.ts
var TAGS = [
  "a",
  "abbr",
  "address",
  "area",
  "article",
  "aside",
  "audio",
  "b",
  "bdi",
  "bdo",
  "blockquote",
  "br",
  "button",
  "canvas",
  "caption",
  "cite",
  "code",
  "col",
  "colgroup",
  "data",
  "datalist",
  "dd",
  "del",
  "details",
  "dfn",
  "dialog",
  "div",
  "dl",
  "dt",
  "em",
  "embed",
  "fieldset",
  "figcaption",
  "figure",
  "footer",
  "form",
  "h1",
  "h2",
  "h3",
  "h4",
  "h5",
  "h6",
  "header",
  "hgroup",
  "hr",
  "i",
  "iframe",
  "img",
  "input",
  "ins",
  "kbd",
  "label",
  "legend",
  "li",
  "main",
  "map",
  "mark",
  "menu",
  "meter",
  "nav",
  "object",
  "ol",
  "optgroup",
  "option",
  "output",
  "p",
  "picture",
  "pre",
  "progress",
  "q",
  "rp",
  "rt",
  "ruby",
  "s",
  "samp",
  "search",
  "section",
  "select",
  "small",
  "source",
  "span",
  "strong",
  "sub",
  "summary",
  "sup",
  "svg",
  "table",
  "tbody",
  "td",
  "textarea",
  "tfoot",
  "th",
  "thead",
  "time",
  "tr",
  "track",
  "u",
  "ul",
  "var",
  "video",
  "wbr"
];
function toJsxName(tag) {
  if (tag === "object") return "Obj";
  if (tag === "var") return "Var";
  if (tag.length <= 1) return tag.toUpperCase();
  return tag.charAt(0).toUpperCase() + tag.slice(1);
}
__name(toJsxName, "toJsxName");
var PRIMITIVE_JSX_NAMES = TAGS.map(toJsxName);

// ../reference-core/src/styled/props/container.ts
patterns({
  containerSetup: {
    jsx: [...PRIMITIVE_JSX_NAMES],
    properties: {
      container: { type: "string" }
    },
    blocklist: ["container"],
    transform(props) {
      const { container, ...rest } = props;
      if (container === void 0) return rest;
      return {
        ...rest,
        containerType: "inline-size",
        ...typeof container === "string" && container && { containerName: container }
      };
    }
  }
});

// ../reference-core/src/styled/props/font.ts
var font_exports2 = {};
recipe({
  fontStyle: {
    className: "r_font",
    variants: {
      font: {
        sans: {
          fontFamily: "sans",
          letterSpacing: "-0.01em",
          fontWeight: "400"
        },
        serif: {
          fontFamily: "serif",
          letterSpacing: "normal",
          fontWeight: "373"
        },
        mono: {
          fontFamily: "mono",
          letterSpacing: "-0.04em",
          fontWeight: "393"
        }
      }
    }
  }
});
patterns({
  fontPreset: {
    jsx: [...PRIMITIVE_JSX_NAMES],
    properties: {
      font: { type: "string" }
    },
    blocklist: ["font"],
    transform(props) {
      const { font, ...rest } = props;
      const FONT_PRESETS = {
        sans: { fontFamily: "sans", letterSpacing: "-0.01em", fontWeight: "400" },
        serif: { fontFamily: "serif", letterSpacing: "normal", fontWeight: "373" },
        mono: { fontFamily: "mono", letterSpacing: "-0.04em", fontWeight: "393" }
      };
      const fontStyles = font ? FONT_PRESETS[font] || {} : {};
      return {
        ...fontStyles,
        ...rest
      };
    }
  }
});

// ../reference-core/src/styled/props/r.ts
var r_exports = {};
patterns({
  responsiveContainer: {
    jsx: [...PRIMITIVE_JSX_NAMES],
    properties: {
      r: { type: "object" },
      container: { type: "string" }
    },
    blocklist: ["r"],
    transform(props) {
      const { r, container, ...rest } = props;
      if (!r) return rest;
      const prefix = container ? `@container ${container} (min-width:` : `@container (min-width:`;
      return {
        ...rest,
        ...Object.fromEntries(
          Object.entries(r).map(([bp, styles]) => [`${prefix} ${bp}px)`, styles])
        )
      };
    }
  }
});

// ../reference-core/.ref/panda-entry.ts
var defaultFragments = [panda_base_exports, colors_exports, font_exports, styled_exports, patterns_exports, api_exports, patterns_exports2, recipe_exports, tokens_exports, container_exports, font_exports2, props_exports, r_exports].map((m) => m?.default !== void 0 ? m.default : null).filter(Boolean);
var collected = globalThis[COLLECTOR_KEY] || [];
var fragments = [...defaultFragments, ...collected];
var config = fragments.reduce((acc, frag) => deepMerge(acc, frag), {});
var panda_entry_default = defineConfig2(config);
export {
  panda_entry_default as default
};

