// Generated by reference-cli — do not edit manually
import { defineConfig } from '@pandacss/dev'

// Base structural config
const baseConfig = {"preflight":false,"outdir":"styled","emitTokensOnly":false,"include":["./src/**/*.{ts,tsx}"],"exclude":[]}

// Collector setup — each collector initialises its own globalThis slot
globalThis['__PANDA_CONFIG__'] = []
globalThis['__FONT_CONFIG__'] = []

// Fragment bundles (each self-contained IIFE, functions intact)


// deepMerge — arrays and functions are replaced, plain objects are recursively merged
function deepMerge(target, ...sources) {
  const result = { ...target }
  for (const source of sources) {
    if (!source || typeof source !== 'object') continue
    for (const key of Object.keys(source)) {
      const targetVal = result[key]
      const sourceVal = source[key]
      if (sourceVal === undefined) continue
      if (Array.isArray(sourceVal) || typeof sourceVal === 'function') {
        result[key] = sourceVal
      } else if (
        sourceVal !== null && typeof sourceVal === 'object' &&
        targetVal !== null && typeof targetVal === 'object' && !Array.isArray(targetVal)
      ) {
        result[key] = deepMerge({ ...targetVal }, sourceVal)
      } else {
        result[key] = sourceVal
      }
    }
  }
  return result
}


const fragments = ['__PANDA_CONFIG__', '__FONT_CONFIG__'].flatMap(k => globalThis[k] ?? [])
;['__PANDA_CONFIG__', '__FONT_CONFIG__'].forEach(k => delete globalThis[k])
const config = deepMerge(baseConfig, ...fragments)

export default defineConfig(config)
