import { mkdirSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import type { ReferenceUIConfig } from '../../config'
import type { BaseSystem } from '../../config/types'
import { getOutDirPath } from '../../lib/paths'
import { log } from '../../lib/log'
import {
  createCollectorBundleFromBase,
  createPortableBaseFragmentBundle,
  prepareBaseFragments,
} from './fragments'
import type { BaseArtifacts } from './types'

function createBaseSystem(config: ReferenceUIConfig, fragment: string): BaseSystem {
  return {
    name: config.name,
    fragment,
  }
}

function writeBaseSystem(cwd: string, baseSystem: BaseSystem): void {
  const systemDir = join(getOutDirPath(cwd), 'system')
  const outputPath = join(systemDir, 'baseSystem.mjs')
  const typesPath = join(systemDir, 'baseSystem.d.mts')

  mkdirSync(systemDir, { recursive: true })
  writeFileSync(
    outputPath,
    `/** Generated by reference-cli — do not edit manually */\nexport const baseSystem = ${JSON.stringify(baseSystem, null, 2)}\n`,
    'utf-8'
  )
  writeFileSync(
    typesPath,
    `import type { BaseSystem } from '@reference-ui/cli'\nexport declare const baseSystem: BaseSystem\n`,
    'utf-8'
  )

  log.debug('base', 'baseSystem written', outputPath)
}

/**
 * Build the portable base-system artefact once, then expose the collector bundle
 * that config generation uses to write `panda.config.ts`.
 */
export async function createBaseArtifacts(
  cwd: string,
  config: ReferenceUIConfig
): Promise<BaseArtifacts> {
  const preparedFragments = await prepareBaseFragments(cwd, config)
  const collectorBundle = await createCollectorBundleFromBase(cwd, preparedFragments)
  const baseSystem = createBaseSystem(
    config,
    createPortableBaseFragmentBundle(preparedFragments)
  )

  writeBaseSystem(cwd, baseSystem)

  return {
    collectorBundle,
    baseSystem,
  }
}
